// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Auth.Me.Collection.MagazineIssues.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Auth.Me.Collection.MagazineIssues
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\me\collection\magazine-issues
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MagazineIssuesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Marechai.ApiClient.auth.me.collection.magazineIssues.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Auth.Me.Collection.MagazineIssues.Item.WithIssueItemRequestBuilder"/></returns>
        public global::Marechai.ApiClient.Auth.Me.Collection.MagazineIssues.Item.WithIssueItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("issueId", position);
                return new global::Marechai.ApiClient.Auth.Me.Collection.MagazineIssues.Item.WithIssueItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Marechai.ApiClient.auth.me.collection.magazineIssues.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Auth.Me.Collection.MagazineIssues.Item.WithIssueItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Marechai.ApiClient.Auth.Me.Collection.MagazineIssues.Item.WithIssueItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("issueId", position);
                return new global::Marechai.ApiClient.Auth.Me.Collection.MagazineIssues.Item.WithIssueItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Auth.Me.Collection.MagazineIssues.MagazineIssuesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MagazineIssuesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/me/collection/magazine-issues", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Auth.Me.Collection.MagazineIssues.MagazineIssuesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MagazineIssuesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/me/collection/magazine-issues", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
