// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Auth.ChangePassword;
using Marechai.ApiClient.Auth.Email;
using Marechai.ApiClient.Auth.Login;
using Marechai.ApiClient.Auth.Me;
using Marechai.ApiClient.Auth.Password;
using Marechai.ApiClient.Auth.Register;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The changePassword property</summary>
        public global::Marechai.ApiClient.Auth.ChangePassword.ChangePasswordRequestBuilder ChangePassword
        {
            get => new global::Marechai.ApiClient.Auth.ChangePassword.ChangePasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email property</summary>
        public global::Marechai.ApiClient.Auth.Email.EmailRequestBuilder Email
        {
            get => new global::Marechai.ApiClient.Auth.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::Marechai.ApiClient.Auth.Login.LoginRequestBuilder Login
        {
            get => new global::Marechai.ApiClient.Auth.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::Marechai.ApiClient.Auth.Me.MeRequestBuilder Me
        {
            get => new global::Marechai.ApiClient.Auth.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The password property</summary>
        public global::Marechai.ApiClient.Auth.Password.PasswordRequestBuilder Password
        {
            get => new global::Marechai.ApiClient.Auth.Password.PasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::Marechai.ApiClient.Auth.Register.RegisterRequestBuilder Register
        {
            get => new global::Marechai.ApiClient.Auth.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
