// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Sitemap.Machines.Ids;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Sitemap.Machines
{
    /// <summary>
    /// Builds and executes requests for operations under \sitemap\machines
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MachinesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ids property</summary>
        public global::Marechai.ApiClient.Sitemap.Machines.Ids.IdsRequestBuilder Ids
        {
            get => new global::Marechai.ApiClient.Sitemap.Machines.Ids.IdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Sitemap.Machines.MachinesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MachinesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sitemap/machines", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Sitemap.Machines.MachinesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MachinesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sitemap/machines", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
