// <auto-generated/>
#pragma warning disable CS0618
using Marechai.App.Countries.Item.Companies;
using Marechai.App.Countries.Item.Name;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.App.Countries.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \countries\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CountriesItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The companies property</summary>
        public global::Marechai.App.Countries.Item.Companies.CompaniesRequestBuilder Companies
        {
            get => new global::Marechai.App.Countries.Item.Companies.CompaniesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The name property</summary>
        public global::Marechai.App.Countries.Item.Name.NameRequestBuilder Name
        {
            get => new global::Marechai.App.Countries.Item.Name.NameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.Countries.Item.CountriesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CountriesItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/countries/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.Countries.Item.CountriesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CountriesItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/countries/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
