<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Aaru.CommonTypes"/>
    <PackageReference Include="Markdig"/>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="Svg.Skia"/>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Marechai.Database\Marechai.Database.csproj"/>
    <ProjectReference Include="..\Marechai.Data\Marechai.Data.csproj" />
  </ItemGroup>

</Project>
