// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Software.Covers.Item;
using Marechai.ApiClient.Software.Covers.Pending;
using Marechai.ApiClient.Software.Covers.Upload;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Software.Covers
{
    /// <summary>
    /// Builds and executes requests for operations under \software\covers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CoversRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The pending property</summary>
        public global::Marechai.ApiClient.Software.Covers.Pending.PendingRequestBuilder Pending
        {
            get => new global::Marechai.ApiClient.Software.Covers.Pending.PendingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload property</summary>
        public global::Marechai.ApiClient.Software.Covers.Upload.UploadRequestBuilder Upload
        {
            get => new global::Marechai.ApiClient.Software.Covers.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Marechai.ApiClient.software.covers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Software.Covers.Item.CoversItemRequestBuilder"/></returns>
        public global::Marechai.ApiClient.Software.Covers.Item.CoversItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Marechai.ApiClient.Software.Covers.Item.CoversItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Marechai.ApiClient.software.covers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Software.Covers.Item.CoversItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Marechai.ApiClient.Software.Covers.Item.CoversItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Marechai.ApiClient.Software.Covers.Item.CoversItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Software.Covers.CoversRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CoversRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software/covers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Software.Covers.CoversRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CoversRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software/covers", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
