// <auto-generated/>
#pragma warning disable CS0618
using Marechai.App.Software.OsCompatibility.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.App.Software.OsCompatibility.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \software\os-compatibility\{softwareVersionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSoftwareVersionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Marechai.App.software.osCompatibility.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.App.Software.OsCompatibility.Item.Item.WithOsVersionItemRequestBuilder"/></returns>
        public global::Marechai.App.Software.OsCompatibility.Item.Item.WithOsVersionItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("osVersionId", position);
                return new global::Marechai.App.Software.OsCompatibility.Item.Item.WithOsVersionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Marechai.App.software.osCompatibility.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.App.Software.OsCompatibility.Item.Item.WithOsVersionItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Marechai.App.Software.OsCompatibility.Item.Item.WithOsVersionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("osVersionId", position);
                return new global::Marechai.App.Software.OsCompatibility.Item.Item.WithOsVersionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.Software.OsCompatibility.Item.WithSoftwareVersionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSoftwareVersionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software/os-compatibility/{softwareVersionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.Software.OsCompatibility.Item.WithSoftwareVersionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSoftwareVersionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software/os-compatibility/{softwareVersionId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
