<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Marechai.Database</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aaru.CommonTypes"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql"/>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Json.Microsoft"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Marechai.Data\Marechai.Data.csproj"/>
  </ItemGroup>
</Project>