// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Software.Item.Platforms.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Software.Item.Platforms
{
    /// <summary>
    /// Builds and executes requests for operations under \software\{-id}\platforms
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlatformsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Marechai.ApiClient.software.item.platforms.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Software.Item.Platforms.Item.WithPlatformItemRequestBuilder"/></returns>
        public global::Marechai.ApiClient.Software.Item.Platforms.Item.WithPlatformItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("platformId", position);
                return new global::Marechai.ApiClient.Software.Item.Platforms.Item.WithPlatformItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Marechai.ApiClient.software.item.platforms.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Software.Item.Platforms.Item.WithPlatformItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Marechai.ApiClient.Software.Item.Platforms.Item.WithPlatformItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("platformId", position);
                return new global::Marechai.ApiClient.Software.Item.Platforms.Item.WithPlatformItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Software.Item.Platforms.PlatformsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlatformsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software/{%2Did}/platforms", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Software.Item.Platforms.PlatformsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlatformsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software/{%2Did}/platforms", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
