// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Models;
using Marechai.ApiClient.Notifications.Item;
using Marechai.ApiClient.Notifications.ReadAll;
using Marechai.ApiClient.Notifications.UnreadCount;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Marechai.ApiClient.Notifications
{
    /// <summary>
    /// Builds and executes requests for operations under \notifications
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotificationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The readAll property</summary>
        public global::Marechai.ApiClient.Notifications.ReadAll.ReadAllRequestBuilder ReadAll
        {
            get => new global::Marechai.ApiClient.Notifications.ReadAll.ReadAllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unreadCount property</summary>
        public global::Marechai.ApiClient.Notifications.UnreadCount.UnreadCountRequestBuilder UnreadCount
        {
            get => new global::Marechai.ApiClient.Notifications.UnreadCount.UnreadCountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Marechai.ApiClient.notifications.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Notifications.Item.NotificationsItemRequestBuilder"/></returns>
        public global::Marechai.ApiClient.Notifications.Item.NotificationsItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Marechai.ApiClient.Notifications.Item.NotificationsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Marechai.ApiClient.notifications.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Notifications.Item.NotificationsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Marechai.ApiClient.Notifications.Item.NotificationsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Marechai.ApiClient.Notifications.Item.NotificationsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Notifications.NotificationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotificationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/notifications{?unreadOnly*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Notifications.NotificationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotificationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/notifications{?unreadOnly*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::Marechai.ApiClient.Models.AdminNotificationDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Marechai.ApiClient.Models.AdminNotificationDto>?> GetAsync(Action<RequestConfiguration<global::Marechai.ApiClient.Notifications.NotificationsRequestBuilder.NotificationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Marechai.ApiClient.Models.AdminNotificationDto>> GetAsync(Action<RequestConfiguration<global::Marechai.ApiClient.Notifications.NotificationsRequestBuilder.NotificationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Marechai.ApiClient.Models.AdminNotificationDto>(requestInfo, global::Marechai.ApiClient.Models.AdminNotificationDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Marechai.ApiClient.Notifications.NotificationsRequestBuilder.NotificationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Marechai.ApiClient.Notifications.NotificationsRequestBuilder.NotificationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Notifications.NotificationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Marechai.ApiClient.Notifications.NotificationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Marechai.ApiClient.Notifications.NotificationsRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class NotificationsRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("unreadOnly")]
            public bool? UnreadOnly { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NotificationsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Marechai.ApiClient.Notifications.NotificationsRequestBuilder.NotificationsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
