// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Books.ByLetter;
using Marechai.ApiClient.Books.ByYear;
using Marechai.ApiClient.Books.Companies;
using Marechai.ApiClient.Books.Count;
using Marechai.ApiClient.Books.Item;
using Marechai.ApiClient.Books.MaximumYear;
using Marechai.ApiClient.Books.MinimumYear;
using Marechai.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Marechai.ApiClient.Books
{
    /// <summary>
    /// Builds and executes requests for operations under \books
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BooksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The byLetter property</summary>
        public global::Marechai.ApiClient.Books.ByLetter.ByLetterRequestBuilder ByLetter
        {
            get => new global::Marechai.ApiClient.Books.ByLetter.ByLetterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The byYear property</summary>
        public global::Marechai.ApiClient.Books.ByYear.ByYearRequestBuilder ByYear
        {
            get => new global::Marechai.ApiClient.Books.ByYear.ByYearRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The companies property</summary>
        public global::Marechai.ApiClient.Books.Companies.CompaniesRequestBuilder Companies
        {
            get => new global::Marechai.ApiClient.Books.Companies.CompaniesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The count property</summary>
        public global::Marechai.ApiClient.Books.Count.CountRequestBuilder Count
        {
            get => new global::Marechai.ApiClient.Books.Count.CountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The maximumYear property</summary>
        public global::Marechai.ApiClient.Books.MaximumYear.MaximumYearRequestBuilder MaximumYear
        {
            get => new global::Marechai.ApiClient.Books.MaximumYear.MaximumYearRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The minimumYear property</summary>
        public global::Marechai.ApiClient.Books.MinimumYear.MinimumYearRequestBuilder MinimumYear
        {
            get => new global::Marechai.ApiClient.Books.MinimumYear.MinimumYearRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Marechai.ApiClient.books.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Books.Item.BookItemRequestBuilder"/></returns>
        public global::Marechai.ApiClient.Books.Item.BookItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("book%2Did", position);
                return new global::Marechai.ApiClient.Books.Item.BookItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Marechai.ApiClient.books.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Books.Item.BookItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Marechai.ApiClient.Books.Item.BookItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("book%2Did", position);
                return new global::Marechai.ApiClient.Books.Item.BookItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Books.BooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BooksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/books{?skip*,take*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Books.BooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BooksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/books{?skip*,take*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::Marechai.ApiClient.Models.BookDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Marechai.ApiClient.Models.ProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Marechai.ApiClient.Models.BookDto>?> GetAsync(Action<RequestConfiguration<global::Marechai.ApiClient.Books.BooksRequestBuilder.BooksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Marechai.ApiClient.Models.BookDto>> GetAsync(Action<RequestConfiguration<global::Marechai.ApiClient.Books.BooksRequestBuilder.BooksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Marechai.ApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Marechai.ApiClient.Models.BookDto>(requestInfo, global::Marechai.ApiClient.Models.BookDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="long"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Marechai.ApiClient.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Marechai.ApiClient.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<long?> PostAsync(global::Marechai.ApiClient.Models.BookDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<long?> PostAsync(global::Marechai.ApiClient.Models.BookDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Marechai.ApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::Marechai.ApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<long?>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Marechai.ApiClient.Books.BooksRequestBuilder.BooksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Marechai.ApiClient.Books.BooksRequestBuilder.BooksRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Marechai.ApiClient.Models.BookDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Marechai.ApiClient.Models.BookDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Books.BooksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Marechai.ApiClient.Books.BooksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Marechai.ApiClient.Books.BooksRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class BooksRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("skip")]
            public int? Skip { get; set; }
            [QueryParameter("take")]
            public int? Take { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BooksRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Marechai.ApiClient.Books.BooksRequestBuilder.BooksRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BooksRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
