// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Auth.Me.Delete.Cancel;
using Marechai.ApiClient.Auth.Me.Delete.Confirm;
using Marechai.ApiClient.Auth.Me.Delete.Request;
using Marechai.ApiClient.Auth.Me.Delete.Status;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Auth.Me.Delete
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\me\delete
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeleteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::Marechai.ApiClient.Auth.Me.Delete.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::Marechai.ApiClient.Auth.Me.Delete.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The confirm property</summary>
        public global::Marechai.ApiClient.Auth.Me.Delete.Confirm.ConfirmRequestBuilder Confirm
        {
            get => new global::Marechai.ApiClient.Auth.Me.Delete.Confirm.ConfirmRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The request property</summary>
        public global::Marechai.ApiClient.Auth.Me.Delete.Request.RequestRequestBuilder Request
        {
            get => new global::Marechai.ApiClient.Auth.Me.Delete.Request.RequestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Marechai.ApiClient.Auth.Me.Delete.Status.StatusRequestBuilder Status
        {
            get => new global::Marechai.ApiClient.Auth.Me.Delete.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Auth.Me.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/me/delete", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Auth.Me.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/me/delete", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
