// <auto-generated/>
#pragma warning disable CS0618
using Marechai.App.Models;
using Marechai.App.Software.Barcodes;
using Marechai.App.Software.ByLetter;
using Marechai.App.Software.ByPlatform;
using Marechai.App.Software.ByYear;
using Marechai.App.Software.CompanyRoles;
using Marechai.App.Software.Count;
using Marechai.App.Software.Families;
using Marechai.App.Software.Item;
using Marechai.App.Software.MaximumYear;
using Marechai.App.Software.MinimumYear;
using Marechai.App.Software.OsCompatibility;
using Marechai.App.Software.Platforms;
using Marechai.App.Software.ProductCodes;
using Marechai.App.Software.Releases;
using Marechai.App.Software.Requirements;
using Marechai.App.Software.Roles;
using Marechai.App.Software.SubvariantLanguages;
using Marechai.App.Software.Subvariants;
using Marechai.App.Software.VariantLanguages;
using Marechai.App.Software.Variants;
using Marechai.App.Software.Versions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Marechai.App.Software
{
    /// <summary>
    /// Builds and executes requests for operations under \software
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SoftwareRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The barcodes property</summary>
        public global::Marechai.App.Software.Barcodes.BarcodesRequestBuilder Barcodes
        {
            get => new global::Marechai.App.Software.Barcodes.BarcodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The byLetter property</summary>
        public global::Marechai.App.Software.ByLetter.ByLetterRequestBuilder ByLetter
        {
            get => new global::Marechai.App.Software.ByLetter.ByLetterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The byPlatform property</summary>
        public global::Marechai.App.Software.ByPlatform.ByPlatformRequestBuilder ByPlatform
        {
            get => new global::Marechai.App.Software.ByPlatform.ByPlatformRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The byYear property</summary>
        public global::Marechai.App.Software.ByYear.ByYearRequestBuilder ByYear
        {
            get => new global::Marechai.App.Software.ByYear.ByYearRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The companyRoles property</summary>
        public global::Marechai.App.Software.CompanyRoles.CompanyRolesRequestBuilder CompanyRoles
        {
            get => new global::Marechai.App.Software.CompanyRoles.CompanyRolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The count property</summary>
        public global::Marechai.App.Software.Count.CountRequestBuilder Count
        {
            get => new global::Marechai.App.Software.Count.CountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The families property</summary>
        public global::Marechai.App.Software.Families.FamiliesRequestBuilder Families
        {
            get => new global::Marechai.App.Software.Families.FamiliesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The maximumYear property</summary>
        public global::Marechai.App.Software.MaximumYear.MaximumYearRequestBuilder MaximumYear
        {
            get => new global::Marechai.App.Software.MaximumYear.MaximumYearRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The minimumYear property</summary>
        public global::Marechai.App.Software.MinimumYear.MinimumYearRequestBuilder MinimumYear
        {
            get => new global::Marechai.App.Software.MinimumYear.MinimumYearRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The osCompatibility property</summary>
        public global::Marechai.App.Software.OsCompatibility.OsCompatibilityRequestBuilder OsCompatibility
        {
            get => new global::Marechai.App.Software.OsCompatibility.OsCompatibilityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The platforms property</summary>
        public global::Marechai.App.Software.Platforms.PlatformsRequestBuilder Platforms
        {
            get => new global::Marechai.App.Software.Platforms.PlatformsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The productCodes property</summary>
        public global::Marechai.App.Software.ProductCodes.ProductCodesRequestBuilder ProductCodes
        {
            get => new global::Marechai.App.Software.ProductCodes.ProductCodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The releases property</summary>
        public global::Marechai.App.Software.Releases.ReleasesRequestBuilder Releases
        {
            get => new global::Marechai.App.Software.Releases.ReleasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The requirements property</summary>
        public global::Marechai.App.Software.Requirements.RequirementsRequestBuilder Requirements
        {
            get => new global::Marechai.App.Software.Requirements.RequirementsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::Marechai.App.Software.Roles.RolesRequestBuilder Roles
        {
            get => new global::Marechai.App.Software.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subvariantLanguages property</summary>
        public global::Marechai.App.Software.SubvariantLanguages.SubvariantLanguagesRequestBuilder SubvariantLanguages
        {
            get => new global::Marechai.App.Software.SubvariantLanguages.SubvariantLanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subvariants property</summary>
        public global::Marechai.App.Software.Subvariants.SubvariantsRequestBuilder Subvariants
        {
            get => new global::Marechai.App.Software.Subvariants.SubvariantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The variantLanguages property</summary>
        public global::Marechai.App.Software.VariantLanguages.VariantLanguagesRequestBuilder VariantLanguages
        {
            get => new global::Marechai.App.Software.VariantLanguages.VariantLanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The variants property</summary>
        public global::Marechai.App.Software.Variants.VariantsRequestBuilder Variants
        {
            get => new global::Marechai.App.Software.Variants.VariantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The versions property</summary>
        public global::Marechai.App.Software.Versions.VersionsRequestBuilder Versions
        {
            get => new global::Marechai.App.Software.Versions.VersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Marechai.App.software.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.App.Software.Item.ItemRequestBuilder"/></returns>
        public global::Marechai.App.Software.Item.ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("%2Did", position);
                return new global::Marechai.App.Software.Item.ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Marechai.App.software.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.App.Software.Item.ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Marechai.App.Software.Item.ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("%2Did", position);
                return new global::Marechai.App.Software.Item.ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.Software.SoftwareRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SoftwareRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.Software.SoftwareRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SoftwareRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software", rawUrl)
        {
        }
        /// <returns>A List&lt;global::Marechai.App.Models.SoftwareDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Marechai.App.Models.ProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Marechai.App.Models.SoftwareDto>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Marechai.App.Models.SoftwareDto>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Marechai.App.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Marechai.App.Models.SoftwareDto>(requestInfo, global::Marechai.App.Models.SoftwareDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="int"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Marechai.App.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Marechai.App.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<int?> PostAsync(global::Marechai.App.Models.SoftwareDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<int?> PostAsync(global::Marechai.App.Models.SoftwareDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Marechai.App.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::Marechai.App.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<int?>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Marechai.App.Models.SoftwareDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Marechai.App.Models.SoftwareDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Marechai.App.Software.SoftwareRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Marechai.App.Software.SoftwareRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Marechai.App.Software.SoftwareRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SoftwareRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SoftwareRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
