using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class A
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(new {Id = "aaa", Scope = "I", Type = "L", ReferenceName = "Ghotuo"},
                                 new {Id = "aab", Scope = "I", Type = "L", ReferenceName = "Alumu-Tesu"},
                                 new {Id = "aac", Scope = "I", Type = "L", ReferenceName = "Ari"},
                                 new {Id = "aad", Scope = "I", Type = "L", ReferenceName = "Amal"},
                                 new {Id = "aae", Scope = "I", Type = "L", ReferenceName = "Arbëreshë Albanian"},
                                 new {Id = "aaf", Scope = "I", Type = "L", ReferenceName = "Aranadan"},
                                 new {Id = "aag", Scope = "I", Type = "L", ReferenceName = "Ambrak"},
                                 new {Id = "aah", Scope = "I", Type = "L", ReferenceName = "Abu' Arapesh"},
                                 new {Id = "aai", Scope = "I", Type = "L", ReferenceName = "Arifama-Miniafia"},
                                 new {Id = "aak", Scope = "I", Type = "L", ReferenceName = "Ankave"},
                                 new {Id = "aal", Scope = "I", Type = "L", ReferenceName = "Afade"},
                                 new {Id = "aan", Scope = "I", Type = "L", ReferenceName = "Anambé"},
                                 new {Id = "aao", Scope = "I", Type = "L", ReferenceName = "Algerian Saharan Arabic"},
                                 new {Id = "aap", Scope = "I", Type = "L", ReferenceName = "Pará Arára"},
                                 new {Id = "aaq", Scope = "I", Type = "E", ReferenceName = "Eastern Abnaki"},
                                 new
                                 {
                                     Id            = "aar",
                                     Part2B        = "aar",
                                     Part2T        = "aar",
                                     Part1         = "aa",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Afar"
                                 }, new {Id = "aas", Scope = "I", Type = "L", ReferenceName = "Aasáx"},
                                 new {Id    = "aat", Scope = "I", Type = "L", ReferenceName = "Arvanitika Albanian"},
                                 new {Id    = "aau", Scope = "I", Type = "L", ReferenceName = "Abau"},
                                 new {Id    = "aaw", Scope = "I", Type = "L", ReferenceName = "Solong"},
                                 new {Id    = "aax", Scope = "I", Type = "L", ReferenceName = "Mandobo Atas"},
                                 new {Id    = "aaz", Scope = "I", Type = "L", ReferenceName = "Amarasi"},
                                 new {Id    = "aba", Scope = "I", Type = "L", ReferenceName = "Abé"},
                                 new {Id    = "abb", Scope = "I", Type = "L", ReferenceName = "Bankon"},
                                 new {Id    = "abc", Scope = "I", Type = "L", ReferenceName = "Ambala Ayta"},
                                 new {Id    = "abd", Scope = "I", Type = "L", ReferenceName = "Manide"},
                                 new {Id    = "abe", Scope = "I", Type = "L", ReferenceName = "Western Abnaki"},
                                 new {Id    = "abf", Scope = "I", Type = "L", ReferenceName = "Abai Sungai"},
                                 new {Id    = "abg", Scope = "I", Type = "L", ReferenceName = "Abaga"},
                                 new {Id    = "abh", Scope = "I", Type = "L", ReferenceName = "Tajiki Arabic"},
                                 new {Id    = "abi", Scope = "I", Type = "L", ReferenceName = "Abidji"},
                                 new {Id    = "abj", Scope = "I", Type = "E", ReferenceName = "Aka-Bea"},
                                 new
                                 {
                                     Id            = "abk",
                                     Part2B        = "abk",
                                     Part2T        = "abk",
                                     Part1         = "ab",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Abkhazian"
                                 }, new {Id = "abl", Scope = "I", Type = "L", ReferenceName = "Lampung Nyo"},
                                 new {Id    = "abm", Scope = "I", Type = "L", ReferenceName = "Abanyom"},
                                 new {Id    = "abn", Scope = "I", Type = "L", ReferenceName = "Abua"},
                                 new {Id    = "abo", Scope = "I", Type = "L", ReferenceName = "Abon"},
                                 new {Id    = "abp", Scope = "I", Type = "L", ReferenceName = "Abellen Ayta"},
                                 new {Id    = "abq", Scope = "I", Type = "L", ReferenceName = "Abaza"},
                                 new {Id    = "abr", Scope = "I", Type = "L", ReferenceName = "Abron"},
                                 new {Id    = "abs", Scope = "I", Type = "L", ReferenceName = "Ambonese Malay"},
                                 new {Id    = "abt", Scope = "I", Type = "L", ReferenceName = "Ambulas"},
                                 new {Id    = "abu", Scope = "I", Type = "L", ReferenceName = "Abure"},
                                 new {Id    = "abv", Scope = "I", Type = "L", ReferenceName = "Baharna Arabic"},
                                 new {Id    = "abw", Scope = "I", Type = "L", ReferenceName = "Pal"},
                                 new {Id    = "abx", Scope = "I", Type = "L", ReferenceName = "Inabaknon"},
                                 new {Id    = "aby", Scope = "I", Type = "L", ReferenceName = "Aneme Wake"},
                                 new {Id    = "abz", Scope = "I", Type = "L", ReferenceName = "Abui"},
                                 new {Id    = "aca", Scope = "I", Type = "L", ReferenceName = "Achagua"},
                                 new {Id    = "acb", Scope = "I", Type = "L", ReferenceName = "Áncá"},
                                 new {Id    = "acd", Scope = "I", Type = "L", ReferenceName = "Gikyode"},
                                 new
                                 {
                                     Id            = "ace",
                                     Part2B        = "ace",
                                     Part2T        = "ace",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Achinese"
                                 },
                                 new
                                 {
                                     Id            = "acf",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Saint Lucian Creole French"
                                 }, new
                                 {
                                     Id            = "ach",
                                     Part2B        = "ach",
                                     Part2T        = "ach",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Acoli"
                                 }, new {Id = "aci", Scope = "I", Type = "E", ReferenceName = "Aka-Cari"},
                                 new {Id    = "ack", Scope = "I", Type = "E", ReferenceName = "Aka-Kora"},
                                 new {Id    = "acl", Scope = "I", Type = "E", ReferenceName = "Akar-Bale"},
                                 new {Id    = "acm", Scope = "I", Type = "L", ReferenceName = "Mesopotamian Arabic"},
                                 new {Id    = "acn", Scope = "I", Type = "L", ReferenceName = "Achang"},
                                 new {Id    = "acp", Scope = "I", Type = "L", ReferenceName = "Eastern Acipa"},
                                 new {Id    = "acq", Scope = "I", Type = "L", ReferenceName = "Ta'izzi-Adeni Arabic"},
                                 new {Id    = "acr", Scope = "I", Type = "L", ReferenceName = "Achi"},
                                 new {Id    = "acs", Scope = "I", Type = "E", ReferenceName = "Acroá"},
                                 new {Id    = "act", Scope = "I", Type = "L", ReferenceName = "Achterhoeks"},
                                 new {Id    = "acu", Scope = "I", Type = "L", ReferenceName = "Achuar-Shiwiar"},
                                 new {Id    = "acv", Scope = "I", Type = "L", ReferenceName = "Achumawi"},
                                 new {Id    = "acw", Scope = "I", Type = "L", ReferenceName = "Hijazi Arabic"},
                                 new {Id    = "acx", Scope = "I", Type = "L", ReferenceName = "Omani Arabic"},
                                 new {Id    = "acy", Scope = "I", Type = "L", ReferenceName = "Cypriot Arabic"},
                                 new {Id    = "acz", Scope = "I", Type = "L", ReferenceName = "Acheron"},
                                 new
                                 {
                                     Id            = "ada",
                                     Part2B        = "ada",
                                     Part2T        = "ada",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Adangme"
                                 }, new {Id = "adb", Scope = "I", Type = "L", ReferenceName = "Adabe"},
                                 new {Id    = "add", Scope = "I", Type = "L", ReferenceName = "Lidzonka"},
                                 new {Id    = "ade", Scope = "I", Type = "L", ReferenceName = "Adele"},
                                 new {Id    = "adf", Scope = "I", Type = "L", ReferenceName = "Dhofari Arabic"},
                                 new {Id    = "adg", Scope = "I", Type = "L", ReferenceName = "Andegerebinha"},
                                 new {Id    = "adh", Scope = "I", Type = "L", ReferenceName = "Adhola"},
                                 new {Id    = "adi", Scope = "I", Type = "L", ReferenceName = "Adi"},
                                 new {Id    = "adj", Scope = "I", Type = "L", ReferenceName = "Adioukrou"},
                                 new {Id    = "adl", Scope = "I", Type = "L", ReferenceName = "Galo"},
                                 new {Id    = "adn", Scope = "I", Type = "L", ReferenceName = "Adang"},
                                 new {Id    = "ado", Scope = "I", Type = "L", ReferenceName = "Abu"},
                                 new {Id    = "adq", Scope = "I", Type = "L", ReferenceName = "Adangbe"},
                                 new {Id    = "adr", Scope = "I", Type = "L", ReferenceName = "Adonara"},
                                 new
                                     {
                                         Id            = "ads",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Adamorobe Sign Language"
                                     },
                                 new {Id = "adt", Scope = "I", Type = "L", ReferenceName = "Adnyamathanha"},
                                 new {Id = "adu", Scope = "I", Type = "L", ReferenceName = "Aduge"},
                                 new {Id = "adw", Scope = "I", Type = "L", ReferenceName = "Amundava"},
                                 new {Id = "adx", Scope = "I", Type = "L", ReferenceName = "Amdo Tibetan"},
                                 new
                                 {
                                     Id            = "ady",
                                     Part2B        = "ady",
                                     Part2T        = "ady",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Adyghe"
                                 }, new {Id = "adz", Scope = "I", Type = "L", ReferenceName = "Adzera"},
                                 new {Id    = "aea", Scope = "I", Type = "E", ReferenceName = "Areba"},
                                 new {Id    = "aeb", Scope = "I", Type = "L", ReferenceName = "Tunisian Arabic"},
                                 new {Id    = "aec", Scope = "I", Type = "L", ReferenceName = "Saidi Arabic"},
                                 new
                                     {
                                         Id            = "aed",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Argentine Sign Language"
                                     },
                                 new {Id = "aee", Scope = "I", Type = "L", ReferenceName = "Northeast Pashai"},
                                 new {Id = "aek", Scope = "I", Type = "L", ReferenceName = "Haeke"},
                                 new {Id = "ael", Scope = "I", Type = "L", ReferenceName = "Ambele"},
                                 new {Id = "aem", Scope = "I", Type = "L", ReferenceName = "Arem"},
                                 new {Id = "aen", Scope = "I", Type = "L", ReferenceName = "Armenian Sign Language"},
                                 new {Id = "aeq", Scope = "I", Type = "L", ReferenceName = "Aer"},
                                 new {Id = "aer", Scope = "I", Type = "L", ReferenceName = "Eastern Arrernte"},
                                 new {Id = "aes", Scope = "I", Type = "E", ReferenceName = "Alsea"},
                                 new {Id = "aeu", Scope = "I", Type = "L", ReferenceName = "Akeu"},
                                 new {Id = "aew", Scope = "I", Type = "L", ReferenceName = "Ambakich"},
                                 new {Id = "aey", Scope = "I", Type = "L", ReferenceName = "Amele"},
                                 new {Id = "aez", Scope = "I", Type = "L", ReferenceName = "Aeka"},
                                 new {Id = "afb", Scope = "I", Type = "L", ReferenceName = "Gulf Arabic"},
                                 new {Id = "afd", Scope = "I", Type = "L", ReferenceName = "Andai"},
                                 new {Id = "afe", Scope = "I", Type = "L", ReferenceName = "Putukwam"},
                                 new {Id = "afg", Scope = "I", Type = "L", ReferenceName = "Afghan Sign Language"},
                                 new
                                 {
                                     Id            = "afh",
                                     Part2B        = "afh",
                                     Part2T        = "afh",
                                     Scope         = "I",
                                     Type          = "C",
                                     ReferenceName = "Afrihili"
                                 }, new {Id = "afi", Scope = "I", Type = "L", ReferenceName = "Akrukay"},
                                 new {Id    = "afk", Scope = "I", Type = "L", ReferenceName = "Nanubae"},
                                 new {Id    = "afn", Scope = "I", Type = "L", ReferenceName = "Defaka"},
                                 new {Id    = "afo", Scope = "I", Type = "L", ReferenceName = "Eloyi"},
                                 new {Id    = "afp", Scope = "I", Type = "L", ReferenceName = "Tapei"},
                                 new
                                 {
                                     Id            = "afr",
                                     Part2B        = "afr",
                                     Part2T        = "afr",
                                     Part1         = "af",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Afrikaans"
                                 }, new {Id = "afs", Scope = "I", Type = "L", ReferenceName = "Afro-Seminole Creole"},
                                 new {Id    = "aft", Scope = "I", Type = "L", ReferenceName = "Afitti"},
                                 new {Id    = "afu", Scope = "I", Type = "L", ReferenceName = "Awutu"},
                                 new {Id    = "afz", Scope = "I", Type = "L", ReferenceName = "Obokuitai"},
                                 new {Id    = "aga", Scope = "I", Type = "E", ReferenceName = "Aguano"},
                                 new {Id    = "agb", Scope = "I", Type = "L", ReferenceName = "Legbo"},
                                 new {Id    = "agc", Scope = "I", Type = "L", ReferenceName = "Agatu"},
                                 new {Id    = "agd", Scope = "I", Type = "L", ReferenceName = "Agarabi"},
                                 new {Id    = "age", Scope = "I", Type = "L", ReferenceName = "Angal"},
                                 new {Id    = "agf", Scope = "I", Type = "L", ReferenceName = "Arguni"},
                                 new {Id    = "agg", Scope = "I", Type = "L", ReferenceName = "Angor"},
                                 new {Id    = "agh", Scope = "I", Type = "L", ReferenceName = "Ngelima"},
                                 new {Id    = "agi", Scope = "I", Type = "L", ReferenceName = "Agariya"},
                                 new {Id    = "agj", Scope = "I", Type = "L", ReferenceName = "Argobba"},
                                 new {Id    = "agk", Scope = "I", Type = "L", ReferenceName = "Isarog Agta"},
                                 new {Id    = "agl", Scope = "I", Type = "L", ReferenceName = "Fembe"},
                                 new {Id    = "agm", Scope = "I", Type = "L", ReferenceName = "Angaataha"},
                                 new {Id    = "agn", Scope = "I", Type = "L", ReferenceName = "Agutaynen"},
                                 new {Id    = "ago", Scope = "I", Type = "L", ReferenceName = "Tainae"},
                                 new {Id    = "agq", Scope = "I", Type = "L", ReferenceName = "Aghem"},
                                 new {Id    = "agr", Scope = "I", Type = "L", ReferenceName = "Aguaruna"},
                                 new {Id    = "ags", Scope = "I", Type = "L", ReferenceName = "Esimbi"},
                                 new {Id    = "agt", Scope = "I", Type = "L", ReferenceName = "Central Cagayan Agta"},
                                 new {Id    = "agu", Scope = "I", Type = "L", ReferenceName = "Aguacateco"},
                                 new {Id    = "agv", Scope = "I", Type = "L", ReferenceName = "Remontado Dumagat"},
                                 new {Id    = "agw", Scope = "I", Type = "L", ReferenceName = "Kahua"},
                                 new {Id    = "agx", Scope = "I", Type = "L", ReferenceName = "Aghul"},
                                 new {Id    = "agy", Scope = "I", Type = "L", ReferenceName = "Southern Alta"},
                                 new {Id    = "agz", Scope = "I", Type = "L", ReferenceName = "Mt. Iriga Agta"},
                                 new {Id    = "aha", Scope = "I", Type = "L", ReferenceName = "Ahanta"},
                                 new {Id    = "ahb", Scope = "I", Type = "L", ReferenceName = "Axamb"},
                                 new {Id    = "ahg", Scope = "I", Type = "L", ReferenceName = "Qimant"},
                                 new {Id    = "ahh", Scope = "I", Type = "L", ReferenceName = "Aghu"},
                                 new {Id    = "ahi", Scope = "I", Type = "L", ReferenceName = "Tiagbamrin Aizi"},
                                 new {Id    = "ahk", Scope = "I", Type = "L", ReferenceName = "Akha"},
                                 new {Id    = "ahl", Scope = "I", Type = "L", ReferenceName = "Igo"},
                                 new {Id    = "ahm", Scope = "I", Type = "L", ReferenceName = "Mobumrin Aizi"},
                                 new {Id    = "ahn", Scope = "I", Type = "L", ReferenceName = "Àhàn"},
                                 new {Id    = "aho", Scope = "I", Type = "E", ReferenceName = "Ahom"},
                                 new {Id    = "ahp", Scope = "I", Type = "L", ReferenceName = "Aproumu Aizi"},
                                 new {Id    = "ahr", Scope = "I", Type = "L", ReferenceName = "Ahirani"},
                                 new {Id    = "ahs", Scope = "I", Type = "L", ReferenceName = "Ashe"},
                                 new {Id    = "aht", Scope = "I", Type = "L", ReferenceName = "Ahtena"},
                                 new {Id    = "aia", Scope = "I", Type = "L", ReferenceName = "Arosi"},
                                 new {Id    = "aib", Scope = "I", Type = "L", ReferenceName = "Ainu (China)"},
                                 new {Id    = "aic", Scope = "I", Type = "L", ReferenceName = "Ainbai"},
                                 new {Id    = "aid", Scope = "I", Type = "E", ReferenceName = "Alngith"},
                                 new {Id    = "aie", Scope = "I", Type = "L", ReferenceName = "Amara"},
                                 new {Id    = "aif", Scope = "I", Type = "L", ReferenceName = "Agi"},
                                 new
                                 {
                                     Id            = "aig",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Antigua and Barbuda Creole English"
                                 }, new {Id = "aih", Scope = "I", Type = "L", ReferenceName = "Ai-Cham"},
                                 new
                                     {
                                         Id            = "aii",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Assyrian Neo-Aramaic"
                                     },
                                 new {Id = "aij", Scope = "I", Type = "L", ReferenceName = "Lishanid Noshan"},
                                 new {Id = "aik", Scope = "I", Type = "L", ReferenceName = "Ake"},
                                 new {Id = "ail", Scope = "I", Type = "L", ReferenceName = "Aimele"},
                                 new {Id = "aim", Scope = "I", Type = "L", ReferenceName = "Aimol"},
                                 new
                                 {
                                     Id            = "ain",
                                     Part2B        = "ain",
                                     Part2T        = "ain",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Ainu (Japan)"
                                 }, new {Id = "aio", Scope = "I", Type = "L", ReferenceName = "Aiton"},
                                 new {Id    = "aip", Scope = "I", Type = "L", ReferenceName = "Burumakok"},
                                 new {Id    = "aiq", Scope = "I", Type = "L", ReferenceName = "Aimaq"},
                                 new {Id    = "air", Scope = "I", Type = "L", ReferenceName = "Airoran"},
                                 new {Id    = "ait", Scope = "I", Type = "E", ReferenceName = "Arikem"},
                                 new {Id    = "aiw", Scope = "I", Type = "L", ReferenceName = "Aari"},
                                 new {Id    = "aix", Scope = "I", Type = "L", ReferenceName = "Aighon"},
                                 new {Id    = "aiy", Scope = "I", Type = "L", ReferenceName = "Ali"},
                                 new {Id    = "aja", Scope = "I", Type = "L", ReferenceName = "Aja (South Sudan)"},
                                 new {Id    = "ajg", Scope = "I", Type = "L", ReferenceName = "Aja (Benin)"},
                                 new {Id    = "aji", Scope = "I", Type = "L", ReferenceName = "Ajië"},
                                 new {Id    = "ajn", Scope = "I", Type = "L", ReferenceName = "Andajin"},
                                 new {Id    = "ajp", Scope = "I", Type = "L", ReferenceName = "South Levantine Arabic"},
                                 new {Id    = "ajt", Scope = "I", Type = "L", ReferenceName = "Judeo-Tunisian Arabic"},
                                 new {Id    = "aju", Scope = "I", Type = "L", ReferenceName = "Judeo-Moroccan Arabic"},
                                 new {Id    = "ajw", Scope = "I", Type = "E", ReferenceName = "Ajawa"},
                                 new {Id    = "ajz", Scope = "I", Type = "L", ReferenceName = "Amri Karbi"},
                                 new
                                 {
                                     Id            = "aka",
                                     Part2B        = "aka",
                                     Part2T        = "aka",
                                     Part1         = "ak",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Akan"
                                 }, new {Id = "akb", Scope = "I", Type = "L", ReferenceName = "Batak Angkola"},
                                 new {Id    = "akc", Scope = "I", Type = "L", ReferenceName = "Mpur"},
                                 new {Id    = "akd", Scope = "I", Type = "L", ReferenceName = "Ukpet-Ehom"},
                                 new {Id    = "ake", Scope = "I", Type = "L", ReferenceName = "Akawaio"},
                                 new {Id    = "akf", Scope = "I", Type = "L", ReferenceName = "Akpa"},
                                 new {Id    = "akg", Scope = "I", Type = "L", ReferenceName = "Anakalangu"},
                                 new {Id    = "akh", Scope = "I", Type = "L", ReferenceName = "Angal Heneng"},
                                 new {Id    = "aki", Scope = "I", Type = "L", ReferenceName = "Aiome"},
                                 new {Id    = "akj", Scope = "I", Type = "E", ReferenceName = "Aka-Jeru"},
                                 new
                                 {
                                     Id            = "akk",
                                     Part2B        = "akk",
                                     Part2T        = "akk",
                                     Scope         = "I",
                                     Type          = "A",
                                     ReferenceName = "Akkadian"
                                 }, new {Id = "akl", Scope = "I", Type = "L", ReferenceName = "Aklanon"},
                                 new {Id    = "akm", Scope = "I", Type = "E", ReferenceName = "Aka-Bo"},
                                 new {Id    = "ako", Scope = "I", Type = "L", ReferenceName = "Akurio"},
                                 new {Id    = "akp", Scope = "I", Type = "L", ReferenceName = "Siwu"},
                                 new {Id    = "akq", Scope = "I", Type = "L", ReferenceName = "Ak"},
                                 new {Id    = "akr", Scope = "I", Type = "L", ReferenceName = "Araki"},
                                 new {Id    = "aks", Scope = "I", Type = "L", ReferenceName = "Akaselem"},
                                 new {Id    = "akt", Scope = "I", Type = "L", ReferenceName = "Akolet"},
                                 new {Id    = "aku", Scope = "I", Type = "L", ReferenceName = "Akum"},
                                 new {Id    = "akv", Scope = "I", Type = "L", ReferenceName = "Akhvakh"},
                                 new {Id    = "akw", Scope = "I", Type = "L", ReferenceName = "Akwa"},
                                 new {Id    = "akx", Scope = "I", Type = "E", ReferenceName = "Aka-Kede"},
                                 new {Id    = "aky", Scope = "I", Type = "E", ReferenceName = "Aka-Kol"},
                                 new {Id    = "akz", Scope = "I", Type = "L", ReferenceName = "Alabama"},
                                 new {Id    = "ala", Scope = "I", Type = "L", ReferenceName = "Alago"},
                                 new {Id    = "alc", Scope = "I", Type = "L", ReferenceName = "Qawasqar"},
                                 new {Id    = "ald", Scope = "I", Type = "L", ReferenceName = "Alladian"},
                                 new
                                 {
                                     Id            = "ale",
                                     Part2B        = "ale",
                                     Part2T        = "ale",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Aleut"
                                 }, new {Id = "alf", Scope = "I", Type = "L", ReferenceName = "Alege"},
                                 new {Id    = "alh", Scope = "I", Type = "L", ReferenceName = "Alawa"},
                                 new {Id    = "ali", Scope = "I", Type = "L", ReferenceName = "Amaimon"},
                                 new {Id    = "alj", Scope = "I", Type = "L", ReferenceName = "Alangan"},
                                 new {Id    = "alk", Scope = "I", Type = "L", ReferenceName = "Alak"},
                                 new {Id    = "all", Scope = "I", Type = "L", ReferenceName = "Allar"},
                                 new {Id    = "alm", Scope = "I", Type = "L", ReferenceName = "Amblong"},
                                 new {Id    = "aln", Scope = "I", Type = "L", ReferenceName = "Gheg Albanian"},
                                 new {Id    = "alo", Scope = "I", Type = "L", ReferenceName = "Larike-Wakasihu"},
                                 new {Id    = "alp", Scope = "I", Type = "L", ReferenceName = "Alune"},
                                 new {Id    = "alq", Scope = "I", Type = "L", ReferenceName = "Algonquin"},
                                 new {Id    = "alr", Scope = "I", Type = "L", ReferenceName = "Alutor"},
                                 new {Id    = "als", Scope = "I", Type = "L", ReferenceName = "Tosk Albanian"},
                                 new
                                 {
                                     Id            = "alt",
                                     Part2B        = "alt",
                                     Part2T        = "alt",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Southern Altai"
                                 }, new {Id = "alu", Scope = "I", Type = "L", ReferenceName = "'Are'are"},
                                 new {Id    = "alw", Scope = "I", Type = "L", ReferenceName = "Alaba-K’abeena"},
                                 new {Id    = "alx", Scope = "I", Type = "L", ReferenceName = "Amol"},
                                 new {Id    = "aly", Scope = "I", Type = "L", ReferenceName = "Alyawarr"},
                                 new {Id    = "alz", Scope = "I", Type = "L", ReferenceName = "Alur"},
                                 new {Id    = "ama", Scope = "I", Type = "E", ReferenceName = "Amanayé"},
                                 new {Id    = "amb", Scope = "I", Type = "L", ReferenceName = "Ambo"},
                                 new {Id    = "amc", Scope = "I", Type = "L", ReferenceName = "Amahuaca"},
                                 new {Id    = "ame", Scope = "I", Type = "L", ReferenceName = "Yanesha'"},
                                 new {Id    = "amf", Scope = "I", Type = "L", ReferenceName = "Hamer-Banna"},
                                 new {Id    = "amg", Scope = "I", Type = "L", ReferenceName = "Amurdak"},
                                 new
                                 {
                                     Id            = "amh",
                                     Part2B        = "amh",
                                     Part2T        = "amh",
                                     Part1         = "am",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Amharic"
                                 }, new {Id = "ami", Scope = "I", Type = "L", ReferenceName = "Amis"},
                                 new {Id    = "amj", Scope = "I", Type = "L", ReferenceName = "Amdang"},
                                 new {Id    = "amk", Scope = "I", Type = "L", ReferenceName = "Ambai"},
                                 new {Id    = "aml", Scope = "I", Type = "L", ReferenceName = "War-Jaintia"},
                                 new {Id    = "amm", Scope = "I", Type = "L", ReferenceName = "Ama (Papua New Guinea)"},
                                 new {Id    = "amn", Scope = "I", Type = "L", ReferenceName = "Amanab"},
                                 new {Id    = "amo", Scope = "I", Type = "L", ReferenceName = "Amo"},
                                 new {Id    = "amp", Scope = "I", Type = "L", ReferenceName = "Alamblak"},
                                 new {Id    = "amq", Scope = "I", Type = "L", ReferenceName = "Amahai"},
                                 new {Id    = "amr", Scope = "I", Type = "L", ReferenceName = "Amarakaeri"},
                                 new {Id    = "ams", Scope = "I", Type = "L", ReferenceName = "Southern Amami-Oshima"},
                                 new {Id    = "amt", Scope = "I", Type = "L", ReferenceName = "Amto"},
                                 new {Id    = "amu", Scope = "I", Type = "L", ReferenceName = "Guerrero Amuzgo"},
                                 new {Id    = "amv", Scope = "I", Type = "L", ReferenceName = "Ambelau"},
                                 new {Id    = "amw", Scope = "I", Type = "L", ReferenceName = "Western Neo-Aramaic"},
                                 new {Id    = "amx", Scope = "I", Type = "L", ReferenceName = "Anmatyerre"},
                                 new {Id    = "amy", Scope = "I", Type = "L", ReferenceName = "Ami"},
                                 new {Id    = "amz", Scope = "I", Type = "E", ReferenceName = "Atampaya"},
                                 new {Id    = "ana", Scope = "I", Type = "E", ReferenceName = "Andaqui"},
                                 new {Id    = "anb", Scope = "I", Type = "E", ReferenceName = "Andoa"},
                                 new {Id    = "anc", Scope = "I", Type = "L", ReferenceName = "Ngas"},
                                 new {Id    = "and", Scope = "I", Type = "L", ReferenceName = "Ansus"},
                                 new {Id    = "ane", Scope = "I", Type = "L", ReferenceName = "Xârâcùù"},
                                 new {Id    = "anf", Scope = "I", Type = "L", ReferenceName = "Animere"},
                                 new
                                 {
                                     Id            = "ang",
                                     Part2B        = "ang",
                                     Part2T        = "ang",
                                     Scope         = "I",
                                     Type          = "H",
                                     ReferenceName = "Old English (ca. 450-1100)"
                                 }, new {Id = "anh", Scope = "I", Type = "L", ReferenceName = "Nend"},
                                 new {Id    = "ani", Scope = "I", Type = "L", ReferenceName = "Andi"},
                                 new {Id    = "anj", Scope = "I", Type = "L", ReferenceName = "Anor"},
                                 new {Id    = "ank", Scope = "I", Type = "L", ReferenceName = "Goemai"},
                                 new {Id    = "anl", Scope = "I", Type = "L", ReferenceName = "Anu-Hkongso Chin"},
                                 new {Id    = "anm", Scope = "I", Type = "L", ReferenceName = "Anal"},
                                 new {Id    = "ann", Scope = "I", Type = "L", ReferenceName = "Obolo"},
                                 new {Id    = "ano", Scope = "I", Type = "L", ReferenceName = "Andoque"},
                                 new
                                 {
                                     Id            = "anp",
                                     Part2B        = "anp",
                                     Part2T        = "anp",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Angika"
                                 }, new {Id = "anq", Scope = "I", Type = "L", ReferenceName = "Jarawa (India)"},
                                 new {Id    = "anr", Scope = "I", Type = "L", ReferenceName = "Andh"},
                                 new {Id    = "ans", Scope = "I", Type = "E", ReferenceName = "Anserma"},
                                 new {Id    = "ant", Scope = "I", Type = "L", ReferenceName = "Antakarinya"},
                                 new {Id    = "anu", Scope = "I", Type = "L", ReferenceName = "Anuak"},
                                 new {Id    = "anv", Scope = "I", Type = "L", ReferenceName = "Denya"},
                                 new {Id    = "anw", Scope = "I", Type = "L", ReferenceName = "Anaang"},
                                 new {Id    = "anx", Scope = "I", Type = "L", ReferenceName = "Andra-Hus"},
                                 new {Id    = "any", Scope = "I", Type = "L", ReferenceName = "Anyin"},
                                 new {Id    = "anz", Scope = "I", Type = "L", ReferenceName = "Anem"},
                                 new {Id    = "aoa", Scope = "I", Type = "L", ReferenceName = "Angolar"},
                                 new {Id    = "aob", Scope = "I", Type = "L", ReferenceName = "Abom"},
                                 new {Id    = "aoc", Scope = "I", Type = "L", ReferenceName = "Pemon"},
                                 new {Id    = "aod", Scope = "I", Type = "L", ReferenceName = "Andarum"},
                                 new {Id    = "aoe", Scope = "I", Type = "L", ReferenceName = "Angal Enen"},
                                 new {Id    = "aof", Scope = "I", Type = "L", ReferenceName = "Bragat"},
                                 new {Id    = "aog", Scope = "I", Type = "L", ReferenceName = "Angoram"},
                                 new {Id    = "aoh", Scope = "I", Type = "E", ReferenceName = "Arma"},
                                 new {Id    = "aoi", Scope = "I", Type = "L", ReferenceName = "Anindilyakwa"},
                                 new {Id    = "aoj", Scope = "I", Type = "L", ReferenceName = "Mufian"},
                                 new {Id    = "aok", Scope = "I", Type = "L", ReferenceName = "Arhö"},
                                 new {Id    = "aol", Scope = "I", Type = "L", ReferenceName = "Alor"},
                                 new {Id    = "aom", Scope = "I", Type = "L", ReferenceName = "Ömie"},
                                 new {Id    = "aon", Scope = "I", Type = "L", ReferenceName = "Bumbita Arapesh"},
                                 new {Id    = "aor", Scope = "I", Type = "E", ReferenceName = "Aore"},
                                 new {Id    = "aos", Scope = "I", Type = "L", ReferenceName = "Taikat"},
                                 new {Id    = "aot", Scope = "I", Type = "L", ReferenceName = "Atong (India)"},
                                 new {Id    = "aou", Scope = "I", Type = "L", ReferenceName = "A'ou"},
                                 new {Id    = "aox", Scope = "I", Type = "L", ReferenceName = "Atorada"},
                                 new {Id    = "aoz", Scope = "I", Type = "L", ReferenceName = "Uab Meto"},
                                 new {Id    = "apb", Scope = "I", Type = "L", ReferenceName = "Sa'a"},
                                 new {Id    = "apc", Scope = "I", Type = "L", ReferenceName = "North Levantine Arabic"},
                                 new {Id    = "apd", Scope = "I", Type = "L", ReferenceName = "Sudanese Arabic"},
                                 new {Id    = "ape", Scope = "I", Type = "L", ReferenceName = "Bukiyip"},
                                 new {Id    = "apf", Scope = "I", Type = "L", ReferenceName = "Pahanan Agta"},
                                 new {Id    = "apg", Scope = "I", Type = "L", ReferenceName = "Ampanang"},
                                 new {Id    = "aph", Scope = "I", Type = "L", ReferenceName = "Athpariya"},
                                 new {Id    = "api", Scope = "I", Type = "L", ReferenceName = "Apiaká"},
                                 new {Id    = "apj", Scope = "I", Type = "L", ReferenceName = "Jicarilla Apache"},
                                 new {Id    = "apk", Scope = "I", Type = "L", ReferenceName = "Kiowa Apache"},
                                 new {Id    = "apl", Scope = "I", Type = "L", ReferenceName = "Lipan Apache"},
                                 new
                                 {
                                     Id            = "apm",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mescalero-Chiricahua Apache"
                                 }, new {Id = "apn", Scope = "I", Type = "L", ReferenceName = "Apinayé"},
                                 new {Id    = "apo", Scope = "I", Type = "L", ReferenceName = "Ambul"},
                                 new {Id    = "app", Scope = "I", Type = "L", ReferenceName = "Apma"},
                                 new {Id    = "apq", Scope = "I", Type = "L", ReferenceName = "A-Pucikwar"},
                                 new {Id    = "apr", Scope = "I", Type = "L", ReferenceName = "Arop-Lokep"},
                                 new {Id    = "aps", Scope = "I", Type = "L", ReferenceName = "Arop-Sissano"},
                                 new {Id    = "apt", Scope = "I", Type = "L", ReferenceName = "Apatani"},
                                 new {Id    = "apu", Scope = "I", Type = "L", ReferenceName = "Apurinã"},
                                 new {Id    = "apv", Scope = "I", Type = "E", ReferenceName = "Alapmunte"},
                                 new {Id    = "apw", Scope = "I", Type = "L", ReferenceName = "Western Apache"},
                                 new {Id    = "apx", Scope = "I", Type = "L", ReferenceName = "Aputai"},
                                 new {Id    = "apy", Scope = "I", Type = "L", ReferenceName = "Apalaí"},
                                 new {Id    = "apz", Scope = "I", Type = "L", ReferenceName = "Safeyoka"},
                                 new {Id    = "aqc", Scope = "I", Type = "L", ReferenceName = "Archi"},
                                 new {Id    = "aqd", Scope = "I", Type = "L", ReferenceName = "Ampari Dogon"},
                                 new {Id    = "aqg", Scope = "I", Type = "L", ReferenceName = "Arigidi"},
                                 new {Id    = "aqm", Scope = "I", Type = "L", ReferenceName = "Atohwaim"},
                                 new {Id    = "aqn", Scope = "I", Type = "L", ReferenceName = "Northern Alta"},
                                 new {Id    = "aqp", Scope = "I", Type = "E", ReferenceName = "Atakapa"},
                                 new {Id    = "aqr", Scope = "I", Type = "L", ReferenceName = "Arhâ"},
                                 new {Id    = "aqt", Scope = "I", Type = "L", ReferenceName = "Angaité"},
                                 new {Id    = "aqz", Scope = "I", Type = "L", ReferenceName = "Akuntsu"},
                                 new
                                 {
                                     Id            = "ara",
                                     Part2B        = "ara",
                                     Part2T        = "ara",
                                     Part1         = "ar",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Arabic"
                                 }, new {Id = "arb", Scope = "I", Type = "L", ReferenceName = "Standard Arabic"},
                                 new
                                 {
                                     Id            = "arc",
                                     Part2B        = "arc",
                                     Part2T        = "arc",
                                     Scope         = "I",
                                     Type          = "A",
                                     ReferenceName = "Official Aramaic (700-300 BCE)"
                                 }, new {Id = "ard", Scope = "I", Type = "E", ReferenceName = "Arabana"},
                                 new {Id    = "are", Scope = "I", Type = "L", ReferenceName = "Western Arrarnta"},
                                 new
                                 {
                                     Id            = "arg",
                                     Part2B        = "arg",
                                     Part2T        = "arg",
                                     Part1         = "an",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Aragonese"
                                 }, new {Id = "arh", Scope = "I", Type = "L", ReferenceName = "Arhuaco"},
                                 new {Id    = "ari", Scope = "I", Type = "L", ReferenceName = "Arikara"},
                                 new {Id    = "arj", Scope = "I", Type = "E", ReferenceName = "Arapaso"},
                                 new {Id    = "ark", Scope = "I", Type = "L", ReferenceName = "Arikapú"},
                                 new {Id    = "arl", Scope = "I", Type = "L", ReferenceName = "Arabela"},
                                 new
                                 {
                                     Id            = "arn",
                                     Part2B        = "arn",
                                     Part2T        = "arn",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mapudungun"
                                 }, new {Id = "aro", Scope = "I", Type = "L", ReferenceName = "Araona"},
                                 new
                                 {
                                     Id            = "arp",
                                     Part2B        = "arp",
                                     Part2T        = "arp",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Arapaho"
                                 }, new {Id = "arq", Scope = "I", Type = "L", ReferenceName = "Algerian Arabic"},
                                 new {Id    = "arr", Scope = "I", Type = "L", ReferenceName = "Karo (Brazil)"},
                                 new {Id    = "ars", Scope = "I", Type = "L", ReferenceName = "Najdi Arabic"},
                                 new {Id    = "aru", Scope = "I", Type = "E", ReferenceName = "Aruá (Amazonas State)"},
                                 new {Id    = "arv", Scope = "I", Type = "L", ReferenceName = "Arbore"},
                                 new
                                 {
                                     Id            = "arw",
                                     Part2B        = "arw",
                                     Part2T        = "arw",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Arawak"
                                 }, new {Id = "arx", Scope = "I", Type = "L", ReferenceName = "Aruá (Rodonia State)"},
                                 new {Id    = "ary", Scope = "I", Type = "L", ReferenceName = "Moroccan Arabic"},
                                 new {Id    = "arz", Scope = "I", Type = "L", ReferenceName = "Egyptian Arabic"},
                                 new {Id    = "asa", Scope = "I", Type = "L", ReferenceName = "Asu (Tanzania)"},
                                 new {Id    = "asb", Scope = "I", Type = "L", ReferenceName = "Assiniboine"},
                                 new {Id    = "asc", Scope = "I", Type = "L", ReferenceName = "Casuarina Coast Asmat"},
                                 new {Id    = "ase", Scope = "I", Type = "L", ReferenceName = "American Sign Language"},
                                 new {Id    = "asf", Scope = "I", Type = "L", ReferenceName = "Auslan"},
                                 new {Id    = "asg", Scope = "I", Type = "L", ReferenceName = "Cishingini"},
                                 new {Id    = "ash", Scope = "I", Type = "E", ReferenceName = "Abishira"},
                                 new {Id    = "asi", Scope = "I", Type = "L", ReferenceName = "Buruwai"},
                                 new {Id    = "asj", Scope = "I", Type = "L", ReferenceName = "Sari"},
                                 new {Id    = "ask", Scope = "I", Type = "L", ReferenceName = "Ashkun"},
                                 new {Id    = "asl", Scope = "I", Type = "L", ReferenceName = "Asilulu"},
                                 new
                                 {
                                     Id            = "asm",
                                     Part2B        = "asm",
                                     Part2T        = "asm",
                                     Part1         = "as",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Assamese"
                                 }, new {Id = "asn", Scope = "I", Type = "L", ReferenceName = "Xingú Asuriní"},
                                 new {Id    = "aso", Scope = "I", Type = "L", ReferenceName = "Dano"},
                                 new {Id    = "asp", Scope = "I", Type = "L", ReferenceName = "Algerian Sign Language"},
                                 new {Id    = "asq", Scope = "I", Type = "L", ReferenceName = "Austrian Sign Language"},
                                 new {Id    = "asr", Scope = "I", Type = "L", ReferenceName = "Asuri"},
                                 new {Id    = "ass", Scope = "I", Type = "L", ReferenceName = "Ipulo"},
                                 new
                                 {
                                     Id            = "ast",
                                     Part2B        = "ast",
                                     Part2T        = "ast",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Asturian"
                                 }, new {Id = "asu", Scope = "I", Type = "L", ReferenceName = "Tocantins Asurini"},
                                 new {Id    = "asv", Scope = "I", Type = "L", ReferenceName = "Asoa"},
                                 new
                                 {
                                     Id            = "asw",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Australian Aborigines Sign Language"
                                 }, new {Id = "asx", Scope = "I", Type = "L", ReferenceName = "Muratayak"},
                                 new {Id    = "asy", Scope = "I", Type = "L", ReferenceName = "Yaosakor Asmat"},
                                 new {Id    = "asz", Scope = "I", Type = "L", ReferenceName = "As"},
                                 new {Id    = "ata", Scope = "I", Type = "L", ReferenceName = "Pele-Ata"},
                                 new {Id    = "atb", Scope = "I", Type = "L", ReferenceName = "Zaiwa"},
                                 new {Id    = "atc", Scope = "I", Type = "E", ReferenceName = "Atsahuaca"},
                                 new {Id    = "atd", Scope = "I", Type = "L", ReferenceName = "Ata Manobo"},
                                 new {Id    = "ate", Scope = "I", Type = "L", ReferenceName = "Atemble"},
                                 new
                                     {
                                         Id            = "atg",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Ivbie North-Okpela-Arhe"
                                     },
                                 new {Id = "ati", Scope = "I", Type = "L", ReferenceName = "Attié"},
                                 new {Id = "atj", Scope = "I", Type = "L", ReferenceName = "Atikamekw"},
                                 new {Id = "atk", Scope = "I", Type = "L", ReferenceName = "Ati"},
                                 new {Id = "atl", Scope = "I", Type = "L", ReferenceName = "Mt. Iraya Agta"},
                                 new {Id = "atm", Scope = "I", Type = "L", ReferenceName = "Ata"},
                                 new {Id = "atn", Scope = "I", Type = "L", ReferenceName = "Ashtiani"},
                                 new {Id = "ato", Scope = "I", Type = "L", ReferenceName = "Atong (Cameroon)"},
                                 new {Id = "atp", Scope = "I", Type = "L", ReferenceName = "Pudtol Atta"},
                                 new {Id = "atq", Scope = "I", Type = "L", ReferenceName = "Aralle-Tabulahan"},
                                 new {Id = "atr", Scope = "I", Type = "L", ReferenceName = "Waimiri-Atroari"},
                                 new {Id = "ats", Scope = "I", Type = "L", ReferenceName = "Gros Ventre"},
                                 new {Id = "att", Scope = "I", Type = "L", ReferenceName = "Pamplona Atta"},
                                 new {Id = "atu", Scope = "I", Type = "L", ReferenceName = "Reel"},
                                 new {Id = "atv", Scope = "I", Type = "L", ReferenceName = "Northern Altai"},
                                 new {Id = "atw", Scope = "I", Type = "L", ReferenceName = "Atsugewi"},
                                 new {Id = "atx", Scope = "I", Type = "L", ReferenceName = "Arutani"},
                                 new {Id = "aty", Scope = "I", Type = "L", ReferenceName = "Aneityum"},
                                 new {Id = "atz", Scope = "I", Type = "L", ReferenceName = "Arta"},
                                 new {Id = "aua", Scope = "I", Type = "L", ReferenceName = "Asumboa"},
                                 new {Id = "aub", Scope = "I", Type = "L", ReferenceName = "Alugu"},
                                 new {Id = "auc", Scope = "I", Type = "L", ReferenceName = "Waorani"},
                                 new {Id = "aud", Scope = "I", Type = "L", ReferenceName = "Anuta"},
                                 new {Id = "aug", Scope = "I", Type = "L", ReferenceName = "Aguna"},
                                 new {Id = "auh", Scope = "I", Type = "L", ReferenceName = "Aushi"},
                                 new {Id = "aui", Scope = "I", Type = "L", ReferenceName = "Anuki"},
                                 new {Id = "auj", Scope = "I", Type = "L", ReferenceName = "Awjilah"},
                                 new {Id = "auk", Scope = "I", Type = "L", ReferenceName = "Heyo"},
                                 new {Id = "aul", Scope = "I", Type = "L", ReferenceName = "Aulua"},
                                 new {Id = "aum", Scope = "I", Type = "L", ReferenceName = "Asu (Nigeria)"},
                                 new {Id = "aun", Scope = "I", Type = "L", ReferenceName = "Molmo One"},
                                 new {Id = "auo", Scope = "I", Type = "E", ReferenceName = "Auyokawa"},
                                 new {Id = "aup", Scope = "I", Type = "L", ReferenceName = "Makayam"},
                                 new {Id = "auq", Scope = "I", Type = "L", ReferenceName = "Anus"},
                                 new {Id = "aur", Scope = "I", Type = "L", ReferenceName = "Aruek"},
                                 new {Id = "aut", Scope = "I", Type = "L", ReferenceName = "Austral"},
                                 new {Id = "auu", Scope = "I", Type = "L", ReferenceName = "Auye"},
                                 new {Id = "auw", Scope = "I", Type = "L", ReferenceName = "Awyi"},
                                 new {Id = "aux", Scope = "I", Type = "E", ReferenceName = "Aurá"},
                                 new {Id = "auy", Scope = "I", Type = "L", ReferenceName = "Awiyaana"},
                                 new {Id = "auz", Scope = "I", Type = "L", ReferenceName = "Uzbeki Arabic"},
                                 new
                                 {
                                     Id            = "ava",
                                     Part2B        = "ava",
                                     Part2T        = "ava",
                                     Part1         = "av",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Avaric"
                                 }, new {Id = "avb", Scope = "I", Type = "L", ReferenceName = "Avau"},
                                 new {Id    = "avd", Scope = "I", Type = "L", ReferenceName = "Alviri-Vidari"},
                                 new
                                 {
                                     Id            = "ave",
                                     Part2B        = "ave",
                                     Part2T        = "ave",
                                     Part1         = "ae",
                                     Scope         = "I",
                                     Type          = "A",
                                     ReferenceName = "Avestan"
                                 }, new {Id = "avi", Scope = "I", Type = "L", ReferenceName = "Avikam"},
                                 new {Id    = "avk", Scope = "I", Type = "C", ReferenceName = "Kotava"},
                                 new
                                 {
                                     Id            = "avl",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Eastern Egyptian Bedawi Arabic"
                                 }, new {Id = "avm", Scope = "I", Type = "E", ReferenceName = "Angkamuthi"},
                                 new {Id    = "avn", Scope = "I", Type = "L", ReferenceName = "Avatime"},
                                 new {Id    = "avo", Scope = "I", Type = "E", ReferenceName = "Agavotaguerra"},
                                 new {Id    = "avs", Scope = "I", Type = "E", ReferenceName = "Aushiri"},
                                 new {Id    = "avt", Scope = "I", Type = "L", ReferenceName = "Au"},
                                 new {Id    = "avu", Scope = "I", Type = "L", ReferenceName = "Avokaya"},
                                 new {Id    = "avv", Scope = "I", Type = "L", ReferenceName = "Avá-Canoeiro"},
                                 new
                                 {
                                     Id            = "awa",
                                     Part2B        = "awa",
                                     Part2T        = "awa",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Awadhi"
                                 }, new {Id = "awb", Scope = "I", Type = "L", ReferenceName = "Awa (Papua New Guinea)"},
                                 new {Id    = "awc", Scope = "I", Type = "L", ReferenceName = "Cicipu"},
                                 new {Id    = "awe", Scope = "I", Type = "L", ReferenceName = "Awetí"},
                                 new {Id    = "awg", Scope = "I", Type = "E", ReferenceName = "Anguthimri"},
                                 new {Id    = "awh", Scope = "I", Type = "L", ReferenceName = "Awbono"},
                                 new {Id    = "awi", Scope = "I", Type = "L", ReferenceName = "Aekyom"},
                                 new {Id    = "awk", Scope = "I", Type = "E", ReferenceName = "Awabakal"},
                                 new {Id    = "awm", Scope = "I", Type = "L", ReferenceName = "Arawum"},
                                 new {Id    = "awn", Scope = "I", Type = "L", ReferenceName = "Awngi"},
                                 new {Id    = "awo", Scope = "I", Type = "L", ReferenceName = "Awak"},
                                 new {Id    = "awr", Scope = "I", Type = "L", ReferenceName = "Awera"},
                                 new {Id    = "aws", Scope = "I", Type = "L", ReferenceName = "South Awyu"},
                                 new {Id    = "awt", Scope = "I", Type = "L", ReferenceName = "Araweté"},
                                 new {Id    = "awu", Scope = "I", Type = "L", ReferenceName = "Central Awyu"},
                                 new {Id    = "awv", Scope = "I", Type = "L", ReferenceName = "Jair Awyu"},
                                 new {Id    = "aww", Scope = "I", Type = "L", ReferenceName = "Awun"},
                                 new {Id    = "awx", Scope = "I", Type = "L", ReferenceName = "Awara"},
                                 new {Id    = "awy", Scope = "I", Type = "L", ReferenceName = "Edera Awyu"},
                                 new {Id    = "axb", Scope = "I", Type = "E", ReferenceName = "Abipon"},
                                 new {Id    = "axe", Scope = "I", Type = "E", ReferenceName = "Ayerrerenge"},
                                 new {Id    = "axg", Scope = "I", Type = "E", ReferenceName = "Mato Grosso Arára"},
                                 new
                                 {
                                     Id            = "axk",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Yaka (Central African Republic)"
                                 },
                                 new {Id = "axl", Scope = "I", Type = "E", ReferenceName = "Lower Southern Aranda"},
                                 new {Id = "axm", Scope = "I", Type = "H", ReferenceName = "Middle Armenian"},
                                 new {Id = "axx", Scope = "I", Type = "L", ReferenceName = "Xârâgurè"},
                                 new {Id = "aya", Scope = "I", Type = "L", ReferenceName = "Awar"},
                                 new {Id = "ayb", Scope = "I", Type = "L", ReferenceName = "Ayizo Gbe"},
                                 new {Id = "ayc", Scope = "I", Type = "L", ReferenceName = "Southern Aymara"},
                                 new {Id = "ayd", Scope = "I", Type = "E", ReferenceName = "Ayabadhu"},
                                 new {Id = "aye", Scope = "I", Type = "L", ReferenceName = "Ayere"},
                                 new {Id = "ayg", Scope = "I", Type = "L", ReferenceName = "Ginyanga"},
                                 new {Id = "ayh", Scope = "I", Type = "L", ReferenceName = "Hadrami Arabic"},
                                 new {Id = "ayi", Scope = "I", Type = "L", ReferenceName = "Leyigha"},
                                 new {Id = "ayk", Scope = "I", Type = "L", ReferenceName = "Akuku"},
                                 new {Id = "ayl", Scope = "I", Type = "L", ReferenceName = "Libyan Arabic"},
                                 new
                                 {
                                     Id            = "aym",
                                     Part2B        = "aym",
                                     Part2T        = "aym",
                                     Part1         = "ay",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Aymara"
                                 }, new {Id = "ayn", Scope = "I", Type = "L", ReferenceName = "Sanaani Arabic"},
                                 new {Id    = "ayo", Scope = "I", Type = "L", ReferenceName = "Ayoreo"},
                                 new
                                     {
                                         Id            = "ayp",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "North Mesopotamian Arabic"
                                     },
                                 new {Id = "ayq", Scope = "I", Type = "L", ReferenceName = "Ayi (Papua New Guinea)"},
                                 new {Id = "ayr", Scope = "I", Type = "L", ReferenceName = "Central Aymara"},
                                 new {Id = "ays", Scope = "I", Type = "L", ReferenceName = "Sorsogon Ayta"},
                                 new {Id = "ayt", Scope = "I", Type = "L", ReferenceName = "Magbukun Ayta"},
                                 new {Id = "ayu", Scope = "I", Type = "L", ReferenceName = "Ayu"},
                                 new {Id = "ayy", Scope = "I", Type = "E", ReferenceName = "Tayabas Ayta"},
                                 new {Id = "ayz", Scope = "I", Type = "L", ReferenceName = "Mai Brat"},
                                 new {Id = "aza", Scope = "I", Type = "L", ReferenceName = "Azha"},
                                 new {Id = "azb", Scope = "I", Type = "L", ReferenceName = "South Azerbaijani"},
                                 new
                                     {
                                         Id            = "azd",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Eastern Durango Nahuatl"
                                     },
                                 new
                                 {
                                     Id            = "aze",
                                     Part2B        = "aze",
                                     Part2T        = "aze",
                                     Part1         = "az",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Azerbaijani"
                                 },
                                 new {Id = "azg", Scope = "I", Type = "L", ReferenceName = "San Pedro Amuzgos Amuzgo"},
                                 new {Id = "azj", Scope = "I", Type = "L", ReferenceName = "North Azerbaijani"},
                                 new {Id = "azm", Scope = "I", Type = "L", ReferenceName = "Ipalapa Amuzgo"},
                                 new {Id = "azn", Scope = "I", Type = "L", ReferenceName = "Western Durango Nahuatl"},
                                 new {Id = "azo", Scope = "I", Type = "L", ReferenceName = "Awing"},
                                 new {Id = "azt", Scope = "I", Type = "L", ReferenceName = "Faire Atta"},
                                 new {Id = "azz", Scope = "I", Type = "L", ReferenceName = "Highland Puebla Nahuatl"});
        }
    }
}