using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class B
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(new {Id = "baa", Scope = "I", Type = "L", ReferenceName = "Babatana"},
                                 new {Id = "bab", Scope = "I", Type = "L", ReferenceName = "Bainouk-Gunyuño"},
                                 new {Id = "bac", Scope = "I", Type = "L", ReferenceName = "Badui"},
                                 new {Id = "bae", Scope = "I", Type = "E", ReferenceName = "Baré"},
                                 new {Id = "baf", Scope = "I", Type = "L", ReferenceName = "Nubaca"},
                                 new {Id = "bag", Scope = "I", Type = "L", ReferenceName = "Tuki"},
                                 new {Id = "bah", Scope = "I", Type = "L", ReferenceName = "Bahamas Creole English"},
                                 new {Id = "baj", Scope = "I", Type = "L", ReferenceName = "Barakai"},
                                 new
                                 {
                                     Id            = "bak",
                                     Part2B        = "bak",
                                     Part2T        = "bak",
                                     Part1         = "ba",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bashkir"
                                 }, new
                                 {
                                     Id            = "bal",
                                     Part2B        = "bal",
                                     Part2T        = "bal",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Baluchi"
                                 }, new
                                 {
                                     Id            = "bam",
                                     Part2B        = "bam",
                                     Part2T        = "bam",
                                     Part1         = "bm",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bambara"
                                 }, new
                                 {
                                     Id            = "ban",
                                     Part2B        = "ban",
                                     Part2T        = "ban",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Balinese"
                                 }, new {Id = "bao", Scope = "I", Type = "L", ReferenceName = "Waimaha"},
                                 new {Id    = "bap", Scope = "I", Type = "L", ReferenceName = "Bantawa"},
                                 new {Id    = "bar", Scope = "I", Type = "L", ReferenceName = "Bavarian"},
                                 new
                                 {
                                     Id            = "bas",
                                     Part2B        = "bas",
                                     Part2T        = "bas",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Basa (Cameroon)"
                                 }, new {Id = "bau", Scope = "I", Type = "L", ReferenceName = "Bada (Nigeria)"},
                                 new {Id    = "bav", Scope = "I", Type = "L", ReferenceName = "Vengo"},
                                 new {Id    = "baw", Scope = "I", Type = "L", ReferenceName = "Bambili-Bambui"},
                                 new {Id    = "bax", Scope = "I", Type = "L", ReferenceName = "Bamun"},
                                 new {Id    = "bay", Scope = "I", Type = "L", ReferenceName = "Batuley"},
                                 new {Id    = "bba", Scope = "I", Type = "L", ReferenceName = "Baatonum"},
                                 new {Id    = "bbb", Scope = "I", Type = "L", ReferenceName = "Barai"},
                                 new {Id    = "bbc", Scope = "I", Type = "L", ReferenceName = "Batak Toba"},
                                 new {Id    = "bbd", Scope = "I", Type = "L", ReferenceName = "Bau"},
                                 new {Id    = "bbe", Scope = "I", Type = "L", ReferenceName = "Bangba"},
                                 new {Id    = "bbf", Scope = "I", Type = "L", ReferenceName = "Baibai"},
                                 new {Id    = "bbg", Scope = "I", Type = "L", ReferenceName = "Barama"},
                                 new {Id    = "bbh", Scope = "I", Type = "L", ReferenceName = "Bugan"},
                                 new {Id    = "bbi", Scope = "I", Type = "L", ReferenceName = "Barombi"},
                                 new {Id    = "bbj", Scope = "I", Type = "L", ReferenceName = "Ghomálá'"},
                                 new {Id    = "bbk", Scope = "I", Type = "L", ReferenceName = "Babanki"},
                                 new {Id    = "bbl", Scope = "I", Type = "L", ReferenceName = "Bats"},
                                 new {Id    = "bbm", Scope = "I", Type = "L", ReferenceName = "Babango"},
                                 new {Id    = "bbn", Scope = "I", Type = "L", ReferenceName = "Uneapa"},
                                 new {Id    = "bbo", Scope = "I", Type = "L", ReferenceName = "Northern Bobo Madaré"},
                                 new {Id    = "bbp", Scope = "I", Type = "L", ReferenceName = "West Central Banda"},
                                 new {Id    = "bbq", Scope = "I", Type = "L", ReferenceName = "Bamali"},
                                 new {Id    = "bbr", Scope = "I", Type = "L", ReferenceName = "Girawa"},
                                 new {Id    = "bbs", Scope = "I", Type = "L", ReferenceName = "Bakpinka"},
                                 new {Id    = "bbt", Scope = "I", Type = "L", ReferenceName = "Mburku"},
                                 new {Id    = "bbu", Scope = "I", Type = "L", ReferenceName = "Kulung (Nigeria)"},
                                 new {Id    = "bbv", Scope = "I", Type = "L", ReferenceName = "Karnai"},
                                 new {Id    = "bbw", Scope = "I", Type = "L", ReferenceName = "Baba"},
                                 new {Id    = "bbx", Scope = "I", Type = "L", ReferenceName = "Bubia"},
                                 new {Id    = "bby", Scope = "I", Type = "L", ReferenceName = "Befang"},
                                 new {Id    = "bbz", Scope = "I", Type = "L", ReferenceName = "Babalia Creole Arabic"},
                                 new {Id    = "bca", Scope = "I", Type = "L", ReferenceName = "Central Bai"},
                                 new {Id    = "bcb", Scope = "I", Type = "L", ReferenceName = "Bainouk-Samik"},
                                 new {Id    = "bcc", Scope = "I", Type = "L", ReferenceName = "Southern Balochi"},
                                 new {Id    = "bcd", Scope = "I", Type = "L", ReferenceName = "North Babar"},
                                 new {Id    = "bce", Scope = "I", Type = "L", ReferenceName = "Bamenyam"},
                                 new {Id    = "bcf", Scope = "I", Type = "L", ReferenceName = "Bamu"},
                                 new {Id    = "bcg", Scope = "I", Type = "L", ReferenceName = "Baga Pokur"},
                                 new {Id    = "bch", Scope = "I", Type = "L", ReferenceName = "Bariai"},
                                 new {Id    = "bci", Scope = "I", Type = "L", ReferenceName = "Baoulé"},
                                 new {Id    = "bcj", Scope = "I", Type = "L", ReferenceName = "Bardi"},
                                 new {Id    = "bck", Scope = "I", Type = "L", ReferenceName = "Bunuba"},
                                 new {Id    = "bcl", Scope = "I", Type = "L", ReferenceName = "Central Bikol"},
                                 new {Id    = "bcm", Scope = "I", Type = "L", ReferenceName = "Bannoni"},
                                 new {Id    = "bcn", Scope = "I", Type = "L", ReferenceName = "Bali (Nigeria)"},
                                 new {Id    = "bco", Scope = "I", Type = "L", ReferenceName = "Kaluli"},
                                 new
                                 {
                                     Id            = "bcp",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bali (Democratic Republic of Congo)"
                                 }, new {Id = "bcq", Scope = "I", Type = "L", ReferenceName = "Bench"},
                                 new {Id    = "bcr", Scope = "I", Type = "L", ReferenceName = "Babine"},
                                 new {Id    = "bcs", Scope = "I", Type = "L", ReferenceName = "Kohumono"},
                                 new {Id    = "bct", Scope = "I", Type = "L", ReferenceName = "Bendi"},
                                 new {Id    = "bcu", Scope = "I", Type = "L", ReferenceName = "Awad Bing"},
                                 new {Id    = "bcv", Scope = "I", Type = "L", ReferenceName = "Shoo-Minda-Nye"},
                                 new {Id    = "bcw", Scope = "I", Type = "L", ReferenceName = "Bana"},
                                 new {Id    = "bcy", Scope = "I", Type = "L", ReferenceName = "Bacama"},
                                 new {Id    = "bcz", Scope = "I", Type = "L", ReferenceName = "Bainouk-Gunyaamolo"},
                                 new {Id    = "bda", Scope = "I", Type = "L", ReferenceName = "Bayot"},
                                 new {Id    = "bdb", Scope = "I", Type = "L", ReferenceName = "Basap"},
                                 new {Id    = "bdc", Scope = "I", Type = "L", ReferenceName = "Emberá-Baudó"},
                                 new {Id    = "bdd", Scope = "I", Type = "L", ReferenceName = "Bunama"},
                                 new {Id    = "bde", Scope = "I", Type = "L", ReferenceName = "Bade"},
                                 new {Id    = "bdf", Scope = "I", Type = "L", ReferenceName = "Biage"},
                                 new {Id    = "bdg", Scope = "I", Type = "L", ReferenceName = "Bonggi"},
                                 new {Id    = "bdh", Scope = "I", Type = "L", ReferenceName = "Baka (South Sudan)"},
                                 new {Id    = "bdi", Scope = "I", Type = "L", ReferenceName = "Burun"},
                                 new {Id    = "bdj", Scope = "I", Type = "L", ReferenceName = "Bai (South Sudan)"},
                                 new {Id    = "bdk", Scope = "I", Type = "L", ReferenceName = "Budukh"},
                                 new {Id    = "bdl", Scope = "I", Type = "L", ReferenceName = "Indonesian Bajau"},
                                 new {Id    = "bdm", Scope = "I", Type = "L", ReferenceName = "Buduma"},
                                 new {Id    = "bdn", Scope = "I", Type = "L", ReferenceName = "Baldemu"},
                                 new {Id    = "bdo", Scope = "I", Type = "L", ReferenceName = "Morom"},
                                 new {Id    = "bdp", Scope = "I", Type = "L", ReferenceName = "Bende"},
                                 new {Id    = "bdq", Scope = "I", Type = "L", ReferenceName = "Bahnar"},
                                 new {Id    = "bdr", Scope = "I", Type = "L", ReferenceName = "West Coast Bajau"},
                                 new {Id    = "bds", Scope = "I", Type = "L", ReferenceName = "Burunge"},
                                 new {Id    = "bdt", Scope = "I", Type = "L", ReferenceName = "Bokoto"},
                                 new {Id    = "bdu", Scope = "I", Type = "L", ReferenceName = "Oroko"},
                                 new {Id    = "bdv", Scope = "I", Type = "L", ReferenceName = "Bodo Parja"},
                                 new {Id    = "bdw", Scope = "I", Type = "L", ReferenceName = "Baham"},
                                 new {Id    = "bdx", Scope = "I", Type = "L", ReferenceName = "Budong-Budong"},
                                 new {Id    = "bdy", Scope = "I", Type = "L", ReferenceName = "Bandjalang"},
                                 new {Id    = "bdz", Scope = "I", Type = "L", ReferenceName = "Badeshi"},
                                 new {Id    = "bea", Scope = "I", Type = "L", ReferenceName = "Beaver"},
                                 new {Id    = "beb", Scope = "I", Type = "L", ReferenceName = "Bebele"},
                                 new {Id    = "bec", Scope = "I", Type = "L", ReferenceName = "Iceve-Maci"},
                                 new {Id    = "bed", Scope = "I", Type = "L", ReferenceName = "Bedoanas"},
                                 new {Id    = "bee", Scope = "I", Type = "L", ReferenceName = "Byangsi"},
                                 new {Id    = "bef", Scope = "I", Type = "L", ReferenceName = "Benabena"},
                                 new {Id    = "beg", Scope = "I", Type = "L", ReferenceName = "Belait"},
                                 new {Id    = "beh", Scope = "I", Type = "L", ReferenceName = "Biali"},
                                 new {Id    = "bei", Scope = "I", Type = "L", ReferenceName = "Bekati'"},
                                 new
                                 {
                                     Id            = "bej",
                                     Part2B        = "bej",
                                     Part2T        = "bej",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Beja"
                                 }, new {Id = "bek", Scope = "I", Type = "L", ReferenceName = "Bebeli"},
                                 new
                                 {
                                     Id            = "bel",
                                     Part2B        = "bel",
                                     Part2T        = "bel",
                                     Part1         = "be",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Belarusian"
                                 }, new
                                 {
                                     Id            = "bem",
                                     Part2B        = "bem",
                                     Part2T        = "bem",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bemba (Zambia)"
                                 }, new
                                 {
                                     Id            = "ben",
                                     Part2B        = "ben",
                                     Part2T        = "ben",
                                     Part1         = "bn",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bengali"
                                 }, new {Id = "beo", Scope = "I", Type = "L", ReferenceName = "Beami"},
                                 new {Id    = "bep", Scope = "I", Type = "L", ReferenceName = "Besoa"},
                                 new {Id    = "beq", Scope = "I", Type = "L", ReferenceName = "Beembe"},
                                 new {Id    = "bes", Scope = "I", Type = "L", ReferenceName = "Besme"},
                                 new {Id    = "bet", Scope = "I", Type = "L", ReferenceName = "Guiberoua Béte"},
                                 new {Id    = "beu", Scope = "I", Type = "L", ReferenceName = "Blagar"},
                                 new {Id    = "bev", Scope = "I", Type = "L", ReferenceName = "Daloa Bété"},
                                 new {Id    = "bew", Scope = "I", Type = "L", ReferenceName = "Betawi"},
                                 new {Id    = "bex", Scope = "I", Type = "L", ReferenceName = "Jur Modo"},
                                 new
                                     {
                                         Id            = "bey",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Beli (Papua New Guinea)"
                                     },
                                 new {Id = "bez", Scope = "I", Type = "L", ReferenceName = "Bena (Tanzania)"},
                                 new {Id = "bfa", Scope = "I", Type = "L", ReferenceName = "Bari"},
                                 new {Id = "bfb", Scope = "I", Type = "L", ReferenceName = "Pauri Bareli"},
                                 new {Id = "bfc", Scope = "I", Type = "L", ReferenceName = "Panyi Bai"},
                                 new {Id = "bfd", Scope = "I", Type = "L", ReferenceName = "Bafut"},
                                 new {Id = "bfe", Scope = "I", Type = "L", ReferenceName = "Betaf"},
                                 new {Id = "bff", Scope = "I", Type = "L", ReferenceName = "Bofi"},
                                 new {Id = "bfg", Scope = "I", Type = "L", ReferenceName = "Busang Kayan"},
                                 new {Id = "bfh", Scope = "I", Type = "L", ReferenceName = "Blafe"},
                                 new {Id = "bfi", Scope = "I", Type = "L", ReferenceName = "British Sign Language"},
                                 new {Id = "bfj", Scope = "I", Type = "L", ReferenceName = "Bafanji"},
                                 new {Id = "bfk", Scope = "I", Type = "L", ReferenceName = "Ban Khor Sign Language"},
                                 new {Id = "bfl", Scope = "I", Type = "L", ReferenceName = "Banda-Ndélé"},
                                 new {Id = "bfm", Scope = "I", Type = "L", ReferenceName = "Mmen"},
                                 new {Id = "bfn", Scope = "I", Type = "L", ReferenceName = "Bunak"},
                                 new {Id = "bfo", Scope = "I", Type = "L", ReferenceName = "Malba Birifor"},
                                 new {Id = "bfp", Scope = "I", Type = "L", ReferenceName = "Beba"},
                                 new {Id = "bfq", Scope = "I", Type = "L", ReferenceName = "Badaga"},
                                 new {Id = "bfr", Scope = "I", Type = "L", ReferenceName = "Bazigar"},
                                 new {Id = "bfs", Scope = "I", Type = "L", ReferenceName = "Southern Bai"},
                                 new {Id = "bft", Scope = "I", Type = "L", ReferenceName = "Balti"},
                                 new {Id = "bfu", Scope = "I", Type = "L", ReferenceName = "Gahri"},
                                 new {Id = "bfw", Scope = "I", Type = "L", ReferenceName = "Bondo"},
                                 new {Id = "bfx", Scope = "I", Type = "L", ReferenceName = "Bantayanon"},
                                 new {Id = "bfy", Scope = "I", Type = "L", ReferenceName = "Bagheli"},
                                 new {Id = "bfz", Scope = "I", Type = "L", ReferenceName = "Mahasu Pahari"},
                                 new {Id = "bga", Scope = "I", Type = "L", ReferenceName = "Gwamhi-Wuri"},
                                 new {Id = "bgb", Scope = "I", Type = "L", ReferenceName = "Bobongko"},
                                 new {Id = "bgc", Scope = "I", Type = "L", ReferenceName = "Haryanvi"},
                                 new {Id = "bgd", Scope = "I", Type = "L", ReferenceName = "Rathwi Bareli"},
                                 new {Id = "bge", Scope = "I", Type = "L", ReferenceName = "Bauria"},
                                 new {Id = "bgf", Scope = "I", Type = "L", ReferenceName = "Bangandu"},
                                 new {Id = "bgg", Scope = "I", Type = "L", ReferenceName = "Bugun"},
                                 new {Id = "bgi", Scope = "I", Type = "L", ReferenceName = "Giangan"},
                                 new {Id = "bgj", Scope = "I", Type = "L", ReferenceName = "Bangolan"},
                                 new {Id = "bgk", Scope = "I", Type = "L", ReferenceName = "Bit"},
                                 new {Id = "bgl", Scope = "I", Type = "L", ReferenceName = "Bo (Laos)"},
                                 new {Id = "bgn", Scope = "I", Type = "L", ReferenceName = "Western Balochi"},
                                 new {Id = "bgo", Scope = "I", Type = "L", ReferenceName = "Baga Koga"},
                                 new {Id = "bgp", Scope = "I", Type = "L", ReferenceName = "Eastern Balochi"},
                                 new {Id = "bgq", Scope = "I", Type = "L", ReferenceName = "Bagri"},
                                 new {Id = "bgr", Scope = "I", Type = "L", ReferenceName = "Bawm Chin"},
                                 new {Id = "bgs", Scope = "I", Type = "L", ReferenceName = "Tagabawa"},
                                 new {Id = "bgt", Scope = "I", Type = "L", ReferenceName = "Bughotu"},
                                 new {Id = "bgu", Scope = "I", Type = "L", ReferenceName = "Mbongno"},
                                 new {Id = "bgv", Scope = "I", Type = "L", ReferenceName = "Warkay-Bipim"},
                                 new {Id = "bgw", Scope = "I", Type = "L", ReferenceName = "Bhatri"},
                                 new {Id = "bgx", Scope = "I", Type = "L", ReferenceName = "Balkan Gagauz Turkish"},
                                 new {Id = "bgy", Scope = "I", Type = "L", ReferenceName = "Benggoi"},
                                 new {Id = "bgz", Scope = "I", Type = "L", ReferenceName = "Banggai"},
                                 new {Id = "bha", Scope = "I", Type = "L", ReferenceName = "Bharia"},
                                 new {Id = "bhb", Scope = "I", Type = "L", ReferenceName = "Bhili"},
                                 new {Id = "bhc", Scope = "I", Type = "L", ReferenceName = "Biga"},
                                 new {Id = "bhd", Scope = "I", Type = "L", ReferenceName = "Bhadrawahi"},
                                 new {Id = "bhe", Scope = "I", Type = "L", ReferenceName = "Bhaya"},
                                 new {Id = "bhf", Scope = "I", Type = "L", ReferenceName = "Odiai"},
                                 new {Id = "bhg", Scope = "I", Type = "L", ReferenceName = "Binandere"},
                                 new {Id = "bhh", Scope = "I", Type = "L", ReferenceName = "Bukharic"},
                                 new {Id = "bhi", Scope = "I", Type = "L", ReferenceName = "Bhilali"},
                                 new {Id = "bhj", Scope = "I", Type = "L", ReferenceName = "Bahing"},
                                 new {Id = "bhl", Scope = "I", Type = "L", ReferenceName = "Bimin"},
                                 new {Id = "bhm", Scope = "I", Type = "L", ReferenceName = "Bathari"},
                                 new {Id = "bhn", Scope = "I", Type = "L", ReferenceName = "Bohtan Neo-Aramaic"},
                                 new
                                 {
                                     Id            = "bho",
                                     Part2B        = "bho",
                                     Part2T        = "bho",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bhojpuri"
                                 }, new {Id = "bhp", Scope = "I", Type = "L", ReferenceName = "Bima"},
                                 new {Id    = "bhq", Scope = "I", Type = "L", ReferenceName = "Tukang Besi South"},
                                 new {Id    = "bhr", Scope = "I", Type = "L", ReferenceName = "Bara Malagasy"},
                                 new {Id    = "bhs", Scope = "I", Type = "L", ReferenceName = "Buwal"},
                                 new {Id    = "bht", Scope = "I", Type = "L", ReferenceName = "Bhattiyali"},
                                 new {Id    = "bhu", Scope = "I", Type = "L", ReferenceName = "Bhunjia"},
                                 new {Id    = "bhv", Scope = "I", Type = "L", ReferenceName = "Bahau"},
                                 new {Id    = "bhw", Scope = "I", Type = "L", ReferenceName = "Biak"},
                                 new {Id    = "bhx", Scope = "I", Type = "L", ReferenceName = "Bhalay"},
                                 new {Id    = "bhy", Scope = "I", Type = "L", ReferenceName = "Bhele"},
                                 new {Id    = "bhz", Scope = "I", Type = "L", ReferenceName = "Bada (Indonesia)"},
                                 new {Id    = "bia", Scope = "I", Type = "L", ReferenceName = "Badimaya"},
                                 new {Id    = "bib", Scope = "I", Type = "L", ReferenceName = "Bissa"},
                                 new {Id    = "bic", Scope = "I", Type = "L", ReferenceName = "Bikaru"},
                                 new {Id    = "bid", Scope = "I", Type = "L", ReferenceName = "Bidiyo"},
                                 new {Id    = "bie", Scope = "I", Type = "L", ReferenceName = "Bepour"},
                                 new {Id    = "bif", Scope = "I", Type = "L", ReferenceName = "Biafada"},
                                 new {Id    = "big", Scope = "I", Type = "L", ReferenceName = "Biangai"},
                                 new {Id    = "bij", Scope = "I", Type = "L", ReferenceName = "Vaghat-Ya-Bijim-Legeri"},
                                 new
                                 {
                                     Id            = "bik",
                                     Part2B        = "bik",
                                     Part2T        = "bik",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Bikol"
                                 }, new {Id = "bil", Scope = "I", Type = "L", ReferenceName = "Bile"},
                                 new {Id    = "bim", Scope = "I", Type = "L", ReferenceName = "Bimoba"},
                                 new
                                 {
                                     Id            = "bin",
                                     Part2B        = "bin",
                                     Part2T        = "bin",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bini"
                                 }, new {Id = "bio", Scope = "I", Type = "L", ReferenceName = "Nai"},
                                 new {Id    = "bip", Scope = "I", Type = "L", ReferenceName = "Bila"},
                                 new {Id    = "biq", Scope = "I", Type = "L", ReferenceName = "Bipi"},
                                 new {Id    = "bir", Scope = "I", Type = "L", ReferenceName = "Bisorio"},
                                 new
                                 {
                                     Id            = "bis",
                                     Part2B        = "bis",
                                     Part2T        = "bis",
                                     Part1         = "bi",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bislama"
                                 }, new {Id = "bit", Scope = "I", Type = "L", ReferenceName = "Berinomo"},
                                 new {Id    = "biu", Scope = "I", Type = "L", ReferenceName = "Biete"},
                                 new {Id    = "biv", Scope = "I", Type = "L", ReferenceName = "Southern Birifor"},
                                 new {Id    = "biw", Scope = "I", Type = "L", ReferenceName = "Kol (Cameroon)"},
                                 new {Id    = "bix", Scope = "I", Type = "L", ReferenceName = "Bijori"},
                                 new {Id    = "biy", Scope = "I", Type = "L", ReferenceName = "Birhor"},
                                 new {Id    = "biz", Scope = "I", Type = "L", ReferenceName = "Baloi"},
                                 new {Id    = "bja", Scope = "I", Type = "L", ReferenceName = "Budza"},
                                 new {Id    = "bjb", Scope = "I", Type = "E", ReferenceName = "Banggarla"},
                                 new {Id    = "bjc", Scope = "I", Type = "L", ReferenceName = "Bariji"},
                                 new {Id    = "bje", Scope = "I", Type = "L", ReferenceName = "Biao-Jiao Mien"},
                                 new
                                 {
                                     Id            = "bjf",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Barzani Jewish Neo-Aramaic"
                                 }, new {Id = "bjg", Scope = "I", Type = "L", ReferenceName = "Bidyogo"},
                                 new {Id    = "bjh", Scope = "I", Type = "L", ReferenceName = "Bahinemo"},
                                 new {Id    = "bji", Scope = "I", Type = "L", ReferenceName = "Burji"},
                                 new {Id    = "bjj", Scope = "I", Type = "L", ReferenceName = "Kanauji"},
                                 new {Id    = "bjk", Scope = "I", Type = "L", ReferenceName = "Barok"},
                                 new
                                     {
                                         Id            = "bjl",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Bulu (Papua New Guinea)"
                                     },
                                 new {Id = "bjm", Scope = "I", Type = "L", ReferenceName = "Bajelani"},
                                 new {Id = "bjn", Scope = "I", Type = "L", ReferenceName = "Banjar"},
                                 new {Id = "bjo", Scope = "I", Type = "L", ReferenceName = "Mid-Southern Banda"},
                                 new {Id = "bjp", Scope = "I", Type = "L", ReferenceName = "Fanamaket"},
                                 new {Id = "bjr", Scope = "I", Type = "L", ReferenceName = "Binumarien"},
                                 new {Id = "bjs", Scope = "I", Type = "L", ReferenceName = "Bajan"},
                                 new {Id = "bjt", Scope = "I", Type = "L", ReferenceName = "Balanta-Ganja"},
                                 new {Id = "bju", Scope = "I", Type = "L", ReferenceName = "Busuu"},
                                 new {Id = "bjv", Scope = "I", Type = "L", ReferenceName = "Bedjond"},
                                 new {Id = "bjw", Scope = "I", Type = "L", ReferenceName = "Bakwé"},
                                 new {Id = "bjx", Scope = "I", Type = "L", ReferenceName = "Banao Itneg"},
                                 new {Id = "bjy", Scope = "I", Type = "E", ReferenceName = "Bayali"},
                                 new {Id = "bjz", Scope = "I", Type = "L", ReferenceName = "Baruga"},
                                 new {Id = "bka", Scope = "I", Type = "L", ReferenceName = "Kyak"},
                                 new {Id = "bkc", Scope = "I", Type = "L", ReferenceName = "Baka (Cameroon)"},
                                 new {Id = "bkd", Scope = "I", Type = "L", ReferenceName = "Binukid"},
                                 new {Id = "bkf", Scope = "I", Type = "L", ReferenceName = "Beeke"},
                                 new {Id = "bkg", Scope = "I", Type = "L", ReferenceName = "Buraka"},
                                 new {Id = "bkh", Scope = "I", Type = "L", ReferenceName = "Bakoko"},
                                 new {Id = "bki", Scope = "I", Type = "L", ReferenceName = "Baki"},
                                 new {Id = "bkj", Scope = "I", Type = "L", ReferenceName = "Pande"},
                                 new {Id = "bkk", Scope = "I", Type = "L", ReferenceName = "Brokskat"},
                                 new {Id = "bkl", Scope = "I", Type = "L", ReferenceName = "Berik"},
                                 new {Id = "bkm", Scope = "I", Type = "L", ReferenceName = "Kom (Cameroon)"},
                                 new {Id = "bkn", Scope = "I", Type = "L", ReferenceName = "Bukitan"},
                                 new {Id = "bko", Scope = "I", Type = "L", ReferenceName = "Kwa'"},
                                 new
                                 {
                                     Id            = "bkp",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Boko (Democratic Republic of Congo)"
                                 }, new {Id = "bkq", Scope = "I", Type = "L", ReferenceName = "Bakairí"},
                                 new {Id    = "bkr", Scope = "I", Type = "L", ReferenceName = "Bakumpai"},
                                 new
                                     {
                                         Id            = "bks",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Northern Sorsoganon"
                                     },
                                 new {Id = "bkt", Scope = "I", Type = "L", ReferenceName = "Boloki"},
                                 new {Id = "bku", Scope = "I", Type = "L", ReferenceName = "Buhid"},
                                 new {Id = "bkv", Scope = "I", Type = "L", ReferenceName = "Bekwarra"},
                                 new {Id = "bkw", Scope = "I", Type = "L", ReferenceName = "Bekwel"},
                                 new {Id = "bkx", Scope = "I", Type = "L", ReferenceName = "Baikeno"},
                                 new {Id = "bky", Scope = "I", Type = "L", ReferenceName = "Bokyi"},
                                 new {Id = "bkz", Scope = "I", Type = "L", ReferenceName = "Bungku"},
                                 new
                                 {
                                     Id            = "bla",
                                     Part2B        = "bla",
                                     Part2T        = "bla",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Siksika"
                                 }, new {Id = "blb", Scope = "I", Type = "L", ReferenceName = "Bilua"},
                                 new {Id    = "blc", Scope = "I", Type = "L", ReferenceName = "Bella Coola"},
                                 new {Id    = "bld", Scope = "I", Type = "L", ReferenceName = "Bolango"},
                                 new {Id    = "ble", Scope = "I", Type = "L", ReferenceName = "Balanta-Kentohe"},
                                 new {Id    = "blf", Scope = "I", Type = "L", ReferenceName = "Buol"},
                                 new {Id    = "blg", Scope = "I", Type = "L", ReferenceName = "Balau"},
                                 new {Id    = "blh", Scope = "I", Type = "L", ReferenceName = "Kuwaa"},
                                 new {Id    = "bli", Scope = "I", Type = "L", ReferenceName = "Bolia"},
                                 new {Id    = "blj", Scope = "I", Type = "L", ReferenceName = "Bolongan"},
                                 new {Id    = "blk", Scope = "I", Type = "L", ReferenceName = "Pa'o Karen"},
                                 new {Id    = "bll", Scope = "I", Type = "E", ReferenceName = "Biloxi"},
                                 new {Id    = "blm", Scope = "I", Type = "L", ReferenceName = "Beli (South Sudan)"},
                                 new
                                 {
                                     Id            = "bln",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Southern Catanduanes Bikol"
                                 }, new {Id = "blo", Scope = "I", Type = "L", ReferenceName = "Anii"},
                                 new {Id    = "blp", Scope = "I", Type = "L", ReferenceName = "Blablanga"},
                                 new {Id    = "blq", Scope = "I", Type = "L", ReferenceName = "Baluan-Pam"},
                                 new {Id    = "blr", Scope = "I", Type = "L", ReferenceName = "Blang"},
                                 new {Id    = "bls", Scope = "I", Type = "L", ReferenceName = "Balaesang"},
                                 new {Id    = "blt", Scope = "I", Type = "L", ReferenceName = "Tai Dam"},
                                 new {Id    = "blv", Scope = "I", Type = "L", ReferenceName = "Kibala"},
                                 new {Id    = "blw", Scope = "I", Type = "L", ReferenceName = "Balangao"},
                                 new {Id    = "blx", Scope = "I", Type = "L", ReferenceName = "Mag-Indi Ayta"},
                                 new {Id    = "bly", Scope = "I", Type = "L", ReferenceName = "Notre"},
                                 new {Id    = "blz", Scope = "I", Type = "L", ReferenceName = "Balantak"},
                                 new {Id    = "bma", Scope = "I", Type = "L", ReferenceName = "Lame"},
                                 new {Id    = "bmb", Scope = "I", Type = "L", ReferenceName = "Bembe"},
                                 new {Id    = "bmc", Scope = "I", Type = "L", ReferenceName = "Biem"},
                                 new {Id    = "bmd", Scope = "I", Type = "L", ReferenceName = "Baga Manduri"},
                                 new {Id    = "bme", Scope = "I", Type = "L", ReferenceName = "Limassa"},
                                 new {Id    = "bmf", Scope = "I", Type = "L", ReferenceName = "Bom-Kim"},
                                 new {Id    = "bmg", Scope = "I", Type = "L", ReferenceName = "Bamwe"},
                                 new {Id    = "bmh", Scope = "I", Type = "L", ReferenceName = "Kein"},
                                 new {Id    = "bmi", Scope = "I", Type = "L", ReferenceName = "Bagirmi"},
                                 new {Id    = "bmj", Scope = "I", Type = "L", ReferenceName = "Bote-Majhi"},
                                 new {Id    = "bmk", Scope = "I", Type = "L", ReferenceName = "Ghayavi"},
                                 new {Id    = "bml", Scope = "I", Type = "L", ReferenceName = "Bomboli"},
                                 new
                                 {
                                     Id            = "bmm",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Northern Betsimisaraka Malagasy"
                                 },
                                 new {Id = "bmn", Scope = "I", Type = "E", ReferenceName = "Bina (Papua New Guinea)"},
                                 new {Id = "bmo", Scope = "I", Type = "L", ReferenceName = "Bambalang"},
                                 new {Id = "bmp", Scope = "I", Type = "L", ReferenceName = "Bulgebi"},
                                 new {Id = "bmq", Scope = "I", Type = "L", ReferenceName = "Bomu"},
                                 new {Id = "bmr", Scope = "I", Type = "L", ReferenceName = "Muinane"},
                                 new {Id = "bms", Scope = "I", Type = "L", ReferenceName = "Bilma Kanuri"},
                                 new {Id = "bmt", Scope = "I", Type = "L", ReferenceName = "Biao Mon"},
                                 new {Id = "bmu", Scope = "I", Type = "L", ReferenceName = "Somba-Siawari"},
                                 new {Id = "bmv", Scope = "I", Type = "L", ReferenceName = "Bum"},
                                 new {Id = "bmw", Scope = "I", Type = "L", ReferenceName = "Bomwali"},
                                 new {Id = "bmx", Scope = "I", Type = "L", ReferenceName = "Baimak"},
                                 new {Id = "bmz", Scope = "I", Type = "L", ReferenceName = "Baramu"},
                                 new {Id = "bna", Scope = "I", Type = "L", ReferenceName = "Bonerate"},
                                 new {Id = "bnb", Scope = "I", Type = "L", ReferenceName = "Bookan"},
                                 new {Id = "bnc", Scope = "M", Type = "L", ReferenceName = "Bontok"},
                                 new {Id = "bnd", Scope = "I", Type = "L", ReferenceName = "Banda (Indonesia)"},
                                 new {Id = "bne", Scope = "I", Type = "L", ReferenceName = "Bintauna"},
                                 new {Id = "bnf", Scope = "I", Type = "L", ReferenceName = "Masiwang"},
                                 new {Id = "bng", Scope = "I", Type = "L", ReferenceName = "Benga"},
                                 new {Id = "bni", Scope = "I", Type = "L", ReferenceName = "Bangi"},
                                 new {Id = "bnj", Scope = "I", Type = "L", ReferenceName = "Eastern Tawbuid"},
                                 new {Id = "bnk", Scope = "I", Type = "L", ReferenceName = "Bierebo"},
                                 new {Id = "bnl", Scope = "I", Type = "L", ReferenceName = "Boon"},
                                 new {Id = "bnm", Scope = "I", Type = "L", ReferenceName = "Batanga"},
                                 new {Id = "bnn", Scope = "I", Type = "L", ReferenceName = "Bunun"},
                                 new {Id = "bno", Scope = "I", Type = "L", ReferenceName = "Bantoanon"},
                                 new {Id = "bnp", Scope = "I", Type = "L", ReferenceName = "Bola"},
                                 new {Id = "bnq", Scope = "I", Type = "L", ReferenceName = "Bantik"},
                                 new {Id = "bnr", Scope = "I", Type = "L", ReferenceName = "Butmas-Tur"},
                                 new {Id = "bns", Scope = "I", Type = "L", ReferenceName = "Bundeli"},
                                 new {Id = "bnu", Scope = "I", Type = "L", ReferenceName = "Bentong"},
                                 new {Id = "bnv", Scope = "I", Type = "L", ReferenceName = "Bonerif"},
                                 new {Id = "bnw", Scope = "I", Type = "L", ReferenceName = "Bisis"},
                                 new {Id = "bnx", Scope = "I", Type = "L", ReferenceName = "Bangubangu"},
                                 new {Id = "bny", Scope = "I", Type = "L", ReferenceName = "Bintulu"},
                                 new {Id = "bnz", Scope = "I", Type = "L", ReferenceName = "Beezen"},
                                 new {Id = "boa", Scope = "I", Type = "L", ReferenceName = "Bora"},
                                 new {Id = "bob", Scope = "I", Type = "L", ReferenceName = "Aweer"},
                                 new
                                 {
                                     Id            = "bod",
                                     Part2B        = "tib",
                                     Part2T        = "bod",
                                     Part1         = "bo",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tibetan"
                                 }, new {Id = "boe", Scope = "I", Type = "L", ReferenceName = "Mundabli"},
                                 new {Id    = "bof", Scope = "I", Type = "L", ReferenceName = "Bolon"},
                                 new {Id    = "bog", Scope = "I", Type = "L", ReferenceName = "Bamako Sign Language"},
                                 new {Id    = "boh", Scope = "I", Type = "L", ReferenceName = "Boma"},
                                 new {Id    = "boi", Scope = "I", Type = "E", ReferenceName = "Barbareño"},
                                 new {Id    = "boj", Scope = "I", Type = "L", ReferenceName = "Anjam"},
                                 new {Id    = "bok", Scope = "I", Type = "L", ReferenceName = "Bonjo"},
                                 new {Id    = "bol", Scope = "I", Type = "L", ReferenceName = "Bole"},
                                 new {Id    = "bom", Scope = "I", Type = "L", ReferenceName = "Berom"},
                                 new {Id    = "bon", Scope = "I", Type = "L", ReferenceName = "Bine"},
                                 new {Id    = "boo", Scope = "I", Type = "L", ReferenceName = "Tiemacèwè Bozo"},
                                 new {Id    = "bop", Scope = "I", Type = "L", ReferenceName = "Bonkiman"},
                                 new {Id    = "boq", Scope = "I", Type = "L", ReferenceName = "Bogaya"},
                                 new {Id    = "bor", Scope = "I", Type = "L", ReferenceName = "Borôro"},
                                 new
                                 {
                                     Id            = "bos",
                                     Part2B        = "bos",
                                     Part2T        = "bos",
                                     Part1         = "bs",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bosnian"
                                 }, new {Id = "bot", Scope = "I", Type = "L", ReferenceName = "Bongo"},
                                 new {Id    = "bou", Scope = "I", Type = "L", ReferenceName = "Bondei"},
                                 new {Id    = "bov", Scope = "I", Type = "L", ReferenceName = "Tuwuli"},
                                 new {Id    = "bow", Scope = "I", Type = "E", ReferenceName = "Rema"},
                                 new {Id    = "box", Scope = "I", Type = "L", ReferenceName = "Buamu"},
                                 new
                                 {
                                     Id            = "boy",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bodo (Central African Republic)"
                                 }, new {Id = "boz", Scope = "I", Type = "L", ReferenceName = "Tiéyaxo Bozo"},
                                 new {Id    = "bpa", Scope = "I", Type = "L", ReferenceName = "Daakaka"},
                                 new {Id    = "bpb", Scope = "I", Type = "E", ReferenceName = "Barbacoas"},
                                 new {Id    = "bpd", Scope = "I", Type = "L", ReferenceName = "Banda-Banda"},
                                 new {Id    = "bpg", Scope = "I", Type = "L", ReferenceName = "Bonggo"},
                                 new {Id    = "bph", Scope = "I", Type = "L", ReferenceName = "Botlikh"},
                                 new {Id    = "bpi", Scope = "I", Type = "L", ReferenceName = "Bagupi"},
                                 new {Id    = "bpj", Scope = "I", Type = "L", ReferenceName = "Binji"},
                                 new {Id    = "bpk", Scope = "I", Type = "L", ReferenceName = "Orowe"},
                                 new
                                 {
                                     Id            = "bpl",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Broome Pearling Lugger Pidgin"
                                 }, new {Id = "bpm", Scope = "I", Type = "L", ReferenceName = "Biyom"},
                                 new {Id    = "bpn", Scope = "I", Type = "L", ReferenceName = "Dzao Min"},
                                 new {Id    = "bpo", Scope = "I", Type = "L", ReferenceName = "Anasi"},
                                 new {Id    = "bpp", Scope = "I", Type = "L", ReferenceName = "Kaure"},
                                 new {Id    = "bpq", Scope = "I", Type = "L", ReferenceName = "Banda Malay"},
                                 new {Id    = "bpr", Scope = "I", Type = "L", ReferenceName = "Koronadal Blaan"},
                                 new {Id    = "bps", Scope = "I", Type = "L", ReferenceName = "Sarangani Blaan"},
                                 new {Id    = "bpt", Scope = "I", Type = "E", ReferenceName = "Barrow Point"},
                                 new {Id    = "bpu", Scope = "I", Type = "L", ReferenceName = "Bongu"},
                                 new {Id    = "bpv", Scope = "I", Type = "L", ReferenceName = "Bian Marind"},
                                 new
                                     {
                                         Id            = "bpw",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Bo (Papua New Guinea)"
                                     },
                                 new {Id = "bpx", Scope = "I", Type = "L", ReferenceName = "Palya Bareli"},
                                 new {Id = "bpy", Scope = "I", Type = "L", ReferenceName = "Bishnupriya"},
                                 new {Id = "bpz", Scope = "I", Type = "L", ReferenceName = "Bilba"},
                                 new {Id = "bqa", Scope = "I", Type = "L", ReferenceName = "Tchumbuli"},
                                 new {Id = "bqb", Scope = "I", Type = "L", ReferenceName = "Bagusa"},
                                 new {Id = "bqc", Scope = "I", Type = "L", ReferenceName = "Boko (Benin)"},
                                 new {Id = "bqd", Scope = "I", Type = "L", ReferenceName = "Bung"},
                                 new {Id = "bqf", Scope = "I", Type = "E", ReferenceName = "Baga Kaloum"},
                                 new {Id = "bqg", Scope = "I", Type = "L", ReferenceName = "Bago-Kusuntu"},
                                 new {Id = "bqh", Scope = "I", Type = "L", ReferenceName = "Baima"},
                                 new {Id = "bqi", Scope = "I", Type = "L", ReferenceName = "Bakhtiari"},
                                 new {Id = "bqj", Scope = "I", Type = "L", ReferenceName = "Bandial"},
                                 new {Id = "bqk", Scope = "I", Type = "L", ReferenceName = "Banda-Mbrès"},
                                 new {Id = "bql", Scope = "I", Type = "L", ReferenceName = "Bilakura"},
                                 new {Id = "bqm", Scope = "I", Type = "L", ReferenceName = "Wumboko"},
                                 new
                                     {
                                         Id            = "bqn",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Bulgarian Sign Language"
                                     },
                                 new {Id = "bqo", Scope = "I", Type = "L", ReferenceName = "Balo"},
                                 new {Id = "bqp", Scope = "I", Type = "L", ReferenceName = "Busa"},
                                 new {Id = "bqq", Scope = "I", Type = "L", ReferenceName = "Biritai"},
                                 new {Id = "bqr", Scope = "I", Type = "L", ReferenceName = "Burusu"},
                                 new {Id = "bqs", Scope = "I", Type = "L", ReferenceName = "Bosngun"},
                                 new {Id = "bqt", Scope = "I", Type = "L", ReferenceName = "Bamukumbit"},
                                 new {Id = "bqu", Scope = "I", Type = "L", ReferenceName = "Boguru"},
                                 new {Id = "bqv", Scope = "I", Type = "L", ReferenceName = "Koro Wachi"},
                                 new {Id = "bqw", Scope = "I", Type = "L", ReferenceName = "Buru (Nigeria)"},
                                 new {Id = "bqx", Scope = "I", Type = "L", ReferenceName = "Baangi"},
                                 new
                                     {
                                         Id            = "bqy",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Bengkala Sign Language"
                                     },
                                 new {Id = "bqz", Scope = "I", Type = "L", ReferenceName = "Bakaka"},
                                 new
                                 {
                                     Id            = "bra",
                                     Part2B        = "bra",
                                     Part2T        = "bra",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Braj"
                                 }, new {Id = "brb", Scope = "I", Type = "L", ReferenceName = "Lave"},
                                 new {Id    = "brc", Scope = "I", Type = "E", ReferenceName = "Berbice Creole Dutch"},
                                 new {Id    = "brd", Scope = "I", Type = "L", ReferenceName = "Baraamu"},
                                 new
                                 {
                                     Id            = "bre",
                                     Part2B        = "bre",
                                     Part2T        = "bre",
                                     Part1         = "br",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Breton"
                                 }, new {Id = "brf", Scope = "I", Type = "L", ReferenceName = "Bera"},
                                 new {Id    = "brg", Scope = "I", Type = "L", ReferenceName = "Baure"},
                                 new {Id    = "brh", Scope = "I", Type = "L", ReferenceName = "Brahui"},
                                 new {Id    = "bri", Scope = "I", Type = "L", ReferenceName = "Mokpwe"},
                                 new {Id    = "brj", Scope = "I", Type = "L", ReferenceName = "Bieria"},
                                 new {Id    = "brk", Scope = "I", Type = "E", ReferenceName = "Birked"},
                                 new {Id    = "brl", Scope = "I", Type = "L", ReferenceName = "Birwa"},
                                 new {Id    = "brm", Scope = "I", Type = "L", ReferenceName = "Barambu"},
                                 new {Id    = "brn", Scope = "I", Type = "L", ReferenceName = "Boruca"},
                                 new {Id    = "bro", Scope = "I", Type = "L", ReferenceName = "Brokkat"},
                                 new {Id    = "brp", Scope = "I", Type = "L", ReferenceName = "Barapasi"},
                                 new {Id    = "brq", Scope = "I", Type = "L", ReferenceName = "Breri"},
                                 new {Id    = "brr", Scope = "I", Type = "L", ReferenceName = "Birao"},
                                 new {Id    = "brs", Scope = "I", Type = "L", ReferenceName = "Baras"},
                                 new {Id    = "brt", Scope = "I", Type = "L", ReferenceName = "Bitare"},
                                 new {Id    = "bru", Scope = "I", Type = "L", ReferenceName = "Eastern Bru"},
                                 new {Id    = "brv", Scope = "I", Type = "L", ReferenceName = "Western Bru"},
                                 new {Id    = "brw", Scope = "I", Type = "L", ReferenceName = "Bellari"},
                                 new {Id    = "brx", Scope = "I", Type = "L", ReferenceName = "Bodo (India)"},
                                 new {Id    = "bry", Scope = "I", Type = "L", ReferenceName = "Burui"},
                                 new {Id    = "brz", Scope = "I", Type = "L", ReferenceName = "Bilbil"},
                                 new {Id    = "bsa", Scope = "I", Type = "L", ReferenceName = "Abinomn"},
                                 new {Id    = "bsb", Scope = "I", Type = "L", ReferenceName = "Brunei Bisaya"},
                                 new {Id    = "bsc", Scope = "I", Type = "L", ReferenceName = "Bassari"},
                                 new {Id    = "bse", Scope = "I", Type = "L", ReferenceName = "Wushi"},
                                 new {Id    = "bsf", Scope = "I", Type = "L", ReferenceName = "Bauchi"},
                                 new {Id    = "bsg", Scope = "I", Type = "L", ReferenceName = "Bashkardi"},
                                 new {Id    = "bsh", Scope = "I", Type = "L", ReferenceName = "Kati"},
                                 new {Id    = "bsi", Scope = "I", Type = "L", ReferenceName = "Bassossi"},
                                 new {Id    = "bsj", Scope = "I", Type = "L", ReferenceName = "Bangwinji"},
                                 new {Id    = "bsk", Scope = "I", Type = "L", ReferenceName = "Burushaski"},
                                 new {Id    = "bsl", Scope = "I", Type = "E", ReferenceName = "Basa-Gumna"},
                                 new {Id    = "bsm", Scope = "I", Type = "L", ReferenceName = "Busami"},
                                 new {Id    = "bsn", Scope = "I", Type = "L", ReferenceName = "Barasana-Eduria"},
                                 new {Id    = "bso", Scope = "I", Type = "L", ReferenceName = "Buso"},
                                 new {Id    = "bsp", Scope = "I", Type = "L", ReferenceName = "Baga Sitemu"},
                                 new {Id    = "bsq", Scope = "I", Type = "L", ReferenceName = "Bassa"},
                                 new {Id    = "bsr", Scope = "I", Type = "L", ReferenceName = "Bassa-Kontagora"},
                                 new {Id    = "bss", Scope = "I", Type = "L", ReferenceName = "Akoose"},
                                 new {Id    = "bst", Scope = "I", Type = "L", ReferenceName = "Basketo"},
                                 new {Id    = "bsu", Scope = "I", Type = "L", ReferenceName = "Bahonsuai"},
                                 new {Id    = "bsv", Scope = "I", Type = "E", ReferenceName = "Baga Sobané"},
                                 new {Id    = "bsw", Scope = "I", Type = "L", ReferenceName = "Baiso"},
                                 new {Id    = "bsx", Scope = "I", Type = "L", ReferenceName = "Yangkam"},
                                 new {Id    = "bsy", Scope = "I", Type = "L", ReferenceName = "Sabah Bisaya"},
                                 new {Id    = "bta", Scope = "I", Type = "L", ReferenceName = "Bata"},
                                 new {Id    = "btc", Scope = "I", Type = "L", ReferenceName = "Bati (Cameroon)"},
                                 new {Id    = "btd", Scope = "I", Type = "L", ReferenceName = "Batak Dairi"},
                                 new {Id    = "bte", Scope = "I", Type = "E", ReferenceName = "Gamo-Ningi"},
                                 new {Id    = "btf", Scope = "I", Type = "L", ReferenceName = "Birgit"},
                                 new {Id    = "btg", Scope = "I", Type = "L", ReferenceName = "Gagnoa Bété"},
                                 new {Id    = "bth", Scope = "I", Type = "L", ReferenceName = "Biatah Bidayuh"},
                                 new {Id    = "bti", Scope = "I", Type = "L", ReferenceName = "Burate"},
                                 new {Id    = "btj", Scope = "I", Type = "L", ReferenceName = "Bacanese Malay"},
                                 new {Id    = "btm", Scope = "I", Type = "L", ReferenceName = "Batak Mandailing"},
                                 new {Id    = "btn", Scope = "I", Type = "L", ReferenceName = "Ratagnon"},
                                 new {Id    = "bto", Scope = "I", Type = "L", ReferenceName = "Rinconada Bikol"},
                                 new {Id    = "btp", Scope = "I", Type = "L", ReferenceName = "Budibud"},
                                 new {Id    = "btq", Scope = "I", Type = "L", ReferenceName = "Batek"},
                                 new {Id    = "btr", Scope = "I", Type = "L", ReferenceName = "Baetora"},
                                 new {Id    = "bts", Scope = "I", Type = "L", ReferenceName = "Batak Simalungun"},
                                 new {Id    = "btt", Scope = "I", Type = "L", ReferenceName = "Bete-Bendi"},
                                 new {Id    = "btu", Scope = "I", Type = "L", ReferenceName = "Batu"},
                                 new {Id    = "btv", Scope = "I", Type = "L", ReferenceName = "Bateri"},
                                 new {Id    = "btw", Scope = "I", Type = "L", ReferenceName = "Butuanon"},
                                 new {Id    = "btx", Scope = "I", Type = "L", ReferenceName = "Batak Karo"},
                                 new {Id    = "bty", Scope = "I", Type = "L", ReferenceName = "Bobot"},
                                 new {Id    = "btz", Scope = "I", Type = "L", ReferenceName = "Batak Alas-Kluet"},
                                 new
                                 {
                                     Id            = "bua",
                                     Part2B        = "bua",
                                     Part2T        = "bua",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Buriat"
                                 }, new {Id = "bub", Scope = "I", Type = "L", ReferenceName = "Bua"},
                                 new {Id    = "buc", Scope = "I", Type = "L", ReferenceName = "Bushi"},
                                 new {Id    = "bud", Scope = "I", Type = "L", ReferenceName = "Ntcham"},
                                 new {Id    = "bue", Scope = "I", Type = "E", ReferenceName = "Beothuk"},
                                 new {Id    = "buf", Scope = "I", Type = "L", ReferenceName = "Bushoong"},
                                 new
                                 {
                                     Id            = "bug",
                                     Part2B        = "bug",
                                     Part2T        = "bug",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Buginese"
                                 }, new {Id = "buh", Scope = "I", Type = "L", ReferenceName = "Younuo Bunu"},
                                 new {Id    = "bui", Scope = "I", Type = "L", ReferenceName = "Bongili"},
                                 new {Id    = "buj", Scope = "I", Type = "L", ReferenceName = "Basa-Gurmana"},
                                 new {Id    = "buk", Scope = "I", Type = "L", ReferenceName = "Bugawac"},
                                 new
                                 {
                                     Id            = "bul",
                                     Part2B        = "bul",
                                     Part2T        = "bul",
                                     Part1         = "bg",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bulgarian"
                                 }, new {Id = "bum", Scope = "I", Type = "L", ReferenceName = "Bulu (Cameroon)"},
                                 new {Id    = "bun", Scope = "I", Type = "L", ReferenceName = "Sherbro"},
                                 new {Id    = "buo", Scope = "I", Type = "L", ReferenceName = "Terei"},
                                 new {Id    = "bup", Scope = "I", Type = "L", ReferenceName = "Busoa"},
                                 new {Id    = "buq", Scope = "I", Type = "L", ReferenceName = "Brem"},
                                 new {Id    = "bus", Scope = "I", Type = "L", ReferenceName = "Bokobaru"},
                                 new {Id    = "but", Scope = "I", Type = "L", ReferenceName = "Bungain"},
                                 new {Id    = "buu", Scope = "I", Type = "L", ReferenceName = "Budu"},
                                 new {Id    = "buv", Scope = "I", Type = "L", ReferenceName = "Bun"},
                                 new {Id    = "buw", Scope = "I", Type = "L", ReferenceName = "Bubi"},
                                 new {Id    = "bux", Scope = "I", Type = "L", ReferenceName = "Boghom"},
                                 new {Id    = "buy", Scope = "I", Type = "L", ReferenceName = "Bullom So"},
                                 new {Id    = "buz", Scope = "I", Type = "L", ReferenceName = "Bukwen"},
                                 new {Id    = "bva", Scope = "I", Type = "L", ReferenceName = "Barein"},
                                 new {Id    = "bvb", Scope = "I", Type = "L", ReferenceName = "Bube"},
                                 new {Id    = "bvc", Scope = "I", Type = "L", ReferenceName = "Baelelea"},
                                 new {Id    = "bvd", Scope = "I", Type = "L", ReferenceName = "Baeggu"},
                                 new {Id    = "bve", Scope = "I", Type = "L", ReferenceName = "Berau Malay"},
                                 new {Id    = "bvf", Scope = "I", Type = "L", ReferenceName = "Boor"},
                                 new {Id    = "bvg", Scope = "I", Type = "L", ReferenceName = "Bonkeng"},
                                 new {Id    = "bvh", Scope = "I", Type = "L", ReferenceName = "Bure"},
                                 new {Id    = "bvi", Scope = "I", Type = "L", ReferenceName = "Belanda Viri"},
                                 new {Id    = "bvj", Scope = "I", Type = "L", ReferenceName = "Baan"},
                                 new {Id    = "bvk", Scope = "I", Type = "L", ReferenceName = "Bukat"},
                                 new {Id    = "bvl", Scope = "I", Type = "L", ReferenceName = "Bolivian Sign Language"},
                                 new {Id    = "bvm", Scope = "I", Type = "L", ReferenceName = "Bamunka"},
                                 new {Id    = "bvn", Scope = "I", Type = "L", ReferenceName = "Buna"},
                                 new {Id    = "bvo", Scope = "I", Type = "L", ReferenceName = "Bolgo"},
                                 new {Id    = "bvp", Scope = "I", Type = "L", ReferenceName = "Bumang"},
                                 new {Id    = "bvq", Scope = "I", Type = "L", ReferenceName = "Birri"},
                                 new {Id    = "bvr", Scope = "I", Type = "L", ReferenceName = "Burarra"},
                                 new {Id    = "bvt", Scope = "I", Type = "L", ReferenceName = "Bati (Indonesia)"},
                                 new {Id    = "bvu", Scope = "I", Type = "L", ReferenceName = "Bukit Malay"},
                                 new {Id    = "bvv", Scope = "I", Type = "E", ReferenceName = "Baniva"},
                                 new {Id    = "bvw", Scope = "I", Type = "L", ReferenceName = "Boga"},
                                 new {Id    = "bvx", Scope = "I", Type = "L", ReferenceName = "Dibole"},
                                 new {Id    = "bvy", Scope = "I", Type = "L", ReferenceName = "Baybayanon"},
                                 new {Id    = "bvz", Scope = "I", Type = "L", ReferenceName = "Bauzi"},
                                 new {Id    = "bwa", Scope = "I", Type = "L", ReferenceName = "Bwatoo"},
                                 new {Id    = "bwb", Scope = "I", Type = "L", ReferenceName = "Namosi-Naitasiri-Serua"},
                                 new {Id    = "bwc", Scope = "I", Type = "L", ReferenceName = "Bwile"},
                                 new {Id    = "bwd", Scope = "I", Type = "L", ReferenceName = "Bwaidoka"},
                                 new {Id    = "bwe", Scope = "I", Type = "L", ReferenceName = "Bwe Karen"},
                                 new {Id    = "bwf", Scope = "I", Type = "L", ReferenceName = "Boselewa"},
                                 new {Id    = "bwg", Scope = "I", Type = "L", ReferenceName = "Barwe"},
                                 new {Id    = "bwh", Scope = "I", Type = "L", ReferenceName = "Bishuo"},
                                 new {Id    = "bwi", Scope = "I", Type = "L", ReferenceName = "Baniwa"},
                                 new {Id    = "bwj", Scope = "I", Type = "L", ReferenceName = "Láá Láá Bwamu"},
                                 new {Id    = "bwk", Scope = "I", Type = "L", ReferenceName = "Bauwaki"},
                                 new {Id    = "bwl", Scope = "I", Type = "L", ReferenceName = "Bwela"},
                                 new {Id    = "bwm", Scope = "I", Type = "L", ReferenceName = "Biwat"},
                                 new {Id    = "bwn", Scope = "I", Type = "L", ReferenceName = "Wunai Bunu"},
                                 new {Id    = "bwo", Scope = "I", Type = "L", ReferenceName = "Boro (Ethiopia)"},
                                 new {Id    = "bwp", Scope = "I", Type = "L", ReferenceName = "Mandobo Bawah"},
                                 new {Id    = "bwq", Scope = "I", Type = "L", ReferenceName = "Southern Bobo Madaré"},
                                 new {Id    = "bwr", Scope = "I", Type = "L", ReferenceName = "Bura-Pabir"},
                                 new {Id    = "bws", Scope = "I", Type = "L", ReferenceName = "Bomboma"},
                                 new {Id    = "bwt", Scope = "I", Type = "L", ReferenceName = "Bafaw-Balong"},
                                 new {Id    = "bwu", Scope = "I", Type = "L", ReferenceName = "Buli (Ghana)"},
                                 new {Id    = "bww", Scope = "I", Type = "L", ReferenceName = "Bwa"},
                                 new {Id    = "bwx", Scope = "I", Type = "L", ReferenceName = "Bu-Nao Bunu"},
                                 new {Id    = "bwy", Scope = "I", Type = "L", ReferenceName = "Cwi Bwamu"},
                                 new {Id    = "bwz", Scope = "I", Type = "L", ReferenceName = "Bwisi"},
                                 new {Id    = "bxa", Scope = "I", Type = "L", ReferenceName = "Tairaha"},
                                 new {Id    = "bxb", Scope = "I", Type = "L", ReferenceName = "Belanda Bor"},
                                 new {Id    = "bxc", Scope = "I", Type = "L", ReferenceName = "Molengue"},
                                 new {Id    = "bxd", Scope = "I", Type = "L", ReferenceName = "Pela"},
                                 new {Id    = "bxe", Scope = "I", Type = "L", ReferenceName = "Birale"},
                                 new {Id    = "bxf", Scope = "I", Type = "L", ReferenceName = "Bilur"},
                                 new {Id    = "bxg", Scope = "I", Type = "L", ReferenceName = "Bangala"},
                                 new {Id    = "bxh", Scope = "I", Type = "L", ReferenceName = "Buhutu"},
                                 new {Id    = "bxi", Scope = "I", Type = "E", ReferenceName = "Pirlatapa"},
                                 new {Id    = "bxj", Scope = "I", Type = "L", ReferenceName = "Bayungu"},
                                 new {Id    = "bxk", Scope = "I", Type = "L", ReferenceName = "Bukusu"},
                                 new {Id    = "bxl", Scope = "I", Type = "L", ReferenceName = "Jalkunan"},
                                 new {Id    = "bxm", Scope = "I", Type = "L", ReferenceName = "Mongolia Buriat"},
                                 new {Id    = "bxn", Scope = "I", Type = "L", ReferenceName = "Burduna"},
                                 new {Id    = "bxo", Scope = "I", Type = "L", ReferenceName = "Barikanchi"},
                                 new {Id    = "bxp", Scope = "I", Type = "L", ReferenceName = "Bebil"},
                                 new {Id    = "bxq", Scope = "I", Type = "L", ReferenceName = "Beele"},
                                 new {Id    = "bxr", Scope = "I", Type = "L", ReferenceName = "Russia Buriat"},
                                 new {Id    = "bxs", Scope = "I", Type = "L", ReferenceName = "Busam"},
                                 new {Id    = "bxu", Scope = "I", Type = "L", ReferenceName = "China Buriat"},
                                 new {Id    = "bxv", Scope = "I", Type = "L", ReferenceName = "Berakou"},
                                 new {Id    = "bxw", Scope = "I", Type = "L", ReferenceName = "Bankagooma"},
                                 new {Id    = "bxz", Scope = "I", Type = "L", ReferenceName = "Binahari"},
                                 new {Id    = "bya", Scope = "I", Type = "L", ReferenceName = "Batak"},
                                 new {Id    = "byb", Scope = "I", Type = "L", ReferenceName = "Bikya"},
                                 new {Id    = "byc", Scope = "I", Type = "L", ReferenceName = "Ubaghara"},
                                 new {Id    = "byd", Scope = "I", Type = "L", ReferenceName = "Benyadu'"},
                                 new {Id    = "bye", Scope = "I", Type = "L", ReferenceName = "Pouye"},
                                 new {Id    = "byf", Scope = "I", Type = "L", ReferenceName = "Bete"},
                                 new {Id    = "byg", Scope = "I", Type = "E", ReferenceName = "Baygo"},
                                 new {Id    = "byh", Scope = "I", Type = "L", ReferenceName = "Bhujel"},
                                 new {Id    = "byi", Scope = "I", Type = "L", ReferenceName = "Buyu"},
                                 new {Id    = "byj", Scope = "I", Type = "L", ReferenceName = "Bina (Nigeria)"},
                                 new {Id    = "byk", Scope = "I", Type = "L", ReferenceName = "Biao"},
                                 new {Id    = "byl", Scope = "I", Type = "L", ReferenceName = "Bayono"},
                                 new {Id    = "bym", Scope = "I", Type = "L", ReferenceName = "Bidjara"},
                                 new
                                 {
                                     Id            = "byn",
                                     Part2B        = "byn",
                                     Part2T        = "byn",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Bilin"
                                 }, new {Id = "byo", Scope = "I", Type = "L", ReferenceName = "Biyo"},
                                 new {Id    = "byp", Scope = "I", Type = "L", ReferenceName = "Bumaji"},
                                 new {Id    = "byq", Scope = "I", Type = "E", ReferenceName = "Basay"},
                                 new {Id    = "byr", Scope = "I", Type = "L", ReferenceName = "Baruya"},
                                 new {Id    = "bys", Scope = "I", Type = "L", ReferenceName = "Burak"},
                                 new {Id    = "byt", Scope = "I", Type = "E", ReferenceName = "Berti"},
                                 new {Id    = "byv", Scope = "I", Type = "L", ReferenceName = "Medumba"},
                                 new {Id    = "byw", Scope = "I", Type = "L", ReferenceName = "Belhariya"},
                                 new {Id    = "byx", Scope = "I", Type = "L", ReferenceName = "Qaqet"},
                                 new {Id    = "byz", Scope = "I", Type = "L", ReferenceName = "Banaro"},
                                 new {Id    = "bza", Scope = "I", Type = "L", ReferenceName = "Bandi"},
                                 new {Id    = "bzb", Scope = "I", Type = "L", ReferenceName = "Andio"},
                                 new
                                 {
                                     Id            = "bzc",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Southern Betsimisaraka Malagasy"
                                 }, new {Id = "bzd", Scope = "I", Type = "L", ReferenceName = "Bribri"},
                                 new {Id    = "bze", Scope = "I", Type = "L", ReferenceName = "Jenaama Bozo"},
                                 new {Id    = "bzf", Scope = "I", Type = "L", ReferenceName = "Boikin"},
                                 new {Id    = "bzg", Scope = "I", Type = "L", ReferenceName = "Babuza"},
                                 new {Id    = "bzh", Scope = "I", Type = "L", ReferenceName = "Mapos Buang"},
                                 new {Id    = "bzi", Scope = "I", Type = "L", ReferenceName = "Bisu"},
                                 new
                                     {
                                         Id            = "bzj",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Belize Kriol English"
                                     },
                                 new
                                     {
                                         Id            = "bzk",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Nicaragua Creole English"
                                     },
                                 new {Id = "bzl", Scope = "I", Type = "L", ReferenceName = "Boano (Sulawesi)"},
                                 new {Id = "bzm", Scope = "I", Type = "L", ReferenceName = "Bolondo"},
                                 new {Id = "bzn", Scope = "I", Type = "L", ReferenceName = "Boano (Maluku)"},
                                 new {Id = "bzo", Scope = "I", Type = "L", ReferenceName = "Bozaba"},
                                 new {Id = "bzp", Scope = "I", Type = "L", ReferenceName = "Kemberano"},
                                 new {Id = "bzq", Scope = "I", Type = "L", ReferenceName = "Buli (Indonesia)"},
                                 new {Id = "bzr", Scope = "I", Type = "E", ReferenceName = "Biri"},
                                 new
                                     {
                                         Id            = "bzs",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Brazilian Sign Language"
                                     },
                                 new {Id = "bzt", Scope = "I", Type = "C", ReferenceName = "Brithenig"},
                                 new {Id = "bzu", Scope = "I", Type = "L", ReferenceName = "Burmeso"},
                                 new {Id = "bzv", Scope = "I", Type = "L", ReferenceName = "Naami"},
                                 new {Id = "bzw", Scope = "I", Type = "L", ReferenceName = "Basa (Nigeria)"},
                                 new {Id = "bzx", Scope = "I", Type = "L", ReferenceName = "Kɛlɛngaxo Bozo"},
                                 new {Id = "bzy", Scope = "I", Type = "L", ReferenceName = "Obanliku"},
                                 new {Id = "bzz", Scope = "I", Type = "L", ReferenceName = "Evant"});
        }
    }
}