using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class D
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(new {Id = "daa", Scope = "I", Type = "L", ReferenceName = "Dangaléat"},
                                 new {Id = "dac", Scope = "I", Type = "L", ReferenceName = "Dambi"},
                                 new {Id = "dad", Scope = "I", Type = "L", ReferenceName = "Marik"},
                                 new {Id = "dae", Scope = "I", Type = "L", ReferenceName = "Duupa"},
                                 new {Id = "dag", Scope = "I", Type = "L", ReferenceName = "Dagbani"},
                                 new {Id = "dah", Scope = "I", Type = "L", ReferenceName = "Gwahatike"},
                                 new {Id = "dai", Scope = "I", Type = "L", ReferenceName = "Day"},
                                 new {Id = "daj", Scope = "I", Type = "L", ReferenceName = "Dar Fur Daju"},
                                 new
                                 {
                                     Id            = "dak",
                                     Part2B        = "dak",
                                     Part2T        = "dak",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Dakota"
                                 }, new {Id = "dal", Scope = "I", Type = "L", ReferenceName = "Dahalo"},
                                 new {Id    = "dam", Scope = "I", Type = "L", ReferenceName = "Damakawa"},
                                 new
                                 {
                                     Id            = "dan",
                                     Part2B        = "dan",
                                     Part2T        = "dan",
                                     Part1         = "da",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Danish"
                                 }, new {Id = "dao", Scope = "I", Type = "L", ReferenceName = "Daai Chin"},
                                 new {Id    = "daq", Scope = "I", Type = "L", ReferenceName = "Dandami Maria"},
                                 new
                                 {
                                     Id            = "dar",
                                     Part2B        = "dar",
                                     Part2T        = "dar",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Dargwa"
                                 }, new {Id = "das", Scope = "I", Type = "L", ReferenceName = "Daho-Doo"},
                                 new {Id    = "dau", Scope = "I", Type = "L", ReferenceName = "Dar Sila Daju"},
                                 new {Id    = "dav", Scope = "I", Type = "L", ReferenceName = "Taita"},
                                 new {Id    = "daw", Scope = "I", Type = "L", ReferenceName = "Davawenyo"},
                                 new {Id    = "dax", Scope = "I", Type = "L", ReferenceName = "Dayi"},
                                 new {Id    = "daz", Scope = "I", Type = "L", ReferenceName = "Dao"},
                                 new {Id    = "dba", Scope = "I", Type = "L", ReferenceName = "Bangime"},
                                 new {Id    = "dbb", Scope = "I", Type = "L", ReferenceName = "Deno"},
                                 new {Id    = "dbd", Scope = "I", Type = "L", ReferenceName = "Dadiya"},
                                 new {Id    = "dbe", Scope = "I", Type = "L", ReferenceName = "Dabe"},
                                 new {Id    = "dbf", Scope = "I", Type = "L", ReferenceName = "Edopi"},
                                 new {Id    = "dbg", Scope = "I", Type = "L", ReferenceName = "Dogul Dom Dogon"},
                                 new {Id    = "dbi", Scope = "I", Type = "L", ReferenceName = "Doka"},
                                 new {Id    = "dbj", Scope = "I", Type = "L", ReferenceName = "Ida'an"},
                                 new {Id    = "dbl", Scope = "I", Type = "L", ReferenceName = "Dyirbal"},
                                 new {Id    = "dbm", Scope = "I", Type = "L", ReferenceName = "Duguri"},
                                 new {Id    = "dbn", Scope = "I", Type = "L", ReferenceName = "Duriankere"},
                                 new {Id    = "dbo", Scope = "I", Type = "L", ReferenceName = "Dulbu"},
                                 new {Id    = "dbp", Scope = "I", Type = "L", ReferenceName = "Duwai"},
                                 new {Id    = "dbq", Scope = "I", Type = "L", ReferenceName = "Daba"},
                                 new {Id    = "dbr", Scope = "I", Type = "L", ReferenceName = "Dabarre"},
                                 new {Id    = "dbt", Scope = "I", Type = "L", ReferenceName = "Ben Tey Dogon"},
                                 new {Id    = "dbu", Scope = "I", Type = "L", ReferenceName = "Bondum Dom Dogon"},
                                 new {Id    = "dbv", Scope = "I", Type = "L", ReferenceName = "Dungu"},
                                 new {Id    = "dbw", Scope = "I", Type = "L", ReferenceName = "Bankan Tey Dogon"},
                                 new {Id    = "dby", Scope = "I", Type = "L", ReferenceName = "Dibiyaso"},
                                 new {Id    = "dcc", Scope = "I", Type = "L", ReferenceName = "Deccan"},
                                 new {Id    = "dcr", Scope = "I", Type = "E", ReferenceName = "Negerhollands"},
                                 new {Id    = "dda", Scope = "I", Type = "E", ReferenceName = "Dadi Dadi"},
                                 new {Id    = "ddd", Scope = "I", Type = "L", ReferenceName = "Dongotono"},
                                 new {Id    = "dde", Scope = "I", Type = "L", ReferenceName = "Doondo"},
                                 new {Id    = "ddg", Scope = "I", Type = "L", ReferenceName = "Fataluku"},
                                 new {Id    = "ddi", Scope = "I", Type = "L", ReferenceName = "West Goodenough"},
                                 new {Id    = "ddj", Scope = "I", Type = "L", ReferenceName = "Jaru"},
                                 new {Id    = "ddn", Scope = "I", Type = "L", ReferenceName = "Dendi (Benin)"},
                                 new {Id    = "ddo", Scope = "I", Type = "L", ReferenceName = "Dido"},
                                 new {Id    = "ddr", Scope = "I", Type = "E", ReferenceName = "Dhudhuroa"},
                                 new {Id    = "dds", Scope = "I", Type = "L", ReferenceName = "Donno So Dogon"},
                                 new {Id    = "ddw", Scope = "I", Type = "L", ReferenceName = "Dawera-Daweloor"},
                                 new {Id    = "dec", Scope = "I", Type = "L", ReferenceName = "Dagik"},
                                 new {Id    = "ded", Scope = "I", Type = "L", ReferenceName = "Dedua"},
                                 new {Id    = "dee", Scope = "I", Type = "L", ReferenceName = "Dewoin"},
                                 new {Id    = "def", Scope = "I", Type = "L", ReferenceName = "Dezfuli"},
                                 new {Id    = "deg", Scope = "I", Type = "L", ReferenceName = "Degema"},
                                 new {Id    = "deh", Scope = "I", Type = "L", ReferenceName = "Dehwari"},
                                 new {Id    = "dei", Scope = "I", Type = "L", ReferenceName = "Demisa"},
                                 new {Id    = "dek", Scope = "I", Type = "L", ReferenceName = "Dek"},
                                 new
                                 {
                                     Id            = "del",
                                     Part2B        = "del",
                                     Part2T        = "del",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Delaware"
                                 }, new {Id = "dem", Scope = "I", Type = "L", ReferenceName = "Dem"},
                                 new
                                 {
                                     Id            = "den",
                                     Part2B        = "den",
                                     Part2T        = "den",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Slave (Athapascan)"
                                 }, new {Id = "dep", Scope = "I", Type = "E", ReferenceName = "Pidgin Delaware"},
                                 new
                                 {
                                     Id            = "deq",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Dendi (Central African Republic)"
                                 }, new {Id = "der", Scope = "I", Type = "L", ReferenceName = "Deori"},
                                 new {Id    = "des", Scope = "I", Type = "L", ReferenceName = "Desano"},
                                 new
                                 {
                                     Id            = "deu",
                                     Part2B        = "ger",
                                     Part2T        = "deu",
                                     Part1         = "de",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "German"
                                 }, new {Id = "dev", Scope = "I", Type = "L", ReferenceName = "Domung"},
                                 new {Id    = "dez", Scope = "I", Type = "L", ReferenceName = "Dengese"},
                                 new {Id    = "dga", Scope = "I", Type = "L", ReferenceName = "Southern Dagaare"},
                                 new {Id    = "dgb", Scope = "I", Type = "L", ReferenceName = "Bunoge Dogon"},
                                 new {Id    = "dgc", Scope = "I", Type = "L", ReferenceName = "Casiguran Dumagat Agta"},
                                 new {Id    = "dgd", Scope = "I", Type = "L", ReferenceName = "Dagaari Dioula"},
                                 new {Id    = "dge", Scope = "I", Type = "L", ReferenceName = "Degenan"},
                                 new {Id    = "dgg", Scope = "I", Type = "L", ReferenceName = "Doga"},
                                 new {Id    = "dgh", Scope = "I", Type = "L", ReferenceName = "Dghwede"},
                                 new {Id    = "dgi", Scope = "I", Type = "L", ReferenceName = "Northern Dagara"},
                                 new {Id    = "dgk", Scope = "I", Type = "L", ReferenceName = "Dagba"},
                                 new {Id    = "dgl", Scope = "I", Type = "L", ReferenceName = "Andaandi"},
                                 new {Id    = "dgn", Scope = "I", Type = "E", ReferenceName = "Dagoman"},
                                 new
                                 {
                                     Id            = "dgo",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Dogri (individual language)"
                                 }, new
                                 {
                                     Id            = "dgr",
                                     Part2B        = "dgr",
                                     Part2T        = "dgr",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Dogrib"
                                 }, new {Id = "dgs", Scope = "I", Type = "L", ReferenceName = "Dogoso"},
                                 new {Id    = "dgt", Scope = "I", Type = "E", ReferenceName = "Ndra'ngith"},
                                 new {Id    = "dgu", Scope = "I", Type = "L", ReferenceName = "Degaru"},
                                 new {Id    = "dgw", Scope = "I", Type = "E", ReferenceName = "Daungwurrung"},
                                 new {Id    = "dgx", Scope = "I", Type = "L", ReferenceName = "Doghoro"},
                                 new {Id    = "dgz", Scope = "I", Type = "L", ReferenceName = "Daga"},
                                 new {Id    = "dhd", Scope = "I", Type = "L", ReferenceName = "Dhundari"},
                                 new {Id    = "dhg", Scope = "I", Type = "L", ReferenceName = "Dhangu-Djangu"},
                                 new {Id    = "dhi", Scope = "I", Type = "L", ReferenceName = "Dhimal"},
                                 new {Id    = "dhl", Scope = "I", Type = "L", ReferenceName = "Dhalandji"},
                                 new {Id    = "dhm", Scope = "I", Type = "L", ReferenceName = "Zemba"},
                                 new {Id    = "dhn", Scope = "I", Type = "L", ReferenceName = "Dhanki"},
                                 new {Id    = "dho", Scope = "I", Type = "L", ReferenceName = "Dhodia"},
                                 new {Id    = "dhr", Scope = "I", Type = "L", ReferenceName = "Dhargari"},
                                 new {Id    = "dhs", Scope = "I", Type = "L", ReferenceName = "Dhaiso"},
                                 new {Id    = "dhu", Scope = "I", Type = "E", ReferenceName = "Dhurga"},
                                 new {Id    = "dhv", Scope = "I", Type = "L", ReferenceName = "Dehu"},
                                 new {Id    = "dhw", Scope = "I", Type = "L", ReferenceName = "Dhanwar (Nepal)"},
                                 new {Id    = "dhx", Scope = "I", Type = "L", ReferenceName = "Dhungaloo"},
                                 new {Id    = "dia", Scope = "I", Type = "L", ReferenceName = "Dia"},
                                 new {Id    = "dib", Scope = "I", Type = "L", ReferenceName = "South Central Dinka"},
                                 new {Id    = "dic", Scope = "I", Type = "L", ReferenceName = "Lakota Dida"},
                                 new {Id    = "did", Scope = "I", Type = "L", ReferenceName = "Didinga"},
                                 new {Id    = "dif", Scope = "I", Type = "E", ReferenceName = "Dieri"},
                                 new {Id    = "dig", Scope = "I", Type = "L", ReferenceName = "Digo"},
                                 new {Id    = "dih", Scope = "I", Type = "L", ReferenceName = "Kumiai"},
                                 new {Id    = "dii", Scope = "I", Type = "L", ReferenceName = "Dimbong"},
                                 new {Id    = "dij", Scope = "I", Type = "L", ReferenceName = "Dai"},
                                 new {Id    = "dik", Scope = "I", Type = "L", ReferenceName = "Southwestern Dinka"},
                                 new {Id    = "dil", Scope = "I", Type = "L", ReferenceName = "Dilling"},
                                 new {Id    = "dim", Scope = "I", Type = "L", ReferenceName = "Dime"},
                                 new
                                 {
                                     Id            = "din",
                                     Part2B        = "din",
                                     Part2T        = "din",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Dinka"
                                 }, new {Id = "dio", Scope = "I", Type = "L", ReferenceName = "Dibo"},
                                 new {Id    = "dip", Scope = "I", Type = "L", ReferenceName = "Northeastern Dinka"},
                                 new
                                 {
                                     Id            = "diq",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Dimli (individual language)"
                                 }, new {Id = "dir", Scope = "I", Type = "L", ReferenceName = "Dirim"},
                                 new {Id    = "dis", Scope = "I", Type = "L", ReferenceName = "Dimasa"},
                                 new {Id    = "diu", Scope = "I", Type = "L", ReferenceName = "Diriku"},
                                 new
                                 {
                                     Id            = "div",
                                     Part2B        = "div",
                                     Part2T        = "div",
                                     Part1         = "dv",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Dhivehi"
                                 }, new {Id = "diw", Scope = "I", Type = "L", ReferenceName = "Northwestern Dinka"},
                                 new {Id    = "dix", Scope = "I", Type = "L", ReferenceName = "Dixon Reef"},
                                 new {Id    = "diy", Scope = "I", Type = "L", ReferenceName = "Diuwe"},
                                 new {Id    = "diz", Scope = "I", Type = "L", ReferenceName = "Ding"},
                                 new {Id    = "dja", Scope = "I", Type = "E", ReferenceName = "Djadjawurrung"},
                                 new {Id    = "djb", Scope = "I", Type = "L", ReferenceName = "Djinba"},
                                 new {Id    = "djc", Scope = "I", Type = "L", ReferenceName = "Dar Daju Daju"},
                                 new {Id    = "djd", Scope = "I", Type = "L", ReferenceName = "Djamindjung"},
                                 new {Id    = "dje", Scope = "I", Type = "L", ReferenceName = "Zarma"},
                                 new {Id    = "djf", Scope = "I", Type = "E", ReferenceName = "Djangun"},
                                 new {Id    = "dji", Scope = "I", Type = "L", ReferenceName = "Djinang"},
                                 new {Id    = "djj", Scope = "I", Type = "L", ReferenceName = "Djeebbana"},
                                 new {Id    = "djk", Scope = "I", Type = "L", ReferenceName = "Eastern Maroon Creole"},
                                 new {Id    = "djm", Scope = "I", Type = "L", ReferenceName = "Jamsay Dogon"},
                                 new {Id    = "djn", Scope = "I", Type = "L", ReferenceName = "Jawoyn"},
                                 new {Id    = "djo", Scope = "I", Type = "L", ReferenceName = "Jangkang"},
                                 new {Id    = "djr", Scope = "I", Type = "L", ReferenceName = "Djambarrpuyngu"},
                                 new {Id    = "dju", Scope = "I", Type = "L", ReferenceName = "Kapriman"},
                                 new {Id    = "djw", Scope = "I", Type = "E", ReferenceName = "Djawi"},
                                 new {Id    = "dka", Scope = "I", Type = "L", ReferenceName = "Dakpakha"},
                                 new {Id    = "dkk", Scope = "I", Type = "L", ReferenceName = "Dakka"},
                                 new {Id    = "dkr", Scope = "I", Type = "L", ReferenceName = "Kuijau"},
                                 new {Id    = "dks", Scope = "I", Type = "L", ReferenceName = "Southeastern Dinka"},
                                 new {Id    = "dkx", Scope = "I", Type = "L", ReferenceName = "Mazagway"},
                                 new {Id    = "dlg", Scope = "I", Type = "L", ReferenceName = "Dolgan"},
                                 new {Id    = "dlk", Scope = "I", Type = "L", ReferenceName = "Dahalik"},
                                 new {Id    = "dlm", Scope = "I", Type = "E", ReferenceName = "Dalmatian"},
                                 new {Id    = "dln", Scope = "I", Type = "L", ReferenceName = "Darlong"},
                                 new {Id    = "dma", Scope = "I", Type = "L", ReferenceName = "Duma"},
                                 new {Id    = "dmb", Scope = "I", Type = "L", ReferenceName = "Mombo Dogon"},
                                 new {Id    = "dmc", Scope = "I", Type = "L", ReferenceName = "Gavak"},
                                 new {Id    = "dmd", Scope = "I", Type = "E", ReferenceName = "Madhi Madhi"},
                                 new {Id    = "dme", Scope = "I", Type = "L", ReferenceName = "Dugwor"},
                                 new {Id    = "dmg", Scope = "I", Type = "L", ReferenceName = "Upper Kinabatangan"},
                                 new {Id    = "dmk", Scope = "I", Type = "L", ReferenceName = "Domaaki"},
                                 new {Id    = "dml", Scope = "I", Type = "L", ReferenceName = "Dameli"},
                                 new {Id    = "dmm", Scope = "I", Type = "L", ReferenceName = "Dama"},
                                 new {Id    = "dmo", Scope = "I", Type = "L", ReferenceName = "Kemedzung"},
                                 new {Id    = "dmr", Scope = "I", Type = "L", ReferenceName = "East Damar"},
                                 new {Id    = "dms", Scope = "I", Type = "L", ReferenceName = "Dampelas"},
                                 new {Id    = "dmu", Scope = "I", Type = "L", ReferenceName = "Dubu"},
                                 new {Id    = "dmv", Scope = "I", Type = "L", ReferenceName = "Dumpas"},
                                 new {Id    = "dmw", Scope = "I", Type = "L", ReferenceName = "Mudburra"},
                                 new {Id    = "dmx", Scope = "I", Type = "L", ReferenceName = "Dema"},
                                 new {Id    = "dmy", Scope = "I", Type = "L", ReferenceName = "Demta"},
                                 new
                                     {
                                         Id            = "dna",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Upper Grand Valley Dani"
                                     },
                                 new {Id = "dnd", Scope = "I", Type = "L", ReferenceName = "Daonda"},
                                 new {Id = "dne", Scope = "I", Type = "L", ReferenceName = "Ndendeule"},
                                 new {Id = "dng", Scope = "I", Type = "L", ReferenceName = "Dungan"},
                                 new
                                     {
                                         Id            = "dni",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Lower Grand Valley Dani"
                                     },
                                 new {Id = "dnj", Scope = "I", Type = "L", ReferenceName = "Dan"},
                                 new {Id = "dnk", Scope = "I", Type = "L", ReferenceName = "Dengka"},
                                 new {Id = "dnn", Scope = "I", Type = "L", ReferenceName = "Dzùùngoo"},
                                 new {Id = "dno", Scope = "I", Type = "L", ReferenceName = "Ndrulo"},
                                 new {Id = "dnr", Scope = "I", Type = "L", ReferenceName = "Danaru"},
                                 new {Id = "dnt", Scope = "I", Type = "L", ReferenceName = "Mid Grand Valley Dani"},
                                 new {Id = "dnu", Scope = "I", Type = "L", ReferenceName = "Danau"},
                                 new {Id = "dnv", Scope = "I", Type = "L", ReferenceName = "Danu"},
                                 new {Id = "dnw", Scope = "I", Type = "L", ReferenceName = "Western Dani"},
                                 new {Id = "dny", Scope = "I", Type = "L", ReferenceName = "Dení"},
                                 new {Id = "doa", Scope = "I", Type = "L", ReferenceName = "Dom"},
                                 new {Id = "dob", Scope = "I", Type = "L", ReferenceName = "Dobu"},
                                 new {Id = "doc", Scope = "I", Type = "L", ReferenceName = "Northern Dong"},
                                 new {Id = "doe", Scope = "I", Type = "L", ReferenceName = "Doe"},
                                 new {Id = "dof", Scope = "I", Type = "L", ReferenceName = "Domu"},
                                 new {Id = "doh", Scope = "I", Type = "L", ReferenceName = "Dong"},
                                 new
                                 {
                                     Id            = "doi",
                                     Part2B        = "doi",
                                     Part2T        = "doi",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Dogri (macrolanguage)"
                                 }, new {Id = "dok", Scope = "I", Type = "L", ReferenceName = "Dondo"},
                                 new {Id    = "dol", Scope = "I", Type = "L", ReferenceName = "Doso"},
                                 new
                                     {
                                         Id            = "don",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Toura (Papua New Guinea)"
                                     },
                                 new {Id = "doo", Scope = "I", Type = "L", ReferenceName = "Dongo"},
                                 new {Id = "dop", Scope = "I", Type = "L", ReferenceName = "Lukpa"},
                                 new
                                     {
                                         Id            = "doq",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Dominican Sign Language"
                                     },
                                 new {Id = "dor", Scope = "I", Type = "L", ReferenceName = "Dori'o"},
                                 new {Id = "dos", Scope = "I", Type = "L", ReferenceName = "Dogosé"},
                                 new {Id = "dot", Scope = "I", Type = "L", ReferenceName = "Dass"},
                                 new {Id = "dov", Scope = "I", Type = "L", ReferenceName = "Dombe"},
                                 new {Id = "dow", Scope = "I", Type = "L", ReferenceName = "Doyayo"},
                                 new {Id = "dox", Scope = "I", Type = "L", ReferenceName = "Bussa"},
                                 new {Id = "doy", Scope = "I", Type = "L", ReferenceName = "Dompo"},
                                 new {Id = "doz", Scope = "I", Type = "L", ReferenceName = "Dorze"},
                                 new {Id = "dpp", Scope = "I", Type = "L", ReferenceName = "Papar"},
                                 new {Id = "drb", Scope = "I", Type = "L", ReferenceName = "Dair"},
                                 new {Id = "drc", Scope = "I", Type = "L", ReferenceName = "Minderico"},
                                 new {Id = "drd", Scope = "I", Type = "L", ReferenceName = "Darmiya"},
                                 new {Id = "dre", Scope = "I", Type = "L", ReferenceName = "Dolpo"},
                                 new {Id = "drg", Scope = "I", Type = "L", ReferenceName = "Rungus"},
                                 new {Id = "dri", Scope = "I", Type = "L", ReferenceName = "C'Lela"},
                                 new {Id = "drl", Scope = "I", Type = "L", ReferenceName = "Paakantyi"},
                                 new {Id = "drn", Scope = "I", Type = "L", ReferenceName = "West Damar"},
                                 new {Id = "dro", Scope = "I", Type = "L", ReferenceName = "Daro-Matu Melanau"},
                                 new {Id = "drq", Scope = "I", Type = "E", ReferenceName = "Dura"},
                                 new {Id = "drr", Scope = "I", Type = "E", ReferenceName = "Dororo"},
                                 new {Id = "drs", Scope = "I", Type = "L", ReferenceName = "Gedeo"},
                                 new {Id = "drt", Scope = "I", Type = "L", ReferenceName = "Drents"},
                                 new {Id = "dru", Scope = "I", Type = "L", ReferenceName = "Rukai"},
                                 new {Id = "dry", Scope = "I", Type = "L", ReferenceName = "Darai"},
                                 new
                                 {
                                     Id            = "dsb",
                                     Part2B        = "dsb",
                                     Part2T        = "dsb",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Lower Sorbian"
                                 }, new {Id = "dse", Scope = "I", Type = "L", ReferenceName = "Dutch Sign Language"},
                                 new {Id    = "dsh", Scope = "I", Type = "L", ReferenceName = "Daasanach"},
                                 new {Id    = "dsi", Scope = "I", Type = "L", ReferenceName = "Disa"},
                                 new {Id    = "dsl", Scope = "I", Type = "L", ReferenceName = "Danish Sign Language"},
                                 new {Id    = "dsn", Scope = "I", Type = "E", ReferenceName = "Dusner"},
                                 new {Id    = "dso", Scope = "I", Type = "L", ReferenceName = "Desiya"},
                                 new {Id    = "dsq", Scope = "I", Type = "L", ReferenceName = "Tadaksahak"},
                                 new {Id    = "dta", Scope = "I", Type = "L", ReferenceName = "Daur"},
                                 new
                                 {
                                     Id            = "dtb",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Labuk-Kinabatangan Kadazan"
                                 }, new {Id = "dtd", Scope = "I", Type = "L", ReferenceName = "Ditidaht"},
                                 new {Id    = "dth", Scope = "I", Type = "E", ReferenceName = "Adithinngithigh"},
                                 new {Id    = "dti", Scope = "I", Type = "L", ReferenceName = "Ana Tinga Dogon"},
                                 new {Id    = "dtk", Scope = "I", Type = "L", ReferenceName = "Tene Kan Dogon"},
                                 new {Id    = "dtm", Scope = "I", Type = "L", ReferenceName = "Tomo Kan Dogon"},
                                 new {Id    = "dtn", Scope = "I", Type = "L", ReferenceName = "Daatsʼíin"},
                                 new {Id    = "dto", Scope = "I", Type = "L", ReferenceName = "Tommo So Dogon"},
                                 new {Id    = "dtp", Scope = "I", Type = "L", ReferenceName = "Kadazan Dusun"},
                                 new {Id    = "dtr", Scope = "I", Type = "L", ReferenceName = "Lotud"},
                                 new {Id    = "dts", Scope = "I", Type = "L", ReferenceName = "Toro So Dogon"},
                                 new {Id    = "dtt", Scope = "I", Type = "L", ReferenceName = "Toro Tegu Dogon"},
                                 new {Id    = "dtu", Scope = "I", Type = "L", ReferenceName = "Tebul Ure Dogon"},
                                 new {Id    = "dty", Scope = "I", Type = "L", ReferenceName = "Dotyali"},
                                 new
                                 {
                                     Id            = "dua",
                                     Part2B        = "dua",
                                     Part2T        = "dua",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Duala"
                                 }, new {Id = "dub", Scope = "I", Type = "L", ReferenceName = "Dubli"},
                                 new {Id    = "duc", Scope = "I", Type = "L", ReferenceName = "Duna"},
                                 new {Id    = "due", Scope = "I", Type = "L", ReferenceName = "Umiray Dumaget Agta"},
                                 new {Id    = "duf", Scope = "I", Type = "L", ReferenceName = "Dumbea"},
                                 new {Id    = "dug", Scope = "I", Type = "L", ReferenceName = "Duruma"},
                                 new {Id    = "duh", Scope = "I", Type = "L", ReferenceName = "Dungra Bhil"},
                                 new {Id    = "dui", Scope = "I", Type = "L", ReferenceName = "Dumun"},
                                 new {Id    = "duk", Scope = "I", Type = "L", ReferenceName = "Uyajitaya"},
                                 new {Id    = "dul", Scope = "I", Type = "L", ReferenceName = "Alabat Island Agta"},
                                 new
                                 {
                                     Id            = "dum",
                                     Part2B        = "dum",
                                     Part2T        = "dum",
                                     Scope         = "I",
                                     Type          = "H",
                                     ReferenceName = "Middle Dutch (ca. 1050-1350)"
                                 }, new {Id = "dun", Scope = "I", Type = "L", ReferenceName = "Dusun Deyah"},
                                 new {Id    = "duo", Scope = "I", Type = "L", ReferenceName = "Dupaninan Agta"},
                                 new {Id    = "dup", Scope = "I", Type = "L", ReferenceName = "Duano"},
                                 new {Id    = "duq", Scope = "I", Type = "L", ReferenceName = "Dusun Malang"},
                                 new {Id    = "dur", Scope = "I", Type = "L", ReferenceName = "Dii"},
                                 new {Id    = "dus", Scope = "I", Type = "L", ReferenceName = "Dumi"},
                                 new {Id    = "duu", Scope = "I", Type = "L", ReferenceName = "Drung"},
                                 new {Id    = "duv", Scope = "I", Type = "L", ReferenceName = "Duvle"},
                                 new {Id    = "duw", Scope = "I", Type = "L", ReferenceName = "Dusun Witu"},
                                 new {Id    = "dux", Scope = "I", Type = "L", ReferenceName = "Duungooma"},
                                 new {Id    = "duy", Scope = "I", Type = "E", ReferenceName = "Dicamay Agta"},
                                 new {Id    = "duz", Scope = "I", Type = "E", ReferenceName = "Duli-Gey"},
                                 new {Id    = "dva", Scope = "I", Type = "L", ReferenceName = "Duau"},
                                 new {Id    = "dwa", Scope = "I", Type = "L", ReferenceName = "Diri"},
                                 new {Id    = "dwr", Scope = "I", Type = "L", ReferenceName = "Dawro"},
                                 new
                                     {
                                         Id            = "dws",
                                         Scope         = "I",
                                         Type          = "C",
                                         ReferenceName = "Dutton World Speedwords"
                                     },
                                 new {Id = "dwu", Scope = "I", Type = "L", ReferenceName = "Dhuwal"},
                                 new {Id = "dww", Scope = "I", Type = "L", ReferenceName = "Dawawa"},
                                 new {Id = "dwy", Scope = "I", Type = "L", ReferenceName = "Dhuwaya"},
                                 new {Id = "dwz", Scope = "I", Type = "L", ReferenceName = "Dewas Rai"},
                                 new {Id = "dya", Scope = "I", Type = "L", ReferenceName = "Dyan"},
                                 new {Id = "dyb", Scope = "I", Type = "E", ReferenceName = "Dyaberdyaber"},
                                 new {Id = "dyd", Scope = "I", Type = "E", ReferenceName = "Dyugun"},
                                 new {Id = "dyg", Scope = "I", Type = "E", ReferenceName = "Villa Viciosa Agta"},
                                 new {Id = "dyi", Scope = "I", Type = "L", ReferenceName = "Djimini Senoufo"},
                                 new {Id = "dym", Scope = "I", Type = "L", ReferenceName = "Yanda Dom Dogon"},
                                 new {Id = "dyn", Scope = "I", Type = "L", ReferenceName = "Dyangadi"},
                                 new {Id = "dyo", Scope = "I", Type = "L", ReferenceName = "Jola-Fonyi"},
                                 new
                                 {
                                     Id            = "dyu",
                                     Part2B        = "dyu",
                                     Part2T        = "dyu",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Dyula"
                                 }, new {Id = "dyy", Scope = "I", Type = "L", ReferenceName = "Djabugay"},
                                 new {Id    = "dza", Scope = "I", Type = "L", ReferenceName = "Tunzu"},
                                 new {Id    = "dze", Scope = "I", Type = "E", ReferenceName = "Djiwarli"},
                                 new {Id    = "dzg", Scope = "I", Type = "L", ReferenceName = "Dazaga"},
                                 new {Id    = "dzl", Scope = "I", Type = "L", ReferenceName = "Dzalakha"},
                                 new {Id    = "dzn", Scope = "I", Type = "L", ReferenceName = "Dzando"},
                                 new
                                 {
                                     Id            = "dzo",
                                     Part2B        = "dzo",
                                     Part2T        = "dzo",
                                     Part1         = "dz",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Dzongkha"
                                 });
        }
    }
}