using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class L
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(new {Id = "laa", Scope = "I", Type = "L", ReferenceName = "Southern Subanen"},
                                 new {Id = "lab", Scope = "I", Type = "A", ReferenceName = "Linear A"},
                                 new {Id = "lac", Scope = "I", Type = "L", ReferenceName = "Lacandon"},
                                 new
                                 {
                                     Id            = "lad",
                                     Part2B        = "lad",
                                     Part2T        = "lad",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Ladino"
                                 }, new {Id = "lae", Scope = "I", Type = "L", ReferenceName = "Pattani"},
                                 new {Id    = "laf", Scope = "I", Type = "L", ReferenceName = "Lafofa"},
                                 new {Id    = "lag", Scope = "I", Type = "L", ReferenceName = "Langi"},
                                 new
                                 {
                                     Id            = "lah",
                                     Part2B        = "lah",
                                     Part2T        = "lah",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Lahnda"
                                 }, new {Id = "lai", Scope = "I", Type = "L", ReferenceName = "Lambya"},
                                 new {Id    = "laj", Scope = "I", Type = "L", ReferenceName = "Lango (Uganda)"},
                                 new {Id    = "lak", Scope = "I", Type = "L", ReferenceName = "Laka (Nigeria)"},
                                 new {Id    = "lal", Scope = "I", Type = "L", ReferenceName = "Lalia"},
                                 new
                                 {
                                     Id            = "lam",
                                     Part2B        = "lam",
                                     Part2T        = "lam",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Lamba"
                                 }, new {Id = "lan", Scope = "I", Type = "L", ReferenceName = "Laru"},
                                 new
                                 {
                                     Id            = "lao",
                                     Part2B        = "lao",
                                     Part2T        = "lao",
                                     Part1         = "lo",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Lao"
                                 }, new {Id = "lap", Scope = "I", Type = "L", ReferenceName = "Laka (Chad)"},
                                 new {Id    = "laq", Scope = "I", Type = "L", ReferenceName = "Qabiao"},
                                 new {Id    = "lar", Scope = "I", Type = "L", ReferenceName = "Larteh"},
                                 new {Id    = "las", Scope = "I", Type = "L", ReferenceName = "Lama (Togo)"},
                                 new
                                 {
                                     Id            = "lat",
                                     Part2B        = "lat",
                                     Part2T        = "lat",
                                     Part1         = "la",
                                     Scope         = "I",
                                     Type          = "A",
                                     ReferenceName = "Latin"
                                 }, new {Id = "lau", Scope = "I", Type = "L", ReferenceName = "Laba"},
                                 new
                                 {
                                     Id            = "lav",
                                     Part2B        = "lav",
                                     Part2T        = "lav",
                                     Part1         = "lv",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Latvian"
                                 }, new {Id = "law", Scope = "I", Type = "L", ReferenceName = "Lauje"},
                                 new {Id    = "lax", Scope = "I", Type = "L", ReferenceName = "Tiwa"},
                                 new {Id    = "lay", Scope = "I", Type = "L", ReferenceName = "Lama Bai"},
                                 new {Id    = "laz", Scope = "I", Type = "E", ReferenceName = "Aribwatsa"},
                                 new {Id    = "lbb", Scope = "I", Type = "L", ReferenceName = "Label"},
                                 new {Id    = "lbc", Scope = "I", Type = "L", ReferenceName = "Lakkia"},
                                 new {Id    = "lbe", Scope = "I", Type = "L", ReferenceName = "Lak"},
                                 new {Id    = "lbf", Scope = "I", Type = "L", ReferenceName = "Tinani"},
                                 new {Id    = "lbg", Scope = "I", Type = "L", ReferenceName = "Laopang"},
                                 new {Id    = "lbi", Scope = "I", Type = "L", ReferenceName = "La'bi"},
                                 new {Id    = "lbj", Scope = "I", Type = "L", ReferenceName = "Ladakhi"},
                                 new {Id    = "lbk", Scope = "I", Type = "L", ReferenceName = "Central Bontok"},
                                 new {Id    = "lbl", Scope = "I", Type = "L", ReferenceName = "Libon Bikol"},
                                 new {Id    = "lbm", Scope = "I", Type = "L", ReferenceName = "Lodhi"},
                                 new {Id    = "lbn", Scope = "I", Type = "L", ReferenceName = "Rmeet"},
                                 new {Id    = "lbo", Scope = "I", Type = "L", ReferenceName = "Laven"},
                                 new {Id    = "lbq", Scope = "I", Type = "L", ReferenceName = "Wampar"},
                                 new {Id    = "lbr", Scope = "I", Type = "L", ReferenceName = "Lohorung"},
                                 new {Id    = "lbs", Scope = "I", Type = "L", ReferenceName = "Libyan Sign Language"},
                                 new {Id    = "lbt", Scope = "I", Type = "L", ReferenceName = "Lachi"},
                                 new {Id    = "lbu", Scope = "I", Type = "L", ReferenceName = "Labu"},
                                 new {Id    = "lbv", Scope = "I", Type = "L", ReferenceName = "Lavatbura-Lamusong"},
                                 new {Id    = "lbw", Scope = "I", Type = "L", ReferenceName = "Tolaki"},
                                 new {Id    = "lbx", Scope = "I", Type = "L", ReferenceName = "Lawangan"},
                                 new {Id    = "lby", Scope = "I", Type = "E", ReferenceName = "Lamalama"},
                                 new {Id    = "lbz", Scope = "I", Type = "L", ReferenceName = "Lardil"},
                                 new {Id    = "lcc", Scope = "I", Type = "L", ReferenceName = "Legenyem"},
                                 new {Id    = "lcd", Scope = "I", Type = "L", ReferenceName = "Lola"},
                                 new {Id    = "lce", Scope = "I", Type = "L", ReferenceName = "Loncong"},
                                 new {Id    = "lcf", Scope = "I", Type = "L", ReferenceName = "Lubu"},
                                 new {Id    = "lch", Scope = "I", Type = "L", ReferenceName = "Luchazi"},
                                 new {Id    = "lcl", Scope = "I", Type = "L", ReferenceName = "Lisela"},
                                 new {Id    = "lcm", Scope = "I", Type = "L", ReferenceName = "Tungag"},
                                 new {Id    = "lcp", Scope = "I", Type = "L", ReferenceName = "Western Lawa"},
                                 new {Id    = "lcq", Scope = "I", Type = "L", ReferenceName = "Luhu"},
                                 new {Id    = "lcs", Scope = "I", Type = "L", ReferenceName = "Lisabata-Nuniali"},
                                 new {Id    = "lda", Scope = "I", Type = "L", ReferenceName = "Kla-Dan"},
                                 new {Id    = "ldb", Scope = "I", Type = "L", ReferenceName = "Dũya"},
                                 new {Id    = "ldd", Scope = "I", Type = "L", ReferenceName = "Luri"},
                                 new {Id    = "ldg", Scope = "I", Type = "L", ReferenceName = "Lenyima"},
                                 new {Id    = "ldh", Scope = "I", Type = "L", ReferenceName = "Lamja-Dengsa-Tola"},
                                 new {Id    = "ldi", Scope = "I", Type = "L", ReferenceName = "Laari"},
                                 new {Id    = "ldj", Scope = "I", Type = "L", ReferenceName = "Lemoro"},
                                 new {Id    = "ldk", Scope = "I", Type = "L", ReferenceName = "Leelau"},
                                 new {Id    = "ldl", Scope = "I", Type = "L", ReferenceName = "Kaan"},
                                 new {Id    = "ldm", Scope = "I", Type = "L", ReferenceName = "Landoma"},
                                 new {Id    = "ldn", Scope = "I", Type = "C", ReferenceName = "Láadan"},
                                 new {Id    = "ldo", Scope = "I", Type = "L", ReferenceName = "Loo"},
                                 new {Id    = "ldp", Scope = "I", Type = "L", ReferenceName = "Tso"},
                                 new {Id    = "ldq", Scope = "I", Type = "L", ReferenceName = "Lufu"},
                                 new {Id    = "lea", Scope = "I", Type = "L", ReferenceName = "Lega-Shabunda"},
                                 new {Id    = "leb", Scope = "I", Type = "L", ReferenceName = "Lala-Bisa"},
                                 new {Id    = "lec", Scope = "I", Type = "L", ReferenceName = "Leco"},
                                 new {Id    = "led", Scope = "I", Type = "L", ReferenceName = "Lendu"},
                                 new {Id    = "lee", Scope = "I", Type = "L", ReferenceName = "Lyélé"},
                                 new {Id    = "lef", Scope = "I", Type = "L", ReferenceName = "Lelemi"},
                                 new {Id    = "leh", Scope = "I", Type = "L", ReferenceName = "Lenje"},
                                 new {Id    = "lei", Scope = "I", Type = "L", ReferenceName = "Lemio"},
                                 new {Id    = "lej", Scope = "I", Type = "L", ReferenceName = "Lengola"},
                                 new {Id    = "lek", Scope = "I", Type = "L", ReferenceName = "Leipon"},
                                 new
                                 {
                                     Id            = "lel",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Lele (Democratic Republic of Congo)"
                                 }, new {Id = "lem", Scope = "I", Type = "L", ReferenceName = "Nomaande"},
                                 new {Id    = "len", Scope = "I", Type = "E", ReferenceName = "Lenca"},
                                 new {Id    = "leo", Scope = "I", Type = "L", ReferenceName = "Leti (Cameroon)"},
                                 new {Id    = "lep", Scope = "I", Type = "L", ReferenceName = "Lepcha"},
                                 new {Id    = "leq", Scope = "I", Type = "L", ReferenceName = "Lembena"},
                                 new {Id    = "ler", Scope = "I", Type = "L", ReferenceName = "Lenkau"},
                                 new {Id    = "les", Scope = "I", Type = "L", ReferenceName = "Lese"},
                                 new {Id    = "let", Scope = "I", Type = "L", ReferenceName = "Lesing-Gelimi"},
                                 new
                                     {
                                         Id            = "leu",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Kara (Papua New Guinea)"
                                     },
                                 new {Id = "lev", Scope = "I", Type = "L", ReferenceName = "Lamma"},
                                 new {Id = "lew", Scope = "I", Type = "L", ReferenceName = "Ledo Kaili"},
                                 new {Id = "lex", Scope = "I", Type = "L", ReferenceName = "Luang"},
                                 new {Id = "ley", Scope = "I", Type = "L", ReferenceName = "Lemolang"},
                                 new
                                 {
                                     Id            = "lez",
                                     Part2B        = "lez",
                                     Part2T        = "lez",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Lezghian"
                                 }, new {Id = "lfa", Scope = "I", Type = "L", ReferenceName = "Lefa"},
                                 new {Id    = "lfn", Scope = "I", Type = "C", ReferenceName = "Lingua Franca Nova"},
                                 new {Id    = "lga", Scope = "I", Type = "L", ReferenceName = "Lungga"},
                                 new {Id    = "lgb", Scope = "I", Type = "L", ReferenceName = "Laghu"},
                                 new {Id    = "lgg", Scope = "I", Type = "L", ReferenceName = "Lugbara"},
                                 new {Id    = "lgh", Scope = "I", Type = "L", ReferenceName = "Laghuu"},
                                 new {Id    = "lgi", Scope = "I", Type = "L", ReferenceName = "Lengilu"},
                                 new {Id    = "lgk", Scope = "I", Type = "L", ReferenceName = "Lingarak"},
                                 new {Id    = "lgl", Scope = "I", Type = "L", ReferenceName = "Wala"},
                                 new {Id    = "lgm", Scope = "I", Type = "L", ReferenceName = "Lega-Mwenga"},
                                 new {Id    = "lgn", Scope = "I", Type = "L", ReferenceName = "T'apo"},
                                 new {Id    = "lgq", Scope = "I", Type = "L", ReferenceName = "Logba"},
                                 new {Id    = "lgr", Scope = "I", Type = "L", ReferenceName = "Lengo"},
                                 new {Id    = "lgt", Scope = "I", Type = "L", ReferenceName = "Pahi"},
                                 new {Id    = "lgu", Scope = "I", Type = "L", ReferenceName = "Longgu"},
                                 new {Id    = "lgz", Scope = "I", Type = "L", ReferenceName = "Ligenza"},
                                 new {Id    = "lha", Scope = "I", Type = "L", ReferenceName = "Laha (Viet Nam)"},
                                 new {Id    = "lhh", Scope = "I", Type = "L", ReferenceName = "Laha (Indonesia)"},
                                 new {Id    = "lhi", Scope = "I", Type = "L", ReferenceName = "Lahu Shi"},
                                 new {Id    = "lhl", Scope = "I", Type = "L", ReferenceName = "Lahul Lohar"},
                                 new {Id    = "lhm", Scope = "I", Type = "L", ReferenceName = "Lhomi"},
                                 new {Id    = "lhn", Scope = "I", Type = "L", ReferenceName = "Lahanan"},
                                 new {Id    = "lhp", Scope = "I", Type = "L", ReferenceName = "Lhokpu"},
                                 new {Id    = "lhs", Scope = "I", Type = "E", ReferenceName = "Mlahsö"},
                                 new {Id    = "lht", Scope = "I", Type = "L", ReferenceName = "Lo-Toga"},
                                 new {Id    = "lhu", Scope = "I", Type = "L", ReferenceName = "Lahu"},
                                 new {Id    = "lia", Scope = "I", Type = "L", ReferenceName = "West-Central Limba"},
                                 new {Id    = "lib", Scope = "I", Type = "L", ReferenceName = "Likum"},
                                 new {Id    = "lic", Scope = "I", Type = "L", ReferenceName = "Hlai"},
                                 new {Id    = "lid", Scope = "I", Type = "L", ReferenceName = "Nyindrou"},
                                 new {Id    = "lie", Scope = "I", Type = "L", ReferenceName = "Likila"},
                                 new {Id    = "lif", Scope = "I", Type = "L", ReferenceName = "Limbu"},
                                 new {Id    = "lig", Scope = "I", Type = "L", ReferenceName = "Ligbi"},
                                 new {Id    = "lih", Scope = "I", Type = "L", ReferenceName = "Lihir"},
                                 new {Id    = "lij", Scope = "I", Type = "L", ReferenceName = "Ligurian"},
                                 new {Id    = "lik", Scope = "I", Type = "L", ReferenceName = "Lika"},
                                 new {Id    = "lil", Scope = "I", Type = "L", ReferenceName = "Lillooet"},
                                 new
                                 {
                                     Id            = "lim",
                                     Part2B        = "lim",
                                     Part2T        = "lim",
                                     Part1         = "li",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Limburgan"
                                 }, new
                                 {
                                     Id            = "lin",
                                     Part2B        = "lin",
                                     Part2T        = "lin",
                                     Part1         = "ln",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Lingala"
                                 }, new {Id = "lio", Scope = "I", Type = "L", ReferenceName = "Liki"},
                                 new {Id    = "lip", Scope = "I", Type = "L", ReferenceName = "Sekpele"},
                                 new {Id    = "liq", Scope = "I", Type = "L", ReferenceName = "Libido"},
                                 new {Id    = "lir", Scope = "I", Type = "L", ReferenceName = "Liberian English"},
                                 new {Id    = "lis", Scope = "I", Type = "L", ReferenceName = "Lisu"},
                                 new
                                 {
                                     Id            = "lit",
                                     Part2B        = "lit",
                                     Part2T        = "lit",
                                     Part1         = "lt",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Lithuanian"
                                 }, new {Id = "liu", Scope = "I", Type = "L", ReferenceName = "Logorik"},
                                 new {Id    = "liv", Scope = "I", Type = "L", ReferenceName = "Liv"},
                                 new {Id    = "liw", Scope = "I", Type = "L", ReferenceName = "Col"},
                                 new {Id    = "lix", Scope = "I", Type = "L", ReferenceName = "Liabuku"},
                                 new {Id    = "liy", Scope = "I", Type = "L", ReferenceName = "Banda-Bambari"},
                                 new {Id    = "liz", Scope = "I", Type = "L", ReferenceName = "Libinza"},
                                 new {Id    = "lja", Scope = "I", Type = "E", ReferenceName = "Golpa"},
                                 new {Id    = "lje", Scope = "I", Type = "L", ReferenceName = "Rampi"},
                                 new {Id    = "lji", Scope = "I", Type = "L", ReferenceName = "Laiyolo"},
                                 new {Id    = "ljl", Scope = "I", Type = "L", ReferenceName = "Li'o"},
                                 new {Id    = "ljp", Scope = "I", Type = "L", ReferenceName = "Lampung Api"},
                                 new {Id    = "ljw", Scope = "I", Type = "L", ReferenceName = "Yirandali"},
                                 new {Id    = "ljx", Scope = "I", Type = "E", ReferenceName = "Yuru"},
                                 new {Id    = "lka", Scope = "I", Type = "L", ReferenceName = "Lakalei"},
                                 new {Id    = "lkb", Scope = "I", Type = "L", ReferenceName = "Kabras"},
                                 new {Id    = "lkc", Scope = "I", Type = "L", ReferenceName = "Kucong"},
                                 new {Id    = "lkd", Scope = "I", Type = "L", ReferenceName = "Lakondê"},
                                 new {Id    = "lke", Scope = "I", Type = "L", ReferenceName = "Kenyi"},
                                 new {Id    = "lkh", Scope = "I", Type = "L", ReferenceName = "Lakha"},
                                 new {Id    = "lki", Scope = "I", Type = "L", ReferenceName = "Laki"},
                                 new {Id    = "lkj", Scope = "I", Type = "L", ReferenceName = "Remun"},
                                 new {Id    = "lkl", Scope = "I", Type = "L", ReferenceName = "Laeko-Libuat"},
                                 new {Id    = "lkm", Scope = "I", Type = "E", ReferenceName = "Kalaamaya"},
                                 new {Id    = "lkn", Scope = "I", Type = "L", ReferenceName = "Lakon"},
                                 new {Id    = "lko", Scope = "I", Type = "L", ReferenceName = "Khayo"},
                                 new {Id    = "lkr", Scope = "I", Type = "L", ReferenceName = "Päri"},
                                 new {Id    = "lks", Scope = "I", Type = "L", ReferenceName = "Kisa"},
                                 new {Id    = "lkt", Scope = "I", Type = "L", ReferenceName = "Lakota"},
                                 new {Id    = "lku", Scope = "I", Type = "E", ReferenceName = "Kungkari"},
                                 new {Id    = "lky", Scope = "I", Type = "L", ReferenceName = "Lokoya"},
                                 new {Id    = "lla", Scope = "I", Type = "L", ReferenceName = "Lala-Roba"},
                                 new {Id    = "llb", Scope = "I", Type = "L", ReferenceName = "Lolo"},
                                 new {Id    = "llc", Scope = "I", Type = "L", ReferenceName = "Lele (Guinea)"},
                                 new {Id    = "lld", Scope = "I", Type = "L", ReferenceName = "Ladin"},
                                 new
                                     {
                                         Id            = "lle",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Lele (Papua New Guinea)"
                                     },
                                 new {Id = "llf", Scope = "I", Type = "E", ReferenceName = "Hermit"},
                                 new {Id = "llg", Scope = "I", Type = "L", ReferenceName = "Lole"},
                                 new {Id = "llh", Scope = "I", Type = "L", ReferenceName = "Lamu"},
                                 new {Id = "lli", Scope = "I", Type = "L", ReferenceName = "Teke-Laali"},
                                 new {Id = "llj", Scope = "I", Type = "E", ReferenceName = "Ladji Ladji"},
                                 new {Id = "llk", Scope = "I", Type = "E", ReferenceName = "Lelak"},
                                 new {Id = "lll", Scope = "I", Type = "L", ReferenceName = "Lilau"},
                                 new {Id = "llm", Scope = "I", Type = "L", ReferenceName = "Lasalimu"},
                                 new {Id = "lln", Scope = "I", Type = "L", ReferenceName = "Lele (Chad)"},
                                 new {Id = "llp", Scope = "I", Type = "L", ReferenceName = "North Efate"},
                                 new {Id = "llq", Scope = "I", Type = "L", ReferenceName = "Lolak"},
                                 new
                                     {
                                         Id            = "lls",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Lithuanian Sign Language"
                                     },
                                 new {Id = "llu", Scope = "I", Type = "L", ReferenceName = "Lau"},
                                 new {Id = "llx", Scope = "I", Type = "L", ReferenceName = "Lauan"},
                                 new {Id = "lma", Scope = "I", Type = "L", ReferenceName = "East Limba"},
                                 new {Id = "lmb", Scope = "I", Type = "L", ReferenceName = "Merei"},
                                 new {Id = "lmc", Scope = "I", Type = "E", ReferenceName = "Limilngan"},
                                 new {Id = "lmd", Scope = "I", Type = "L", ReferenceName = "Lumun"},
                                 new {Id = "lme", Scope = "I", Type = "L", ReferenceName = "Pévé"},
                                 new {Id = "lmf", Scope = "I", Type = "L", ReferenceName = "South Lembata"},
                                 new {Id = "lmg", Scope = "I", Type = "L", ReferenceName = "Lamogai"},
                                 new {Id = "lmh", Scope = "I", Type = "L", ReferenceName = "Lambichhong"},
                                 new {Id = "lmi", Scope = "I", Type = "L", ReferenceName = "Lombi"},
                                 new {Id = "lmj", Scope = "I", Type = "L", ReferenceName = "West Lembata"},
                                 new {Id = "lmk", Scope = "I", Type = "L", ReferenceName = "Lamkang"},
                                 new {Id = "lml", Scope = "I", Type = "L", ReferenceName = "Hano"},
                                 new {Id = "lmn", Scope = "I", Type = "L", ReferenceName = "Lambadi"},
                                 new {Id = "lmo", Scope = "I", Type = "L", ReferenceName = "Lombard"},
                                 new {Id = "lmp", Scope = "I", Type = "L", ReferenceName = "Limbum"},
                                 new {Id = "lmq", Scope = "I", Type = "L", ReferenceName = "Lamatuka"},
                                 new {Id = "lmr", Scope = "I", Type = "L", ReferenceName = "Lamalera"},
                                 new {Id = "lmu", Scope = "I", Type = "L", ReferenceName = "Lamenu"},
                                 new {Id = "lmv", Scope = "I", Type = "L", ReferenceName = "Lomaiviti"},
                                 new {Id = "lmw", Scope = "I", Type = "L", ReferenceName = "Lake Miwok"},
                                 new {Id = "lmx", Scope = "I", Type = "L", ReferenceName = "Laimbue"},
                                 new {Id = "lmy", Scope = "I", Type = "L", ReferenceName = "Lamboya"},
                                 new {Id = "lmz", Scope = "I", Type = "E", ReferenceName = "Lumbee"},
                                 new {Id = "lna", Scope = "I", Type = "L", ReferenceName = "Langbashe"},
                                 new {Id = "lnb", Scope = "I", Type = "L", ReferenceName = "Mbalanhu"},
                                 new {Id = "lnd", Scope = "I", Type = "L", ReferenceName = "Lundayeh"},
                                 new {Id = "lng", Scope = "I", Type = "A", ReferenceName = "Langobardic"},
                                 new {Id = "lnh", Scope = "I", Type = "L", ReferenceName = "Lanoh"},
                                 new {Id = "lni", Scope = "I", Type = "L", ReferenceName = "Daantanai'"},
                                 new {Id = "lnj", Scope = "I", Type = "E", ReferenceName = "Leningitij"},
                                 new {Id = "lnl", Scope = "I", Type = "L", ReferenceName = "South Central Banda"},
                                 new {Id = "lnm", Scope = "I", Type = "L", ReferenceName = "Langam"},
                                 new {Id = "lnn", Scope = "I", Type = "L", ReferenceName = "Lorediakarkar"},
                                 new {Id = "lno", Scope = "I", Type = "L", ReferenceName = "Lango (South Sudan)"},
                                 new {Id = "lns", Scope = "I", Type = "L", ReferenceName = "Lamnso'"},
                                 new {Id = "lnu", Scope = "I", Type = "L", ReferenceName = "Longuda"},
                                 new {Id = "lnw", Scope = "I", Type = "E", ReferenceName = "Lanima"},
                                 new {Id = "lnz", Scope = "I", Type = "L", ReferenceName = "Lonzo"},
                                 new {Id = "loa", Scope = "I", Type = "L", ReferenceName = "Loloda"},
                                 new {Id = "lob", Scope = "I", Type = "L", ReferenceName = "Lobi"},
                                 new {Id = "loc", Scope = "I", Type = "L", ReferenceName = "Inonhan"},
                                 new {Id = "loe", Scope = "I", Type = "L", ReferenceName = "Saluan"},
                                 new {Id = "lof", Scope = "I", Type = "L", ReferenceName = "Logol"},
                                 new {Id = "log", Scope = "I", Type = "L", ReferenceName = "Logo"},
                                 new {Id = "loh", Scope = "I", Type = "L", ReferenceName = "Narim"},
                                 new {Id = "loi", Scope = "I", Type = "L", ReferenceName = "Loma (Côte d'Ivoire)"},
                                 new {Id = "loj", Scope = "I", Type = "L", ReferenceName = "Lou"},
                                 new {Id = "lok", Scope = "I", Type = "L", ReferenceName = "Loko"},
                                 new
                                 {
                                     Id            = "lol",
                                     Part2B        = "lol",
                                     Part2T        = "lol",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mongo"
                                 }, new {Id = "lom", Scope = "I", Type = "L", ReferenceName = "Loma (Liberia)"},
                                 new {Id    = "lon", Scope = "I", Type = "L", ReferenceName = "Malawi Lomwe"},
                                 new {Id    = "loo", Scope = "I", Type = "L", ReferenceName = "Lombo"},
                                 new {Id    = "lop", Scope = "I", Type = "L", ReferenceName = "Lopa"},
                                 new {Id    = "loq", Scope = "I", Type = "L", ReferenceName = "Lobala"},
                                 new {Id    = "lor", Scope = "I", Type = "L", ReferenceName = "Téén"},
                                 new {Id    = "los", Scope = "I", Type = "L", ReferenceName = "Loniu"},
                                 new {Id    = "lot", Scope = "I", Type = "L", ReferenceName = "Otuho"},
                                 new {Id    = "lou", Scope = "I", Type = "L", ReferenceName = "Louisiana Creole"},
                                 new {Id    = "lov", Scope = "I", Type = "L", ReferenceName = "Lopi"},
                                 new {Id    = "low", Scope = "I", Type = "L", ReferenceName = "Tampias Lobu"},
                                 new {Id    = "lox", Scope = "I", Type = "L", ReferenceName = "Loun"},
                                 new {Id    = "loy", Scope = "I", Type = "L", ReferenceName = "Loke"},
                                 new
                                 {
                                     Id            = "loz",
                                     Part2B        = "loz",
                                     Part2T        = "loz",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Lozi"
                                 }, new {Id = "lpa", Scope = "I", Type = "L", ReferenceName = "Lelepa"},
                                 new {Id    = "lpe", Scope = "I", Type = "L", ReferenceName = "Lepki"},
                                 new {Id    = "lpn", Scope = "I", Type = "L", ReferenceName = "Long Phuri Naga"},
                                 new {Id    = "lpo", Scope = "I", Type = "L", ReferenceName = "Lipo"},
                                 new {Id    = "lpx", Scope = "I", Type = "L", ReferenceName = "Lopit"},
                                 new {Id    = "lra", Scope = "I", Type = "L", ReferenceName = "Rara Bakati'"},
                                 new {Id    = "lrc", Scope = "I", Type = "L", ReferenceName = "Northern Luri"},
                                 new {Id    = "lre", Scope = "I", Type = "E", ReferenceName = "Laurentian"},
                                 new {Id    = "lrg", Scope = "I", Type = "E", ReferenceName = "Laragia"},
                                 new {Id    = "lri", Scope = "I", Type = "L", ReferenceName = "Marachi"},
                                 new {Id    = "lrk", Scope = "I", Type = "L", ReferenceName = "Loarki"},
                                 new {Id    = "lrl", Scope = "I", Type = "L", ReferenceName = "Lari"},
                                 new {Id    = "lrm", Scope = "I", Type = "L", ReferenceName = "Marama"},
                                 new {Id    = "lrn", Scope = "I", Type = "L", ReferenceName = "Lorang"},
                                 new {Id    = "lro", Scope = "I", Type = "L", ReferenceName = "Laro"},
                                 new {Id    = "lrr", Scope = "I", Type = "L", ReferenceName = "Southern Yamphu"},
                                 new {Id    = "lrt", Scope = "I", Type = "L", ReferenceName = "Larantuka Malay"},
                                 new {Id    = "lrv", Scope = "I", Type = "L", ReferenceName = "Larevat"},
                                 new {Id    = "lrz", Scope = "I", Type = "L", ReferenceName = "Lemerig"},
                                 new {Id    = "lsa", Scope = "I", Type = "L", ReferenceName = "Lasgerdi"},
                                 new {Id    = "lsd", Scope = "I", Type = "L", ReferenceName = "Lishana Deni"},
                                 new {Id    = "lse", Scope = "I", Type = "L", ReferenceName = "Lusengo"},
                                 new {Id    = "lsh", Scope = "I", Type = "L", ReferenceName = "Lish"},
                                 new {Id    = "lsi", Scope = "I", Type = "L", ReferenceName = "Lashi"},
                                 new {Id    = "lsl", Scope = "I", Type = "L", ReferenceName = "Latvian Sign Language"},
                                 new {Id    = "lsm", Scope = "I", Type = "L", ReferenceName = "Saamia"},
                                 new {Id    = "lsn", Scope = "I", Type = "L", ReferenceName = "Tibetan Sign Language"},
                                 new {Id    = "lso", Scope = "I", Type = "L", ReferenceName = "Laos Sign Language"},
                                 new
                                     {
                                         Id            = "lsp",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Panamanian Sign Language"
                                     },
                                 new {Id = "lsr", Scope = "I", Type = "L", ReferenceName = "Aruop"},
                                 new {Id = "lss", Scope = "I", Type = "L", ReferenceName = "Lasi"},
                                 new
                                 {
                                     Id            = "lst",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Trinidad and Tobago Sign Language"
                                 },
                                 new {Id = "lsv", Scope = "I", Type = "L", ReferenceName = "Sivia Sign Language"},
                                 new {Id = "lsy", Scope = "I", Type = "L", ReferenceName = "Mauritian Sign Language"},
                                 new {Id = "ltc", Scope = "I", Type = "H", ReferenceName = "Late Middle Chinese"},
                                 new {Id = "ltg", Scope = "I", Type = "L", ReferenceName = "Latgalian"},
                                 new {Id = "lth", Scope = "I", Type = "L", ReferenceName = "Thur"},
                                 new {Id = "lti", Scope = "I", Type = "L", ReferenceName = "Leti (Indonesia)"},
                                 new {Id = "ltn", Scope = "I", Type = "L", ReferenceName = "Latundê"},
                                 new {Id = "lto", Scope = "I", Type = "L", ReferenceName = "Tsotso"},
                                 new {Id = "lts", Scope = "I", Type = "L", ReferenceName = "Tachoni"},
                                 new {Id = "ltu", Scope = "I", Type = "L", ReferenceName = "Latu"},
                                 new
                                 {
                                     Id            = "ltz",
                                     Part2B        = "ltz",
                                     Part2T        = "ltz",
                                     Part1         = "lb",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Luxembourgish"
                                 }, new
                                 {
                                     Id            = "lua",
                                     Part2B        = "lua",
                                     Part2T        = "lua",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Luba-Lulua"
                                 }, new
                                 {
                                     Id            = "lub",
                                     Part2B        = "lub",
                                     Part2T        = "lub",
                                     Part1         = "lu",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Luba-Katanga"
                                 }, new {Id = "luc", Scope = "I", Type = "L", ReferenceName = "Aringa"},
                                 new {Id    = "lud", Scope = "I", Type = "L", ReferenceName = "Ludian"},
                                 new {Id    = "lue", Scope = "I", Type = "L", ReferenceName = "Luvale"},
                                 new {Id    = "luf", Scope = "I", Type = "L", ReferenceName = "Laua"},
                                 new
                                 {
                                     Id            = "lug",
                                     Part2B        = "lug",
                                     Part2T        = "lug",
                                     Part1         = "lg",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Ganda"
                                 }, new
                                 {
                                     Id            = "lui",
                                     Part2B        = "lui",
                                     Part2T        = "lui",
                                     Scope         = "I",
                                     Type          = "E",
                                     ReferenceName = "Luiseno"
                                 }, new {Id = "luj", Scope = "I", Type = "L", ReferenceName = "Luna"},
                                 new {Id    = "luk", Scope = "I", Type = "L", ReferenceName = "Lunanakha"},
                                 new {Id    = "lul", Scope = "I", Type = "L", ReferenceName = "Olu'bo"},
                                 new {Id    = "lum", Scope = "I", Type = "L", ReferenceName = "Luimbi"},
                                 new
                                 {
                                     Id            = "lun",
                                     Part2B        = "lun",
                                     Part2T        = "lun",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Lunda"
                                 }, new
                                 {
                                     Id            = "luo",
                                     Part2B        = "luo",
                                     Part2T        = "luo",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Luo (Kenya and Tanzania)"
                                 }, new {Id = "lup", Scope = "I", Type = "L", ReferenceName = "Lumbu"},
                                 new {Id    = "luq", Scope = "I", Type = "L", ReferenceName = "Lucumi"},
                                 new {Id    = "lur", Scope = "I", Type = "L", ReferenceName = "Laura"},
                                 new
                                 {
                                     Id            = "lus",
                                     Part2B        = "lus",
                                     Part2T        = "lus",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Lushai"
                                 }, new {Id = "lut", Scope = "I", Type = "L", ReferenceName = "Lushootseed"},
                                 new {Id    = "luu", Scope = "I", Type = "L", ReferenceName = "Lumba-Yakkha"},
                                 new {Id    = "luv", Scope = "I", Type = "L", ReferenceName = "Luwati"},
                                 new {Id    = "luw", Scope = "I", Type = "L", ReferenceName = "Luo (Cameroon)"},
                                 new {Id    = "luy", Scope = "M", Type = "L", ReferenceName = "Luyia"},
                                 new {Id    = "luz", Scope = "I", Type = "L", ReferenceName = "Southern Luri"},
                                 new {Id    = "lva", Scope = "I", Type = "L", ReferenceName = "Maku'a"},
                                 new {Id    = "lvi", Scope = "I", Type = "L", ReferenceName = "Lavi"},
                                 new {Id    = "lvk", Scope = "I", Type = "L", ReferenceName = "Lavukaleve"},
                                 new {Id    = "lvs", Scope = "I", Type = "L", ReferenceName = "Standard Latvian"},
                                 new {Id    = "lvu", Scope = "I", Type = "L", ReferenceName = "Levuka"},
                                 new {Id    = "lwa", Scope = "I", Type = "L", ReferenceName = "Lwalu"},
                                 new {Id    = "lwe", Scope = "I", Type = "L", ReferenceName = "Lewo Eleng"},
                                 new {Id    = "lwg", Scope = "I", Type = "L", ReferenceName = "Wanga"},
                                 new {Id    = "lwh", Scope = "I", Type = "L", ReferenceName = "White Lachi"},
                                 new {Id    = "lwl", Scope = "I", Type = "L", ReferenceName = "Eastern Lawa"},
                                 new {Id    = "lwm", Scope = "I", Type = "L", ReferenceName = "Laomian"},
                                 new {Id    = "lwo", Scope = "I", Type = "L", ReferenceName = "Luwo"},
                                 new {Id    = "lws", Scope = "I", Type = "L", ReferenceName = "Malawian Sign Language"},
                                 new {Id    = "lwt", Scope = "I", Type = "L", ReferenceName = "Lewotobi"},
                                 new {Id    = "lwu", Scope = "I", Type = "L", ReferenceName = "Lawu"},
                                 new {Id    = "lww", Scope = "I", Type = "L", ReferenceName = "Lewo"},
                                 new {Id    = "lya", Scope = "I", Type = "L", ReferenceName = "Layakha"},
                                 new {Id    = "lyg", Scope = "I", Type = "L", ReferenceName = "Lyngngam"},
                                 new {Id    = "lyn", Scope = "I", Type = "L", ReferenceName = "Luyana"},
                                 new {Id    = "lzh", Scope = "I", Type = "H", ReferenceName = "Literary Chinese"},
                                 new {Id    = "lzl", Scope = "I", Type = "L", ReferenceName = "Litzlitz"},
                                 new {Id    = "lzn", Scope = "I", Type = "L", ReferenceName = "Leinong Naga"},
                                 new {Id    = "lzz", Scope = "I", Type = "L", ReferenceName = "Laz"});
        }
    }
}