using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class M
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(
                                 new
                                 {
                                     Id            = "maa",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "San Jerónimo Tecóatl Mazatec"
                                 }, new {Id = "mab", Scope = "I", Type = "L", ReferenceName = "Yutanduchi Mixtec"},
                                 new
                                 {
                                     Id            = "mad",
                                     Part2B        = "mad",
                                     Part2T        = "mad",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Madurese"
                                 }, new {Id = "mae", Scope = "I", Type = "L", ReferenceName = "Bo-Rukul"},
                                 new {Id    = "maf", Scope = "I", Type = "L", ReferenceName = "Mafa"},
                                 new
                                 {
                                     Id            = "mag",
                                     Part2B        = "mag",
                                     Part2T        = "mag",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Magahi"
                                 }, new
                                 {
                                     Id            = "mah",
                                     Part2B        = "mah",
                                     Part2T        = "mah",
                                     Part1         = "mh",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Marshallese"
                                 }, new
                                 {
                                     Id            = "mai",
                                     Part2B        = "mai",
                                     Part2T        = "mai",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Maithili"
                                 }, new {Id = "maj", Scope = "I", Type = "L", ReferenceName = "Jalapa De Díaz Mazatec"},
                                 new
                                 {
                                     Id            = "mak",
                                     Part2B        = "mak",
                                     Part2T        = "mak",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Makasar"
                                 }, new
                                 {
                                     Id            = "mal",
                                     Part2B        = "mal",
                                     Part2T        = "mal",
                                     Part1         = "ml",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Malayalam"
                                 }, new {Id = "mam", Scope = "I", Type = "L", ReferenceName = "Mam"},
                                 new
                                 {
                                     Id            = "man",
                                     Part2B        = "man",
                                     Part2T        = "man",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Mandingo"
                                 }, new {Id = "maq", Scope = "I", Type = "L", ReferenceName = "Chiquihuitlán Mazatec"},
                                 new
                                 {
                                     Id            = "mar",
                                     Part2B        = "mar",
                                     Part2T        = "mar",
                                     Part1         = "mr",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Marathi"
                                 }, new
                                 {
                                     Id            = "mas",
                                     Part2B        = "mas",
                                     Part2T        = "mas",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Masai"
                                 },
                                 new {Id = "mat", Scope = "I", Type = "L", ReferenceName = "San Francisco Matlatzinca"},
                                 new {Id = "mau", Scope = "I", Type = "L", ReferenceName = "Huautla Mazatec"},
                                 new {Id = "mav", Scope = "I", Type = "L", ReferenceName = "Sateré-Mawé"},
                                 new {Id = "maw", Scope = "I", Type = "L", ReferenceName = "Mampruli"},
                                 new {Id = "max", Scope = "I", Type = "L", ReferenceName = "North Moluccan Malay"},
                                 new {Id = "maz", Scope = "I", Type = "L", ReferenceName = "Central Mazahua"},
                                 new {Id = "mba", Scope = "I", Type = "L", ReferenceName = "Higaonon"},
                                 new {Id = "mbb", Scope = "I", Type = "L", ReferenceName = "Western Bukidnon Manobo"},
                                 new {Id = "mbc", Scope = "I", Type = "L", ReferenceName = "Macushi"},
                                 new {Id = "mbd", Scope = "I", Type = "L", ReferenceName = "Dibabawon Manobo"},
                                 new {Id = "mbe", Scope = "I", Type = "E", ReferenceName = "Molale"},
                                 new {Id = "mbf", Scope = "I", Type = "L", ReferenceName = "Baba Malay"},
                                 new {Id = "mbh", Scope = "I", Type = "L", ReferenceName = "Mangseng"},
                                 new {Id = "mbi", Scope = "I", Type = "L", ReferenceName = "Ilianen Manobo"},
                                 new {Id = "mbj", Scope = "I", Type = "L", ReferenceName = "Nadëb"},
                                 new {Id = "mbk", Scope = "I", Type = "L", ReferenceName = "Malol"},
                                 new {Id = "mbl", Scope = "I", Type = "L", ReferenceName = "Maxakalí"},
                                 new {Id = "mbm", Scope = "I", Type = "L", ReferenceName = "Ombamba"},
                                 new {Id = "mbn", Scope = "I", Type = "L", ReferenceName = "Macaguán"},
                                 new {Id = "mbo", Scope = "I", Type = "L", ReferenceName = "Mbo (Cameroon)"},
                                 new {Id = "mbp", Scope = "I", Type = "L", ReferenceName = "Malayo"},
                                 new {Id = "mbq", Scope = "I", Type = "L", ReferenceName = "Maisin"},
                                 new {Id = "mbr", Scope = "I", Type = "L", ReferenceName = "Nukak Makú"},
                                 new {Id = "mbs", Scope = "I", Type = "L", ReferenceName = "Sarangani Manobo"},
                                 new {Id = "mbt", Scope = "I", Type = "L", ReferenceName = "Matigsalug Manobo"},
                                 new {Id = "mbu", Scope = "I", Type = "L", ReferenceName = "Mbula-Bwazza"},
                                 new {Id = "mbv", Scope = "I", Type = "L", ReferenceName = "Mbulungish"},
                                 new {Id = "mbw", Scope = "I", Type = "L", ReferenceName = "Maring"},
                                 new
                                 {
                                     Id            = "mbx",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mari (East Sepik Province)"
                                 }, new {Id = "mby", Scope = "I", Type = "L", ReferenceName = "Memoni"},
                                 new {Id    = "mbz", Scope = "I", Type = "L", ReferenceName = "Amoltepec Mixtec"},
                                 new {Id    = "mca", Scope = "I", Type = "L", ReferenceName = "Maca"},
                                 new {Id    = "mcb", Scope = "I", Type = "L", ReferenceName = "Machiguenga"},
                                 new {Id    = "mcc", Scope = "I", Type = "L", ReferenceName = "Bitur"},
                                 new {Id    = "mcd", Scope = "I", Type = "L", ReferenceName = "Sharanahua"},
                                 new {Id    = "mce", Scope = "I", Type = "L", ReferenceName = "Itundujia Mixtec"},
                                 new {Id    = "mcf", Scope = "I", Type = "L", ReferenceName = "Matsés"},
                                 new {Id    = "mcg", Scope = "I", Type = "L", ReferenceName = "Mapoyo"},
                                 new {Id    = "mch", Scope = "I", Type = "L", ReferenceName = "Maquiritari"},
                                 new {Id    = "mci", Scope = "I", Type = "L", ReferenceName = "Mese"},
                                 new {Id    = "mcj", Scope = "I", Type = "L", ReferenceName = "Mvanip"},
                                 new {Id    = "mck", Scope = "I", Type = "L", ReferenceName = "Mbunda"},
                                 new {Id    = "mcl", Scope = "I", Type = "E", ReferenceName = "Macaguaje"},
                                 new
                                 {
                                     Id            = "mcm",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Malaccan Creole Portuguese"
                                 }, new {Id = "mcn", Scope = "I", Type = "L", ReferenceName = "Masana"},
                                 new {Id    = "mco", Scope = "I", Type = "L", ReferenceName = "Coatlán Mixe"},
                                 new {Id    = "mcp", Scope = "I", Type = "L", ReferenceName = "Makaa"},
                                 new {Id    = "mcq", Scope = "I", Type = "L", ReferenceName = "Ese"},
                                 new {Id    = "mcr", Scope = "I", Type = "L", ReferenceName = "Menya"},
                                 new {Id    = "mcs", Scope = "I", Type = "L", ReferenceName = "Mambai"},
                                 new {Id    = "mct", Scope = "I", Type = "L", ReferenceName = "Mengisa"},
                                 new {Id    = "mcu", Scope = "I", Type = "L", ReferenceName = "Cameroon Mambila"},
                                 new {Id    = "mcv", Scope = "I", Type = "L", ReferenceName = "Minanibai"},
                                 new {Id    = "mcw", Scope = "I", Type = "L", ReferenceName = "Mawa (Chad)"},
                                 new {Id    = "mcx", Scope = "I", Type = "L", ReferenceName = "Mpiemo"},
                                 new {Id    = "mcy", Scope = "I", Type = "L", ReferenceName = "South Watut"},
                                 new {Id    = "mcz", Scope = "I", Type = "L", ReferenceName = "Mawan"},
                                 new {Id    = "mda", Scope = "I", Type = "L", ReferenceName = "Mada (Nigeria)"},
                                 new {Id    = "mdb", Scope = "I", Type = "L", ReferenceName = "Morigi"},
                                 new
                                     {
                                         Id            = "mdc",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Male (Papua New Guinea)"
                                     },
                                 new {Id = "mdd", Scope = "I", Type = "L", ReferenceName = "Mbum"},
                                 new {Id = "mde", Scope = "I", Type = "L", ReferenceName = "Maba (Chad)"},
                                 new
                                 {
                                     Id            = "mdf",
                                     Part2B        = "mdf",
                                     Part2T        = "mdf",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Moksha"
                                 }, new {Id = "mdg", Scope = "I", Type = "L", ReferenceName = "Massalat"},
                                 new {Id    = "mdh", Scope = "I", Type = "L", ReferenceName = "Maguindanaon"},
                                 new {Id    = "mdi", Scope = "I", Type = "L", ReferenceName = "Mamvu"},
                                 new {Id    = "mdj", Scope = "I", Type = "L", ReferenceName = "Mangbetu"},
                                 new {Id    = "mdk", Scope = "I", Type = "L", ReferenceName = "Mangbutu"},
                                 new {Id    = "mdl", Scope = "I", Type = "L", ReferenceName = "Maltese Sign Language"},
                                 new {Id    = "mdm", Scope = "I", Type = "L", ReferenceName = "Mayogo"},
                                 new {Id    = "mdn", Scope = "I", Type = "L", ReferenceName = "Mbati"},
                                 new {Id    = "mdp", Scope = "I", Type = "L", ReferenceName = "Mbala"},
                                 new {Id    = "mdq", Scope = "I", Type = "L", ReferenceName = "Mbole"},
                                 new
                                 {
                                     Id            = "mdr",
                                     Part2B        = "mdr",
                                     Part2T        = "mdr",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mandar"
                                 },
                                 new {Id = "mds", Scope = "I", Type = "L", ReferenceName = "Maria (Papua New Guinea)"},
                                 new {Id = "mdt", Scope = "I", Type = "L", ReferenceName = "Mbere"},
                                 new {Id = "mdu", Scope = "I", Type = "L", ReferenceName = "Mboko"},
                                 new
                                 {
                                     Id            = "mdv",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Santa Lucía Monteverde Mixtec"
                                 }, new {Id = "mdw", Scope = "I", Type = "L", ReferenceName = "Mbosi"},
                                 new {Id    = "mdx", Scope = "I", Type = "L", ReferenceName = "Dizin"},
                                 new {Id    = "mdy", Scope = "I", Type = "L", ReferenceName = "Male (Ethiopia)"},
                                 new {Id    = "mdz", Scope = "I", Type = "L", ReferenceName = "Suruí Do Pará"},
                                 new {Id    = "mea", Scope = "I", Type = "L", ReferenceName = "Menka"},
                                 new {Id    = "meb", Scope = "I", Type = "L", ReferenceName = "Ikobi"},
                                 new {Id    = "mec", Scope = "I", Type = "L", ReferenceName = "Marra"},
                                 new {Id    = "med", Scope = "I", Type = "L", ReferenceName = "Melpa"},
                                 new {Id    = "mee", Scope = "I", Type = "L", ReferenceName = "Mengen"},
                                 new {Id    = "mef", Scope = "I", Type = "L", ReferenceName = "Megam"},
                                 new
                                 {
                                     Id            = "meh",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Southwestern Tlaxiaco Mixtec"
                                 }, new {Id = "mei", Scope = "I", Type = "L", ReferenceName = "Midob"},
                                 new {Id    = "mej", Scope = "I", Type = "L", ReferenceName = "Meyah"},
                                 new {Id    = "mek", Scope = "I", Type = "L", ReferenceName = "Mekeo"},
                                 new {Id    = "mel", Scope = "I", Type = "L", ReferenceName = "Central Melanau"},
                                 new {Id    = "mem", Scope = "I", Type = "E", ReferenceName = "Mangala"},
                                 new
                                 {
                                     Id            = "men",
                                     Part2B        = "men",
                                     Part2T        = "men",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mende (Sierra Leone)"
                                 }, new {Id = "meo", Scope = "I", Type = "L", ReferenceName = "Kedah Malay"},
                                 new {Id    = "mep", Scope = "I", Type = "L", ReferenceName = "Miriwoong"},
                                 new {Id    = "meq", Scope = "I", Type = "L", ReferenceName = "Merey"},
                                 new {Id    = "mer", Scope = "I", Type = "L", ReferenceName = "Meru"},
                                 new {Id    = "mes", Scope = "I", Type = "L", ReferenceName = "Masmaje"},
                                 new {Id    = "met", Scope = "I", Type = "L", ReferenceName = "Mato"},
                                 new {Id    = "meu", Scope = "I", Type = "L", ReferenceName = "Motu"},
                                 new {Id    = "mev", Scope = "I", Type = "L", ReferenceName = "Mano"},
                                 new {Id    = "mew", Scope = "I", Type = "L", ReferenceName = "Maaka"},
                                 new {Id    = "mey", Scope = "I", Type = "L", ReferenceName = "Hassaniyya"},
                                 new {Id    = "mez", Scope = "I", Type = "L", ReferenceName = "Menominee"},
                                 new {Id    = "mfa", Scope = "I", Type = "L", ReferenceName = "Pattani Malay"},
                                 new {Id    = "mfb", Scope = "I", Type = "L", ReferenceName = "Bangka"},
                                 new {Id    = "mfc", Scope = "I", Type = "L", ReferenceName = "Mba"},
                                 new {Id    = "mfd", Scope = "I", Type = "L", ReferenceName = "Mendankwe-Nkwen"},
                                 new {Id    = "mfe", Scope = "I", Type = "L", ReferenceName = "Morisyen"},
                                 new {Id    = "mff", Scope = "I", Type = "L", ReferenceName = "Naki"},
                                 new {Id    = "mfg", Scope = "I", Type = "L", ReferenceName = "Mogofin"},
                                 new {Id    = "mfh", Scope = "I", Type = "L", ReferenceName = "Matal"},
                                 new {Id    = "mfi", Scope = "I", Type = "L", ReferenceName = "Wandala"},
                                 new {Id    = "mfj", Scope = "I", Type = "L", ReferenceName = "Mefele"},
                                 new {Id    = "mfk", Scope = "I", Type = "L", ReferenceName = "North Mofu"},
                                 new {Id    = "mfl", Scope = "I", Type = "L", ReferenceName = "Putai"},
                                 new {Id    = "mfm", Scope = "I", Type = "L", ReferenceName = "Marghi South"},
                                 new {Id    = "mfn", Scope = "I", Type = "L", ReferenceName = "Cross River Mbembe"},
                                 new {Id    = "mfo", Scope = "I", Type = "L", ReferenceName = "Mbe"},
                                 new {Id    = "mfp", Scope = "I", Type = "L", ReferenceName = "Makassar Malay"},
                                 new {Id    = "mfq", Scope = "I", Type = "L", ReferenceName = "Moba"},
                                 new {Id    = "mfr", Scope = "I", Type = "L", ReferenceName = "Marrithiyel"},
                                 new {Id    = "mfs", Scope = "I", Type = "L", ReferenceName = "Mexican Sign Language"},
                                 new {Id    = "mft", Scope = "I", Type = "L", ReferenceName = "Mokerang"},
                                 new {Id    = "mfu", Scope = "I", Type = "L", ReferenceName = "Mbwela"},
                                 new {Id    = "mfv", Scope = "I", Type = "L", ReferenceName = "Mandjak"},
                                 new {Id    = "mfw", Scope = "I", Type = "E", ReferenceName = "Mulaha"},
                                 new {Id    = "mfx", Scope = "I", Type = "L", ReferenceName = "Melo"},
                                 new {Id    = "mfy", Scope = "I", Type = "L", ReferenceName = "Mayo"},
                                 new {Id    = "mfz", Scope = "I", Type = "L", ReferenceName = "Mabaan"},
                                 new
                                 {
                                     Id            = "mga",
                                     Part2B        = "mga",
                                     Part2T        = "mga",
                                     Scope         = "I",
                                     Type          = "H",
                                     ReferenceName = "Middle Irish (900-1200)"
                                 }, new {Id = "mgb", Scope = "I", Type = "L", ReferenceName = "Mararit"},
                                 new {Id    = "mgc", Scope = "I", Type = "L", ReferenceName = "Morokodo"},
                                 new {Id    = "mgd", Scope = "I", Type = "L", ReferenceName = "Moru"},
                                 new {Id    = "mge", Scope = "I", Type = "L", ReferenceName = "Mango"},
                                 new {Id    = "mgf", Scope = "I", Type = "L", ReferenceName = "Maklew"},
                                 new {Id    = "mgg", Scope = "I", Type = "L", ReferenceName = "Mpumpong"},
                                 new {Id    = "mgh", Scope = "I", Type = "L", ReferenceName = "Makhuwa-Meetto"},
                                 new {Id    = "mgi", Scope = "I", Type = "L", ReferenceName = "Lijili"},
                                 new {Id    = "mgj", Scope = "I", Type = "L", ReferenceName = "Abureni"},
                                 new {Id    = "mgk", Scope = "I", Type = "L", ReferenceName = "Mawes"},
                                 new {Id    = "mgl", Scope = "I", Type = "L", ReferenceName = "Maleu-Kilenge"},
                                 new {Id    = "mgm", Scope = "I", Type = "L", ReferenceName = "Mambae"},
                                 new {Id    = "mgn", Scope = "I", Type = "L", ReferenceName = "Mbangi"},
                                 new {Id    = "mgo", Scope = "I", Type = "L", ReferenceName = "Meta'"},
                                 new {Id    = "mgp", Scope = "I", Type = "L", ReferenceName = "Eastern Magar"},
                                 new {Id    = "mgq", Scope = "I", Type = "L", ReferenceName = "Malila"},
                                 new {Id    = "mgr", Scope = "I", Type = "L", ReferenceName = "Mambwe-Lungu"},
                                 new {Id    = "mgs", Scope = "I", Type = "L", ReferenceName = "Manda (Tanzania)"},
                                 new {Id    = "mgt", Scope = "I", Type = "L", ReferenceName = "Mongol"},
                                 new {Id    = "mgu", Scope = "I", Type = "L", ReferenceName = "Mailu"},
                                 new {Id    = "mgv", Scope = "I", Type = "L", ReferenceName = "Matengo"},
                                 new {Id    = "mgw", Scope = "I", Type = "L", ReferenceName = "Matumbi"},
                                 new {Id    = "mgy", Scope = "I", Type = "L", ReferenceName = "Mbunga"},
                                 new {Id    = "mgz", Scope = "I", Type = "L", ReferenceName = "Mbugwe"},
                                 new {Id    = "mha", Scope = "I", Type = "L", ReferenceName = "Manda (India)"},
                                 new {Id    = "mhb", Scope = "I", Type = "L", ReferenceName = "Mahongwe"},
                                 new {Id    = "mhc", Scope = "I", Type = "L", ReferenceName = "Mocho"},
                                 new {Id    = "mhd", Scope = "I", Type = "L", ReferenceName = "Mbugu"},
                                 new {Id    = "mhe", Scope = "I", Type = "L", ReferenceName = "Besisi"},
                                 new {Id    = "mhf", Scope = "I", Type = "L", ReferenceName = "Mamaa"},
                                 new {Id    = "mhg", Scope = "I", Type = "L", ReferenceName = "Margu"},
                                 new {Id    = "mhi", Scope = "I", Type = "L", ReferenceName = "Ma'di"},
                                 new {Id    = "mhj", Scope = "I", Type = "L", ReferenceName = "Mogholi"},
                                 new {Id    = "mhk", Scope = "I", Type = "L", ReferenceName = "Mungaka"},
                                 new {Id    = "mhl", Scope = "I", Type = "L", ReferenceName = "Mauwake"},
                                 new {Id    = "mhm", Scope = "I", Type = "L", ReferenceName = "Makhuwa-Moniga"},
                                 new {Id    = "mhn", Scope = "I", Type = "L", ReferenceName = "Mócheno"},
                                 new {Id    = "mho", Scope = "I", Type = "L", ReferenceName = "Mashi (Zambia)"},
                                 new {Id    = "mhp", Scope = "I", Type = "L", ReferenceName = "Balinese Malay"},
                                 new {Id    = "mhq", Scope = "I", Type = "L", ReferenceName = "Mandan"},
                                 new {Id    = "mhr", Scope = "I", Type = "L", ReferenceName = "Eastern Mari"},
                                 new {Id    = "mhs", Scope = "I", Type = "L", ReferenceName = "Buru (Indonesia)"},
                                 new {Id    = "mht", Scope = "I", Type = "L", ReferenceName = "Mandahuaca"},
                                 new {Id    = "mhu", Scope = "I", Type = "L", ReferenceName = "Digaro-Mishmi"},
                                 new {Id    = "mhw", Scope = "I", Type = "L", ReferenceName = "Mbukushu"},
                                 new {Id    = "mhx", Scope = "I", Type = "L", ReferenceName = "Maru"},
                                 new {Id    = "mhy", Scope = "I", Type = "L", ReferenceName = "Ma'anyan"},
                                 new {Id    = "mhz", Scope = "I", Type = "L", ReferenceName = "Mor (Mor Islands)"},
                                 new {Id    = "mia", Scope = "I", Type = "L", ReferenceName = "Miami"},
                                 new {Id    = "mib", Scope = "I", Type = "L", ReferenceName = "Atatláhuca Mixtec"},
                                 new
                                 {
                                     Id            = "mic",
                                     Part2B        = "mic",
                                     Part2T        = "mic",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mi'kmaq"
                                 }, new {Id = "mid", Scope = "I", Type = "L", ReferenceName = "Mandaic"},
                                 new {Id    = "mie", Scope = "I", Type = "L", ReferenceName = "Ocotepec Mixtec"},
                                 new {Id    = "mif", Scope = "I", Type = "L", ReferenceName = "Mofu-Gudur"},
                                 new
                                 {
                                     Id            = "mig",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "San Miguel El Grande Mixtec"
                                 }, new {Id = "mih", Scope = "I", Type = "L", ReferenceName = "Chayuco Mixtec"},
                                 new
                                     {
                                         Id            = "mii",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Chigmecatitlán Mixtec"
                                     },
                                 new {Id = "mij", Scope = "I", Type = "L", ReferenceName = "Abar"},
                                 new {Id = "mik", Scope = "I", Type = "L", ReferenceName = "Mikasuki"},
                                 new {Id = "mil", Scope = "I", Type = "L", ReferenceName = "Peñoles Mixtec"},
                                 new
                                     {
                                         Id            = "mim",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Alacatlatzala Mixtec"
                                     },
                                 new
                                 {
                                     Id            = "min",
                                     Part2B        = "min",
                                     Part2T        = "min",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Minangkabau"
                                 },
                                 new {Id = "mio", Scope = "I", Type = "L", ReferenceName = "Pinotepa Nacional Mixtec"},
                                 new {Id = "mip", Scope = "I", Type = "L", ReferenceName = "Apasco-Apoala Mixtec"},
                                 new {Id = "miq", Scope = "I", Type = "L", ReferenceName = "Mískito"},
                                 new {Id = "mir", Scope = "I", Type = "L", ReferenceName = "Isthmus Mixe"},
                                 new
                                 {
                                     Id            = "mis",
                                     Part2B        = "mis",
                                     Part2T        = "mis",
                                     Scope         = "S",
                                     Type          = "S",
                                     ReferenceName = "Uncoded languages"
                                 }, new {Id = "mit", Scope = "I", Type = "L", ReferenceName = "Southern Puebla Mixtec"},
                                 new {Id    = "miu", Scope = "I", Type = "L", ReferenceName = "Cacaloxtepec Mixtec"},
                                 new {Id    = "miw", Scope = "I", Type = "L", ReferenceName = "Akoye"},
                                 new {Id    = "mix", Scope = "I", Type = "L", ReferenceName = "Mixtepec Mixtec"},
                                 new {Id    = "miy", Scope = "I", Type = "L", ReferenceName = "Ayutla Mixtec"},
                                 new {Id    = "miz", Scope = "I", Type = "L", ReferenceName = "Coatzospan Mixtec"},
                                 new {Id    = "mjb", Scope = "I", Type = "L", ReferenceName = "Makalero"},
                                 new
                                     {
                                         Id            = "mjc",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "San Juan Colorado Mixtec"
                                     },
                                 new {Id = "mjd", Scope = "I", Type = "L", ReferenceName = "Northwest Maidu"},
                                 new {Id = "mje", Scope = "I", Type = "E", ReferenceName = "Muskum"},
                                 new {Id = "mjg", Scope = "I", Type = "L", ReferenceName = "Tu"},
                                 new {Id = "mjh", Scope = "I", Type = "L", ReferenceName = "Mwera (Nyasa)"},
                                 new {Id = "mji", Scope = "I", Type = "L", ReferenceName = "Kim Mun"},
                                 new {Id = "mjj", Scope = "I", Type = "L", ReferenceName = "Mawak"},
                                 new {Id = "mjk", Scope = "I", Type = "L", ReferenceName = "Matukar"},
                                 new {Id = "mjl", Scope = "I", Type = "L", ReferenceName = "Mandeali"},
                                 new {Id = "mjm", Scope = "I", Type = "L", ReferenceName = "Medebur"},
                                 new {Id = "mjn", Scope = "I", Type = "L", ReferenceName = "Ma (Papua New Guinea)"},
                                 new {Id = "mjo", Scope = "I", Type = "L", ReferenceName = "Malankuravan"},
                                 new {Id = "mjp", Scope = "I", Type = "L", ReferenceName = "Malapandaram"},
                                 new {Id = "mjq", Scope = "I", Type = "E", ReferenceName = "Malaryan"},
                                 new {Id = "mjr", Scope = "I", Type = "L", ReferenceName = "Malavedan"},
                                 new {Id = "mjs", Scope = "I", Type = "L", ReferenceName = "Miship"},
                                 new {Id = "mjt", Scope = "I", Type = "L", ReferenceName = "Sauria Paharia"},
                                 new {Id = "mju", Scope = "I", Type = "L", ReferenceName = "Manna-Dora"},
                                 new {Id = "mjv", Scope = "I", Type = "L", ReferenceName = "Mannan"},
                                 new {Id = "mjw", Scope = "I", Type = "L", ReferenceName = "Karbi"},
                                 new {Id = "mjx", Scope = "I", Type = "L", ReferenceName = "Mahali"},
                                 new {Id = "mjy", Scope = "I", Type = "E", ReferenceName = "Mahican"},
                                 new {Id = "mjz", Scope = "I", Type = "L", ReferenceName = "Majhi"},
                                 new {Id = "mka", Scope = "I", Type = "L", ReferenceName = "Mbre"},
                                 new {Id = "mkb", Scope = "I", Type = "L", ReferenceName = "Mal Paharia"},
                                 new {Id = "mkc", Scope = "I", Type = "L", ReferenceName = "Siliput"},
                                 new
                                 {
                                     Id            = "mkd",
                                     Part2B        = "mac",
                                     Part2T        = "mkd",
                                     Part1         = "mk",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Macedonian"
                                 }, new {Id = "mke", Scope = "I", Type = "L", ReferenceName = "Mawchi"},
                                 new {Id    = "mkf", Scope = "I", Type = "L", ReferenceName = "Miya"},
                                 new {Id    = "mkg", Scope = "I", Type = "L", ReferenceName = "Mak (China)"},
                                 new {Id    = "mki", Scope = "I", Type = "L", ReferenceName = "Dhatki"},
                                 new {Id    = "mkj", Scope = "I", Type = "L", ReferenceName = "Mokilese"},
                                 new {Id    = "mkk", Scope = "I", Type = "L", ReferenceName = "Byep"},
                                 new {Id    = "mkl", Scope = "I", Type = "L", ReferenceName = "Mokole"},
                                 new {Id    = "mkm", Scope = "I", Type = "L", ReferenceName = "Moklen"},
                                 new {Id    = "mkn", Scope = "I", Type = "L", ReferenceName = "Kupang Malay"},
                                 new {Id    = "mko", Scope = "I", Type = "L", ReferenceName = "Mingang Doso"},
                                 new {Id    = "mkp", Scope = "I", Type = "L", ReferenceName = "Moikodi"},
                                 new {Id    = "mkq", Scope = "I", Type = "E", ReferenceName = "Bay Miwok"},
                                 new {Id    = "mkr", Scope = "I", Type = "L", ReferenceName = "Malas"},
                                 new {Id    = "mks", Scope = "I", Type = "L", ReferenceName = "Silacayoapan Mixtec"},
                                 new {Id    = "mkt", Scope = "I", Type = "L", ReferenceName = "Vamale"},
                                 new {Id    = "mku", Scope = "I", Type = "L", ReferenceName = "Konyanka Maninka"},
                                 new {Id    = "mkv", Scope = "I", Type = "L", ReferenceName = "Mafea"},
                                 new {Id    = "mkw", Scope = "I", Type = "L", ReferenceName = "Kituba (Congo)"},
                                 new {Id    = "mkx", Scope = "I", Type = "L", ReferenceName = "Kinamiging Manobo"},
                                 new {Id    = "mky", Scope = "I", Type = "L", ReferenceName = "East Makian"},
                                 new {Id    = "mkz", Scope = "I", Type = "L", ReferenceName = "Makasae"},
                                 new {Id    = "mla", Scope = "I", Type = "L", ReferenceName = "Malo"},
                                 new {Id    = "mlb", Scope = "I", Type = "L", ReferenceName = "Mbule"},
                                 new {Id    = "mlc", Scope = "I", Type = "L", ReferenceName = "Cao Lan"},
                                 new {Id    = "mle", Scope = "I", Type = "L", ReferenceName = "Manambu"},
                                 new {Id    = "mlf", Scope = "I", Type = "L", ReferenceName = "Mal"},
                                 new
                                 {
                                     Id            = "mlg",
                                     Part2B        = "mlg",
                                     Part2T        = "mlg",
                                     Part1         = "mg",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Malagasy"
                                 }, new {Id = "mlh", Scope = "I", Type = "L", ReferenceName = "Mape"},
                                 new {Id    = "mli", Scope = "I", Type = "L", ReferenceName = "Malimpung"},
                                 new {Id    = "mlj", Scope = "I", Type = "L", ReferenceName = "Miltu"},
                                 new {Id    = "mlk", Scope = "I", Type = "L", ReferenceName = "Ilwana"},
                                 new {Id    = "mll", Scope = "I", Type = "L", ReferenceName = "Malua Bay"},
                                 new {Id    = "mlm", Scope = "I", Type = "L", ReferenceName = "Mulam"},
                                 new {Id    = "mln", Scope = "I", Type = "L", ReferenceName = "Malango"},
                                 new {Id    = "mlo", Scope = "I", Type = "L", ReferenceName = "Mlomp"},
                                 new {Id    = "mlp", Scope = "I", Type = "L", ReferenceName = "Bargam"},
                                 new {Id    = "mlq", Scope = "I", Type = "L", ReferenceName = "Western Maninkakan"},
                                 new {Id    = "mlr", Scope = "I", Type = "L", ReferenceName = "Vame"},
                                 new {Id    = "mls", Scope = "I", Type = "L", ReferenceName = "Masalit"},
                                 new
                                 {
                                     Id            = "mlt",
                                     Part2B        = "mlt",
                                     Part2T        = "mlt",
                                     Part1         = "mt",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Maltese"
                                 }, new {Id = "mlu", Scope = "I", Type = "L", ReferenceName = "To'abaita"},
                                 new {Id    = "mlv", Scope = "I", Type = "L", ReferenceName = "Motlav"},
                                 new {Id    = "mlw", Scope = "I", Type = "L", ReferenceName = "Moloko"},
                                 new {Id    = "mlx", Scope = "I", Type = "L", ReferenceName = "Malfaxal"},
                                 new {Id    = "mlz", Scope = "I", Type = "L", ReferenceName = "Malaynon"},
                                 new {Id    = "mma", Scope = "I", Type = "L", ReferenceName = "Mama"},
                                 new {Id    = "mmb", Scope = "I", Type = "L", ReferenceName = "Momina"},
                                 new {Id    = "mmc", Scope = "I", Type = "L", ReferenceName = "Michoacán Mazahua"},
                                 new {Id    = "mmd", Scope = "I", Type = "L", ReferenceName = "Maonan"},
                                 new {Id    = "mme", Scope = "I", Type = "L", ReferenceName = "Mae"},
                                 new {Id    = "mmf", Scope = "I", Type = "L", ReferenceName = "Mundat"},
                                 new {Id    = "mmg", Scope = "I", Type = "L", ReferenceName = "North Ambrym"},
                                 new {Id    = "mmh", Scope = "I", Type = "L", ReferenceName = "Mehináku"},
                                 new {Id    = "mmi", Scope = "I", Type = "L", ReferenceName = "Musar"},
                                 new {Id    = "mmj", Scope = "I", Type = "L", ReferenceName = "Majhwar"},
                                 new {Id    = "mmk", Scope = "I", Type = "L", ReferenceName = "Mukha-Dora"},
                                 new {Id    = "mml", Scope = "I", Type = "L", ReferenceName = "Man Met"},
                                 new {Id    = "mmm", Scope = "I", Type = "L", ReferenceName = "Maii"},
                                 new {Id    = "mmn", Scope = "I", Type = "L", ReferenceName = "Mamanwa"},
                                 new {Id    = "mmo", Scope = "I", Type = "L", ReferenceName = "Mangga Buang"},
                                 new {Id    = "mmp", Scope = "I", Type = "L", ReferenceName = "Siawi"},
                                 new {Id    = "mmq", Scope = "I", Type = "L", ReferenceName = "Musak"},
                                 new {Id    = "mmr", Scope = "I", Type = "L", ReferenceName = "Western Xiangxi Miao"},
                                 new {Id    = "mmt", Scope = "I", Type = "L", ReferenceName = "Malalamai"},
                                 new {Id    = "mmu", Scope = "I", Type = "L", ReferenceName = "Mmaala"},
                                 new {Id    = "mmv", Scope = "I", Type = "E", ReferenceName = "Miriti"},
                                 new {Id    = "mmw", Scope = "I", Type = "L", ReferenceName = "Emae"},
                                 new {Id    = "mmx", Scope = "I", Type = "L", ReferenceName = "Madak"},
                                 new {Id    = "mmy", Scope = "I", Type = "L", ReferenceName = "Migaama"},
                                 new {Id    = "mmz", Scope = "I", Type = "L", ReferenceName = "Mabaale"},
                                 new {Id    = "mna", Scope = "I", Type = "L", ReferenceName = "Mbula"},
                                 new {Id    = "mnb", Scope = "I", Type = "L", ReferenceName = "Muna"},
                                 new
                                 {
                                     Id            = "mnc",
                                     Part2B        = "mnc",
                                     Part2T        = "mnc",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Manchu"
                                 }, new {Id = "mnd", Scope = "I", Type = "L", ReferenceName = "Mondé"},
                                 new {Id    = "mne", Scope = "I", Type = "L", ReferenceName = "Naba"},
                                 new {Id    = "mnf", Scope = "I", Type = "L", ReferenceName = "Mundani"},
                                 new {Id    = "mng", Scope = "I", Type = "L", ReferenceName = "Eastern Mnong"},
                                 new
                                 {
                                     Id            = "mnh",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mono (Democratic Republic of Congo)"
                                 }, new
                                 {
                                     Id            = "mni",
                                     Part2B        = "mni",
                                     Part2T        = "mni",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Manipuri"
                                 }, new {Id = "mnj", Scope = "I", Type = "L", ReferenceName = "Munji"},
                                 new {Id    = "mnk", Scope = "I", Type = "L", ReferenceName = "Mandinka"},
                                 new {Id    = "mnl", Scope = "I", Type = "L", ReferenceName = "Tiale"},
                                 new {Id    = "mnm", Scope = "I", Type = "L", ReferenceName = "Mapena"},
                                 new {Id    = "mnn", Scope = "I", Type = "L", ReferenceName = "Southern Mnong"},
                                 new {Id    = "mnp", Scope = "I", Type = "L", ReferenceName = "Min Bei Chinese"},
                                 new {Id    = "mnq", Scope = "I", Type = "L", ReferenceName = "Minriq"},
                                 new {Id    = "mnr", Scope = "I", Type = "L", ReferenceName = "Mono (USA)"},
                                 new {Id    = "mns", Scope = "I", Type = "L", ReferenceName = "Mansi"},
                                 new {Id    = "mnu", Scope = "I", Type = "L", ReferenceName = "Mer"},
                                 new {Id    = "mnv", Scope = "I", Type = "L", ReferenceName = "Rennell-Bellona"},
                                 new {Id    = "mnw", Scope = "I", Type = "L", ReferenceName = "Mon"},
                                 new {Id    = "mnx", Scope = "I", Type = "L", ReferenceName = "Manikion"},
                                 new {Id    = "mny", Scope = "I", Type = "L", ReferenceName = "Manyawa"},
                                 new {Id    = "mnz", Scope = "I", Type = "L", ReferenceName = "Moni"},
                                 new {Id    = "moa", Scope = "I", Type = "L", ReferenceName = "Mwan"},
                                 new {Id    = "moc", Scope = "I", Type = "L", ReferenceName = "Mocoví"},
                                 new {Id    = "mod", Scope = "I", Type = "E", ReferenceName = "Mobilian"},
                                 new {Id    = "moe", Scope = "I", Type = "L", ReferenceName = "Montagnais"},
                                 new {Id    = "mog", Scope = "I", Type = "L", ReferenceName = "Mongondow"},
                                 new
                                 {
                                     Id            = "moh",
                                     Part2B        = "moh",
                                     Part2T        = "moh",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mohawk"
                                 }, new {Id = "moi", Scope = "I", Type = "L", ReferenceName = "Mboi"},
                                 new {Id    = "moj", Scope = "I", Type = "L", ReferenceName = "Monzombo"},
                                 new {Id    = "mok", Scope = "I", Type = "L", ReferenceName = "Morori"},
                                 new {Id    = "mom", Scope = "I", Type = "E", ReferenceName = "Mangue"},
                                 new
                                 {
                                     Id            = "mon",
                                     Part2B        = "mon",
                                     Part2T        = "mon",
                                     Part1         = "mn",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Mongolian"
                                 }, new {Id = "moo", Scope = "I", Type = "L", ReferenceName = "Monom"},
                                 new {Id    = "mop", Scope = "I", Type = "L", ReferenceName = "Mopán Maya"},
                                 new
                                     {
                                         Id            = "moq",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Mor (Bomberai Peninsula)"
                                     },
                                 new {Id = "mor", Scope = "I", Type = "L", ReferenceName = "Moro"},
                                 new
                                 {
                                     Id            = "mos",
                                     Part2B        = "mos",
                                     Part2T        = "mos",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mossi"
                                 }, new {Id = "mot", Scope = "I", Type = "L", ReferenceName = "Barí"},
                                 new {Id    = "mou", Scope = "I", Type = "L", ReferenceName = "Mogum"},
                                 new {Id    = "mov", Scope = "I", Type = "L", ReferenceName = "Mohave"},
                                 new {Id    = "mow", Scope = "I", Type = "L", ReferenceName = "Moi (Congo)"},
                                 new {Id    = "mox", Scope = "I", Type = "L", ReferenceName = "Molima"},
                                 new {Id    = "moy", Scope = "I", Type = "L", ReferenceName = "Shekkacho"},
                                 new {Id    = "moz", Scope = "I", Type = "L", ReferenceName = "Mukulu"},
                                 new {Id    = "mpa", Scope = "I", Type = "L", ReferenceName = "Mpoto"},
                                 new {Id    = "mpb", Scope = "I", Type = "L", ReferenceName = "Malak Malak"},
                                 new {Id    = "mpc", Scope = "I", Type = "L", ReferenceName = "Mangarrayi"},
                                 new {Id    = "mpd", Scope = "I", Type = "L", ReferenceName = "Machinere"},
                                 new {Id    = "mpe", Scope = "I", Type = "L", ReferenceName = "Majang"},
                                 new {Id    = "mpg", Scope = "I", Type = "L", ReferenceName = "Marba"},
                                 new {Id    = "mph", Scope = "I", Type = "L", ReferenceName = "Maung"},
                                 new {Id    = "mpi", Scope = "I", Type = "L", ReferenceName = "Mpade"},
                                 new {Id    = "mpj", Scope = "I", Type = "L", ReferenceName = "Martu Wangka"},
                                 new {Id    = "mpk", Scope = "I", Type = "L", ReferenceName = "Mbara (Chad)"},
                                 new {Id    = "mpl", Scope = "I", Type = "L", ReferenceName = "Middle Watut"},
                                 new {Id    = "mpm", Scope = "I", Type = "L", ReferenceName = "Yosondúa Mixtec"},
                                 new {Id    = "mpn", Scope = "I", Type = "L", ReferenceName = "Mindiri"},
                                 new {Id    = "mpo", Scope = "I", Type = "L", ReferenceName = "Miu"},
                                 new {Id    = "mpp", Scope = "I", Type = "L", ReferenceName = "Migabac"},
                                 new {Id    = "mpq", Scope = "I", Type = "L", ReferenceName = "Matís"},
                                 new {Id    = "mpr", Scope = "I", Type = "L", ReferenceName = "Vangunu"},
                                 new {Id    = "mps", Scope = "I", Type = "L", ReferenceName = "Dadibi"},
                                 new {Id    = "mpt", Scope = "I", Type = "L", ReferenceName = "Mian"},
                                 new {Id    = "mpu", Scope = "I", Type = "L", ReferenceName = "Makuráp"},
                                 new {Id    = "mpv", Scope = "I", Type = "L", ReferenceName = "Mungkip"},
                                 new {Id    = "mpw", Scope = "I", Type = "L", ReferenceName = "Mapidian"},
                                 new {Id    = "mpx", Scope = "I", Type = "L", ReferenceName = "Misima-Panaeati"},
                                 new {Id    = "mpy", Scope = "I", Type = "L", ReferenceName = "Mapia"},
                                 new {Id    = "mpz", Scope = "I", Type = "L", ReferenceName = "Mpi"},
                                 new {Id    = "mqa", Scope = "I", Type = "L", ReferenceName = "Maba (Indonesia)"},
                                 new {Id    = "mqb", Scope = "I", Type = "L", ReferenceName = "Mbuko"},
                                 new {Id    = "mqc", Scope = "I", Type = "L", ReferenceName = "Mangole"},
                                 new {Id    = "mqe", Scope = "I", Type = "L", ReferenceName = "Matepi"},
                                 new {Id    = "mqf", Scope = "I", Type = "L", ReferenceName = "Momuna"},
                                 new
                                     {
                                         Id            = "mqg",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Kota Bangun Kutai Malay"
                                     },
                                 new {Id = "mqh", Scope = "I", Type = "L", ReferenceName = "Tlazoyaltepec Mixtec"},
                                 new {Id = "mqi", Scope = "I", Type = "L", ReferenceName = "Mariri"},
                                 new {Id = "mqj", Scope = "I", Type = "L", ReferenceName = "Mamasa"},
                                 new
                                     {
                                         Id            = "mqk",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Rajah Kabunsuwan Manobo"
                                     },
                                 new {Id = "mql", Scope = "I", Type = "L", ReferenceName = "Mbelime"},
                                 new {Id = "mqm", Scope = "I", Type = "L", ReferenceName = "South Marquesan"},
                                 new {Id = "mqn", Scope = "I", Type = "L", ReferenceName = "Moronene"},
                                 new {Id = "mqo", Scope = "I", Type = "L", ReferenceName = "Modole"},
                                 new {Id = "mqp", Scope = "I", Type = "L", ReferenceName = "Manipa"},
                                 new {Id = "mqq", Scope = "I", Type = "L", ReferenceName = "Minokok"},
                                 new {Id = "mqr", Scope = "I", Type = "L", ReferenceName = "Mander"},
                                 new {Id = "mqs", Scope = "I", Type = "L", ReferenceName = "West Makian"},
                                 new {Id = "mqt", Scope = "I", Type = "L", ReferenceName = "Mok"},
                                 new {Id = "mqu", Scope = "I", Type = "L", ReferenceName = "Mandari"},
                                 new {Id = "mqv", Scope = "I", Type = "L", ReferenceName = "Mosimo"},
                                 new {Id = "mqw", Scope = "I", Type = "L", ReferenceName = "Murupi"},
                                 new {Id = "mqx", Scope = "I", Type = "L", ReferenceName = "Mamuju"},
                                 new {Id = "mqy", Scope = "I", Type = "L", ReferenceName = "Manggarai"},
                                 new {Id = "mqz", Scope = "I", Type = "L", ReferenceName = "Pano"},
                                 new {Id = "mra", Scope = "I", Type = "L", ReferenceName = "Mlabri"},
                                 new {Id = "mrb", Scope = "I", Type = "L", ReferenceName = "Marino"},
                                 new {Id = "mrc", Scope = "I", Type = "L", ReferenceName = "Maricopa"},
                                 new {Id = "mrd", Scope = "I", Type = "L", ReferenceName = "Western Magar"},
                                 new
                                 {
                                     Id            = "mre",
                                     Scope         = "I",
                                     Type          = "E",
                                     ReferenceName = "Martha's Vineyard Sign Language"
                                 }, new {Id = "mrf", Scope = "I", Type = "L", ReferenceName = "Elseng"},
                                 new {Id    = "mrg", Scope = "I", Type = "L", ReferenceName = "Mising"},
                                 new {Id    = "mrh", Scope = "I", Type = "L", ReferenceName = "Mara Chin"},
                                 new
                                 {
                                     Id            = "mri",
                                     Part2B        = "mao",
                                     Part2T        = "mri",
                                     Part1         = "mi",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Maori"
                                 }, new {Id = "mrj", Scope = "I", Type = "L", ReferenceName = "Western Mari"},
                                 new {Id    = "mrk", Scope = "I", Type = "L", ReferenceName = "Hmwaveke"},
                                 new {Id    = "mrl", Scope = "I", Type = "L", ReferenceName = "Mortlockese"},
                                 new {Id    = "mrm", Scope = "I", Type = "L", ReferenceName = "Merlav"},
                                 new {Id    = "mrn", Scope = "I", Type = "L", ReferenceName = "Cheke Holo"},
                                 new {Id    = "mro", Scope = "I", Type = "L", ReferenceName = "Mru"},
                                 new {Id    = "mrp", Scope = "I", Type = "L", ReferenceName = "Morouas"},
                                 new {Id    = "mrq", Scope = "I", Type = "L", ReferenceName = "North Marquesan"},
                                 new {Id    = "mrr", Scope = "I", Type = "L", ReferenceName = "Maria (India)"},
                                 new {Id    = "mrs", Scope = "I", Type = "L", ReferenceName = "Maragus"},
                                 new {Id    = "mrt", Scope = "I", Type = "L", ReferenceName = "Marghi Central"},
                                 new {Id    = "mru", Scope = "I", Type = "L", ReferenceName = "Mono (Cameroon)"},
                                 new {Id    = "mrv", Scope = "I", Type = "L", ReferenceName = "Mangareva"},
                                 new {Id    = "mrw", Scope = "I", Type = "L", ReferenceName = "Maranao"},
                                 new {Id    = "mrx", Scope = "I", Type = "L", ReferenceName = "Maremgi"},
                                 new {Id    = "mry", Scope = "I", Type = "L", ReferenceName = "Mandaya"},
                                 new {Id    = "mrz", Scope = "I", Type = "L", ReferenceName = "Marind"},
                                 new
                                 {
                                     Id            = "msa",
                                     Part2B        = "may",
                                     Part2T        = "msa",
                                     Part1         = "ms",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Malay (macrolanguage)"
                                 }, new {Id = "msb", Scope = "I", Type = "L", ReferenceName = "Masbatenyo"},
                                 new {Id    = "msc", Scope = "I", Type = "L", ReferenceName = "Sankaran Maninka"},
                                 new
                                 {
                                     Id            = "msd",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Yucatec Maya Sign Language"
                                 }, new {Id = "mse", Scope = "I", Type = "L", ReferenceName = "Musey"},
                                 new {Id    = "msf", Scope = "I", Type = "L", ReferenceName = "Mekwei"},
                                 new {Id    = "msg", Scope = "I", Type = "L", ReferenceName = "Moraid"},
                                 new {Id    = "msh", Scope = "I", Type = "L", ReferenceName = "Masikoro Malagasy"},
                                 new {Id    = "msi", Scope = "I", Type = "L", ReferenceName = "Sabah Malay"},
                                 new
                                 {
                                     Id            = "msj",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Ma (Democratic Republic of Congo)"
                                 }, new {Id = "msk", Scope = "I", Type = "L", ReferenceName = "Mansaka"},
                                 new {Id    = "msl", Scope = "I", Type = "L", ReferenceName = "Molof"},
                                 new {Id    = "msm", Scope = "I", Type = "L", ReferenceName = "Agusan Manobo"},
                                 new {Id    = "msn", Scope = "I", Type = "L", ReferenceName = "Vurës"},
                                 new {Id    = "mso", Scope = "I", Type = "L", ReferenceName = "Mombum"},
                                 new {Id    = "msp", Scope = "I", Type = "E", ReferenceName = "Maritsauá"},
                                 new {Id    = "msq", Scope = "I", Type = "L", ReferenceName = "Caac"},
                                 new
                                     {
                                         Id            = "msr",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Mongolian Sign Language"
                                     },
                                 new {Id = "mss", Scope = "I", Type = "L", ReferenceName = "West Masela"},
                                 new {Id = "msu", Scope = "I", Type = "L", ReferenceName = "Musom"},
                                 new {Id = "msv", Scope = "I", Type = "L", ReferenceName = "Maslam"},
                                 new {Id = "msw", Scope = "I", Type = "L", ReferenceName = "Mansoanka"},
                                 new {Id = "msx", Scope = "I", Type = "L", ReferenceName = "Moresada"},
                                 new {Id = "msy", Scope = "I", Type = "L", ReferenceName = "Aruamu"},
                                 new {Id = "msz", Scope = "I", Type = "L", ReferenceName = "Momare"},
                                 new {Id = "mta", Scope = "I", Type = "L", ReferenceName = "Cotabato Manobo"},
                                 new {Id = "mtb", Scope = "I", Type = "L", ReferenceName = "Anyin Morofo"},
                                 new {Id = "mtc", Scope = "I", Type = "L", ReferenceName = "Munit"},
                                 new {Id = "mtd", Scope = "I", Type = "L", ReferenceName = "Mualang"},
                                 new
                                     {
                                         Id            = "mte",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Mono (Solomon Islands)"
                                     },
                                 new
                                     {
                                         Id            = "mtf",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Murik (Papua New Guinea)"
                                     },
                                 new {Id = "mtg", Scope = "I", Type = "L", ReferenceName = "Una"},
                                 new {Id = "mth", Scope = "I", Type = "L", ReferenceName = "Munggui"},
                                 new
                                     {
                                         Id            = "mti",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Maiwa (Papua New Guinea)"
                                     },
                                 new {Id = "mtj", Scope = "I", Type = "L", ReferenceName = "Moskona"},
                                 new {Id = "mtk", Scope = "I", Type = "L", ReferenceName = "Mbe'"},
                                 new {Id = "mtl", Scope = "I", Type = "L", ReferenceName = "Montol"},
                                 new {Id = "mtm", Scope = "I", Type = "E", ReferenceName = "Mator"},
                                 new {Id = "mtn", Scope = "I", Type = "E", ReferenceName = "Matagalpa"},
                                 new {Id = "mto", Scope = "I", Type = "L", ReferenceName = "Totontepec Mixe"},
                                 new
                                     {
                                         Id            = "mtp",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Wichí Lhamtés Nocten"
                                     },
                                 new {Id = "mtq", Scope = "I", Type = "L", ReferenceName = "Muong"},
                                 new {Id = "mtr", Scope = "I", Type = "L", ReferenceName = "Mewari"},
                                 new {Id = "mts", Scope = "I", Type = "L", ReferenceName = "Yora"},
                                 new {Id = "mtt", Scope = "I", Type = "L", ReferenceName = "Mota"},
                                 new {Id = "mtu", Scope = "I", Type = "L", ReferenceName = "Tututepec Mixtec"},
                                 new {Id = "mtv", Scope = "I", Type = "L", ReferenceName = "Asaro'o"},
                                 new
                                     {
                                         Id            = "mtw",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Southern Binukidnon"
                                     },
                                 new {Id = "mtx", Scope = "I", Type = "L", ReferenceName = "Tidaá Mixtec"},
                                 new {Id = "mty", Scope = "I", Type = "L", ReferenceName = "Nabi"},
                                 new {Id = "mua", Scope = "I", Type = "L", ReferenceName = "Mundang"},
                                 new {Id = "mub", Scope = "I", Type = "L", ReferenceName = "Mubi"},
                                 new {Id = "muc", Scope = "I", Type = "L", ReferenceName = "Ajumbu"},
                                 new {Id = "mud", Scope = "I", Type = "L", ReferenceName = "Mednyj Aleut"},
                                 new {Id = "mue", Scope = "I", Type = "L", ReferenceName = "Media Lengua"},
                                 new {Id = "mug", Scope = "I", Type = "L", ReferenceName = "Musgu"},
                                 new {Id = "muh", Scope = "I", Type = "L", ReferenceName = "Mündü"},
                                 new {Id = "mui", Scope = "I", Type = "L", ReferenceName = "Musi"},
                                 new {Id = "muj", Scope = "I", Type = "L", ReferenceName = "Mabire"},
                                 new {Id = "muk", Scope = "I", Type = "L", ReferenceName = "Mugom"},
                                 new
                                 {
                                     Id            = "mul",
                                     Part2B        = "mul",
                                     Part2T        = "mul",
                                     Scope         = "S",
                                     Type          = "S",
                                     ReferenceName = "Multiple languages"
                                 }, new {Id = "mum", Scope = "I", Type = "L", ReferenceName = "Maiwala"},
                                 new {Id    = "muo", Scope = "I", Type = "L", ReferenceName = "Nyong"},
                                 new {Id    = "mup", Scope = "I", Type = "L", ReferenceName = "Malvi"},
                                 new {Id    = "muq", Scope = "I", Type = "L", ReferenceName = "Eastern Xiangxi Miao"},
                                 new {Id    = "mur", Scope = "I", Type = "L", ReferenceName = "Murle"},
                                 new
                                 {
                                     Id            = "mus",
                                     Part2B        = "mus",
                                     Part2T        = "mus",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Creek"
                                 }, new {Id = "mut", Scope = "I", Type = "L", ReferenceName = "Western Muria"},
                                 new {Id    = "muu", Scope = "I", Type = "L", ReferenceName = "Yaaku"},
                                 new {Id    = "muv", Scope = "I", Type = "L", ReferenceName = "Muthuvan"},
                                 new {Id    = "mux", Scope = "I", Type = "L", ReferenceName = "Bo-Ung"},
                                 new {Id    = "muy", Scope = "I", Type = "L", ReferenceName = "Muyang"},
                                 new {Id    = "muz", Scope = "I", Type = "L", ReferenceName = "Mursi"},
                                 new {Id    = "mva", Scope = "I", Type = "L", ReferenceName = "Manam"},
                                 new {Id    = "mvb", Scope = "I", Type = "E", ReferenceName = "Mattole"},
                                 new {Id    = "mvd", Scope = "I", Type = "L", ReferenceName = "Mamboru"},
                                 new {Id    = "mve", Scope = "I", Type = "L", ReferenceName = "Marwari (Pakistan)"},
                                 new {Id    = "mvf", Scope = "I", Type = "L", ReferenceName = "Peripheral Mongolian"},
                                 new {Id    = "mvg", Scope = "I", Type = "L", ReferenceName = "Yucuañe Mixtec"},
                                 new {Id    = "mvh", Scope = "I", Type = "L", ReferenceName = "Mulgi"},
                                 new {Id    = "mvi", Scope = "I", Type = "L", ReferenceName = "Miyako"},
                                 new {Id    = "mvk", Scope = "I", Type = "L", ReferenceName = "Mekmek"},
                                 new {Id    = "mvl", Scope = "I", Type = "E", ReferenceName = "Mbara (Australia)"},
                                 new {Id    = "mvm", Scope = "I", Type = "L", ReferenceName = "Muya"},
                                 new {Id    = "mvn", Scope = "I", Type = "L", ReferenceName = "Minaveha"},
                                 new {Id    = "mvo", Scope = "I", Type = "L", ReferenceName = "Marovo"},
                                 new {Id    = "mvp", Scope = "I", Type = "L", ReferenceName = "Duri"},
                                 new {Id    = "mvq", Scope = "I", Type = "L", ReferenceName = "Moere"},
                                 new {Id    = "mvr", Scope = "I", Type = "L", ReferenceName = "Marau"},
                                 new {Id    = "mvs", Scope = "I", Type = "L", ReferenceName = "Massep"},
                                 new {Id    = "mvt", Scope = "I", Type = "L", ReferenceName = "Mpotovoro"},
                                 new {Id    = "mvu", Scope = "I", Type = "L", ReferenceName = "Marfa"},
                                 new {Id    = "mvv", Scope = "I", Type = "L", ReferenceName = "Tagal Murut"},
                                 new {Id    = "mvw", Scope = "I", Type = "L", ReferenceName = "Machinga"},
                                 new {Id    = "mvx", Scope = "I", Type = "L", ReferenceName = "Meoswar"},
                                 new {Id    = "mvy", Scope = "I", Type = "L", ReferenceName = "Indus Kohistani"},
                                 new {Id    = "mvz", Scope = "I", Type = "L", ReferenceName = "Mesqan"},
                                 new {Id    = "mwa", Scope = "I", Type = "L", ReferenceName = "Mwatebu"},
                                 new {Id    = "mwb", Scope = "I", Type = "L", ReferenceName = "Juwal"},
                                 new {Id    = "mwc", Scope = "I", Type = "L", ReferenceName = "Are"},
                                 new {Id    = "mwe", Scope = "I", Type = "L", ReferenceName = "Mwera (Chimwera)"},
                                 new {Id    = "mwf", Scope = "I", Type = "L", ReferenceName = "Murrinh-Patha"},
                                 new {Id    = "mwg", Scope = "I", Type = "L", ReferenceName = "Aiklep"},
                                 new {Id    = "mwh", Scope = "I", Type = "L", ReferenceName = "Mouk-Aria"},
                                 new {Id    = "mwi", Scope = "I", Type = "L", ReferenceName = "Labo"},
                                 new {Id    = "mwk", Scope = "I", Type = "L", ReferenceName = "Kita Maninkakan"},
                                 new
                                 {
                                     Id            = "mwl",
                                     Part2B        = "mwl",
                                     Part2T        = "mwl",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Mirandese"
                                 }, new {Id = "mwm", Scope = "I", Type = "L", ReferenceName = "Sar"},
                                 new {Id    = "mwn", Scope = "I", Type = "L", ReferenceName = "Nyamwanga"},
                                 new {Id    = "mwo", Scope = "I", Type = "L", ReferenceName = "Central Maewo"},
                                 new {Id    = "mwp", Scope = "I", Type = "L", ReferenceName = "Kala Lagaw Ya"},
                                 new {Id    = "mwq", Scope = "I", Type = "L", ReferenceName = "Mün Chin"},
                                 new
                                 {
                                     Id            = "mwr",
                                     Part2B        = "mwr",
                                     Part2T        = "mwr",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Marwari"
                                 }, new {Id = "mws", Scope = "I", Type = "L", ReferenceName = "Mwimbi-Muthambi"},
                                 new {Id    = "mwt", Scope = "I", Type = "L", ReferenceName = "Moken"},
                                 new {Id    = "mwu", Scope = "I", Type = "E", ReferenceName = "Mittu"},
                                 new {Id    = "mwv", Scope = "I", Type = "L", ReferenceName = "Mentawai"},
                                 new {Id    = "mww", Scope = "I", Type = "L", ReferenceName = "Hmong Daw"},
                                 new {Id    = "mwz", Scope = "I", Type = "L", ReferenceName = "Moingi"},
                                 new
                                     {
                                         Id            = "mxa",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Northwest Oaxaca Mixtec"
                                     },
                                 new {Id = "mxb", Scope = "I", Type = "L", ReferenceName = "Tezoatlán Mixtec"},
                                 new {Id = "mxc", Scope = "I", Type = "L", ReferenceName = "Manyika"},
                                 new {Id = "mxd", Scope = "I", Type = "L", ReferenceName = "Modang"},
                                 new {Id = "mxe", Scope = "I", Type = "L", ReferenceName = "Mele-Fila"},
                                 new {Id = "mxf", Scope = "I", Type = "L", ReferenceName = "Malgbe"},
                                 new {Id = "mxg", Scope = "I", Type = "L", ReferenceName = "Mbangala"},
                                 new {Id = "mxh", Scope = "I", Type = "L", ReferenceName = "Mvuba"},
                                 new {Id = "mxi", Scope = "I", Type = "H", ReferenceName = "Mozarabic"},
                                 new {Id = "mxj", Scope = "I", Type = "L", ReferenceName = "Miju-Mishmi"},
                                 new {Id = "mxk", Scope = "I", Type = "L", ReferenceName = "Monumbo"},
                                 new {Id = "mxl", Scope = "I", Type = "L", ReferenceName = "Maxi Gbe"},
                                 new {Id = "mxm", Scope = "I", Type = "L", ReferenceName = "Meramera"},
                                 new {Id = "mxn", Scope = "I", Type = "L", ReferenceName = "Moi (Indonesia)"},
                                 new {Id = "mxo", Scope = "I", Type = "L", ReferenceName = "Mbowe"},
                                 new {Id = "mxp", Scope = "I", Type = "L", ReferenceName = "Tlahuitoltepec Mixe"},
                                 new {Id = "mxq", Scope = "I", Type = "L", ReferenceName = "Juquila Mixe"},
                                 new {Id = "mxr", Scope = "I", Type = "L", ReferenceName = "Murik (Malaysia)"},
                                 new {Id = "mxs", Scope = "I", Type = "L", ReferenceName = "Huitepec Mixtec"},
                                 new {Id = "mxt", Scope = "I", Type = "L", ReferenceName = "Jamiltepec Mixtec"},
                                 new {Id = "mxu", Scope = "I", Type = "L", ReferenceName = "Mada (Cameroon)"},
                                 new {Id = "mxv", Scope = "I", Type = "L", ReferenceName = "Metlatónoc Mixtec"},
                                 new {Id = "mxw", Scope = "I", Type = "L", ReferenceName = "Namo"},
                                 new {Id = "mxx", Scope = "I", Type = "L", ReferenceName = "Mahou"},
                                 new
                                 {
                                     Id            = "mxy",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Southeastern Nochixtlán Mixtec"
                                 }, new {Id = "mxz", Scope = "I", Type = "L", ReferenceName = "Central Masela"},
                                 new
                                 {
                                     Id            = "mya",
                                     Part2B        = "bur",
                                     Part2T        = "mya",
                                     Part1         = "my",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Burmese"
                                 }, new {Id = "myb", Scope = "I", Type = "L", ReferenceName = "Mbay"},
                                 new {Id    = "myc", Scope = "I", Type = "L", ReferenceName = "Mayeka"},
                                 new {Id    = "mye", Scope = "I", Type = "L", ReferenceName = "Myene"},
                                 new {Id    = "myf", Scope = "I", Type = "L", ReferenceName = "Bambassi"},
                                 new {Id    = "myg", Scope = "I", Type = "L", ReferenceName = "Manta"},
                                 new {Id    = "myh", Scope = "I", Type = "L", ReferenceName = "Makah"},
                                 new {Id    = "myj", Scope = "I", Type = "L", ReferenceName = "Mangayat"},
                                 new {Id    = "myk", Scope = "I", Type = "L", ReferenceName = "Mamara Senoufo"},
                                 new {Id    = "myl", Scope = "I", Type = "L", ReferenceName = "Moma"},
                                 new {Id    = "mym", Scope = "I", Type = "L", ReferenceName = "Me'en"},
                                 new {Id    = "myo", Scope = "I", Type = "L", ReferenceName = "Anfillo"},
                                 new {Id    = "myp", Scope = "I", Type = "L", ReferenceName = "Pirahã"},
                                 new {Id    = "myr", Scope = "I", Type = "L", ReferenceName = "Muniche"},
                                 new {Id    = "mys", Scope = "I", Type = "E", ReferenceName = "Mesmes"},
                                 new {Id    = "myu", Scope = "I", Type = "L", ReferenceName = "Mundurukú"},
                                 new
                                 {
                                     Id            = "myv",
                                     Part2B        = "myv",
                                     Part2T        = "myv",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Erzya"
                                 }, new {Id = "myw", Scope = "I", Type = "L", ReferenceName = "Muyuw"},
                                 new {Id    = "myx", Scope = "I", Type = "L", ReferenceName = "Masaaba"},
                                 new {Id    = "myy", Scope = "I", Type = "L", ReferenceName = "Macuna"},
                                 new {Id    = "myz", Scope = "I", Type = "H", ReferenceName = "Classical Mandaic"},
                                 new
                                 {
                                     Id            = "mza",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Santa María Zacatepec Mixtec"
                                 }, new {Id = "mzb", Scope = "I", Type = "L", ReferenceName = "Tumzabt"},
                                 new
                                     {
                                         Id            = "mzc",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Madagascar Sign Language"
                                     },
                                 new {Id = "mzd", Scope = "I", Type = "L", ReferenceName = "Malimba"},
                                 new {Id = "mze", Scope = "I", Type = "L", ReferenceName = "Morawa"},
                                 new
                                     {
                                         Id            = "mzg",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Monastic Sign Language"
                                     },
                                 new
                                     {
                                         Id            = "mzh",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Wichí Lhamtés Güisnay"
                                     },
                                 new {Id = "mzi", Scope = "I", Type = "L", ReferenceName = "Ixcatlán Mazatec"},
                                 new {Id = "mzj", Scope = "I", Type = "L", ReferenceName = "Manya"},
                                 new {Id = "mzk", Scope = "I", Type = "L", ReferenceName = "Nigeria Mambila"},
                                 new {Id = "mzl", Scope = "I", Type = "L", ReferenceName = "Mazatlán Mixe"},
                                 new {Id = "mzm", Scope = "I", Type = "L", ReferenceName = "Mumuye"},
                                 new {Id = "mzn", Scope = "I", Type = "L", ReferenceName = "Mazanderani"},
                                 new {Id = "mzo", Scope = "I", Type = "E", ReferenceName = "Matipuhy"},
                                 new {Id = "mzp", Scope = "I", Type = "L", ReferenceName = "Movima"},
                                 new {Id = "mzq", Scope = "I", Type = "L", ReferenceName = "Mori Atas"},
                                 new {Id = "mzr", Scope = "I", Type = "L", ReferenceName = "Marúbo"},
                                 new {Id = "mzs", Scope = "I", Type = "L", ReferenceName = "Macanese"},
                                 new {Id = "mzt", Scope = "I", Type = "L", ReferenceName = "Mintil"},
                                 new {Id = "mzu", Scope = "I", Type = "L", ReferenceName = "Inapang"},
                                 new {Id = "mzv", Scope = "I", Type = "L", ReferenceName = "Manza"},
                                 new {Id = "mzw", Scope = "I", Type = "L", ReferenceName = "Deg"},
                                 new {Id = "mzx", Scope = "I", Type = "L", ReferenceName = "Mawayana"},
                                 new
                                     {
                                         Id            = "mzy",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Mozambican Sign Language"
                                     },
                                 new {Id = "mzz", Scope = "I", Type = "L", ReferenceName = "Maiadomu"});
        }
    }
}