using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class N
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(new {Id = "naa", Scope = "I", Type = "L", ReferenceName = "Namla"},
                                 new {Id = "nab", Scope = "I", Type = "L", ReferenceName = "Southern Nambikuára"},
                                 new {Id = "nac", Scope = "I", Type = "L", ReferenceName = "Narak"},
                                 new {Id = "nae", Scope = "I", Type = "E", ReferenceName = "Naka'ela"},
                                 new {Id = "naf", Scope = "I", Type = "L", ReferenceName = "Nabak"},
                                 new {Id = "nag", Scope = "I", Type = "L", ReferenceName = "Naga Pidgin"},
                                 new {Id = "naj", Scope = "I", Type = "L", ReferenceName = "Nalu"},
                                 new {Id = "nak", Scope = "I", Type = "L", ReferenceName = "Nakanai"},
                                 new {Id = "nal", Scope = "I", Type = "L", ReferenceName = "Nalik"},
                                 new {Id = "nam", Scope = "I", Type = "L", ReferenceName = "Ngan'gityemerri"},
                                 new {Id = "nan", Scope = "I", Type = "L", ReferenceName = "Min Nan Chinese"},
                                 new {Id = "nao", Scope = "I", Type = "L", ReferenceName = "Naaba"},
                                 new
                                 {
                                     Id            = "nap",
                                     Part2B        = "nap",
                                     Part2T        = "nap",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Neapolitan"
                                 }, new {Id = "naq", Scope = "I", Type = "L", ReferenceName = "Khoekhoe"},
                                 new {Id    = "nar", Scope = "I", Type = "L", ReferenceName = "Iguta"},
                                 new {Id    = "nas", Scope = "I", Type = "L", ReferenceName = "Naasioi"},
                                 new {Id    = "nat", Scope = "I", Type = "L", ReferenceName = "Ca̱hungwa̱rya̱"},
                                 new
                                 {
                                     Id            = "nau",
                                     Part2B        = "nau",
                                     Part2T        = "nau",
                                     Part1         = "na",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Nauru"
                                 }, new
                                 {
                                     Id            = "nav",
                                     Part2B        = "nav",
                                     Part2T        = "nav",
                                     Part1         = "nv",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Navajo"
                                 }, new {Id = "naw", Scope = "I", Type = "L", ReferenceName = "Nawuri"},
                                 new {Id    = "nax", Scope = "I", Type = "L", ReferenceName = "Nakwi"},
                                 new {Id    = "nay", Scope = "I", Type = "E", ReferenceName = "Ngarrindjeri"},
                                 new {Id    = "naz", Scope = "I", Type = "L", ReferenceName = "Coatepec Nahuatl"},
                                 new {Id    = "nba", Scope = "I", Type = "L", ReferenceName = "Nyemba"},
                                 new {Id    = "nbb", Scope = "I", Type = "L", ReferenceName = "Ndoe"},
                                 new {Id    = "nbc", Scope = "I", Type = "L", ReferenceName = "Chang Naga"},
                                 new {Id    = "nbd", Scope = "I", Type = "L", ReferenceName = "Ngbinda"},
                                 new {Id    = "nbe", Scope = "I", Type = "L", ReferenceName = "Konyak Naga"},
                                 new {Id    = "nbg", Scope = "I", Type = "L", ReferenceName = "Nagarchal"},
                                 new {Id    = "nbh", Scope = "I", Type = "L", ReferenceName = "Ngamo"},
                                 new {Id    = "nbi", Scope = "I", Type = "L", ReferenceName = "Mao Naga"},
                                 new {Id    = "nbj", Scope = "I", Type = "L", ReferenceName = "Ngarinyman"},
                                 new {Id    = "nbk", Scope = "I", Type = "L", ReferenceName = "Nake"},
                                 new
                                 {
                                     Id            = "nbl",
                                     Part2B        = "nbl",
                                     Part2T        = "nbl",
                                     Part1         = "nr",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "South Ndebele"
                                 }, new {Id = "nbm", Scope = "I", Type = "L", ReferenceName = "Ngbaka Ma'bo"},
                                 new {Id    = "nbn", Scope = "I", Type = "L", ReferenceName = "Kuri"},
                                 new {Id    = "nbo", Scope = "I", Type = "L", ReferenceName = "Nkukoli"},
                                 new {Id    = "nbp", Scope = "I", Type = "L", ReferenceName = "Nnam"},
                                 new {Id    = "nbq", Scope = "I", Type = "L", ReferenceName = "Nggem"},
                                 new {Id    = "nbr", Scope = "I", Type = "L", ReferenceName = "Numana"},
                                 new {Id    = "nbs", Scope = "I", Type = "L", ReferenceName = "Namibian Sign Language"},
                                 new {Id    = "nbt", Scope = "I", Type = "L", ReferenceName = "Na"},
                                 new {Id    = "nbu", Scope = "I", Type = "L", ReferenceName = "Rongmei Naga"},
                                 new {Id    = "nbv", Scope = "I", Type = "L", ReferenceName = "Ngamambo"},
                                 new {Id    = "nbw", Scope = "I", Type = "L", ReferenceName = "Southern Ngbandi"},
                                 new {Id    = "nby", Scope = "I", Type = "L", ReferenceName = "Ningera"},
                                 new {Id    = "nca", Scope = "I", Type = "L", ReferenceName = "Iyo"},
                                 new {Id    = "ncb", Scope = "I", Type = "L", ReferenceName = "Central Nicobarese"},
                                 new {Id    = "ncc", Scope = "I", Type = "L", ReferenceName = "Ponam"},
                                 new {Id    = "ncd", Scope = "I", Type = "L", ReferenceName = "Nachering"},
                                 new {Id    = "nce", Scope = "I", Type = "L", ReferenceName = "Yale"},
                                 new {Id    = "ncf", Scope = "I", Type = "L", ReferenceName = "Notsi"},
                                 new {Id    = "ncg", Scope = "I", Type = "L", ReferenceName = "Nisga'a"},
                                 new
                                     {
                                         Id            = "nch",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Central Huasteca Nahuatl"
                                     },
                                 new {Id = "nci", Scope = "I", Type = "H", ReferenceName = "Classical Nahuatl"},
                                 new
                                     {
                                         Id            = "ncj",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Northern Puebla Nahuatl"
                                     },
                                 new {Id = "nck", Scope = "I", Type = "L", ReferenceName = "Na-kara"},
                                 new {Id = "ncl", Scope = "I", Type = "L", ReferenceName = "Michoacán Nahuatl"},
                                 new {Id = "ncm", Scope = "I", Type = "L", ReferenceName = "Nambo"},
                                 new {Id = "ncn", Scope = "I", Type = "L", ReferenceName = "Nauna"},
                                 new {Id = "nco", Scope = "I", Type = "L", ReferenceName = "Sibe"},
                                 new {Id = "ncq", Scope = "I", Type = "L", ReferenceName = "Northern Katang"},
                                 new {Id = "ncr", Scope = "I", Type = "L", ReferenceName = "Ncane"},
                                 new
                                     {
                                         Id            = "ncs",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Nicaraguan Sign Language"
                                     },
                                 new {Id = "nct", Scope = "I", Type = "L", ReferenceName = "Chothe Naga"},
                                 new {Id = "ncu", Scope = "I", Type = "L", ReferenceName = "Chumburung"},
                                 new {Id = "ncx", Scope = "I", Type = "L", ReferenceName = "Central Puebla Nahuatl"},
                                 new {Id = "ncz", Scope = "I", Type = "E", ReferenceName = "Natchez"},
                                 new {Id = "nda", Scope = "I", Type = "L", ReferenceName = "Ndasa"},
                                 new {Id = "ndb", Scope = "I", Type = "L", ReferenceName = "Kenswei Nsei"},
                                 new {Id = "ndc", Scope = "I", Type = "L", ReferenceName = "Ndau"},
                                 new {Id = "ndd", Scope = "I", Type = "L", ReferenceName = "Nde-Nsele-Nta"},
                                 new
                                 {
                                     Id            = "nde",
                                     Part2B        = "nde",
                                     Part2T        = "nde",
                                     Part1         = "nd",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "North Ndebele"
                                 }, new {Id = "ndf", Scope = "I", Type = "H", ReferenceName = "Nadruvian"},
                                 new {Id    = "ndg", Scope = "I", Type = "L", ReferenceName = "Ndengereko"},
                                 new {Id    = "ndh", Scope = "I", Type = "L", ReferenceName = "Ndali"},
                                 new {Id    = "ndi", Scope = "I", Type = "L", ReferenceName = "Samba Leko"},
                                 new {Id    = "ndj", Scope = "I", Type = "L", ReferenceName = "Ndamba"},
                                 new {Id    = "ndk", Scope = "I", Type = "L", ReferenceName = "Ndaka"},
                                 new {Id    = "ndl", Scope = "I", Type = "L", ReferenceName = "Ndolo"},
                                 new {Id    = "ndm", Scope = "I", Type = "L", ReferenceName = "Ndam"},
                                 new {Id    = "ndn", Scope = "I", Type = "L", ReferenceName = "Ngundi"},
                                 new
                                 {
                                     Id            = "ndo",
                                     Part2B        = "ndo",
                                     Part2T        = "ndo",
                                     Part1         = "ng",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Ndonga"
                                 }, new {Id = "ndp", Scope = "I", Type = "L", ReferenceName = "Ndo"},
                                 new {Id    = "ndq", Scope = "I", Type = "L", ReferenceName = "Ndombe"},
                                 new {Id    = "ndr", Scope = "I", Type = "L", ReferenceName = "Ndoola"},
                                 new
                                 {
                                     Id            = "nds",
                                     Part2B        = "nds",
                                     Part2T        = "nds",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Low German"
                                 }, new {Id = "ndt", Scope = "I", Type = "L", ReferenceName = "Ndunga"},
                                 new {Id    = "ndu", Scope = "I", Type = "L", ReferenceName = "Dugun"},
                                 new {Id    = "ndv", Scope = "I", Type = "L", ReferenceName = "Ndut"},
                                 new {Id    = "ndw", Scope = "I", Type = "L", ReferenceName = "Ndobo"},
                                 new {Id    = "ndx", Scope = "I", Type = "L", ReferenceName = "Nduga"},
                                 new {Id    = "ndy", Scope = "I", Type = "L", ReferenceName = "Lutos"},
                                 new {Id    = "ndz", Scope = "I", Type = "L", ReferenceName = "Ndogo"},
                                 new {Id    = "nea", Scope = "I", Type = "L", ReferenceName = "Eastern Ngad'a"},
                                 new {Id    = "neb", Scope = "I", Type = "L", ReferenceName = "Toura (Côte d'Ivoire)"},
                                 new {Id    = "nec", Scope = "I", Type = "L", ReferenceName = "Nedebang"},
                                 new {Id    = "ned", Scope = "I", Type = "L", ReferenceName = "Nde-Gbite"},
                                 new {Id    = "nee", Scope = "I", Type = "L", ReferenceName = "Nêlêmwa-Nixumwak"},
                                 new {Id    = "nef", Scope = "I", Type = "L", ReferenceName = "Nefamese"},
                                 new {Id    = "neg", Scope = "I", Type = "L", ReferenceName = "Negidal"},
                                 new {Id    = "neh", Scope = "I", Type = "L", ReferenceName = "Nyenkha"},
                                 new {Id    = "nei", Scope = "I", Type = "A", ReferenceName = "Neo-Hittite"},
                                 new {Id    = "nej", Scope = "I", Type = "L", ReferenceName = "Neko"},
                                 new {Id    = "nek", Scope = "I", Type = "L", ReferenceName = "Neku"},
                                 new {Id    = "nem", Scope = "I", Type = "L", ReferenceName = "Nemi"},
                                 new {Id    = "nen", Scope = "I", Type = "L", ReferenceName = "Nengone"},
                                 new {Id    = "neo", Scope = "I", Type = "L", ReferenceName = "Ná-Meo"},
                                 new
                                 {
                                     Id            = "nep",
                                     Part2B        = "nep",
                                     Part2T        = "nep",
                                     Part1         = "ne",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Nepali (macrolanguage)"
                                 }, new {Id = "neq", Scope = "I", Type = "L", ReferenceName = "North Central Mixe"},
                                 new {Id    = "ner", Scope = "I", Type = "L", ReferenceName = "Yahadian"},
                                 new {Id    = "nes", Scope = "I", Type = "L", ReferenceName = "Bhoti Kinnauri"},
                                 new {Id    = "net", Scope = "I", Type = "L", ReferenceName = "Nete"},
                                 new {Id    = "neu", Scope = "I", Type = "C", ReferenceName = "Neo"},
                                 new {Id    = "nev", Scope = "I", Type = "L", ReferenceName = "Nyaheun"},
                                 new
                                 {
                                     Id            = "new",
                                     Part2B        = "new",
                                     Part2T        = "new",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Newari"
                                 }, new {Id = "nex", Scope = "I", Type = "L", ReferenceName = "Neme"},
                                 new {Id    = "ney", Scope = "I", Type = "L", ReferenceName = "Neyo"},
                                 new {Id    = "nez", Scope = "I", Type = "L", ReferenceName = "Nez Perce"},
                                 new {Id    = "nfa", Scope = "I", Type = "L", ReferenceName = "Dhao"},
                                 new {Id    = "nfd", Scope = "I", Type = "L", ReferenceName = "Ahwai"},
                                 new {Id    = "nfl", Scope = "I", Type = "L", ReferenceName = "Ayiwo"},
                                 new {Id    = "nfr", Scope = "I", Type = "L", ReferenceName = "Nafaanra"},
                                 new {Id    = "nfu", Scope = "I", Type = "L", ReferenceName = "Mfumte"},
                                 new {Id    = "nga", Scope = "I", Type = "L", ReferenceName = "Ngbaka"},
                                 new {Id    = "ngb", Scope = "I", Type = "L", ReferenceName = "Northern Ngbandi"},
                                 new
                                 {
                                     Id            = "ngc",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Ngombe (Democratic Republic of Congo)"
                                 },
                                 new
                                 {
                                     Id            = "ngd",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Ngando (Central African Republic)"
                                 }, new {Id = "nge", Scope = "I", Type = "L", ReferenceName = "Ngemba"},
                                 new {Id    = "ngg", Scope = "I", Type = "L", ReferenceName = "Ngbaka Manza"},
                                 new {Id    = "ngh", Scope = "I", Type = "L", ReferenceName = "Nǁng"},
                                 new {Id    = "ngi", Scope = "I", Type = "L", ReferenceName = "Ngizim"},
                                 new {Id    = "ngj", Scope = "I", Type = "L", ReferenceName = "Ngie"},
                                 new {Id    = "ngk", Scope = "I", Type = "L", ReferenceName = "Dalabon"},
                                 new {Id    = "ngl", Scope = "I", Type = "L", ReferenceName = "Lomwe"},
                                 new
                                     {
                                         Id            = "ngm",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Ngatik Men's Creole"
                                     },
                                 new {Id = "ngn", Scope = "I", Type = "L", ReferenceName = "Ngwo"},
                                 new {Id = "ngo", Scope = "I", Type = "L", ReferenceName = "Ngoni"},
                                 new {Id = "ngp", Scope = "I", Type = "L", ReferenceName = "Ngulu"},
                                 new {Id = "ngq", Scope = "I", Type = "L", ReferenceName = "Ngurimi"},
                                 new {Id = "ngr", Scope = "I", Type = "L", ReferenceName = "Engdewu"},
                                 new {Id = "ngs", Scope = "I", Type = "L", ReferenceName = "Gvoko"},
                                 new {Id = "ngt", Scope = "I", Type = "L", ReferenceName = "Kriang"},
                                 new {Id = "ngu", Scope = "I", Type = "L", ReferenceName = "Guerrero Nahuatl"},
                                 new {Id = "ngv", Scope = "I", Type = "E", ReferenceName = "Nagumi"},
                                 new {Id = "ngw", Scope = "I", Type = "L", ReferenceName = "Ngwaba"},
                                 new {Id = "ngx", Scope = "I", Type = "L", ReferenceName = "Nggwahyi"},
                                 new {Id = "ngy", Scope = "I", Type = "L", ReferenceName = "Tibea"},
                                 new {Id = "ngz", Scope = "I", Type = "L", ReferenceName = "Ngungwel"},
                                 new {Id = "nha", Scope = "I", Type = "L", ReferenceName = "Nhanda"},
                                 new {Id = "nhb", Scope = "I", Type = "L", ReferenceName = "Beng"},
                                 new {Id = "nhc", Scope = "I", Type = "E", ReferenceName = "Tabasco Nahuatl"},
                                 new {Id = "nhd", Scope = "I", Type = "L", ReferenceName = "Chiripá"},
                                 new
                                     {
                                         Id            = "nhe",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Eastern Huasteca Nahuatl"
                                     },
                                 new {Id = "nhf", Scope = "I", Type = "L", ReferenceName = "Nhuwala"},
                                 new {Id = "nhg", Scope = "I", Type = "L", ReferenceName = "Tetelcingo Nahuatl"},
                                 new {Id = "nhh", Scope = "I", Type = "L", ReferenceName = "Nahari"},
                                 new
                                 {
                                     Id            = "nhi",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Zacatlán-Ahuacatlán-Tepetzintla Nahuatl"
                                 },
                                 new
                                 {
                                     Id            = "nhk",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Isthmus-Cosoleacaque Nahuatl"
                                 }, new {Id = "nhm", Scope = "I", Type = "L", ReferenceName = "Morelos Nahuatl"},
                                 new {Id    = "nhn", Scope = "I", Type = "L", ReferenceName = "Central Nahuatl"},
                                 new {Id    = "nho", Scope = "I", Type = "L", ReferenceName = "Takuu"},
                                 new
                                     {
                                         Id            = "nhp",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Isthmus-Pajapan Nahuatl"
                                     },
                                 new {Id = "nhq", Scope = "I", Type = "L", ReferenceName = "Huaxcaleca Nahuatl"},
                                 new {Id = "nhr", Scope = "I", Type = "L", ReferenceName = "Naro"},
                                 new {Id = "nht", Scope = "I", Type = "L", ReferenceName = "Ometepec Nahuatl"},
                                 new {Id = "nhu", Scope = "I", Type = "L", ReferenceName = "Noone"},
                                 new
                                     {
                                         Id            = "nhv",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Temascaltepec Nahuatl"
                                     },
                                 new
                                     {
                                         Id            = "nhw",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Western Huasteca Nahuatl"
                                     },
                                 new
                                     {
                                         Id            = "nhx",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Isthmus-Mecayapan Nahuatl"
                                     },
                                 new
                                     {
                                         Id            = "nhy",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Northern Oaxaca Nahuatl"
                                     },
                                 new
                                 {
                                     Id            = "nhz",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Santa María La Alta Nahuatl"
                                 }, new
                                 {
                                     Id            = "nia",
                                     Part2B        = "nia",
                                     Part2T        = "nia",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Nias"
                                 }, new {Id = "nib", Scope = "I", Type = "L", ReferenceName = "Nakame"},
                                 new {Id    = "nid", Scope = "I", Type = "E", ReferenceName = "Ngandi"},
                                 new {Id    = "nie", Scope = "I", Type = "L", ReferenceName = "Niellim"},
                                 new {Id    = "nif", Scope = "I", Type = "L", ReferenceName = "Nek"},
                                 new {Id    = "nig", Scope = "I", Type = "E", ReferenceName = "Ngalakgan"},
                                 new {Id    = "nih", Scope = "I", Type = "L", ReferenceName = "Nyiha (Tanzania)"},
                                 new {Id    = "nii", Scope = "I", Type = "L", ReferenceName = "Nii"},
                                 new {Id    = "nij", Scope = "I", Type = "L", ReferenceName = "Ngaju"},
                                 new {Id    = "nik", Scope = "I", Type = "L", ReferenceName = "Southern Nicobarese"},
                                 new {Id    = "nil", Scope = "I", Type = "L", ReferenceName = "Nila"},
                                 new {Id    = "nim", Scope = "I", Type = "L", ReferenceName = "Nilamba"},
                                 new {Id    = "nin", Scope = "I", Type = "L", ReferenceName = "Ninzo"},
                                 new {Id    = "nio", Scope = "I", Type = "L", ReferenceName = "Nganasan"},
                                 new {Id    = "niq", Scope = "I", Type = "L", ReferenceName = "Nandi"},
                                 new {Id    = "nir", Scope = "I", Type = "L", ReferenceName = "Nimboran"},
                                 new {Id    = "nis", Scope = "I", Type = "L", ReferenceName = "Nimi"},
                                 new {Id    = "nit", Scope = "I", Type = "L", ReferenceName = "Southeastern Kolami"},
                                 new
                                 {
                                     Id            = "niu",
                                     Part2B        = "niu",
                                     Part2T        = "niu",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Niuean"
                                 }, new {Id = "niv", Scope = "I", Type = "L", ReferenceName = "Gilyak"},
                                 new {Id    = "niw", Scope = "I", Type = "L", ReferenceName = "Nimo"},
                                 new {Id    = "nix", Scope = "I", Type = "L", ReferenceName = "Hema"},
                                 new {Id    = "niy", Scope = "I", Type = "L", ReferenceName = "Ngiti"},
                                 new {Id    = "niz", Scope = "I", Type = "L", ReferenceName = "Ningil"},
                                 new {Id    = "nja", Scope = "I", Type = "L", ReferenceName = "Nzanyi"},
                                 new {Id    = "njb", Scope = "I", Type = "L", ReferenceName = "Nocte Naga"},
                                 new {Id    = "njd", Scope = "I", Type = "L", ReferenceName = "Ndonde Hamba"},
                                 new {Id    = "njh", Scope = "I", Type = "L", ReferenceName = "Lotha Naga"},
                                 new {Id    = "nji", Scope = "I", Type = "L", ReferenceName = "Gudanji"},
                                 new {Id    = "njj", Scope = "I", Type = "L", ReferenceName = "Njen"},
                                 new {Id    = "njl", Scope = "I", Type = "L", ReferenceName = "Njalgulgule"},
                                 new {Id    = "njm", Scope = "I", Type = "L", ReferenceName = "Angami Naga"},
                                 new {Id    = "njn", Scope = "I", Type = "L", ReferenceName = "Liangmai Naga"},
                                 new {Id    = "njo", Scope = "I", Type = "L", ReferenceName = "Ao Naga"},
                                 new {Id    = "njr", Scope = "I", Type = "L", ReferenceName = "Njerep"},
                                 new {Id    = "njs", Scope = "I", Type = "L", ReferenceName = "Nisa"},
                                 new {Id    = "njt", Scope = "I", Type = "L", ReferenceName = "Ndyuka-Trio Pidgin"},
                                 new {Id    = "nju", Scope = "I", Type = "L", ReferenceName = "Ngadjunmaya"},
                                 new {Id    = "njx", Scope = "I", Type = "L", ReferenceName = "Kunyi"},
                                 new {Id    = "njy", Scope = "I", Type = "L", ReferenceName = "Njyem"},
                                 new {Id    = "njz", Scope = "I", Type = "L", ReferenceName = "Nyishi"},
                                 new {Id    = "nka", Scope = "I", Type = "L", ReferenceName = "Nkoya"},
                                 new {Id    = "nkb", Scope = "I", Type = "L", ReferenceName = "Khoibu Naga"},
                                 new {Id    = "nkc", Scope = "I", Type = "L", ReferenceName = "Nkongho"},
                                 new {Id    = "nkd", Scope = "I", Type = "L", ReferenceName = "Koireng"},
                                 new {Id    = "nke", Scope = "I", Type = "L", ReferenceName = "Duke"},
                                 new {Id    = "nkf", Scope = "I", Type = "L", ReferenceName = "Inpui Naga"},
                                 new {Id    = "nkg", Scope = "I", Type = "L", ReferenceName = "Nekgini"},
                                 new {Id    = "nkh", Scope = "I", Type = "L", ReferenceName = "Khezha Naga"},
                                 new {Id    = "nki", Scope = "I", Type = "L", ReferenceName = "Thangal Naga"},
                                 new {Id    = "nkj", Scope = "I", Type = "L", ReferenceName = "Nakai"},
                                 new {Id    = "nkk", Scope = "I", Type = "L", ReferenceName = "Nokuku"},
                                 new {Id    = "nkm", Scope = "I", Type = "L", ReferenceName = "Namat"},
                                 new {Id    = "nkn", Scope = "I", Type = "L", ReferenceName = "Nkangala"},
                                 new {Id    = "nko", Scope = "I", Type = "L", ReferenceName = "Nkonya"},
                                 new {Id    = "nkp", Scope = "I", Type = "E", ReferenceName = "Niuatoputapu"},
                                 new {Id    = "nkq", Scope = "I", Type = "L", ReferenceName = "Nkami"},
                                 new {Id    = "nkr", Scope = "I", Type = "L", ReferenceName = "Nukuoro"},
                                 new {Id    = "nks", Scope = "I", Type = "L", ReferenceName = "North Asmat"},
                                 new {Id    = "nkt", Scope = "I", Type = "L", ReferenceName = "Nyika (Tanzania)"},
                                 new {Id    = "nku", Scope = "I", Type = "L", ReferenceName = "Bouna Kulango"},
                                 new
                                     {
                                         Id            = "nkv",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Nyika (Malawi and Zambia)"
                                     },
                                 new {Id = "nkw", Scope = "I", Type = "L", ReferenceName = "Nkutu"},
                                 new {Id = "nkx", Scope = "I", Type = "L", ReferenceName = "Nkoroo"},
                                 new {Id = "nkz", Scope = "I", Type = "L", ReferenceName = "Nkari"},
                                 new {Id = "nla", Scope = "I", Type = "L", ReferenceName = "Ngombale"},
                                 new {Id = "nlc", Scope = "I", Type = "L", ReferenceName = "Nalca"},
                                 new
                                 {
                                     Id            = "nld",
                                     Part2B        = "dut",
                                     Part2T        = "nld",
                                     Part1         = "nl",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Dutch"
                                 }, new {Id = "nle", Scope = "I", Type = "L", ReferenceName = "East Nyala"},
                                 new {Id    = "nlg", Scope = "I", Type = "L", ReferenceName = "Gela"},
                                 new {Id    = "nli", Scope = "I", Type = "L", ReferenceName = "Grangali"},
                                 new {Id    = "nlj", Scope = "I", Type = "L", ReferenceName = "Nyali"},
                                 new {Id    = "nlk", Scope = "I", Type = "L", ReferenceName = "Ninia Yali"},
                                 new {Id    = "nll", Scope = "I", Type = "L", ReferenceName = "Nihali"},
                                 new {Id    = "nlm", Scope = "I", Type = "L", ReferenceName = "Mankiyali"},
                                 new {Id    = "nlo", Scope = "I", Type = "L", ReferenceName = "Ngul"},
                                 new {Id    = "nlq", Scope = "I", Type = "L", ReferenceName = "Lao Naga"},
                                 new {Id    = "nlu", Scope = "I", Type = "L", ReferenceName = "Nchumbulu"},
                                 new {Id    = "nlv", Scope = "I", Type = "L", ReferenceName = "Orizaba Nahuatl"},
                                 new {Id    = "nlw", Scope = "I", Type = "E", ReferenceName = "Walangama"},
                                 new {Id    = "nlx", Scope = "I", Type = "L", ReferenceName = "Nahali"},
                                 new {Id    = "nly", Scope = "I", Type = "L", ReferenceName = "Nyamal"},
                                 new {Id    = "nlz", Scope = "I", Type = "L", ReferenceName = "Nalögo"},
                                 new {Id    = "nma", Scope = "I", Type = "L", ReferenceName = "Maram Naga"},
                                 new {Id    = "nmb", Scope = "I", Type = "L", ReferenceName = "Big Nambas"},
                                 new {Id    = "nmc", Scope = "I", Type = "L", ReferenceName = "Ngam"},
                                 new {Id    = "nmd", Scope = "I", Type = "L", ReferenceName = "Ndumu"},
                                 new {Id    = "nme", Scope = "I", Type = "L", ReferenceName = "Mzieme Naga"},
                                 new {Id    = "nmf", Scope = "I", Type = "L", ReferenceName = "Tangkhul Naga (India)"},
                                 new {Id    = "nmg", Scope = "I", Type = "L", ReferenceName = "Kwasio"},
                                 new {Id    = "nmh", Scope = "I", Type = "L", ReferenceName = "Monsang Naga"},
                                 new {Id    = "nmi", Scope = "I", Type = "L", ReferenceName = "Nyam"},
                                 new
                                 {
                                     Id            = "nmj",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Ngombe (Central African Republic)"
                                 }, new {Id = "nmk", Scope = "I", Type = "L", ReferenceName = "Namakura"},
                                 new {Id    = "nml", Scope = "I", Type = "L", ReferenceName = "Ndemli"},
                                 new {Id    = "nmm", Scope = "I", Type = "L", ReferenceName = "Manangba"},
                                 new {Id    = "nmn", Scope = "I", Type = "L", ReferenceName = "ǃXóõ"},
                                 new {Id    = "nmo", Scope = "I", Type = "L", ReferenceName = "Moyon Naga"},
                                 new {Id    = "nmp", Scope = "I", Type = "E", ReferenceName = "Nimanbur"},
                                 new {Id    = "nmq", Scope = "I", Type = "L", ReferenceName = "Nambya"},
                                 new {Id    = "nmr", Scope = "I", Type = "E", ReferenceName = "Nimbari"},
                                 new {Id    = "nms", Scope = "I", Type = "L", ReferenceName = "Letemboi"},
                                 new {Id    = "nmt", Scope = "I", Type = "L", ReferenceName = "Namonuito"},
                                 new {Id    = "nmu", Scope = "I", Type = "L", ReferenceName = "Northeast Maidu"},
                                 new {Id    = "nmv", Scope = "I", Type = "E", ReferenceName = "Ngamini"},
                                 new {Id    = "nmw", Scope = "I", Type = "L", ReferenceName = "Nimoa"},
                                 new
                                     {
                                         Id            = "nmx",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Nama (Papua New Guinea)"
                                     },
                                 new {Id = "nmy", Scope = "I", Type = "L", ReferenceName = "Namuyi"},
                                 new {Id = "nmz", Scope = "I", Type = "L", ReferenceName = "Nawdm"},
                                 new {Id = "nna", Scope = "I", Type = "L", ReferenceName = "Nyangumarta"},
                                 new {Id = "nnb", Scope = "I", Type = "L", ReferenceName = "Nande"},
                                 new {Id = "nnc", Scope = "I", Type = "L", ReferenceName = "Nancere"},
                                 new {Id = "nnd", Scope = "I", Type = "L", ReferenceName = "West Ambae"},
                                 new {Id = "nne", Scope = "I", Type = "L", ReferenceName = "Ngandyera"},
                                 new {Id = "nnf", Scope = "I", Type = "L", ReferenceName = "Ngaing"},
                                 new {Id = "nng", Scope = "I", Type = "L", ReferenceName = "Maring Naga"},
                                 new {Id = "nnh", Scope = "I", Type = "L", ReferenceName = "Ngiemboon"},
                                 new {Id = "nni", Scope = "I", Type = "L", ReferenceName = "North Nuaulu"},
                                 new {Id = "nnj", Scope = "I", Type = "L", ReferenceName = "Nyangatom"},
                                 new {Id = "nnk", Scope = "I", Type = "L", ReferenceName = "Nankina"},
                                 new
                                     {
                                         Id            = "nnl",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Northern Rengma Naga"
                                     },
                                 new {Id = "nnm", Scope = "I", Type = "L", ReferenceName = "Namia"},
                                 new {Id = "nnn", Scope = "I", Type = "L", ReferenceName = "Ngete"},
                                 new
                                 {
                                     Id            = "nno",
                                     Part2B        = "nno",
                                     Part2T        = "nno",
                                     Part1         = "nn",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Norwegian Nynorsk"
                                 }, new {Id = "nnp", Scope = "I", Type = "L", ReferenceName = "Wancho Naga"},
                                 new {Id    = "nnq", Scope = "I", Type = "L", ReferenceName = "Ngindo"},
                                 new {Id    = "nnr", Scope = "I", Type = "E", ReferenceName = "Narungga"},
                                 new {Id    = "nnt", Scope = "I", Type = "E", ReferenceName = "Nanticoke"},
                                 new {Id    = "nnu", Scope = "I", Type = "L", ReferenceName = "Dwang"},
                                 new {Id    = "nnv", Scope = "I", Type = "E", ReferenceName = "Nugunu (Australia)"},
                                 new {Id    = "nnw", Scope = "I", Type = "L", ReferenceName = "Southern Nuni"},
                                 new {Id    = "nny", Scope = "I", Type = "E", ReferenceName = "Nyangga"},
                                 new {Id    = "nnz", Scope = "I", Type = "L", ReferenceName = "Nda'nda'"},
                                 new {Id    = "noa", Scope = "I", Type = "L", ReferenceName = "Woun Meu"},
                                 new
                                 {
                                     Id            = "nob",
                                     Part2B        = "nob",
                                     Part2T        = "nob",
                                     Part1         = "nb",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Norwegian Bokmål"
                                 }, new {Id = "noc", Scope = "I", Type = "L", ReferenceName = "Nuk"},
                                 new {Id    = "nod", Scope = "I", Type = "L", ReferenceName = "Northern Thai"},
                                 new {Id    = "noe", Scope = "I", Type = "L", ReferenceName = "Nimadi"},
                                 new {Id    = "nof", Scope = "I", Type = "L", ReferenceName = "Nomane"},
                                 new
                                 {
                                     Id            = "nog",
                                     Part2B        = "nog",
                                     Part2T        = "nog",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Nogai"
                                 }, new {Id = "noh", Scope = "I", Type = "L", ReferenceName = "Nomu"},
                                 new {Id    = "noi", Scope = "I", Type = "L", ReferenceName = "Noiri"},
                                 new {Id    = "noj", Scope = "I", Type = "L", ReferenceName = "Nonuya"},
                                 new {Id    = "nok", Scope = "I", Type = "E", ReferenceName = "Nooksack"},
                                 new {Id    = "nol", Scope = "I", Type = "E", ReferenceName = "Nomlaki"},
                                 new {Id    = "nom", Scope = "I", Type = "E", ReferenceName = "Nocamán"},
                                 new
                                 {
                                     Id            = "non",
                                     Part2B        = "non",
                                     Part2T        = "non",
                                     Scope         = "I",
                                     Type          = "H",
                                     ReferenceName = "Old Norse"
                                 }, new {Id = "nop", Scope = "I", Type = "L", ReferenceName = "Numanggang"},
                                 new {Id    = "noq", Scope = "I", Type = "L", ReferenceName = "Ngongo"},
                                 new
                                 {
                                     Id            = "nor",
                                     Part2B        = "nor",
                                     Part2T        = "nor",
                                     Part1         = "no",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Norwegian"
                                 }, new {Id = "nos", Scope = "I", Type = "L", ReferenceName = "Eastern Nisu"},
                                 new {Id    = "not", Scope = "I", Type = "L", ReferenceName = "Nomatsiguenga"},
                                 new {Id    = "nou", Scope = "I", Type = "L", ReferenceName = "Ewage-Notu"},
                                 new {Id    = "nov", Scope = "I", Type = "C", ReferenceName = "Novial"},
                                 new {Id    = "now", Scope = "I", Type = "L", ReferenceName = "Nyambo"},
                                 new {Id    = "noy", Scope = "I", Type = "L", ReferenceName = "Noy"},
                                 new {Id    = "noz", Scope = "I", Type = "L", ReferenceName = "Nayi"},
                                 new {Id    = "npa", Scope = "I", Type = "L", ReferenceName = "Nar Phu"},
                                 new {Id    = "npb", Scope = "I", Type = "L", ReferenceName = "Nupbikha"},
                                 new {Id    = "npg", Scope = "I", Type = "L", ReferenceName = "Ponyo-Gongwang Naga"},
                                 new {Id    = "nph", Scope = "I", Type = "L", ReferenceName = "Phom Naga"},
                                 new
                                 {
                                     Id            = "npi",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Nepali (individual language)"
                                 },
                                 new
                                 {
                                     Id            = "npl",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Southeastern Puebla Nahuatl"
                                 }, new {Id = "npn", Scope = "I", Type = "L", ReferenceName = "Mondropolon"},
                                 new {Id    = "npo", Scope = "I", Type = "L", ReferenceName = "Pochuri Naga"},
                                 new {Id    = "nps", Scope = "I", Type = "L", ReferenceName = "Nipsan"},
                                 new {Id    = "npu", Scope = "I", Type = "L", ReferenceName = "Puimei Naga"},
                                 new {Id    = "npx", Scope = "I", Type = "L", ReferenceName = "Noipx"},
                                 new {Id    = "npy", Scope = "I", Type = "L", ReferenceName = "Napu"},
                                 new {Id    = "nqg", Scope = "I", Type = "L", ReferenceName = "Southern Nago"},
                                 new {Id    = "nqk", Scope = "I", Type = "L", ReferenceName = "Kura Ede Nago"},
                                 new {Id    = "nql", Scope = "I", Type = "L", ReferenceName = "Ngendelengo"},
                                 new {Id    = "nqm", Scope = "I", Type = "L", ReferenceName = "Ndom"},
                                 new {Id    = "nqn", Scope = "I", Type = "L", ReferenceName = "Nen"},
                                 new
                                 {
                                     Id            = "nqo",
                                     Part2B        = "nqo",
                                     Part2T        = "nqo",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "N'Ko"
                                 }, new {Id = "nqq", Scope = "I", Type = "L", ReferenceName = "Kyan-Karyaw Naga"},
                                 new {Id    = "nqy", Scope = "I", Type = "L", ReferenceName = "Akyaung Ari Naga"},
                                 new {Id    = "nra", Scope = "I", Type = "L", ReferenceName = "Ngom"},
                                 new {Id    = "nrb", Scope = "I", Type = "L", ReferenceName = "Nara"},
                                 new {Id    = "nrc", Scope = "I", Type = "A", ReferenceName = "Noric"},
                                 new {Id    = "nre", Scope = "I", Type = "L", ReferenceName = "Southern Rengma Naga"},
                                 new {Id    = "nrf", Scope = "I", Type = "L", ReferenceName = "Jèrriais"},
                                 new {Id    = "nrg", Scope = "I", Type = "L", ReferenceName = "Narango"},
                                 new {Id    = "nri", Scope = "I", Type = "L", ReferenceName = "Chokri Naga"},
                                 new {Id    = "nrk", Scope = "I", Type = "L", ReferenceName = "Ngarla"},
                                 new {Id    = "nrl", Scope = "I", Type = "L", ReferenceName = "Ngarluma"},
                                 new {Id    = "nrm", Scope = "I", Type = "L", ReferenceName = "Narom"},
                                 new {Id    = "nrn", Scope = "I", Type = "E", ReferenceName = "Norn"},
                                 new {Id    = "nrp", Scope = "I", Type = "A", ReferenceName = "North Picene"},
                                 new {Id    = "nrr", Scope = "I", Type = "E", ReferenceName = "Norra"},
                                 new {Id    = "nrt", Scope = "I", Type = "E", ReferenceName = "Northern Kalapuya"},
                                 new {Id    = "nru", Scope = "I", Type = "L", ReferenceName = "Narua"},
                                 new {Id    = "nrx", Scope = "I", Type = "E", ReferenceName = "Ngurmbur"},
                                 new {Id    = "nrz", Scope = "I", Type = "L", ReferenceName = "Lala"},
                                 new {Id    = "nsa", Scope = "I", Type = "L", ReferenceName = "Sangtam Naga"},
                                 new {Id    = "nsc", Scope = "I", Type = "L", ReferenceName = "Nshi"},
                                 new {Id    = "nsd", Scope = "I", Type = "L", ReferenceName = "Southern Nisu"},
                                 new {Id    = "nse", Scope = "I", Type = "L", ReferenceName = "Nsenga"},
                                 new {Id    = "nsf", Scope = "I", Type = "L", ReferenceName = "Northwestern Nisu"},
                                 new {Id    = "nsg", Scope = "I", Type = "L", ReferenceName = "Ngasa"},
                                 new {Id    = "nsh", Scope = "I", Type = "L", ReferenceName = "Ngoshie"},
                                 new {Id    = "nsi", Scope = "I", Type = "L", ReferenceName = "Nigerian Sign Language"},
                                 new {Id    = "nsk", Scope = "I", Type = "L", ReferenceName = "Naskapi"},
                                 new
                                     {
                                         Id            = "nsl",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Norwegian Sign Language"
                                     },
                                 new {Id = "nsm", Scope = "I", Type = "L", ReferenceName = "Sumi Naga"},
                                 new {Id = "nsn", Scope = "I", Type = "L", ReferenceName = "Nehan"},
                                 new
                                 {
                                     Id            = "nso",
                                     Part2B        = "nso",
                                     Part2T        = "nso",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Pedi"
                                 }, new {Id = "nsp", Scope = "I", Type = "L", ReferenceName = "Nepalese Sign Language"},
                                 new {Id    = "nsq", Scope = "I", Type = "L", ReferenceName = "Northern Sierra Miwok"},
                                 new {Id    = "nsr", Scope = "I", Type = "L", ReferenceName = "Maritime Sign Language"},
                                 new {Id    = "nss", Scope = "I", Type = "L", ReferenceName = "Nali"},
                                 new {Id    = "nst", Scope = "I", Type = "L", ReferenceName = "Tase Naga"},
                                 new {Id    = "nsu", Scope = "I", Type = "L", ReferenceName = "Sierra Negra Nahuatl"},
                                 new {Id    = "nsv", Scope = "I", Type = "L", ReferenceName = "Southwestern Nisu"},
                                 new {Id    = "nsw", Scope = "I", Type = "L", ReferenceName = "Navut"},
                                 new {Id    = "nsx", Scope = "I", Type = "L", ReferenceName = "Nsongo"},
                                 new {Id    = "nsy", Scope = "I", Type = "L", ReferenceName = "Nasal"},
                                 new {Id    = "nsz", Scope = "I", Type = "L", ReferenceName = "Nisenan"},
                                 new {Id    = "ntd", Scope = "I", Type = "L", ReferenceName = "Northern Tidung"},
                                 new {Id    = "nte", Scope = "I", Type = "L", ReferenceName = "Nathembo"},
                                 new {Id    = "ntg", Scope = "I", Type = "E", ReferenceName = "Ngantangarra"},
                                 new {Id    = "nti", Scope = "I", Type = "L", ReferenceName = "Natioro"},
                                 new {Id    = "ntj", Scope = "I", Type = "L", ReferenceName = "Ngaanyatjarra"},
                                 new {Id    = "ntk", Scope = "I", Type = "L", ReferenceName = "Ikoma-Nata-Isenye"},
                                 new {Id    = "ntm", Scope = "I", Type = "L", ReferenceName = "Nateni"},
                                 new {Id    = "nto", Scope = "I", Type = "L", ReferenceName = "Ntomba"},
                                 new {Id    = "ntp", Scope = "I", Type = "L", ReferenceName = "Northern Tepehuan"},
                                 new {Id    = "ntr", Scope = "I", Type = "L", ReferenceName = "Delo"},
                                 new {Id    = "ntu", Scope = "I", Type = "L", ReferenceName = "Natügu"},
                                 new {Id    = "ntw", Scope = "I", Type = "E", ReferenceName = "Nottoway"},
                                 new
                                     {
                                         Id            = "ntx",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Tangkhul Naga (Myanmar)"
                                     },
                                 new {Id = "nty", Scope = "I", Type = "L", ReferenceName = "Mantsi"},
                                 new {Id = "ntz", Scope = "I", Type = "L", ReferenceName = "Natanzi"},
                                 new {Id = "nua", Scope = "I", Type = "L", ReferenceName = "Yuanga"},
                                 new {Id = "nuc", Scope = "I", Type = "E", ReferenceName = "Nukuini"},
                                 new {Id = "nud", Scope = "I", Type = "L", ReferenceName = "Ngala"},
                                 new {Id = "nue", Scope = "I", Type = "L", ReferenceName = "Ngundu"},
                                 new {Id = "nuf", Scope = "I", Type = "L", ReferenceName = "Nusu"},
                                 new {Id = "nug", Scope = "I", Type = "E", ReferenceName = "Nungali"},
                                 new {Id = "nuh", Scope = "I", Type = "L", ReferenceName = "Ndunda"},
                                 new {Id = "nui", Scope = "I", Type = "L", ReferenceName = "Ngumbi"},
                                 new {Id = "nuj", Scope = "I", Type = "L", ReferenceName = "Nyole"},
                                 new {Id = "nuk", Scope = "I", Type = "L", ReferenceName = "Nuu-chah-nulth"},
                                 new {Id = "nul", Scope = "I", Type = "E", ReferenceName = "Nusa Laut"},
                                 new {Id = "num", Scope = "I", Type = "L", ReferenceName = "Niuafo'ou"},
                                 new {Id = "nun", Scope = "I", Type = "L", ReferenceName = "Anong"},
                                 new {Id = "nuo", Scope = "I", Type = "L", ReferenceName = "Nguôn"},
                                 new {Id = "nup", Scope = "I", Type = "L", ReferenceName = "Nupe-Nupe-Tako"},
                                 new {Id = "nuq", Scope = "I", Type = "L", ReferenceName = "Nukumanu"},
                                 new {Id = "nur", Scope = "I", Type = "L", ReferenceName = "Nukuria"},
                                 new {Id = "nus", Scope = "I", Type = "L", ReferenceName = "Nuer"},
                                 new {Id = "nut", Scope = "I", Type = "L", ReferenceName = "Nung (Viet Nam)"},
                                 new {Id = "nuu", Scope = "I", Type = "L", ReferenceName = "Ngbundu"},
                                 new {Id = "nuv", Scope = "I", Type = "L", ReferenceName = "Northern Nuni"},
                                 new {Id = "nuw", Scope = "I", Type = "L", ReferenceName = "Nguluwan"},
                                 new {Id = "nux", Scope = "I", Type = "L", ReferenceName = "Mehek"},
                                 new {Id = "nuy", Scope = "I", Type = "L", ReferenceName = "Nunggubuyu"},
                                 new {Id = "nuz", Scope = "I", Type = "L", ReferenceName = "Tlamacazapa Nahuatl"},
                                 new {Id = "nvh", Scope = "I", Type = "L", ReferenceName = "Nasarian"},
                                 new {Id = "nvm", Scope = "I", Type = "L", ReferenceName = "Namiae"},
                                 new {Id = "nvo", Scope = "I", Type = "L", ReferenceName = "Nyokon"},
                                 new {Id = "nwa", Scope = "I", Type = "E", ReferenceName = "Nawathinehena"},
                                 new {Id = "nwb", Scope = "I", Type = "L", ReferenceName = "Nyabwa"},
                                 new
                                 {
                                     Id            = "nwc",
                                     Part2B        = "nwc",
                                     Part2T        = "nwc",
                                     Scope         = "I",
                                     Type          = "H",
                                     ReferenceName = "Classical Newari"
                                 }, new {Id = "nwe", Scope = "I", Type = "L", ReferenceName = "Ngwe"},
                                 new {Id    = "nwg", Scope = "I", Type = "E", ReferenceName = "Ngayawung"},
                                 new {Id    = "nwi", Scope = "I", Type = "L", ReferenceName = "Southwest Tanna"},
                                 new {Id    = "nwm", Scope = "I", Type = "L", ReferenceName = "Nyamusa-Molo"},
                                 new {Id    = "nwo", Scope = "I", Type = "E", ReferenceName = "Nauo"},
                                 new {Id    = "nwr", Scope = "I", Type = "L", ReferenceName = "Nawaru"},
                                 new {Id    = "nwx", Scope = "I", Type = "H", ReferenceName = "Middle Newar"},
                                 new {Id    = "nwy", Scope = "I", Type = "E", ReferenceName = "Nottoway-Meherrin"},
                                 new {Id    = "nxa", Scope = "I", Type = "L", ReferenceName = "Nauete"},
                                 new
                                 {
                                     Id            = "nxd",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Ngando (Democratic Republic of Congo)"
                                 }, new {Id = "nxe", Scope = "I", Type = "L", ReferenceName = "Nage"},
                                 new {Id    = "nxg", Scope = "I", Type = "L", ReferenceName = "Ngad'a"},
                                 new {Id    = "nxi", Scope = "I", Type = "L", ReferenceName = "Nindi"},
                                 new {Id    = "nxk", Scope = "I", Type = "L", ReferenceName = "Koki Naga"},
                                 new {Id    = "nxl", Scope = "I", Type = "L", ReferenceName = "South Nuaulu"},
                                 new {Id    = "nxm", Scope = "I", Type = "A", ReferenceName = "Numidian"},
                                 new {Id    = "nxn", Scope = "I", Type = "E", ReferenceName = "Ngawun"},
                                 new {Id    = "nxo", Scope = "I", Type = "L", ReferenceName = "Ndambomo"},
                                 new {Id    = "nxq", Scope = "I", Type = "L", ReferenceName = "Naxi"},
                                 new {Id    = "nxr", Scope = "I", Type = "L", ReferenceName = "Ninggerum"},
                                 new {Id    = "nxu", Scope = "I", Type = "E", ReferenceName = "Narau"},
                                 new {Id    = "nxx", Scope = "I", Type = "L", ReferenceName = "Nafri"},
                                 new
                                 {
                                     Id            = "nya",
                                     Part2B        = "nya",
                                     Part2T        = "nya",
                                     Part1         = "ny",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Nyanja"
                                 }, new {Id = "nyb", Scope = "I", Type = "L", ReferenceName = "Nyangbo"},
                                 new {Id    = "nyc", Scope = "I", Type = "L", ReferenceName = "Nyanga-li"},
                                 new {Id    = "nyd", Scope = "I", Type = "L", ReferenceName = "Nyore"},
                                 new {Id    = "nye", Scope = "I", Type = "L", ReferenceName = "Nyengo"},
                                 new {Id    = "nyf", Scope = "I", Type = "L", ReferenceName = "Giryama"},
                                 new {Id    = "nyg", Scope = "I", Type = "L", ReferenceName = "Nyindu"},
                                 new {Id    = "nyh", Scope = "I", Type = "L", ReferenceName = "Nyikina"},
                                 new {Id    = "nyi", Scope = "I", Type = "L", ReferenceName = "Ama (Sudan)"},
                                 new {Id    = "nyj", Scope = "I", Type = "L", ReferenceName = "Nyanga"},
                                 new {Id    = "nyk", Scope = "I", Type = "L", ReferenceName = "Nyaneka"},
                                 new {Id    = "nyl", Scope = "I", Type = "L", ReferenceName = "Nyeu"},
                                 new
                                 {
                                     Id            = "nym",
                                     Part2B        = "nym",
                                     Part2T        = "nym",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Nyamwezi"
                                 }, new
                                 {
                                     Id            = "nyn",
                                     Part2B        = "nyn",
                                     Part2T        = "nyn",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Nyankole"
                                 }, new
                                 {
                                     Id            = "nyo",
                                     Part2B        = "nyo",
                                     Part2T        = "nyo",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Nyoro"
                                 }, new {Id = "nyp", Scope = "I", Type = "E", ReferenceName = "Nyang'i"},
                                 new {Id    = "nyq", Scope = "I", Type = "L", ReferenceName = "Nayini"},
                                 new {Id    = "nyr", Scope = "I", Type = "L", ReferenceName = "Nyiha (Malawi)"},
                                 new {Id    = "nys", Scope = "I", Type = "L", ReferenceName = "Nyungar"},
                                 new {Id    = "nyt", Scope = "I", Type = "E", ReferenceName = "Nyawaygi"},
                                 new {Id    = "nyu", Scope = "I", Type = "L", ReferenceName = "Nyungwe"},
                                 new {Id    = "nyv", Scope = "I", Type = "E", ReferenceName = "Nyulnyul"},
                                 new {Id    = "nyw", Scope = "I", Type = "L", ReferenceName = "Nyaw"},
                                 new {Id    = "nyx", Scope = "I", Type = "E", ReferenceName = "Nganyaywana"},
                                 new {Id    = "nyy", Scope = "I", Type = "L", ReferenceName = "Nyakyusa-Ngonde"},
                                 new {Id    = "nza", Scope = "I", Type = "L", ReferenceName = "Tigon Mbembe"},
                                 new {Id    = "nzb", Scope = "I", Type = "L", ReferenceName = "Njebi"},
                                 new {Id    = "nzd", Scope = "I", Type = "L", ReferenceName = "Nzadi"},
                                 new
                                 {
                                     Id            = "nzi",
                                     Part2B        = "nzi",
                                     Part2T        = "nzi",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Nzima"
                                 }, new {Id = "nzk", Scope = "I", Type = "L", ReferenceName = "Nzakara"},
                                 new {Id    = "nzm", Scope = "I", Type = "L", ReferenceName = "Zeme Naga"},
                                 new
                                     {
                                         Id            = "nzs",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "New Zealand Sign Language"
                                     },
                                 new {Id = "nzu", Scope = "I", Type = "L", ReferenceName = "Teke-Nzikou"},
                                 new {Id = "nzy", Scope = "I", Type = "L", ReferenceName = "Nzakambay"},
                                 new {Id = "nzz", Scope = "I", Type = "L", ReferenceName = "Nanga Dama Dogon"});
        }
    }
}