using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class R
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(new {Id = "raa", Scope = "I", Type = "L", ReferenceName = "Dungmali"},
                                 new {Id = "rab", Scope = "I", Type = "L", ReferenceName = "Camling"},
                                 new {Id = "rac", Scope = "I", Type = "L", ReferenceName = "Rasawa"},
                                 new {Id = "rad", Scope = "I", Type = "L", ReferenceName = "Rade"},
                                 new {Id = "raf", Scope = "I", Type = "L", ReferenceName = "Western Meohang"},
                                 new {Id = "rag", Scope = "I", Type = "L", ReferenceName = "Logooli"},
                                 new {Id = "rah", Scope = "I", Type = "L", ReferenceName = "Rabha"},
                                 new {Id = "rai", Scope = "I", Type = "L", ReferenceName = "Ramoaaina"},
                                 new
                                 {
                                     Id            = "raj",
                                     Part2B        = "raj",
                                     Part2T        = "raj",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Rajasthani"
                                 }, new {Id = "rak", Scope = "I", Type = "L", ReferenceName = "Tulu-Bohuai"},
                                 new {Id    = "ral", Scope = "I", Type = "L", ReferenceName = "Ralte"},
                                 new {Id    = "ram", Scope = "I", Type = "L", ReferenceName = "Canela"},
                                 new {Id    = "ran", Scope = "I", Type = "L", ReferenceName = "Riantana"},
                                 new {Id    = "rao", Scope = "I", Type = "L", ReferenceName = "Rao"},
                                 new
                                 {
                                     Id            = "rap",
                                     Part2B        = "rap",
                                     Part2T        = "rap",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Rapanui"
                                 }, new {Id = "raq", Scope = "I", Type = "L", ReferenceName = "Saam"},
                                 new
                                 {
                                     Id            = "rar",
                                     Part2B        = "rar",
                                     Part2T        = "rar",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Rarotongan"
                                 }, new {Id = "ras", Scope = "I", Type = "L", ReferenceName = "Tegali"},
                                 new {Id    = "rat", Scope = "I", Type = "L", ReferenceName = "Razajerdi"},
                                 new {Id    = "rau", Scope = "I", Type = "L", ReferenceName = "Raute"},
                                 new {Id    = "rav", Scope = "I", Type = "L", ReferenceName = "Sampang"},
                                 new {Id    = "raw", Scope = "I", Type = "L", ReferenceName = "Rawang"},
                                 new {Id    = "rax", Scope = "I", Type = "L", ReferenceName = "Rang"},
                                 new {Id    = "ray", Scope = "I", Type = "L", ReferenceName = "Rapa"},
                                 new {Id    = "raz", Scope = "I", Type = "L", ReferenceName = "Rahambuu"},
                                 new {Id    = "rbb", Scope = "I", Type = "L", ReferenceName = "Rumai Palaung"},
                                 new {Id    = "rbk", Scope = "I", Type = "L", ReferenceName = "Northern Bontok"},
                                 new {Id    = "rbl", Scope = "I", Type = "L", ReferenceName = "Miraya Bikol"},
                                 new {Id    = "rbp", Scope = "I", Type = "E", ReferenceName = "Barababaraba"},
                                 new {Id    = "rcf", Scope = "I", Type = "L", ReferenceName = "Réunion Creole French"},
                                 new {Id    = "rdb", Scope = "I", Type = "L", ReferenceName = "Rudbari"},
                                 new {Id    = "rea", Scope = "I", Type = "L", ReferenceName = "Rerau"},
                                 new {Id    = "reb", Scope = "I", Type = "L", ReferenceName = "Rembong"},
                                 new {Id    = "ree", Scope = "I", Type = "L", ReferenceName = "Rejang Kayan"},
                                 new {Id    = "reg", Scope = "I", Type = "L", ReferenceName = "Kara (Tanzania)"},
                                 new {Id    = "rei", Scope = "I", Type = "L", ReferenceName = "Reli"},
                                 new {Id    = "rej", Scope = "I", Type = "L", ReferenceName = "Rejang"},
                                 new {Id    = "rel", Scope = "I", Type = "L", ReferenceName = "Rendille"},
                                 new {Id    = "rem", Scope = "I", Type = "E", ReferenceName = "Remo"},
                                 new {Id    = "ren", Scope = "I", Type = "L", ReferenceName = "Rengao"},
                                 new {Id    = "rer", Scope = "I", Type = "E", ReferenceName = "Rer Bare"},
                                 new {Id    = "res", Scope = "I", Type = "L", ReferenceName = "Reshe"},
                                 new {Id    = "ret", Scope = "I", Type = "L", ReferenceName = "Retta"},
                                 new {Id    = "rey", Scope = "I", Type = "L", ReferenceName = "Reyesano"},
                                 new {Id    = "rga", Scope = "I", Type = "L", ReferenceName = "Roria"},
                                 new {Id    = "rge", Scope = "I", Type = "L", ReferenceName = "Romano-Greek"},
                                 new {Id    = "rgk", Scope = "I", Type = "E", ReferenceName = "Rangkas"},
                                 new {Id    = "rgn", Scope = "I", Type = "L", ReferenceName = "Romagnol"},
                                 new {Id    = "rgr", Scope = "I", Type = "L", ReferenceName = "Resígaro"},
                                 new {Id    = "rgs", Scope = "I", Type = "L", ReferenceName = "Southern Roglai"},
                                 new {Id    = "rgu", Scope = "I", Type = "L", ReferenceName = "Ringgou"},
                                 new {Id    = "rhg", Scope = "I", Type = "L", ReferenceName = "Rohingya"},
                                 new {Id    = "rhp", Scope = "I", Type = "L", ReferenceName = "Yahang"},
                                 new {Id    = "ria", Scope = "I", Type = "L", ReferenceName = "Riang (India)"},
                                 new {Id    = "rif", Scope = "I", Type = "L", ReferenceName = "Tarifit"},
                                 new {Id    = "ril", Scope = "I", Type = "L", ReferenceName = "Riang Lang"},
                                 new {Id    = "rim", Scope = "I", Type = "L", ReferenceName = "Nyaturu"},
                                 new {Id    = "rin", Scope = "I", Type = "L", ReferenceName = "Nungu"},
                                 new {Id    = "rir", Scope = "I", Type = "L", ReferenceName = "Ribun"},
                                 new {Id    = "rit", Scope = "I", Type = "L", ReferenceName = "Ritharrngu"},
                                 new {Id    = "riu", Scope = "I", Type = "L", ReferenceName = "Riung"},
                                 new {Id    = "rjg", Scope = "I", Type = "L", ReferenceName = "Rajong"},
                                 new {Id    = "rji", Scope = "I", Type = "L", ReferenceName = "Raji"},
                                 new {Id    = "rjs", Scope = "I", Type = "L", ReferenceName = "Rajbanshi"},
                                 new {Id    = "rka", Scope = "I", Type = "L", ReferenceName = "Kraol"},
                                 new {Id    = "rkb", Scope = "I", Type = "L", ReferenceName = "Rikbaktsa"},
                                 new {Id    = "rkh", Scope = "I", Type = "L", ReferenceName = "Rakahanga-Manihiki"},
                                 new {Id    = "rki", Scope = "I", Type = "L", ReferenceName = "Rakhine"},
                                 new {Id    = "rkm", Scope = "I", Type = "L", ReferenceName = "Marka"},
                                 new {Id    = "rkt", Scope = "I", Type = "L", ReferenceName = "Rangpuri"},
                                 new {Id    = "rkw", Scope = "I", Type = "E", ReferenceName = "Arakwal"},
                                 new {Id    = "rma", Scope = "I", Type = "L", ReferenceName = "Rama"},
                                 new {Id    = "rmb", Scope = "I", Type = "L", ReferenceName = "Rembarrnga"},
                                 new {Id    = "rmc", Scope = "I", Type = "L", ReferenceName = "Carpathian Romani"},
                                 new {Id    = "rmd", Scope = "I", Type = "E", ReferenceName = "Traveller Danish"},
                                 new {Id    = "rme", Scope = "I", Type = "L", ReferenceName = "Angloromani"},
                                 new {Id    = "rmf", Scope = "I", Type = "L", ReferenceName = "Kalo Finnish Romani"},
                                 new {Id    = "rmg", Scope = "I", Type = "L", ReferenceName = "Traveller Norwegian"},
                                 new {Id    = "rmh", Scope = "I", Type = "L", ReferenceName = "Murkim"},
                                 new {Id    = "rmi", Scope = "I", Type = "L", ReferenceName = "Lomavren"},
                                 new {Id    = "rmk", Scope = "I", Type = "L", ReferenceName = "Romkun"},
                                 new {Id    = "rml", Scope = "I", Type = "L", ReferenceName = "Baltic Romani"},
                                 new {Id    = "rmm", Scope = "I", Type = "L", ReferenceName = "Roma"},
                                 new {Id    = "rmn", Scope = "I", Type = "L", ReferenceName = "Balkan Romani"},
                                 new {Id    = "rmo", Scope = "I", Type = "L", ReferenceName = "Sinte Romani"},
                                 new {Id    = "rmp", Scope = "I", Type = "L", ReferenceName = "Rempi"},
                                 new {Id    = "rmq", Scope = "I", Type = "L", ReferenceName = "Caló"},
                                 new {Id    = "rms", Scope = "I", Type = "L", ReferenceName = "Romanian Sign Language"},
                                 new {Id    = "rmt", Scope = "I", Type = "L", ReferenceName = "Domari"},
                                 new {Id    = "rmu", Scope = "I", Type = "L", ReferenceName = "Tavringer Romani"},
                                 new {Id    = "rmv", Scope = "I", Type = "C", ReferenceName = "Romanova"},
                                 new {Id    = "rmw", Scope = "I", Type = "L", ReferenceName = "Welsh Romani"},
                                 new {Id    = "rmx", Scope = "I", Type = "L", ReferenceName = "Romam"},
                                 new {Id    = "rmy", Scope = "I", Type = "L", ReferenceName = "Vlax Romani"},
                                 new {Id    = "rmz", Scope = "I", Type = "L", ReferenceName = "Marma"},
                                 new {Id    = "rnd", Scope = "I", Type = "L", ReferenceName = "Ruund"},
                                 new {Id    = "rng", Scope = "I", Type = "L", ReferenceName = "Ronga"},
                                 new {Id    = "rnl", Scope = "I", Type = "L", ReferenceName = "Ranglong"},
                                 new {Id    = "rnn", Scope = "I", Type = "L", ReferenceName = "Roon"},
                                 new {Id    = "rnp", Scope = "I", Type = "L", ReferenceName = "Rongpo"},
                                 new {Id    = "rnr", Scope = "I", Type = "E", ReferenceName = "Nari Nari"},
                                 new {Id    = "rnw", Scope = "I", Type = "L", ReferenceName = "Rungwa"},
                                 new {Id    = "rob", Scope = "I", Type = "L", ReferenceName = "Tae'"},
                                 new {Id    = "roc", Scope = "I", Type = "L", ReferenceName = "Cacgia Roglai"},
                                 new {Id    = "rod", Scope = "I", Type = "L", ReferenceName = "Rogo"},
                                 new {Id    = "roe", Scope = "I", Type = "L", ReferenceName = "Ronji"},
                                 new {Id    = "rof", Scope = "I", Type = "L", ReferenceName = "Rombo"},
                                 new {Id    = "rog", Scope = "I", Type = "L", ReferenceName = "Northern Roglai"},
                                 new
                                 {
                                     Id            = "roh",
                                     Part2B        = "roh",
                                     Part2T        = "roh",
                                     Part1         = "rm",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Romansh"
                                 }, new {Id = "rol", Scope = "I", Type = "L", ReferenceName = "Romblomanon"},
                                 new
                                 {
                                     Id            = "rom",
                                     Part2B        = "rom",
                                     Part2T        = "rom",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Romany"
                                 }, new
                                 {
                                     Id            = "ron",
                                     Part2B        = "rum",
                                     Part2T        = "ron",
                                     Part1         = "ro",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Romanian"
                                 }, new {Id = "roo", Scope = "I", Type = "L", ReferenceName = "Rotokas"},
                                 new {Id    = "rop", Scope = "I", Type = "L", ReferenceName = "Kriol"},
                                 new {Id    = "ror", Scope = "I", Type = "L", ReferenceName = "Rongga"},
                                 new {Id    = "rou", Scope = "I", Type = "L", ReferenceName = "Runga"},
                                 new {Id    = "row", Scope = "I", Type = "L", ReferenceName = "Dela-Oenale"},
                                 new {Id    = "rpn", Scope = "I", Type = "L", ReferenceName = "Repanbitip"},
                                 new {Id    = "rpt", Scope = "I", Type = "L", ReferenceName = "Rapting"},
                                 new {Id    = "rri", Scope = "I", Type = "L", ReferenceName = "Ririo"},
                                 new {Id    = "rro", Scope = "I", Type = "L", ReferenceName = "Waima"},
                                 new {Id    = "rrt", Scope = "I", Type = "E", ReferenceName = "Arritinngithigh"},
                                 new {Id    = "rsb", Scope = "I", Type = "L", ReferenceName = "Romano-Serbian"},
                                 new {Id    = "rsl", Scope = "I", Type = "L", ReferenceName = "Russian Sign Language"},
                                 new
                                     {
                                         Id            = "rsm",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Miriwoong Sign Language"
                                     },
                                 new {Id = "rtc", Scope = "I", Type = "L", ReferenceName = "Rungtu Chin"},
                                 new {Id = "rth", Scope = "I", Type = "L", ReferenceName = "Ratahan"},
                                 new {Id = "rtm", Scope = "I", Type = "L", ReferenceName = "Rotuman"},
                                 new {Id = "rts", Scope = "I", Type = "E", ReferenceName = "Yurats"},
                                 new {Id = "rtw", Scope = "I", Type = "L", ReferenceName = "Rathawi"},
                                 new {Id = "rub", Scope = "I", Type = "L", ReferenceName = "Gungu"},
                                 new {Id = "ruc", Scope = "I", Type = "L", ReferenceName = "Ruuli"},
                                 new {Id = "rue", Scope = "I", Type = "L", ReferenceName = "Rusyn"},
                                 new {Id = "ruf", Scope = "I", Type = "L", ReferenceName = "Luguru"},
                                 new {Id = "rug", Scope = "I", Type = "L", ReferenceName = "Roviana"},
                                 new {Id = "ruh", Scope = "I", Type = "L", ReferenceName = "Ruga"},
                                 new {Id = "rui", Scope = "I", Type = "L", ReferenceName = "Rufiji"},
                                 new {Id = "ruk", Scope = "I", Type = "L", ReferenceName = "Che"},
                                 new
                                 {
                                     Id            = "run",
                                     Part2B        = "run",
                                     Part2T        = "run",
                                     Part1         = "rn",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Rundi"
                                 }, new {Id = "ruo", Scope = "I", Type = "L", ReferenceName = "Istro Romanian"},
                                 new
                                 {
                                     Id            = "rup",
                                     Part2B        = "rup",
                                     Part2T        = "rup",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Macedo-Romanian"
                                 }, new {Id = "ruq", Scope = "I", Type = "L", ReferenceName = "Megleno Romanian"},
                                 new
                                 {
                                     Id            = "rus",
                                     Part2B        = "rus",
                                     Part2T        = "rus",
                                     Part1         = "ru",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Russian"
                                 }, new {Id = "rut", Scope = "I", Type = "L", ReferenceName = "Rutul"},
                                 new {Id    = "ruu", Scope = "I", Type = "L", ReferenceName = "Lanas Lobu"},
                                 new {Id    = "ruy", Scope = "I", Type = "L", ReferenceName = "Mala (Nigeria)"},
                                 new {Id    = "ruz", Scope = "I", Type = "L", ReferenceName = "Ruma"},
                                 new {Id    = "rwa", Scope = "I", Type = "L", ReferenceName = "Rawo"},
                                 new {Id    = "rwk", Scope = "I", Type = "L", ReferenceName = "Rwa"},
                                 new {Id    = "rwm", Scope = "I", Type = "L", ReferenceName = "Amba (Uganda)"},
                                 new {Id    = "rwo", Scope = "I", Type = "L", ReferenceName = "Rawa"},
                                 new {Id    = "rwr", Scope = "I", Type = "L", ReferenceName = "Marwari (India)"},
                                 new {Id    = "rxd", Scope = "I", Type = "L", ReferenceName = "Ngardi"},
                                 new {Id    = "rxw", Scope = "I", Type = "E", ReferenceName = "Karuwali"},
                                 new {Id    = "ryn", Scope = "I", Type = "L", ReferenceName = "Northern Amami-Oshima"},
                                 new {Id    = "rys", Scope = "I", Type = "L", ReferenceName = "Yaeyama"},
                                 new {Id    = "ryu", Scope = "I", Type = "L", ReferenceName = "Central Okinawan"},
                                 new {Id    = "rzh", Scope = "I", Type = "L", ReferenceName = "Rāziḥī"});
        }
    }
}