using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class T
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(new {Id = "taa", Scope = "I", Type = "L", ReferenceName = "Lower Tanana"},
                                 new {Id = "tab", Scope = "I", Type = "L", ReferenceName = "Tabassaran"},
                                 new {Id = "tac", Scope = "I", Type = "L", ReferenceName = "Lowland Tarahumara"},
                                 new {Id = "tad", Scope = "I", Type = "L", ReferenceName = "Tause"},
                                 new {Id = "tae", Scope = "I", Type = "L", ReferenceName = "Tariana"},
                                 new {Id = "taf", Scope = "I", Type = "L", ReferenceName = "Tapirapé"},
                                 new {Id = "tag", Scope = "I", Type = "L", ReferenceName = "Tagoi"},
                                 new
                                 {
                                     Id            = "tah",
                                     Part2B        = "tah",
                                     Part2T        = "tah",
                                     Part1         = "ty",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tahitian"
                                 }, new {Id = "taj", Scope = "I", Type = "L", ReferenceName = "Eastern Tamang"},
                                 new {Id    = "tak", Scope = "I", Type = "L", ReferenceName = "Tala"},
                                 new {Id    = "tal", Scope = "I", Type = "L", ReferenceName = "Tal"},
                                 new
                                 {
                                     Id            = "tam",
                                     Part2B        = "tam",
                                     Part2T        = "tam",
                                     Part1         = "ta",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tamil"
                                 }, new {Id = "tan", Scope = "I", Type = "L", ReferenceName = "Tangale"},
                                 new {Id    = "tao", Scope = "I", Type = "L", ReferenceName = "Yami"},
                                 new {Id    = "tap", Scope = "I", Type = "L", ReferenceName = "Taabwa"},
                                 new {Id    = "taq", Scope = "I", Type = "L", ReferenceName = "Tamasheq"},
                                 new {Id    = "tar", Scope = "I", Type = "L", ReferenceName = "Central Tarahumara"},
                                 new {Id    = "tas", Scope = "I", Type = "E", ReferenceName = "Tay Boi"},
                                 new
                                 {
                                     Id            = "tat",
                                     Part2B        = "tat",
                                     Part2T        = "tat",
                                     Part1         = "tt",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tatar"
                                 }, new {Id = "tau", Scope = "I", Type = "L", ReferenceName = "Upper Tanana"},
                                 new {Id    = "tav", Scope = "I", Type = "L", ReferenceName = "Tatuyo"},
                                 new {Id    = "taw", Scope = "I", Type = "L", ReferenceName = "Tai"},
                                 new {Id    = "tax", Scope = "I", Type = "L", ReferenceName = "Tamki"},
                                 new {Id    = "tay", Scope = "I", Type = "L", ReferenceName = "Atayal"},
                                 new {Id    = "taz", Scope = "I", Type = "L", ReferenceName = "Tocho"},
                                 new {Id    = "tba", Scope = "I", Type = "L", ReferenceName = "Aikanã"},
                                 new {Id    = "tbb", Scope = "I", Type = "E", ReferenceName = "Tapeba"},
                                 new {Id    = "tbc", Scope = "I", Type = "L", ReferenceName = "Takia"},
                                 new {Id    = "tbd", Scope = "I", Type = "L", ReferenceName = "Kaki Ae"},
                                 new {Id    = "tbe", Scope = "I", Type = "L", ReferenceName = "Tanimbili"},
                                 new {Id    = "tbf", Scope = "I", Type = "L", ReferenceName = "Mandara"},
                                 new {Id    = "tbg", Scope = "I", Type = "L", ReferenceName = "North Tairora"},
                                 new {Id    = "tbh", Scope = "I", Type = "E", ReferenceName = "Dharawal"},
                                 new {Id    = "tbi", Scope = "I", Type = "L", ReferenceName = "Gaam"},
                                 new {Id    = "tbj", Scope = "I", Type = "L", ReferenceName = "Tiang"},
                                 new {Id    = "tbk", Scope = "I", Type = "L", ReferenceName = "Calamian Tagbanwa"},
                                 new {Id    = "tbl", Scope = "I", Type = "L", ReferenceName = "Tboli"},
                                 new {Id    = "tbm", Scope = "I", Type = "L", ReferenceName = "Tagbu"},
                                 new {Id    = "tbn", Scope = "I", Type = "L", ReferenceName = "Barro Negro Tunebo"},
                                 new {Id    = "tbo", Scope = "I", Type = "L", ReferenceName = "Tawala"},
                                 new {Id    = "tbp", Scope = "I", Type = "L", ReferenceName = "Taworta"},
                                 new {Id    = "tbr", Scope = "I", Type = "L", ReferenceName = "Tumtum"},
                                 new {Id    = "tbs", Scope = "I", Type = "L", ReferenceName = "Tanguat"},
                                 new {Id    = "tbt", Scope = "I", Type = "L", ReferenceName = "Tembo (Kitembo)"},
                                 new {Id    = "tbu", Scope = "I", Type = "E", ReferenceName = "Tubar"},
                                 new {Id    = "tbv", Scope = "I", Type = "L", ReferenceName = "Tobo"},
                                 new {Id    = "tbw", Scope = "I", Type = "L", ReferenceName = "Tagbanwa"},
                                 new {Id    = "tbx", Scope = "I", Type = "L", ReferenceName = "Kapin"},
                                 new {Id    = "tby", Scope = "I", Type = "L", ReferenceName = "Tabaru"},
                                 new {Id    = "tbz", Scope = "I", Type = "L", ReferenceName = "Ditammari"},
                                 new {Id    = "tca", Scope = "I", Type = "L", ReferenceName = "Ticuna"},
                                 new {Id    = "tcb", Scope = "I", Type = "L", ReferenceName = "Tanacross"},
                                 new {Id    = "tcc", Scope = "I", Type = "L", ReferenceName = "Datooga"},
                                 new {Id    = "tcd", Scope = "I", Type = "L", ReferenceName = "Tafi"},
                                 new {Id    = "tce", Scope = "I", Type = "L", ReferenceName = "Southern Tutchone"},
                                 new {Id    = "tcf", Scope = "I", Type = "L", ReferenceName = "Malinaltepec Me'phaa"},
                                 new {Id    = "tcg", Scope = "I", Type = "L", ReferenceName = "Tamagario"},
                                 new
                                 {
                                     Id            = "tch",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Turks And Caicos Creole English"
                                 }, new {Id = "tci", Scope = "I", Type = "L", ReferenceName = "Wára"},
                                 new {Id    = "tck", Scope = "I", Type = "L", ReferenceName = "Tchitchege"},
                                 new {Id    = "tcl", Scope = "I", Type = "E", ReferenceName = "Taman (Myanmar)"},
                                 new {Id    = "tcm", Scope = "I", Type = "L", ReferenceName = "Tanahmerah"},
                                 new {Id    = "tcn", Scope = "I", Type = "L", ReferenceName = "Tichurong"},
                                 new {Id    = "tco", Scope = "I", Type = "L", ReferenceName = "Taungyo"},
                                 new {Id    = "tcp", Scope = "I", Type = "L", ReferenceName = "Tawr Chin"},
                                 new {Id    = "tcq", Scope = "I", Type = "L", ReferenceName = "Kaiy"},
                                 new
                                     {
                                         Id            = "tcs",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Torres Strait Creole"
                                     },
                                 new {Id = "tct", Scope = "I", Type = "L", ReferenceName = "T'en"},
                                 new
                                     {
                                         Id            = "tcu",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Southeastern Tarahumara"
                                     },
                                 new {Id = "tcw", Scope = "I", Type = "L", ReferenceName = "Tecpatlán Totonac"},
                                 new {Id = "tcx", Scope = "I", Type = "L", ReferenceName = "Toda"},
                                 new {Id = "tcy", Scope = "I", Type = "L", ReferenceName = "Tulu"},
                                 new {Id = "tcz", Scope = "I", Type = "L", ReferenceName = "Thado Chin"},
                                 new {Id = "tda", Scope = "I", Type = "L", ReferenceName = "Tagdal"},
                                 new {Id = "tdb", Scope = "I", Type = "L", ReferenceName = "Panchpargania"},
                                 new {Id = "tdc", Scope = "I", Type = "L", ReferenceName = "Emberá-Tadó"},
                                 new {Id = "tdd", Scope = "I", Type = "L", ReferenceName = "Tai Nüa"},
                                 new
                                     {
                                         Id            = "tde",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Tiranige Diga Dogon"
                                     },
                                 new {Id = "tdf", Scope = "I", Type = "L", ReferenceName = "Talieng"},
                                 new {Id = "tdg", Scope = "I", Type = "L", ReferenceName = "Western Tamang"},
                                 new {Id = "tdh", Scope = "I", Type = "L", ReferenceName = "Thulung"},
                                 new {Id = "tdi", Scope = "I", Type = "L", ReferenceName = "Tomadino"},
                                 new {Id = "tdj", Scope = "I", Type = "L", ReferenceName = "Tajio"},
                                 new {Id = "tdk", Scope = "I", Type = "L", ReferenceName = "Tambas"},
                                 new {Id = "tdl", Scope = "I", Type = "L", ReferenceName = "Sur"},
                                 new {Id = "tdm", Scope = "I", Type = "L", ReferenceName = "Taruma"},
                                 new {Id = "tdn", Scope = "I", Type = "L", ReferenceName = "Tondano"},
                                 new {Id = "tdo", Scope = "I", Type = "L", ReferenceName = "Teme"},
                                 new {Id = "tdq", Scope = "I", Type = "L", ReferenceName = "Tita"},
                                 new {Id = "tdr", Scope = "I", Type = "L", ReferenceName = "Todrah"},
                                 new {Id = "tds", Scope = "I", Type = "L", ReferenceName = "Doutai"},
                                 new {Id = "tdt", Scope = "I", Type = "L", ReferenceName = "Tetun Dili"},
                                 new {Id = "tdv", Scope = "I", Type = "L", ReferenceName = "Toro"},
                                 new
                                     {
                                         Id            = "tdx",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Tandroy-Mahafaly Malagasy"
                                     },
                                 new {Id = "tdy", Scope = "I", Type = "L", ReferenceName = "Tadyawan"},
                                 new {Id = "tea", Scope = "I", Type = "L", ReferenceName = "Temiar"},
                                 new {Id = "teb", Scope = "I", Type = "E", ReferenceName = "Tetete"},
                                 new {Id = "tec", Scope = "I", Type = "L", ReferenceName = "Terik"},
                                 new {Id = "ted", Scope = "I", Type = "L", ReferenceName = "Tepo Krumen"},
                                 new {Id = "tee", Scope = "I", Type = "L", ReferenceName = "Huehuetla Tepehua"},
                                 new {Id = "tef", Scope = "I", Type = "L", ReferenceName = "Teressa"},
                                 new {Id = "teg", Scope = "I", Type = "L", ReferenceName = "Teke-Tege"},
                                 new {Id = "teh", Scope = "I", Type = "L", ReferenceName = "Tehuelche"},
                                 new {Id = "tei", Scope = "I", Type = "L", ReferenceName = "Torricelli"},
                                 new {Id = "tek", Scope = "I", Type = "L", ReferenceName = "Ibali Teke"},
                                 new
                                 {
                                     Id            = "tel",
                                     Part2B        = "tel",
                                     Part2T        = "tel",
                                     Part1         = "te",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Telugu"
                                 }, new
                                 {
                                     Id            = "tem",
                                     Part2B        = "tem",
                                     Part2T        = "tem",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Timne"
                                 }, new {Id = "ten", Scope = "I", Type = "E", ReferenceName = "Tama (Colombia)"},
                                 new {Id    = "teo", Scope = "I", Type = "L", ReferenceName = "Teso"},
                                 new {Id    = "tep", Scope = "I", Type = "E", ReferenceName = "Tepecano"},
                                 new {Id    = "teq", Scope = "I", Type = "L", ReferenceName = "Temein"},
                                 new
                                 {
                                     Id            = "ter",
                                     Part2B        = "ter",
                                     Part2T        = "ter",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tereno"
                                 }, new {Id = "tes", Scope = "I", Type = "L", ReferenceName = "Tengger"},
                                 new
                                 {
                                     Id            = "tet",
                                     Part2B        = "tet",
                                     Part2T        = "tet",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tetum"
                                 }, new {Id = "teu", Scope = "I", Type = "L", ReferenceName = "Soo"},
                                 new {Id    = "tev", Scope = "I", Type = "L", ReferenceName = "Teor"},
                                 new {Id    = "tew", Scope = "I", Type = "L", ReferenceName = "Tewa (USA)"},
                                 new {Id    = "tex", Scope = "I", Type = "L", ReferenceName = "Tennet"},
                                 new {Id    = "tey", Scope = "I", Type = "L", ReferenceName = "Tulishi"},
                                 new {Id    = "tez", Scope = "I", Type = "L", ReferenceName = "Tetserret"},
                                 new {Id    = "tfi", Scope = "I", Type = "L", ReferenceName = "Tofin Gbe"},
                                 new {Id    = "tfn", Scope = "I", Type = "L", ReferenceName = "Tanaina"},
                                 new {Id    = "tfo", Scope = "I", Type = "L", ReferenceName = "Tefaro"},
                                 new {Id    = "tfr", Scope = "I", Type = "L", ReferenceName = "Teribe"},
                                 new {Id    = "tft", Scope = "I", Type = "L", ReferenceName = "Ternate"},
                                 new {Id    = "tga", Scope = "I", Type = "L", ReferenceName = "Sagalla"},
                                 new {Id    = "tgb", Scope = "I", Type = "L", ReferenceName = "Tobilung"},
                                 new {Id    = "tgc", Scope = "I", Type = "L", ReferenceName = "Tigak"},
                                 new {Id    = "tgd", Scope = "I", Type = "L", ReferenceName = "Ciwogai"},
                                 new {Id    = "tge", Scope = "I", Type = "L", ReferenceName = "Eastern Gorkha Tamang"},
                                 new {Id    = "tgf", Scope = "I", Type = "L", ReferenceName = "Chalikha"},
                                 new
                                     {
                                         Id            = "tgh",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Tobagonian Creole English"
                                     },
                                 new {Id = "tgi", Scope = "I", Type = "L", ReferenceName = "Lawunuia"},
                                 new {Id = "tgj", Scope = "I", Type = "L", ReferenceName = "Tagin"},
                                 new
                                 {
                                     Id            = "tgk",
                                     Part2B        = "tgk",
                                     Part2T        = "tgk",
                                     Part1         = "tg",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tajik"
                                 }, new
                                 {
                                     Id            = "tgl",
                                     Part2B        = "tgl",
                                     Part2T        = "tgl",
                                     Part1         = "tl",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tagalog"
                                 }, new {Id = "tgn", Scope = "I", Type = "L", ReferenceName = "Tandaganon"},
                                 new {Id    = "tgo", Scope = "I", Type = "L", ReferenceName = "Sudest"},
                                 new {Id    = "tgp", Scope = "I", Type = "L", ReferenceName = "Tangoa"},
                                 new {Id    = "tgq", Scope = "I", Type = "L", ReferenceName = "Tring"},
                                 new {Id    = "tgr", Scope = "I", Type = "L", ReferenceName = "Tareng"},
                                 new {Id    = "tgs", Scope = "I", Type = "L", ReferenceName = "Nume"},
                                 new {Id    = "tgt", Scope = "I", Type = "L", ReferenceName = "Central Tagbanwa"},
                                 new {Id    = "tgu", Scope = "I", Type = "L", ReferenceName = "Tanggu"},
                                 new {Id    = "tgv", Scope = "I", Type = "E", ReferenceName = "Tingui-Boto"},
                                 new {Id    = "tgw", Scope = "I", Type = "L", ReferenceName = "Tagwana Senoufo"},
                                 new {Id    = "tgx", Scope = "I", Type = "L", ReferenceName = "Tagish"},
                                 new {Id    = "tgy", Scope = "I", Type = "E", ReferenceName = "Togoyo"},
                                 new {Id    = "tgz", Scope = "I", Type = "E", ReferenceName = "Tagalaka"},
                                 new
                                 {
                                     Id            = "tha",
                                     Part2B        = "tha",
                                     Part2T        = "tha",
                                     Part1         = "th",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Thai"
                                 }, new {Id = "thd", Scope = "I", Type = "L", ReferenceName = "Kuuk Thaayorre"},
                                 new {Id    = "the", Scope = "I", Type = "L", ReferenceName = "Chitwania Tharu"},
                                 new {Id    = "thf", Scope = "I", Type = "L", ReferenceName = "Thangmi"},
                                 new {Id    = "thh", Scope = "I", Type = "L", ReferenceName = "Northern Tarahumara"},
                                 new {Id    = "thi", Scope = "I", Type = "L", ReferenceName = "Tai Long"},
                                 new {Id    = "thk", Scope = "I", Type = "L", ReferenceName = "Tharaka"},
                                 new {Id    = "thl", Scope = "I", Type = "L", ReferenceName = "Dangaura Tharu"},
                                 new {Id    = "thm", Scope = "I", Type = "L", ReferenceName = "Aheu"},
                                 new {Id    = "thn", Scope = "I", Type = "L", ReferenceName = "Thachanadan"},
                                 new {Id    = "thp", Scope = "I", Type = "L", ReferenceName = "Thompson"},
                                 new {Id    = "thq", Scope = "I", Type = "L", ReferenceName = "Kochila Tharu"},
                                 new {Id    = "thr", Scope = "I", Type = "L", ReferenceName = "Rana Tharu"},
                                 new {Id    = "ths", Scope = "I", Type = "L", ReferenceName = "Thakali"},
                                 new {Id    = "tht", Scope = "I", Type = "L", ReferenceName = "Tahltan"},
                                 new {Id    = "thu", Scope = "I", Type = "L", ReferenceName = "Thuri"},
                                 new {Id    = "thv", Scope = "I", Type = "L", ReferenceName = "Tahaggart Tamahaq"},
                                 new {Id    = "thw", Scope = "I", Type = "L", ReferenceName = "Thudam"},
                                 new {Id    = "thy", Scope = "I", Type = "L", ReferenceName = "Tha"},
                                 new {Id    = "thz", Scope = "I", Type = "L", ReferenceName = "Tayart Tamajeq"},
                                 new {Id    = "tia", Scope = "I", Type = "L", ReferenceName = "Tidikelt Tamazight"},
                                 new {Id    = "tic", Scope = "I", Type = "L", ReferenceName = "Tira"},
                                 new {Id    = "tif", Scope = "I", Type = "L", ReferenceName = "Tifal"},
                                 new
                                 {
                                     Id            = "tig",
                                     Part2B        = "tig",
                                     Part2T        = "tig",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tigre"
                                 }, new {Id = "tih", Scope = "I", Type = "L", ReferenceName = "Timugon Murut"},
                                 new {Id    = "tii", Scope = "I", Type = "L", ReferenceName = "Tiene"},
                                 new {Id    = "tij", Scope = "I", Type = "L", ReferenceName = "Tilung"},
                                 new {Id    = "tik", Scope = "I", Type = "L", ReferenceName = "Tikar"},
                                 new {Id    = "til", Scope = "I", Type = "E", ReferenceName = "Tillamook"},
                                 new {Id    = "tim", Scope = "I", Type = "L", ReferenceName = "Timbe"},
                                 new {Id    = "tin", Scope = "I", Type = "L", ReferenceName = "Tindi"},
                                 new {Id    = "tio", Scope = "I", Type = "L", ReferenceName = "Teop"},
                                 new {Id    = "tip", Scope = "I", Type = "L", ReferenceName = "Trimuris"},
                                 new {Id    = "tiq", Scope = "I", Type = "L", ReferenceName = "Tiéfo"},
                                 new
                                 {
                                     Id            = "tir",
                                     Part2B        = "tir",
                                     Part2T        = "tir",
                                     Part1         = "ti",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tigrinya"
                                 }, new {Id = "tis", Scope = "I", Type = "L", ReferenceName = "Masadiit Itneg"},
                                 new {Id    = "tit", Scope = "I", Type = "L", ReferenceName = "Tinigua"},
                                 new {Id    = "tiu", Scope = "I", Type = "L", ReferenceName = "Adasen"},
                                 new
                                 {
                                     Id            = "tiv",
                                     Part2B        = "tiv",
                                     Part2T        = "tiv",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tiv"
                                 }, new {Id = "tiw", Scope = "I", Type = "L", ReferenceName = "Tiwi"},
                                 new {Id    = "tix", Scope = "I", Type = "L", ReferenceName = "Southern Tiwa"},
                                 new {Id    = "tiy", Scope = "I", Type = "L", ReferenceName = "Tiruray"},
                                 new {Id    = "tiz", Scope = "I", Type = "L", ReferenceName = "Tai Hongjin"},
                                 new {Id    = "tja", Scope = "I", Type = "L", ReferenceName = "Tajuasohn"},
                                 new {Id    = "tjg", Scope = "I", Type = "L", ReferenceName = "Tunjung"},
                                 new {Id    = "tji", Scope = "I", Type = "L", ReferenceName = "Northern Tujia"},
                                 new {Id    = "tjj", Scope = "I", Type = "L", ReferenceName = "Tjungundji"},
                                 new {Id    = "tjl", Scope = "I", Type = "L", ReferenceName = "Tai Laing"},
                                 new {Id    = "tjm", Scope = "I", Type = "E", ReferenceName = "Timucua"},
                                 new {Id    = "tjn", Scope = "I", Type = "E", ReferenceName = "Tonjon"},
                                 new {Id    = "tjo", Scope = "I", Type = "L", ReferenceName = "Temacine Tamazight"},
                                 new {Id    = "tjp", Scope = "I", Type = "L", ReferenceName = "Tjupany"},
                                 new {Id    = "tjs", Scope = "I", Type = "L", ReferenceName = "Southern Tujia"},
                                 new {Id    = "tju", Scope = "I", Type = "E", ReferenceName = "Tjurruru"},
                                 new {Id    = "tjw", Scope = "I", Type = "L", ReferenceName = "Djabwurrung"},
                                 new {Id    = "tka", Scope = "I", Type = "E", ReferenceName = "Truká"},
                                 new {Id    = "tkb", Scope = "I", Type = "L", ReferenceName = "Buksa"},
                                 new {Id    = "tkd", Scope = "I", Type = "L", ReferenceName = "Tukudede"},
                                 new {Id    = "tke", Scope = "I", Type = "L", ReferenceName = "Takwane"},
                                 new {Id    = "tkf", Scope = "I", Type = "E", ReferenceName = "Tukumanféd"},
                                 new {Id    = "tkg", Scope = "I", Type = "L", ReferenceName = "Tesaka Malagasy"},
                                 new
                                 {
                                     Id            = "tkl",
                                     Part2B        = "tkl",
                                     Part2T        = "tkl",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tokelau"
                                 }, new {Id = "tkm", Scope = "I", Type = "E", ReferenceName = "Takelma"},
                                 new {Id    = "tkn", Scope = "I", Type = "L", ReferenceName = "Toku-No-Shima"},
                                 new {Id    = "tkp", Scope = "I", Type = "L", ReferenceName = "Tikopia"},
                                 new {Id    = "tkq", Scope = "I", Type = "L", ReferenceName = "Tee"},
                                 new {Id    = "tkr", Scope = "I", Type = "L", ReferenceName = "Tsakhur"},
                                 new {Id    = "tks", Scope = "I", Type = "L", ReferenceName = "Takestani"},
                                 new {Id    = "tkt", Scope = "I", Type = "L", ReferenceName = "Kathoriya Tharu"},
                                 new {Id    = "tku", Scope = "I", Type = "L", ReferenceName = "Upper Necaxa Totonac"},
                                 new {Id    = "tkv", Scope = "I", Type = "L", ReferenceName = "Mur Pano"},
                                 new {Id    = "tkw", Scope = "I", Type = "L", ReferenceName = "Teanu"},
                                 new {Id    = "tkx", Scope = "I", Type = "L", ReferenceName = "Tangko"},
                                 new {Id    = "tkz", Scope = "I", Type = "L", ReferenceName = "Takua"},
                                 new {Id    = "tla", Scope = "I", Type = "L", ReferenceName = "Southwestern Tepehuan"},
                                 new {Id    = "tlb", Scope = "I", Type = "L", ReferenceName = "Tobelo"},
                                 new {Id    = "tlc", Scope = "I", Type = "L", ReferenceName = "Yecuatla Totonac"},
                                 new {Id    = "tld", Scope = "I", Type = "L", ReferenceName = "Talaud"},
                                 new {Id    = "tlf", Scope = "I", Type = "L", ReferenceName = "Telefol"},
                                 new {Id    = "tlg", Scope = "I", Type = "L", ReferenceName = "Tofanma"},
                                 new
                                 {
                                     Id            = "tlh",
                                     Part2B        = "tlh",
                                     Part2T        = "tlh",
                                     Scope         = "I",
                                     Type          = "C",
                                     ReferenceName = "Klingon"
                                 }, new
                                 {
                                     Id            = "tli",
                                     Part2B        = "tli",
                                     Part2T        = "tli",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tlingit"
                                 }, new {Id = "tlj", Scope = "I", Type = "L", ReferenceName = "Talinga-Bwisi"},
                                 new {Id    = "tlk", Scope = "I", Type = "L", ReferenceName = "Taloki"},
                                 new {Id    = "tll", Scope = "I", Type = "L", ReferenceName = "Tetela"},
                                 new {Id    = "tlm", Scope = "I", Type = "L", ReferenceName = "Tolomako"},
                                 new {Id    = "tln", Scope = "I", Type = "L", ReferenceName = "Talondo'"},
                                 new {Id    = "tlo", Scope = "I", Type = "L", ReferenceName = "Talodi"},
                                 new
                                 {
                                     Id            = "tlp",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Filomena Mata-Coahuitlán Totonac"
                                 }, new {Id = "tlq", Scope = "I", Type = "L", ReferenceName = "Tai Loi"},
                                 new {Id    = "tlr", Scope = "I", Type = "L", ReferenceName = "Talise"},
                                 new {Id    = "tls", Scope = "I", Type = "L", ReferenceName = "Tambotalo"},
                                 new {Id    = "tlt", Scope = "I", Type = "L", ReferenceName = "Sou Nama"},
                                 new {Id    = "tlu", Scope = "I", Type = "L", ReferenceName = "Tulehu"},
                                 new {Id    = "tlv", Scope = "I", Type = "L", ReferenceName = "Taliabu"},
                                 new {Id    = "tlx", Scope = "I", Type = "L", ReferenceName = "Khehek"},
                                 new {Id    = "tly", Scope = "I", Type = "L", ReferenceName = "Talysh"},
                                 new {Id    = "tma", Scope = "I", Type = "L", ReferenceName = "Tama (Chad)"},
                                 new {Id    = "tmb", Scope = "I", Type = "L", ReferenceName = "Katbol"},
                                 new {Id    = "tmc", Scope = "I", Type = "L", ReferenceName = "Tumak"},
                                 new {Id    = "tmd", Scope = "I", Type = "L", ReferenceName = "Haruai"},
                                 new {Id    = "tme", Scope = "I", Type = "E", ReferenceName = "Tremembé"},
                                 new {Id    = "tmf", Scope = "I", Type = "L", ReferenceName = "Toba-Maskoy"},
                                 new {Id    = "tmg", Scope = "I", Type = "E", ReferenceName = "Ternateño"},
                                 new
                                 {
                                     Id            = "tmh",
                                     Part2B        = "tmh",
                                     Part2T        = "tmh",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Tamashek"
                                 }, new {Id = "tmi", Scope = "I", Type = "L", ReferenceName = "Tutuba"},
                                 new {Id    = "tmj", Scope = "I", Type = "L", ReferenceName = "Samarokena"},
                                 new {Id    = "tmk", Scope = "I", Type = "L", ReferenceName = "Northwestern Tamang"},
                                 new {Id    = "tml", Scope = "I", Type = "L", ReferenceName = "Tamnim Citak"},
                                 new {Id    = "tmm", Scope = "I", Type = "L", ReferenceName = "Tai Thanh"},
                                 new {Id    = "tmn", Scope = "I", Type = "L", ReferenceName = "Taman (Indonesia)"},
                                 new {Id    = "tmo", Scope = "I", Type = "L", ReferenceName = "Temoq"},
                                 new {Id    = "tmq", Scope = "I", Type = "L", ReferenceName = "Tumleo"},
                                 new
                                 {
                                     Id            = "tmr",
                                     Scope         = "I",
                                     Type          = "E",
                                     ReferenceName = "Jewish Babylonian Aramaic (ca. 200-1200 CE)"
                                 }, new {Id = "tms", Scope = "I", Type = "L", ReferenceName = "Tima"},
                                 new {Id    = "tmt", Scope = "I", Type = "L", ReferenceName = "Tasmate"},
                                 new {Id    = "tmu", Scope = "I", Type = "L", ReferenceName = "Iau"},
                                 new {Id    = "tmv", Scope = "I", Type = "L", ReferenceName = "Tembo (Motembo)"},
                                 new {Id    = "tmw", Scope = "I", Type = "L", ReferenceName = "Temuan"},
                                 new {Id    = "tmy", Scope = "I", Type = "L", ReferenceName = "Tami"},
                                 new {Id    = "tmz", Scope = "I", Type = "E", ReferenceName = "Tamanaku"},
                                 new {Id    = "tna", Scope = "I", Type = "L", ReferenceName = "Tacana"},
                                 new {Id    = "tnb", Scope = "I", Type = "L", ReferenceName = "Western Tunebo"},
                                 new {Id    = "tnc", Scope = "I", Type = "L", ReferenceName = "Tanimuca-Retuarã"},
                                 new {Id    = "tnd", Scope = "I", Type = "L", ReferenceName = "Angosturas Tunebo"},
                                 new {Id    = "tng", Scope = "I", Type = "L", ReferenceName = "Tobanga"},
                                 new {Id    = "tnh", Scope = "I", Type = "L", ReferenceName = "Maiani"},
                                 new {Id    = "tni", Scope = "I", Type = "L", ReferenceName = "Tandia"},
                                 new {Id    = "tnk", Scope = "I", Type = "L", ReferenceName = "Kwamera"},
                                 new {Id    = "tnl", Scope = "I", Type = "L", ReferenceName = "Lenakel"},
                                 new {Id    = "tnm", Scope = "I", Type = "L", ReferenceName = "Tabla"},
                                 new {Id    = "tnn", Scope = "I", Type = "L", ReferenceName = "North Tanna"},
                                 new {Id    = "tno", Scope = "I", Type = "L", ReferenceName = "Toromono"},
                                 new {Id    = "tnp", Scope = "I", Type = "L", ReferenceName = "Whitesands"},
                                 new {Id    = "tnq", Scope = "I", Type = "E", ReferenceName = "Taino"},
                                 new {Id    = "tnr", Scope = "I", Type = "L", ReferenceName = "Ménik"},
                                 new {Id    = "tns", Scope = "I", Type = "L", ReferenceName = "Tenis"},
                                 new {Id    = "tnt", Scope = "I", Type = "L", ReferenceName = "Tontemboan"},
                                 new {Id    = "tnu", Scope = "I", Type = "L", ReferenceName = "Tay Khang"},
                                 new {Id    = "tnv", Scope = "I", Type = "L", ReferenceName = "Tangchangya"},
                                 new {Id    = "tnw", Scope = "I", Type = "L", ReferenceName = "Tonsawang"},
                                 new {Id    = "tnx", Scope = "I", Type = "L", ReferenceName = "Tanema"},
                                 new {Id    = "tny", Scope = "I", Type = "L", ReferenceName = "Tongwe"},
                                 new {Id    = "tnz", Scope = "I", Type = "L", ReferenceName = "Ten'edn"},
                                 new {Id    = "tob", Scope = "I", Type = "L", ReferenceName = "Toba"},
                                 new {Id    = "toc", Scope = "I", Type = "L", ReferenceName = "Coyutla Totonac"},
                                 new {Id    = "tod", Scope = "I", Type = "L", ReferenceName = "Toma"},
                                 new {Id    = "tof", Scope = "I", Type = "L", ReferenceName = "Gizrra"},
                                 new
                                 {
                                     Id            = "tog",
                                     Part2B        = "tog",
                                     Part2T        = "tog",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tonga (Nyasa)"
                                 }, new {Id = "toh", Scope = "I", Type = "L", ReferenceName = "Gitonga"},
                                 new {Id    = "toi", Scope = "I", Type = "L", ReferenceName = "Tonga (Zambia)"},
                                 new {Id    = "toj", Scope = "I", Type = "L", ReferenceName = "Tojolabal"},
                                 new {Id    = "tol", Scope = "I", Type = "E", ReferenceName = "Tolowa"},
                                 new {Id    = "tom", Scope = "I", Type = "L", ReferenceName = "Tombulu"},
                                 new
                                 {
                                     Id            = "ton",
                                     Part2B        = "ton",
                                     Part2T        = "ton",
                                     Part1         = "to",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tonga (Tonga Islands)"
                                 },
                                 new
                                 {
                                     Id            = "too",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Xicotepec De Juárez Totonac"
                                 }, new {Id = "top", Scope = "I", Type = "L", ReferenceName = "Papantla Totonac"},
                                 new {Id    = "toq", Scope = "I", Type = "L", ReferenceName = "Toposa"},
                                 new {Id    = "tor", Scope = "I", Type = "L", ReferenceName = "Togbo-Vara Banda"},
                                 new {Id    = "tos", Scope = "I", Type = "L", ReferenceName = "Highland Totonac"},
                                 new {Id    = "tou", Scope = "I", Type = "L", ReferenceName = "Tho"},
                                 new {Id    = "tov", Scope = "I", Type = "L", ReferenceName = "Upper Taromi"},
                                 new {Id    = "tow", Scope = "I", Type = "L", ReferenceName = "Jemez"},
                                 new {Id    = "tox", Scope = "I", Type = "L", ReferenceName = "Tobian"},
                                 new {Id    = "toy", Scope = "I", Type = "L", ReferenceName = "Topoiyo"},
                                 new {Id    = "toz", Scope = "I", Type = "L", ReferenceName = "To"},
                                 new {Id    = "tpa", Scope = "I", Type = "L", ReferenceName = "Taupota"},
                                 new {Id    = "tpc", Scope = "I", Type = "L", ReferenceName = "Azoyú Me'phaa"},
                                 new {Id    = "tpe", Scope = "I", Type = "L", ReferenceName = "Tippera"},
                                 new {Id    = "tpf", Scope = "I", Type = "L", ReferenceName = "Tarpia"},
                                 new {Id    = "tpg", Scope = "I", Type = "L", ReferenceName = "Kula"},
                                 new
                                 {
                                     Id            = "tpi",
                                     Part2B        = "tpi",
                                     Part2T        = "tpi",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tok Pisin"
                                 }, new {Id = "tpj", Scope = "I", Type = "L", ReferenceName = "Tapieté"},
                                 new {Id    = "tpk", Scope = "I", Type = "E", ReferenceName = "Tupinikin"},
                                 new {Id    = "tpl", Scope = "I", Type = "L", ReferenceName = "Tlacoapa Me'phaa"},
                                 new {Id    = "tpm", Scope = "I", Type = "L", ReferenceName = "Tampulma"},
                                 new {Id    = "tpn", Scope = "I", Type = "E", ReferenceName = "Tupinambá"},
                                 new {Id    = "tpo", Scope = "I", Type = "L", ReferenceName = "Tai Pao"},
                                 new {Id    = "tpp", Scope = "I", Type = "L", ReferenceName = "Pisaflores Tepehua"},
                                 new {Id    = "tpq", Scope = "I", Type = "L", ReferenceName = "Tukpa"},
                                 new {Id    = "tpr", Scope = "I", Type = "L", ReferenceName = "Tuparí"},
                                 new {Id    = "tpt", Scope = "I", Type = "L", ReferenceName = "Tlachichilco Tepehua"},
                                 new {Id    = "tpu", Scope = "I", Type = "L", ReferenceName = "Tampuan"},
                                 new {Id    = "tpv", Scope = "I", Type = "L", ReferenceName = "Tanapag"},
                                 new {Id    = "tpw", Scope = "I", Type = "E", ReferenceName = "Tupí"},
                                 new {Id    = "tpx", Scope = "I", Type = "L", ReferenceName = "Acatepec Me'phaa"},
                                 new {Id    = "tpy", Scope = "I", Type = "L", ReferenceName = "Trumai"},
                                 new {Id    = "tpz", Scope = "I", Type = "L", ReferenceName = "Tinputz"},
                                 new {Id    = "tqb", Scope = "I", Type = "L", ReferenceName = "Tembé"},
                                 new {Id    = "tql", Scope = "I", Type = "L", ReferenceName = "Lehali"},
                                 new {Id    = "tqm", Scope = "I", Type = "L", ReferenceName = "Turumsa"},
                                 new {Id    = "tqn", Scope = "I", Type = "L", ReferenceName = "Tenino"},
                                 new {Id    = "tqo", Scope = "I", Type = "L", ReferenceName = "Toaripi"},
                                 new {Id    = "tqp", Scope = "I", Type = "L", ReferenceName = "Tomoip"},
                                 new {Id    = "tqq", Scope = "I", Type = "L", ReferenceName = "Tunni"},
                                 new {Id    = "tqr", Scope = "I", Type = "E", ReferenceName = "Torona"},
                                 new {Id    = "tqt", Scope = "I", Type = "L", ReferenceName = "Western Totonac"},
                                 new {Id    = "tqu", Scope = "I", Type = "L", ReferenceName = "Touo"},
                                 new {Id    = "tqw", Scope = "I", Type = "E", ReferenceName = "Tonkawa"},
                                 new {Id    = "tra", Scope = "I", Type = "L", ReferenceName = "Tirahi"},
                                 new {Id    = "trb", Scope = "I", Type = "L", ReferenceName = "Terebu"},
                                 new {Id    = "trc", Scope = "I", Type = "L", ReferenceName = "Copala Triqui"},
                                 new {Id    = "trd", Scope = "I", Type = "L", ReferenceName = "Turi"},
                                 new {Id    = "tre", Scope = "I", Type = "L", ReferenceName = "East Tarangan"},
                                 new
                                 {
                                     Id            = "trf",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Trinidadian Creole English"
                                 }, new {Id = "trg", Scope = "I", Type = "L", ReferenceName = "Lishán Didán"},
                                 new {Id    = "trh", Scope = "I", Type = "L", ReferenceName = "Turaka"},
                                 new {Id    = "tri", Scope = "I", Type = "L", ReferenceName = "Trió"},
                                 new {Id    = "trj", Scope = "I", Type = "L", ReferenceName = "Toram"},
                                 new {Id    = "trl", Scope = "I", Type = "L", ReferenceName = "Traveller Scottish"},
                                 new {Id    = "trm", Scope = "I", Type = "L", ReferenceName = "Tregami"},
                                 new {Id    = "trn", Scope = "I", Type = "L", ReferenceName = "Trinitario"},
                                 new {Id    = "tro", Scope = "I", Type = "L", ReferenceName = "Tarao Naga"},
                                 new {Id    = "trp", Scope = "I", Type = "L", ReferenceName = "Kok Borok"},
                                 new
                                 {
                                     Id            = "trq",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "San Martín Itunyoso Triqui"
                                 }, new {Id = "trr", Scope = "I", Type = "L", ReferenceName = "Taushiro"},
                                 new
                                     {
                                         Id            = "trs",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Chicahuaxtla Triqui"
                                     },
                                 new {Id = "trt", Scope = "I", Type = "L", ReferenceName = "Tunggare"},
                                 new {Id = "tru", Scope = "I", Type = "L", ReferenceName = "Turoyo"},
                                 new {Id = "trv", Scope = "I", Type = "L", ReferenceName = "Taroko"},
                                 new {Id = "trw", Scope = "I", Type = "L", ReferenceName = "Torwali"},
                                 new
                                     {
                                         Id            = "trx",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Tringgus-Sembaan Bidayuh"
                                     },
                                 new {Id = "try", Scope = "I", Type = "E", ReferenceName = "Turung"},
                                 new {Id = "trz", Scope = "I", Type = "E", ReferenceName = "Torá"},
                                 new {Id = "tsa", Scope = "I", Type = "L", ReferenceName = "Tsaangi"},
                                 new {Id = "tsb", Scope = "I", Type = "L", ReferenceName = "Tsamai"},
                                 new {Id = "tsc", Scope = "I", Type = "L", ReferenceName = "Tswa"},
                                 new {Id = "tsd", Scope = "I", Type = "L", ReferenceName = "Tsakonian"},
                                 new
                                     {
                                         Id            = "tse",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Tunisian Sign Language"
                                     },
                                 new {Id = "tsg", Scope = "I", Type = "L", ReferenceName = "Tausug"},
                                 new {Id = "tsh", Scope = "I", Type = "L", ReferenceName = "Tsuvan"},
                                 new
                                 {
                                     Id            = "tsi",
                                     Part2B        = "tsi",
                                     Part2T        = "tsi",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tsimshian"
                                 }, new {Id = "tsj", Scope = "I", Type = "L", ReferenceName = "Tshangla"},
                                 new {Id    = "tsk", Scope = "I", Type = "L", ReferenceName = "Tseku"},
                                 new {Id    = "tsl", Scope = "I", Type = "L", ReferenceName = "Ts'ün-Lao"},
                                 new {Id    = "tsm", Scope = "I", Type = "L", ReferenceName = "Turkish Sign Language"},
                                 new
                                 {
                                     Id            = "tsn",
                                     Part2B        = "tsn",
                                     Part2T        = "tsn",
                                     Part1         = "tn",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tswana"
                                 }, new
                                 {
                                     Id            = "tso",
                                     Part2B        = "tso",
                                     Part2T        = "tso",
                                     Part1         = "ts",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tsonga"
                                 }, new {Id = "tsp", Scope = "I", Type = "L", ReferenceName = "Northern Toussian"},
                                 new {Id    = "tsq", Scope = "I", Type = "L", ReferenceName = "Thai Sign Language"},
                                 new {Id    = "tsr", Scope = "I", Type = "L", ReferenceName = "Akei"},
                                 new {Id    = "tss", Scope = "I", Type = "L", ReferenceName = "Taiwan Sign Language"},
                                 new {Id    = "tst", Scope = "I", Type = "L", ReferenceName = "Tondi Songway Kiini"},
                                 new {Id    = "tsu", Scope = "I", Type = "L", ReferenceName = "Tsou"},
                                 new {Id    = "tsv", Scope = "I", Type = "L", ReferenceName = "Tsogo"},
                                 new {Id    = "tsw", Scope = "I", Type = "L", ReferenceName = "Tsishingini"},
                                 new {Id    = "tsx", Scope = "I", Type = "L", ReferenceName = "Mubami"},
                                 new {Id    = "tsy", Scope = "I", Type = "L", ReferenceName = "Tebul Sign Language"},
                                 new {Id    = "tsz", Scope = "I", Type = "L", ReferenceName = "Purepecha"},
                                 new {Id    = "tta", Scope = "I", Type = "E", ReferenceName = "Tutelo"},
                                 new {Id    = "ttb", Scope = "I", Type = "L", ReferenceName = "Gaa"},
                                 new {Id    = "ttc", Scope = "I", Type = "L", ReferenceName = "Tektiteko"},
                                 new {Id    = "ttd", Scope = "I", Type = "L", ReferenceName = "Tauade"},
                                 new {Id    = "tte", Scope = "I", Type = "L", ReferenceName = "Bwanabwana"},
                                 new {Id    = "ttf", Scope = "I", Type = "L", ReferenceName = "Tuotomb"},
                                 new {Id    = "ttg", Scope = "I", Type = "L", ReferenceName = "Tutong"},
                                 new {Id    = "tth", Scope = "I", Type = "L", ReferenceName = "Upper Ta'oih"},
                                 new {Id    = "tti", Scope = "I", Type = "L", ReferenceName = "Tobati"},
                                 new {Id    = "ttj", Scope = "I", Type = "L", ReferenceName = "Tooro"},
                                 new {Id    = "ttk", Scope = "I", Type = "L", ReferenceName = "Totoro"},
                                 new {Id    = "ttl", Scope = "I", Type = "L", ReferenceName = "Totela"},
                                 new {Id    = "ttm", Scope = "I", Type = "L", ReferenceName = "Northern Tutchone"},
                                 new {Id    = "ttn", Scope = "I", Type = "L", ReferenceName = "Towei"},
                                 new {Id    = "tto", Scope = "I", Type = "L", ReferenceName = "Lower Ta'oih"},
                                 new {Id    = "ttp", Scope = "I", Type = "L", ReferenceName = "Tombelala"},
                                 new {Id    = "ttq", Scope = "I", Type = "L", ReferenceName = "Tawallammat Tamajaq"},
                                 new {Id    = "ttr", Scope = "I", Type = "L", ReferenceName = "Tera"},
                                 new {Id    = "tts", Scope = "I", Type = "L", ReferenceName = "Northeastern Thai"},
                                 new {Id    = "ttt", Scope = "I", Type = "L", ReferenceName = "Muslim Tat"},
                                 new {Id    = "ttu", Scope = "I", Type = "L", ReferenceName = "Torau"},
                                 new {Id    = "ttv", Scope = "I", Type = "L", ReferenceName = "Titan"},
                                 new {Id    = "ttw", Scope = "I", Type = "L", ReferenceName = "Long Wat"},
                                 new {Id    = "tty", Scope = "I", Type = "L", ReferenceName = "Sikaritai"},
                                 new {Id    = "ttz", Scope = "I", Type = "L", ReferenceName = "Tsum"},
                                 new {Id    = "tua", Scope = "I", Type = "L", ReferenceName = "Wiarumus"},
                                 new {Id    = "tub", Scope = "I", Type = "E", ReferenceName = "Tübatulabal"},
                                 new {Id    = "tuc", Scope = "I", Type = "L", ReferenceName = "Mutu"},
                                 new {Id    = "tud", Scope = "I", Type = "E", ReferenceName = "Tuxá"},
                                 new {Id    = "tue", Scope = "I", Type = "L", ReferenceName = "Tuyuca"},
                                 new {Id    = "tuf", Scope = "I", Type = "L", ReferenceName = "Central Tunebo"},
                                 new {Id    = "tug", Scope = "I", Type = "L", ReferenceName = "Tunia"},
                                 new {Id    = "tuh", Scope = "I", Type = "L", ReferenceName = "Taulil"},
                                 new {Id    = "tui", Scope = "I", Type = "L", ReferenceName = "Tupuri"},
                                 new {Id    = "tuj", Scope = "I", Type = "L", ReferenceName = "Tugutil"},
                                 new
                                 {
                                     Id            = "tuk",
                                     Part2B        = "tuk",
                                     Part2T        = "tuk",
                                     Part1         = "tk",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Turkmen"
                                 }, new {Id = "tul", Scope = "I", Type = "L", ReferenceName = "Tula"},
                                 new
                                 {
                                     Id            = "tum",
                                     Part2B        = "tum",
                                     Part2T        = "tum",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tumbuka"
                                 }, new {Id = "tun", Scope = "I", Type = "L", ReferenceName = "Tunica"},
                                 new {Id    = "tuo", Scope = "I", Type = "L", ReferenceName = "Tucano"},
                                 new {Id    = "tuq", Scope = "I", Type = "L", ReferenceName = "Tedaga"},
                                 new
                                 {
                                     Id            = "tur",
                                     Part2B        = "tur",
                                     Part2T        = "tur",
                                     Part1         = "tr",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Turkish"
                                 }, new {Id = "tus", Scope = "I", Type = "L", ReferenceName = "Tuscarora"},
                                 new {Id    = "tuu", Scope = "I", Type = "L", ReferenceName = "Tututni"},
                                 new {Id    = "tuv", Scope = "I", Type = "L", ReferenceName = "Turkana"},
                                 new {Id    = "tux", Scope = "I", Type = "E", ReferenceName = "Tuxináwa"},
                                 new {Id    = "tuy", Scope = "I", Type = "L", ReferenceName = "Tugen"},
                                 new {Id    = "tuz", Scope = "I", Type = "L", ReferenceName = "Turka"},
                                 new {Id    = "tva", Scope = "I", Type = "L", ReferenceName = "Vaghua"},
                                 new {Id    = "tvd", Scope = "I", Type = "L", ReferenceName = "Tsuvadi"},
                                 new {Id    = "tve", Scope = "I", Type = "L", ReferenceName = "Te'un"},
                                 new {Id    = "tvk", Scope = "I", Type = "L", ReferenceName = "Southeast Ambrym"},
                                 new
                                 {
                                     Id            = "tvl",
                                     Part2B        = "tvl",
                                     Part2T        = "tvl",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tuvalu"
                                 }, new {Id = "tvm", Scope = "I", Type = "L", ReferenceName = "Tela-Masbuar"},
                                 new {Id    = "tvn", Scope = "I", Type = "L", ReferenceName = "Tavoyan"},
                                 new {Id    = "tvo", Scope = "I", Type = "L", ReferenceName = "Tidore"},
                                 new {Id    = "tvs", Scope = "I", Type = "L", ReferenceName = "Taveta"},
                                 new {Id    = "tvt", Scope = "I", Type = "L", ReferenceName = "Tutsa Naga"},
                                 new {Id    = "tvu", Scope = "I", Type = "L", ReferenceName = "Tunen"},
                                 new {Id    = "tvw", Scope = "I", Type = "L", ReferenceName = "Sedoa"},
                                 new {Id    = "tvx", Scope = "I", Type = "E", ReferenceName = "Taivoan"},
                                 new {Id    = "tvy", Scope = "I", Type = "E", ReferenceName = "Timor Pidgin"},
                                 new {Id    = "twa", Scope = "I", Type = "E", ReferenceName = "Twana"},
                                 new {Id    = "twb", Scope = "I", Type = "L", ReferenceName = "Western Tawbuid"},
                                 new {Id    = "twc", Scope = "I", Type = "E", ReferenceName = "Teshenawa"},
                                 new {Id    = "twd", Scope = "I", Type = "L", ReferenceName = "Twents"},
                                 new {Id    = "twe", Scope = "I", Type = "L", ReferenceName = "Tewa (Indonesia)"},
                                 new {Id    = "twf", Scope = "I", Type = "L", ReferenceName = "Northern Tiwa"},
                                 new {Id    = "twg", Scope = "I", Type = "L", ReferenceName = "Tereweng"},
                                 new {Id    = "twh", Scope = "I", Type = "L", ReferenceName = "Tai Dón"},
                                 new
                                 {
                                     Id            = "twi",
                                     Part2B        = "twi",
                                     Part2T        = "twi",
                                     Part1         = "tw",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Twi"
                                 }, new {Id = "twl", Scope = "I", Type = "L", ReferenceName = "Tawara"},
                                 new {Id    = "twm", Scope = "I", Type = "L", ReferenceName = "Tawang Monpa"},
                                 new {Id    = "twn", Scope = "I", Type = "L", ReferenceName = "Twendi"},
                                 new {Id    = "two", Scope = "I", Type = "L", ReferenceName = "Tswapong"},
                                 new {Id    = "twp", Scope = "I", Type = "L", ReferenceName = "Ere"},
                                 new {Id    = "twq", Scope = "I", Type = "L", ReferenceName = "Tasawaq"},
                                 new
                                     {
                                         Id            = "twr",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Southwestern Tarahumara"
                                     },
                                 new {Id = "twt", Scope = "I", Type = "E", ReferenceName = "Turiwára"},
                                 new {Id = "twu", Scope = "I", Type = "L", ReferenceName = "Termanu"},
                                 new {Id = "tww", Scope = "I", Type = "L", ReferenceName = "Tuwari"},
                                 new {Id = "twx", Scope = "I", Type = "L", ReferenceName = "Tewe"},
                                 new {Id = "twy", Scope = "I", Type = "L", ReferenceName = "Tawoyan"},
                                 new {Id = "txa", Scope = "I", Type = "L", ReferenceName = "Tombonuo"},
                                 new {Id = "txb", Scope = "I", Type = "A", ReferenceName = "Tokharian B"},
                                 new {Id = "txc", Scope = "I", Type = "E", ReferenceName = "Tsetsaut"},
                                 new {Id = "txe", Scope = "I", Type = "L", ReferenceName = "Totoli"},
                                 new {Id = "txg", Scope = "I", Type = "A", ReferenceName = "Tangut"},
                                 new {Id = "txh", Scope = "I", Type = "A", ReferenceName = "Thracian"},
                                 new {Id = "txi", Scope = "I", Type = "L", ReferenceName = "Ikpeng"},
                                 new {Id = "txj", Scope = "I", Type = "L", ReferenceName = "Tarjumo"},
                                 new {Id = "txm", Scope = "I", Type = "L", ReferenceName = "Tomini"},
                                 new {Id = "txn", Scope = "I", Type = "L", ReferenceName = "West Tarangan"},
                                 new {Id = "txo", Scope = "I", Type = "L", ReferenceName = "Toto"},
                                 new {Id = "txq", Scope = "I", Type = "L", ReferenceName = "Tii"},
                                 new {Id = "txr", Scope = "I", Type = "A", ReferenceName = "Tartessian"},
                                 new {Id = "txs", Scope = "I", Type = "L", ReferenceName = "Tonsea"},
                                 new {Id = "txt", Scope = "I", Type = "L", ReferenceName = "Citak"},
                                 new {Id = "txu", Scope = "I", Type = "L", ReferenceName = "Kayapó"},
                                 new {Id = "txx", Scope = "I", Type = "L", ReferenceName = "Tatana"},
                                 new {Id = "txy", Scope = "I", Type = "L", ReferenceName = "Tanosy Malagasy"},
                                 new {Id = "tya", Scope = "I", Type = "L", ReferenceName = "Tauya"},
                                 new {Id = "tye", Scope = "I", Type = "L", ReferenceName = "Kyanga"},
                                 new {Id = "tyh", Scope = "I", Type = "L", ReferenceName = "O'du"},
                                 new {Id = "tyi", Scope = "I", Type = "L", ReferenceName = "Teke-Tsaayi"},
                                 new {Id = "tyj", Scope = "I", Type = "L", ReferenceName = "Tai Do"},
                                 new {Id = "tyl", Scope = "I", Type = "L", ReferenceName = "Thu Lao"},
                                 new {Id = "tyn", Scope = "I", Type = "L", ReferenceName = "Kombai"},
                                 new {Id = "typ", Scope = "I", Type = "E", ReferenceName = "Thaypan"},
                                 new {Id = "tyr", Scope = "I", Type = "L", ReferenceName = "Tai Daeng"},
                                 new {Id = "tys", Scope = "I", Type = "L", ReferenceName = "Tày Sa Pa"},
                                 new {Id = "tyt", Scope = "I", Type = "L", ReferenceName = "Tày Tac"},
                                 new {Id = "tyu", Scope = "I", Type = "L", ReferenceName = "Kua"},
                                 new
                                 {
                                     Id            = "tyv",
                                     Part2B        = "tyv",
                                     Part2T        = "tyv",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Tuvinian"
                                 }, new {Id = "tyx", Scope = "I", Type = "L", ReferenceName = "Teke-Tyee"},
                                 new {Id    = "tyz", Scope = "I", Type = "L", ReferenceName = "Tày"},
                                 new
                                     {
                                         Id            = "tza",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Tanzanian Sign Language"
                                     },
                                 new {Id = "tzh", Scope = "I", Type = "L", ReferenceName = "Tzeltal"},
                                 new {Id = "tzj", Scope = "I", Type = "L", ReferenceName = "Tz'utujil"},
                                 new {Id = "tzl", Scope = "I", Type = "C", ReferenceName = "Talossan"},
                                 new
                                     {
                                         Id            = "tzm",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Central Atlas Tamazight"
                                     },
                                 new {Id = "tzn", Scope = "I", Type = "L", ReferenceName = "Tugun"},
                                 new {Id = "tzo", Scope = "I", Type = "L", ReferenceName = "Tzotzil"},
                                 new {Id = "tzx", Scope = "I", Type = "L", ReferenceName = "Tabriak"});
        }
    }
}