using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class W
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(new {Id = "waa", Scope = "I", Type = "L", ReferenceName = "Walla Walla"},
                                 new {Id = "wab", Scope = "I", Type = "L", ReferenceName = "Wab"},
                                 new {Id = "wac", Scope = "I", Type = "E", ReferenceName = "Wasco-Wishram"},
                                 new {Id = "wad", Scope = "I", Type = "L", ReferenceName = "Wandamen"},
                                 new {Id = "wae", Scope = "I", Type = "L", ReferenceName = "Walser"},
                                 new {Id = "waf", Scope = "I", Type = "E", ReferenceName = "Wakoná"},
                                 new {Id = "wag", Scope = "I", Type = "L", ReferenceName = "Wa'ema"},
                                 new {Id = "wah", Scope = "I", Type = "L", ReferenceName = "Watubela"},
                                 new {Id = "wai", Scope = "I", Type = "L", ReferenceName = "Wares"},
                                 new {Id = "waj", Scope = "I", Type = "L", ReferenceName = "Waffa"},
                                 new
                                 {
                                     Id            = "wal",
                                     Part2B        = "wal",
                                     Part2T        = "wal",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Wolaytta"
                                 }, new {Id = "wam", Scope = "I", Type = "E", ReferenceName = "Wampanoag"},
                                 new {Id    = "wan", Scope = "I", Type = "L", ReferenceName = "Wan"},
                                 new {Id    = "wao", Scope = "I", Type = "E", ReferenceName = "Wappo"},
                                 new {Id    = "wap", Scope = "I", Type = "L", ReferenceName = "Wapishana"},
                                 new {Id    = "waq", Scope = "I", Type = "L", ReferenceName = "Wagiman"},
                                 new
                                 {
                                     Id            = "war",
                                     Part2B        = "war",
                                     Part2T        = "war",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Waray (Philippines)"
                                 }, new
                                 {
                                     Id            = "was",
                                     Part2B        = "was",
                                     Part2T        = "was",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Washo"
                                 }, new {Id = "wat", Scope = "I", Type = "L", ReferenceName = "Kaninuwa"},
                                 new {Id    = "wau", Scope = "I", Type = "L", ReferenceName = "Waurá"},
                                 new {Id    = "wav", Scope = "I", Type = "L", ReferenceName = "Waka"},
                                 new {Id    = "waw", Scope = "I", Type = "L", ReferenceName = "Waiwai"},
                                 new {Id    = "wax", Scope = "I", Type = "L", ReferenceName = "Watam"},
                                 new {Id    = "way", Scope = "I", Type = "L", ReferenceName = "Wayana"},
                                 new {Id    = "waz", Scope = "I", Type = "L", ReferenceName = "Wampur"},
                                 new {Id    = "wba", Scope = "I", Type = "L", ReferenceName = "Warao"},
                                 new {Id    = "wbb", Scope = "I", Type = "L", ReferenceName = "Wabo"},
                                 new {Id    = "wbe", Scope = "I", Type = "L", ReferenceName = "Waritai"},
                                 new {Id    = "wbf", Scope = "I", Type = "L", ReferenceName = "Wara"},
                                 new {Id    = "wbh", Scope = "I", Type = "L", ReferenceName = "Wanda"},
                                 new {Id    = "wbi", Scope = "I", Type = "L", ReferenceName = "Vwanji"},
                                 new {Id    = "wbj", Scope = "I", Type = "L", ReferenceName = "Alagwa"},
                                 new {Id    = "wbk", Scope = "I", Type = "L", ReferenceName = "Waigali"},
                                 new {Id    = "wbl", Scope = "I", Type = "L", ReferenceName = "Wakhi"},
                                 new {Id    = "wbm", Scope = "I", Type = "L", ReferenceName = "Wa"},
                                 new {Id    = "wbp", Scope = "I", Type = "L", ReferenceName = "Warlpiri"},
                                 new {Id    = "wbq", Scope = "I", Type = "L", ReferenceName = "Waddar"},
                                 new {Id    = "wbr", Scope = "I", Type = "L", ReferenceName = "Wagdi"},
                                 new
                                     {
                                         Id            = "wbs",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "West Bengal Sign Language"
                                     },
                                 new {Id = "wbt", Scope = "I", Type = "L", ReferenceName = "Warnman"},
                                 new {Id = "wbv", Scope = "I", Type = "L", ReferenceName = "Wajarri"},
                                 new {Id = "wbw", Scope = "I", Type = "L", ReferenceName = "Woi"},
                                 new {Id = "wca", Scope = "I", Type = "L", ReferenceName = "Yanomámi"},
                                 new {Id = "wci", Scope = "I", Type = "L", ReferenceName = "Waci Gbe"},
                                 new {Id = "wdd", Scope = "I", Type = "L", ReferenceName = "Wandji"},
                                 new {Id = "wdg", Scope = "I", Type = "L", ReferenceName = "Wadaginam"},
                                 new {Id = "wdj", Scope = "I", Type = "L", ReferenceName = "Wadjiginy"},
                                 new {Id = "wdk", Scope = "I", Type = "E", ReferenceName = "Wadikali"},
                                 new {Id = "wdu", Scope = "I", Type = "E", ReferenceName = "Wadjigu"},
                                 new {Id = "wdy", Scope = "I", Type = "E", ReferenceName = "Wadjabangayi"},
                                 new {Id = "wea", Scope = "I", Type = "E", ReferenceName = "Wewaw"},
                                 new {Id = "wec", Scope = "I", Type = "L", ReferenceName = "Wè Western"},
                                 new {Id = "wed", Scope = "I", Type = "L", ReferenceName = "Wedau"},
                                 new {Id = "weg", Scope = "I", Type = "L", ReferenceName = "Wergaia"},
                                 new {Id = "weh", Scope = "I", Type = "L", ReferenceName = "Weh"},
                                 new {Id = "wei", Scope = "I", Type = "L", ReferenceName = "Kiunum"},
                                 new {Id = "wem", Scope = "I", Type = "L", ReferenceName = "Weme Gbe"},
                                 new {Id = "weo", Scope = "I", Type = "L", ReferenceName = "Wemale"},
                                 new {Id = "wep", Scope = "I", Type = "L", ReferenceName = "Westphalien"},
                                 new {Id = "wer", Scope = "I", Type = "L", ReferenceName = "Weri"},
                                 new {Id = "wes", Scope = "I", Type = "L", ReferenceName = "Cameroon Pidgin"},
                                 new {Id = "wet", Scope = "I", Type = "L", ReferenceName = "Perai"},
                                 new {Id = "weu", Scope = "I", Type = "L", ReferenceName = "Rawngtu Chin"},
                                 new {Id = "wew", Scope = "I", Type = "L", ReferenceName = "Wejewa"},
                                 new {Id = "wfg", Scope = "I", Type = "L", ReferenceName = "Yafi"},
                                 new {Id = "wga", Scope = "I", Type = "E", ReferenceName = "Wagaya"},
                                 new {Id = "wgb", Scope = "I", Type = "L", ReferenceName = "Wagawaga"},
                                 new {Id = "wgg", Scope = "I", Type = "E", ReferenceName = "Wangkangurru"},
                                 new {Id = "wgi", Scope = "I", Type = "L", ReferenceName = "Wahgi"},
                                 new {Id = "wgo", Scope = "I", Type = "L", ReferenceName = "Waigeo"},
                                 new {Id = "wgu", Scope = "I", Type = "E", ReferenceName = "Wirangu"},
                                 new {Id = "wgy", Scope = "I", Type = "L", ReferenceName = "Warrgamay"},
                                 new {Id = "wha", Scope = "I", Type = "L", ReferenceName = "Sou Upaa"},
                                 new {Id = "whg", Scope = "I", Type = "L", ReferenceName = "North Wahgi"},
                                 new {Id = "whk", Scope = "I", Type = "L", ReferenceName = "Wahau Kenyah"},
                                 new {Id = "whu", Scope = "I", Type = "L", ReferenceName = "Wahau Kayan"},
                                 new {Id = "wib", Scope = "I", Type = "L", ReferenceName = "Southern Toussian"},
                                 new {Id = "wic", Scope = "I", Type = "E", ReferenceName = "Wichita"},
                                 new {Id = "wie", Scope = "I", Type = "E", ReferenceName = "Wik-Epa"},
                                 new {Id = "wif", Scope = "I", Type = "E", ReferenceName = "Wik-Keyangan"},
                                 new {Id = "wig", Scope = "I", Type = "L", ReferenceName = "Wik Ngathan"},
                                 new {Id = "wih", Scope = "I", Type = "L", ReferenceName = "Wik-Me'anha"},
                                 new {Id = "wii", Scope = "I", Type = "L", ReferenceName = "Minidien"},
                                 new {Id = "wij", Scope = "I", Type = "L", ReferenceName = "Wik-Iiyanh"},
                                 new {Id = "wik", Scope = "I", Type = "L", ReferenceName = "Wikalkan"},
                                 new {Id = "wil", Scope = "I", Type = "E", ReferenceName = "Wilawila"},
                                 new {Id = "wim", Scope = "I", Type = "L", ReferenceName = "Wik-Mungkan"},
                                 new {Id = "win", Scope = "I", Type = "L", ReferenceName = "Ho-Chunk"},
                                 new {Id = "wir", Scope = "I", Type = "E", ReferenceName = "Wiraféd"},
                                 new {Id = "wiu", Scope = "I", Type = "L", ReferenceName = "Wiru"},
                                 new {Id = "wiv", Scope = "I", Type = "L", ReferenceName = "Vitu"},
                                 new {Id = "wiy", Scope = "I", Type = "E", ReferenceName = "Wiyot"},
                                 new {Id = "wja", Scope = "I", Type = "L", ReferenceName = "Waja"},
                                 new {Id = "wji", Scope = "I", Type = "L", ReferenceName = "Warji"},
                                 new {Id = "wka", Scope = "I", Type = "E", ReferenceName = "Kw'adza"},
                                 new {Id = "wkb", Scope = "I", Type = "L", ReferenceName = "Kumbaran"},
                                 new {Id = "wkd", Scope = "I", Type = "L", ReferenceName = "Wakde"},
                                 new {Id = "wkl", Scope = "I", Type = "L", ReferenceName = "Kalanadi"},
                                 new {Id = "wkr", Scope = "I", Type = "L", ReferenceName = "Keerray-Woorroong"},
                                 new {Id = "wku", Scope = "I", Type = "L", ReferenceName = "Kunduvadi"},
                                 new {Id = "wkw", Scope = "I", Type = "E", ReferenceName = "Wakawaka"},
                                 new {Id = "wky", Scope = "I", Type = "E", ReferenceName = "Wangkayutyuru"},
                                 new {Id = "wla", Scope = "I", Type = "L", ReferenceName = "Walio"},
                                 new {Id = "wlc", Scope = "I", Type = "L", ReferenceName = "Mwali Comorian"},
                                 new {Id = "wle", Scope = "I", Type = "L", ReferenceName = "Wolane"},
                                 new {Id = "wlg", Scope = "I", Type = "L", ReferenceName = "Kunbarlang"},
                                 new {Id = "wli", Scope = "I", Type = "L", ReferenceName = "Waioli"},
                                 new {Id = "wlk", Scope = "I", Type = "E", ReferenceName = "Wailaki"},
                                 new {Id = "wll", Scope = "I", Type = "L", ReferenceName = "Wali (Sudan)"},
                                 new {Id = "wlm", Scope = "I", Type = "H", ReferenceName = "Middle Welsh"},
                                 new
                                 {
                                     Id            = "wln",
                                     Part2B        = "wln",
                                     Part2T        = "wln",
                                     Part1         = "wa",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Walloon"
                                 }, new {Id = "wlo", Scope = "I", Type = "L", ReferenceName = "Wolio"},
                                 new {Id    = "wlr", Scope = "I", Type = "L", ReferenceName = "Wailapa"},
                                 new {Id    = "wls", Scope = "I", Type = "L", ReferenceName = "Wallisian"},
                                 new {Id    = "wlu", Scope = "I", Type = "E", ReferenceName = "Wuliwuli"},
                                 new {Id    = "wlv", Scope = "I", Type = "L", ReferenceName = "Wichí Lhamtés Vejoz"},
                                 new {Id    = "wlw", Scope = "I", Type = "L", ReferenceName = "Walak"},
                                 new {Id    = "wlx", Scope = "I", Type = "L", ReferenceName = "Wali (Ghana)"},
                                 new {Id    = "wly", Scope = "I", Type = "E", ReferenceName = "Waling"},
                                 new {Id    = "wma", Scope = "I", Type = "E", ReferenceName = "Mawa (Nigeria)"},
                                 new {Id    = "wmb", Scope = "I", Type = "L", ReferenceName = "Wambaya"},
                                 new {Id    = "wmc", Scope = "I", Type = "L", ReferenceName = "Wamas"},
                                 new {Id    = "wmd", Scope = "I", Type = "L", ReferenceName = "Mamaindé"},
                                 new {Id    = "wme", Scope = "I", Type = "L", ReferenceName = "Wambule"},
                                 new {Id    = "wmh", Scope = "I", Type = "L", ReferenceName = "Waima'a"},
                                 new {Id    = "wmi", Scope = "I", Type = "E", ReferenceName = "Wamin"},
                                 new {Id    = "wmm", Scope = "I", Type = "L", ReferenceName = "Maiwa (Indonesia)"},
                                 new {Id    = "wmn", Scope = "I", Type = "E", ReferenceName = "Waamwang"},
                                 new {Id    = "wmo", Scope = "I", Type = "L", ReferenceName = "Wom (Papua New Guinea)"},
                                 new {Id    = "wms", Scope = "I", Type = "L", ReferenceName = "Wambon"},
                                 new {Id    = "wmt", Scope = "I", Type = "L", ReferenceName = "Walmajarri"},
                                 new {Id    = "wmw", Scope = "I", Type = "L", ReferenceName = "Mwani"},
                                 new {Id    = "wmx", Scope = "I", Type = "L", ReferenceName = "Womo"},
                                 new {Id    = "wnb", Scope = "I", Type = "L", ReferenceName = "Wanambre"},
                                 new {Id    = "wnc", Scope = "I", Type = "L", ReferenceName = "Wantoat"},
                                 new {Id    = "wnd", Scope = "I", Type = "E", ReferenceName = "Wandarang"},
                                 new {Id    = "wne", Scope = "I", Type = "L", ReferenceName = "Waneci"},
                                 new {Id    = "wng", Scope = "I", Type = "L", ReferenceName = "Wanggom"},
                                 new {Id    = "wni", Scope = "I", Type = "L", ReferenceName = "Ndzwani Comorian"},
                                 new {Id    = "wnk", Scope = "I", Type = "L", ReferenceName = "Wanukaka"},
                                 new {Id    = "wnm", Scope = "I", Type = "E", ReferenceName = "Wanggamala"},
                                 new {Id    = "wnn", Scope = "I", Type = "E", ReferenceName = "Wunumara"},
                                 new {Id    = "wno", Scope = "I", Type = "L", ReferenceName = "Wano"},
                                 new {Id    = "wnp", Scope = "I", Type = "L", ReferenceName = "Wanap"},
                                 new {Id    = "wnu", Scope = "I", Type = "L", ReferenceName = "Usan"},
                                 new {Id    = "wnw", Scope = "I", Type = "L", ReferenceName = "Wintu"},
                                 new {Id    = "wny", Scope = "I", Type = "L", ReferenceName = "Wanyi"},
                                 new {Id    = "woa", Scope = "I", Type = "L", ReferenceName = "Kuwema"},
                                 new {Id    = "wob", Scope = "I", Type = "L", ReferenceName = "Wè Northern"},
                                 new {Id    = "woc", Scope = "I", Type = "L", ReferenceName = "Wogeo"},
                                 new {Id    = "wod", Scope = "I", Type = "L", ReferenceName = "Wolani"},
                                 new {Id    = "woe", Scope = "I", Type = "L", ReferenceName = "Woleaian"},
                                 new {Id    = "wof", Scope = "I", Type = "L", ReferenceName = "Gambian Wolof"},
                                 new {Id    = "wog", Scope = "I", Type = "L", ReferenceName = "Wogamusin"},
                                 new {Id    = "woi", Scope = "I", Type = "L", ReferenceName = "Kamang"},
                                 new {Id    = "wok", Scope = "I", Type = "L", ReferenceName = "Longto"},
                                 new
                                 {
                                     Id            = "wol",
                                     Part2B        = "wol",
                                     Part2T        = "wol",
                                     Part1         = "wo",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Wolof"
                                 }, new {Id = "wom", Scope = "I", Type = "L", ReferenceName = "Wom (Nigeria)"},
                                 new {Id    = "won", Scope = "I", Type = "L", ReferenceName = "Wongo"},
                                 new {Id    = "woo", Scope = "I", Type = "L", ReferenceName = "Manombai"},
                                 new {Id    = "wor", Scope = "I", Type = "L", ReferenceName = "Woria"},
                                 new {Id    = "wos", Scope = "I", Type = "L", ReferenceName = "Hanga Hundi"},
                                 new {Id    = "wow", Scope = "I", Type = "L", ReferenceName = "Wawonii"},
                                 new {Id    = "woy", Scope = "I", Type = "E", ReferenceName = "Weyto"},
                                 new {Id    = "wpc", Scope = "I", Type = "L", ReferenceName = "Maco"},
                                 new {Id    = "wra", Scope = "I", Type = "L", ReferenceName = "Warapu"},
                                 new {Id    = "wrb", Scope = "I", Type = "E", ReferenceName = "Waluwarra"},
                                 new {Id    = "wrd", Scope = "I", Type = "L", ReferenceName = "Warduji"},
                                 new {Id    = "wrg", Scope = "I", Type = "E", ReferenceName = "Warungu"},
                                 new {Id    = "wrh", Scope = "I", Type = "E", ReferenceName = "Wiradjuri"},
                                 new {Id    = "wri", Scope = "I", Type = "E", ReferenceName = "Wariyangga"},
                                 new {Id    = "wrk", Scope = "I", Type = "L", ReferenceName = "Garrwa"},
                                 new {Id    = "wrl", Scope = "I", Type = "L", ReferenceName = "Warlmanpa"},
                                 new {Id    = "wrm", Scope = "I", Type = "L", ReferenceName = "Warumungu"},
                                 new {Id    = "wrn", Scope = "I", Type = "L", ReferenceName = "Warnang"},
                                 new {Id    = "wro", Scope = "I", Type = "E", ReferenceName = "Worrorra"},
                                 new {Id    = "wrp", Scope = "I", Type = "L", ReferenceName = "Waropen"},
                                 new {Id    = "wrr", Scope = "I", Type = "L", ReferenceName = "Wardaman"},
                                 new {Id    = "wrs", Scope = "I", Type = "L", ReferenceName = "Waris"},
                                 new {Id    = "wru", Scope = "I", Type = "L", ReferenceName = "Waru"},
                                 new {Id    = "wrv", Scope = "I", Type = "L", ReferenceName = "Waruna"},
                                 new {Id    = "wrw", Scope = "I", Type = "E", ReferenceName = "Gugu Warra"},
                                 new {Id    = "wrx", Scope = "I", Type = "L", ReferenceName = "Wae Rana"},
                                 new {Id    = "wry", Scope = "I", Type = "L", ReferenceName = "Merwari"},
                                 new {Id    = "wrz", Scope = "I", Type = "E", ReferenceName = "Waray (Australia)"},
                                 new {Id    = "wsa", Scope = "I", Type = "L", ReferenceName = "Warembori"},
                                 new {Id    = "wsg", Scope = "I", Type = "L", ReferenceName = "Adilabad Gondi"},
                                 new {Id    = "wsi", Scope = "I", Type = "L", ReferenceName = "Wusi"},
                                 new {Id    = "wsk", Scope = "I", Type = "L", ReferenceName = "Waskia"},
                                 new {Id    = "wsr", Scope = "I", Type = "L", ReferenceName = "Owenia"},
                                 new {Id    = "wss", Scope = "I", Type = "L", ReferenceName = "Wasa"},
                                 new {Id    = "wsu", Scope = "I", Type = "E", ReferenceName = "Wasu"},
                                 new {Id    = "wsv", Scope = "I", Type = "E", ReferenceName = "Wotapuri-Katarqalai"},
                                 new {Id    = "wtf", Scope = "I", Type = "L", ReferenceName = "Watiwa"},
                                 new {Id    = "wth", Scope = "I", Type = "E", ReferenceName = "Wathawurrung"},
                                 new {Id    = "wti", Scope = "I", Type = "L", ReferenceName = "Berta"},
                                 new {Id    = "wtk", Scope = "I", Type = "L", ReferenceName = "Watakataui"},
                                 new {Id    = "wtm", Scope = "I", Type = "L", ReferenceName = "Mewati"},
                                 new {Id    = "wtw", Scope = "I", Type = "L", ReferenceName = "Wotu"},
                                 new {Id    = "wua", Scope = "I", Type = "L", ReferenceName = "Wikngenchera"},
                                 new {Id    = "wub", Scope = "I", Type = "L", ReferenceName = "Wunambal"},
                                 new {Id    = "wud", Scope = "I", Type = "L", ReferenceName = "Wudu"},
                                 new {Id    = "wuh", Scope = "I", Type = "L", ReferenceName = "Wutunhua"},
                                 new {Id    = "wul", Scope = "I", Type = "L", ReferenceName = "Silimo"},
                                 new {Id    = "wum", Scope = "I", Type = "L", ReferenceName = "Wumbvu"},
                                 new {Id    = "wun", Scope = "I", Type = "L", ReferenceName = "Bungu"},
                                 new {Id    = "wur", Scope = "I", Type = "E", ReferenceName = "Wurrugu"},
                                 new {Id    = "wut", Scope = "I", Type = "L", ReferenceName = "Wutung"},
                                 new {Id    = "wuu", Scope = "I", Type = "L", ReferenceName = "Wu Chinese"},
                                 new {Id    = "wuv", Scope = "I", Type = "L", ReferenceName = "Wuvulu-Aua"},
                                 new {Id    = "wux", Scope = "I", Type = "L", ReferenceName = "Wulna"},
                                 new {Id    = "wuy", Scope = "I", Type = "L", ReferenceName = "Wauyai"},
                                 new {Id    = "wwa", Scope = "I", Type = "L", ReferenceName = "Waama"},
                                 new {Id    = "wwb", Scope = "I", Type = "E", ReferenceName = "Wakabunga"},
                                 new {Id    = "wwo", Scope = "I", Type = "L", ReferenceName = "Wetamut"},
                                 new {Id    = "wwr", Scope = "I", Type = "E", ReferenceName = "Warrwa"},
                                 new {Id    = "www", Scope = "I", Type = "L", ReferenceName = "Wawa"},
                                 new {Id    = "wxa", Scope = "I", Type = "L", ReferenceName = "Waxianghua"},
                                 new {Id    = "wxw", Scope = "I", Type = "E", ReferenceName = "Wardandi"},
                                 new {Id    = "wya", Scope = "I", Type = "L", ReferenceName = "Wyandot"},
                                 new {Id    = "wyb", Scope = "I", Type = "L", ReferenceName = "Wangaaybuwan-Ngiyambaa"},
                                 new {Id    = "wyi", Scope = "I", Type = "E", ReferenceName = "Woiwurrung"},
                                 new {Id    = "wym", Scope = "I", Type = "L", ReferenceName = "Wymysorys"},
                                 new {Id    = "wyr", Scope = "I", Type = "L", ReferenceName = "Wayoró"},
                                 new {Id    = "wyy", Scope = "I", Type = "L", ReferenceName = "Western Fijian"});
        }
    }
}