using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class X
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(new {Id = "xaa", Scope = "I", Type = "H", ReferenceName = "Andalusian Arabic"},
                                 new {Id = "xab", Scope = "I", Type = "L", ReferenceName = "Sambe"},
                                 new {Id = "xac", Scope = "I", Type = "L", ReferenceName = "Kachari"},
                                 new {Id = "xad", Scope = "I", Type = "E", ReferenceName = "Adai"},
                                 new {Id = "xae", Scope = "I", Type = "A", ReferenceName = "Aequian"},
                                 new {Id = "xag", Scope = "I", Type = "A", ReferenceName = "Aghwan"},
                                 new {Id = "xai", Scope = "I", Type = "E", ReferenceName = "Kaimbé"},
                                 new {Id = "xaj", Scope = "I", Type = "E", ReferenceName = "Ararandewára"},
                                 new {Id = "xak", Scope = "I", Type = "E", ReferenceName = "Máku"},
                                 new
                                 {
                                     Id            = "xal",
                                     Part2B        = "xal",
                                     Part2T        = "xal",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Kalmyk"
                                 }, new {Id = "xam", Scope = "I", Type = "E", ReferenceName = "ǀXam"},
                                 new {Id    = "xan", Scope = "I", Type = "L", ReferenceName = "Xamtanga"},
                                 new {Id    = "xao", Scope = "I", Type = "L", ReferenceName = "Khao"},
                                 new {Id    = "xap", Scope = "I", Type = "E", ReferenceName = "Apalachee"},
                                 new {Id    = "xaq", Scope = "I", Type = "A", ReferenceName = "Aquitanian"},
                                 new {Id    = "xar", Scope = "I", Type = "E", ReferenceName = "Karami"},
                                 new {Id    = "xas", Scope = "I", Type = "E", ReferenceName = "Kamas"},
                                 new {Id    = "xat", Scope = "I", Type = "L", ReferenceName = "Katawixi"},
                                 new {Id    = "xau", Scope = "I", Type = "L", ReferenceName = "Kauwera"},
                                 new {Id    = "xav", Scope = "I", Type = "L", ReferenceName = "Xavánte"},
                                 new {Id    = "xaw", Scope = "I", Type = "L", ReferenceName = "Kawaiisu"},
                                 new {Id    = "xay", Scope = "I", Type = "L", ReferenceName = "Kayan Mahakam"},
                                 new {Id    = "xbb", Scope = "I", Type = "E", ReferenceName = "Lower Burdekin"},
                                 new {Id    = "xbc", Scope = "I", Type = "A", ReferenceName = "Bactrian"},
                                 new {Id    = "xbd", Scope = "I", Type = "E", ReferenceName = "Bindal"},
                                 new {Id    = "xbe", Scope = "I", Type = "E", ReferenceName = "Bigambal"},
                                 new {Id    = "xbg", Scope = "I", Type = "E", ReferenceName = "Bunganditj"},
                                 new {Id    = "xbi", Scope = "I", Type = "L", ReferenceName = "Kombio"},
                                 new {Id    = "xbj", Scope = "I", Type = "E", ReferenceName = "Birrpayi"},
                                 new {Id    = "xbm", Scope = "I", Type = "H", ReferenceName = "Middle Breton"},
                                 new {Id    = "xbn", Scope = "I", Type = "E", ReferenceName = "Kenaboi"},
                                 new {Id    = "xbo", Scope = "I", Type = "H", ReferenceName = "Bolgarian"},
                                 new {Id    = "xbp", Scope = "I", Type = "E", ReferenceName = "Bibbulman"},
                                 new {Id    = "xbr", Scope = "I", Type = "L", ReferenceName = "Kambera"},
                                 new {Id    = "xbw", Scope = "I", Type = "E", ReferenceName = "Kambiwá"},
                                 new {Id    = "xby", Scope = "I", Type = "L", ReferenceName = "Batjala"},
                                 new {Id    = "xcb", Scope = "I", Type = "H", ReferenceName = "Cumbric"},
                                 new {Id    = "xcc", Scope = "I", Type = "A", ReferenceName = "Camunic"},
                                 new {Id    = "xce", Scope = "I", Type = "A", ReferenceName = "Celtiberian"},
                                 new {Id    = "xcg", Scope = "I", Type = "A", ReferenceName = "Cisalpine Gaulish"},
                                 new {Id    = "xch", Scope = "I", Type = "E", ReferenceName = "Chemakum"},
                                 new {Id    = "xcl", Scope = "I", Type = "H", ReferenceName = "Classical Armenian"},
                                 new {Id    = "xcm", Scope = "I", Type = "E", ReferenceName = "Comecrudo"},
                                 new {Id    = "xcn", Scope = "I", Type = "E", ReferenceName = "Cotoname"},
                                 new {Id    = "xco", Scope = "I", Type = "A", ReferenceName = "Chorasmian"},
                                 new {Id    = "xcr", Scope = "I", Type = "A", ReferenceName = "Carian"},
                                 new {Id    = "xct", Scope = "I", Type = "H", ReferenceName = "Classical Tibetan"},
                                 new {Id    = "xcu", Scope = "I", Type = "H", ReferenceName = "Curonian"},
                                 new {Id    = "xcv", Scope = "I", Type = "E", ReferenceName = "Chuvantsy"},
                                 new {Id    = "xcw", Scope = "I", Type = "E", ReferenceName = "Coahuilteco"},
                                 new {Id    = "xcy", Scope = "I", Type = "E", ReferenceName = "Cayuse"},
                                 new {Id    = "xda", Scope = "I", Type = "L", ReferenceName = "Darkinyung"},
                                 new {Id    = "xdc", Scope = "I", Type = "A", ReferenceName = "Dacian"},
                                 new {Id    = "xdk", Scope = "I", Type = "E", ReferenceName = "Dharuk"},
                                 new {Id    = "xdm", Scope = "I", Type = "A", ReferenceName = "Edomite"},
                                 new {Id    = "xdo", Scope = "I", Type = "L", ReferenceName = "Kwandu"},
                                 new {Id    = "xdy", Scope = "I", Type = "L", ReferenceName = "Malayic Dayak"},
                                 new {Id    = "xeb", Scope = "I", Type = "A", ReferenceName = "Eblan"},
                                 new {Id    = "xed", Scope = "I", Type = "L", ReferenceName = "Hdi"},
                                 new {Id    = "xeg", Scope = "I", Type = "E", ReferenceName = "ǁXegwi"},
                                 new {Id    = "xel", Scope = "I", Type = "L", ReferenceName = "Kelo"},
                                 new {Id    = "xem", Scope = "I", Type = "L", ReferenceName = "Kembayan"},
                                 new {Id    = "xep", Scope = "I", Type = "A", ReferenceName = "Epi-Olmec"},
                                 new {Id    = "xer", Scope = "I", Type = "L", ReferenceName = "Xerénte"},
                                 new {Id    = "xes", Scope = "I", Type = "L", ReferenceName = "Kesawai"},
                                 new {Id    = "xet", Scope = "I", Type = "L", ReferenceName = "Xetá"},
                                 new {Id    = "xeu", Scope = "I", Type = "L", ReferenceName = "Keoru-Ahia"},
                                 new {Id    = "xfa", Scope = "I", Type = "A", ReferenceName = "Faliscan"},
                                 new {Id    = "xga", Scope = "I", Type = "A", ReferenceName = "Galatian"},
                                 new {Id    = "xgb", Scope = "I", Type = "E", ReferenceName = "Gbin"},
                                 new {Id    = "xgd", Scope = "I", Type = "E", ReferenceName = "Gudang"},
                                 new {Id    = "xgf", Scope = "I", Type = "E", ReferenceName = "Gabrielino-Fernandeño"},
                                 new {Id    = "xgg", Scope = "I", Type = "E", ReferenceName = "Goreng"},
                                 new {Id    = "xgi", Scope = "I", Type = "E", ReferenceName = "Garingbal"},
                                 new {Id    = "xgl", Scope = "I", Type = "H", ReferenceName = "Galindan"},
                                 new {Id    = "xgm", Scope = "I", Type = "E", ReferenceName = "Dharumbal"},
                                 new {Id    = "xgr", Scope = "I", Type = "E", ReferenceName = "Garza"},
                                 new {Id    = "xgu", Scope = "I", Type = "L", ReferenceName = "Unggumi"},
                                 new {Id    = "xgw", Scope = "I", Type = "E", ReferenceName = "Guwa"},
                                 new {Id    = "xha", Scope = "I", Type = "A", ReferenceName = "Harami"},
                                 new {Id    = "xhc", Scope = "I", Type = "A", ReferenceName = "Hunnic"},
                                 new {Id    = "xhd", Scope = "I", Type = "A", ReferenceName = "Hadrami"},
                                 new {Id    = "xhe", Scope = "I", Type = "L", ReferenceName = "Khetrani"},
                                 new
                                 {
                                     Id            = "xho",
                                     Part2B        = "xho",
                                     Part2T        = "xho",
                                     Part1         = "xh",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Xhosa"
                                 }, new {Id = "xhr", Scope = "I", Type = "A", ReferenceName = "Hernican"},
                                 new {Id    = "xht", Scope = "I", Type = "A", ReferenceName = "Hattic"},
                                 new {Id    = "xhu", Scope = "I", Type = "A", ReferenceName = "Hurrian"},
                                 new {Id    = "xhv", Scope = "I", Type = "L", ReferenceName = "Khua"},
                                 new {Id    = "xib", Scope = "I", Type = "A", ReferenceName = "Iberian"},
                                 new {Id    = "xii", Scope = "I", Type = "L", ReferenceName = "Xiri"},
                                 new {Id    = "xil", Scope = "I", Type = "A", ReferenceName = "Illyrian"},
                                 new {Id    = "xin", Scope = "I", Type = "E", ReferenceName = "Xinca"},
                                 new {Id    = "xir", Scope = "I", Type = "E", ReferenceName = "Xiriâna"},
                                 new {Id    = "xis", Scope = "I", Type = "L", ReferenceName = "Kisan"},
                                 new {Id    = "xiv", Scope = "I", Type = "A", ReferenceName = "Indus Valley Language"},
                                 new {Id    = "xiy", Scope = "I", Type = "L", ReferenceName = "Xipaya"},
                                 new {Id    = "xjb", Scope = "I", Type = "E", ReferenceName = "Minjungbal"},
                                 new {Id    = "xjt", Scope = "I", Type = "E", ReferenceName = "Jaitmatang"},
                                 new {Id    = "xka", Scope = "I", Type = "L", ReferenceName = "Kalkoti"},
                                 new {Id    = "xkb", Scope = "I", Type = "L", ReferenceName = "Northern Nago"},
                                 new {Id    = "xkc", Scope = "I", Type = "L", ReferenceName = "Kho'ini"},
                                 new {Id    = "xkd", Scope = "I", Type = "L", ReferenceName = "Mendalam Kayan"},
                                 new {Id    = "xke", Scope = "I", Type = "L", ReferenceName = "Kereho"},
                                 new {Id    = "xkf", Scope = "I", Type = "L", ReferenceName = "Khengkha"},
                                 new {Id    = "xkg", Scope = "I", Type = "L", ReferenceName = "Kagoro"},
                                 new {Id    = "xki", Scope = "I", Type = "L", ReferenceName = "Kenyan Sign Language"},
                                 new {Id    = "xkj", Scope = "I", Type = "L", ReferenceName = "Kajali"},
                                 new {Id    = "xkk", Scope = "I", Type = "L", ReferenceName = "Kaco'"},
                                 new {Id    = "xkl", Scope = "I", Type = "L", ReferenceName = "Mainstream Kenyah"},
                                 new {Id    = "xkn", Scope = "I", Type = "L", ReferenceName = "Kayan River Kayan"},
                                 new {Id    = "xko", Scope = "I", Type = "L", ReferenceName = "Kiorr"},
                                 new {Id    = "xkp", Scope = "I", Type = "L", ReferenceName = "Kabatei"},
                                 new {Id    = "xkq", Scope = "I", Type = "L", ReferenceName = "Koroni"},
                                 new {Id    = "xkr", Scope = "I", Type = "E", ReferenceName = "Xakriabá"},
                                 new {Id    = "xks", Scope = "I", Type = "L", ReferenceName = "Kumbewaha"},
                                 new {Id    = "xkt", Scope = "I", Type = "L", ReferenceName = "Kantosi"},
                                 new {Id    = "xku", Scope = "I", Type = "L", ReferenceName = "Kaamba"},
                                 new {Id    = "xkv", Scope = "I", Type = "L", ReferenceName = "Kgalagadi"},
                                 new {Id    = "xkw", Scope = "I", Type = "L", ReferenceName = "Kembra"},
                                 new {Id    = "xkx", Scope = "I", Type = "L", ReferenceName = "Karore"},
                                 new {Id    = "xky", Scope = "I", Type = "L", ReferenceName = "Uma' Lasan"},
                                 new {Id    = "xkz", Scope = "I", Type = "L", ReferenceName = "Kurtokha"},
                                 new {Id    = "xla", Scope = "I", Type = "L", ReferenceName = "Kamula"},
                                 new {Id    = "xlb", Scope = "I", Type = "E", ReferenceName = "Loup B"},
                                 new {Id    = "xlc", Scope = "I", Type = "A", ReferenceName = "Lycian"},
                                 new {Id    = "xld", Scope = "I", Type = "A", ReferenceName = "Lydian"},
                                 new {Id    = "xle", Scope = "I", Type = "A", ReferenceName = "Lemnian"},
                                 new {Id    = "xlg", Scope = "I", Type = "A", ReferenceName = "Ligurian (Ancient)"},
                                 new {Id    = "xli", Scope = "I", Type = "A", ReferenceName = "Liburnian"},
                                 new {Id    = "xln", Scope = "I", Type = "A", ReferenceName = "Alanic"},
                                 new {Id    = "xlo", Scope = "I", Type = "E", ReferenceName = "Loup A"},
                                 new {Id    = "xlp", Scope = "I", Type = "A", ReferenceName = "Lepontic"},
                                 new {Id    = "xls", Scope = "I", Type = "A", ReferenceName = "Lusitanian"},
                                 new {Id    = "xlu", Scope = "I", Type = "A", ReferenceName = "Cuneiform Luwian"},
                                 new {Id    = "xly", Scope = "I", Type = "A", ReferenceName = "Elymian"},
                                 new {Id    = "xma", Scope = "I", Type = "L", ReferenceName = "Mushungulu"},
                                 new {Id    = "xmb", Scope = "I", Type = "L", ReferenceName = "Mbonga"},
                                 new {Id    = "xmc", Scope = "I", Type = "L", ReferenceName = "Makhuwa-Marrevone"},
                                 new {Id    = "xmd", Scope = "I", Type = "L", ReferenceName = "Mbudum"},
                                 new {Id    = "xme", Scope = "I", Type = "A", ReferenceName = "Median"},
                                 new {Id    = "xmf", Scope = "I", Type = "L", ReferenceName = "Mingrelian"},
                                 new {Id    = "xmg", Scope = "I", Type = "L", ReferenceName = "Mengaka"},
                                 new {Id    = "xmh", Scope = "I", Type = "L", ReferenceName = "Kugu-Muminh"},
                                 new {Id    = "xmj", Scope = "I", Type = "L", ReferenceName = "Majera"},
                                 new {Id    = "xmk", Scope = "I", Type = "A", ReferenceName = "Ancient Macedonian"},
                                 new
                                     {
                                         Id            = "xml",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Malaysian Sign Language"
                                     },
                                 new {Id = "xmm", Scope = "I", Type = "L", ReferenceName = "Manado Malay"},
                                 new
                                     {
                                         Id            = "xmn",
                                         Scope         = "I",
                                         Type          = "H",
                                         ReferenceName = "Manichaean Middle Persian"
                                     },
                                 new {Id = "xmo", Scope = "I", Type = "L", ReferenceName = "Morerebi"},
                                 new {Id = "xmp", Scope = "I", Type = "E", ReferenceName = "Kuku-Mu'inh"},
                                 new {Id = "xmq", Scope = "I", Type = "E", ReferenceName = "Kuku-Mangk"},
                                 new {Id = "xmr", Scope = "I", Type = "A", ReferenceName = "Meroitic"},
                                 new {Id = "xms", Scope = "I", Type = "L", ReferenceName = "Moroccan Sign Language"},
                                 new {Id = "xmt", Scope = "I", Type = "L", ReferenceName = "Matbat"},
                                 new {Id = "xmu", Scope = "I", Type = "E", ReferenceName = "Kamu"},
                                 new {Id = "xmv", Scope = "I", Type = "L", ReferenceName = "Antankarana Malagasy"},
                                 new {Id = "xmw", Scope = "I", Type = "L", ReferenceName = "Tsimihety Malagasy"},
                                 new {Id = "xmx", Scope = "I", Type = "L", ReferenceName = "Maden"},
                                 new {Id = "xmy", Scope = "I", Type = "L", ReferenceName = "Mayaguduna"},
                                 new {Id = "xmz", Scope = "I", Type = "L", ReferenceName = "Mori Bawah"},
                                 new {Id = "xna", Scope = "I", Type = "A", ReferenceName = "Ancient North Arabian"},
                                 new {Id = "xnb", Scope = "I", Type = "L", ReferenceName = "Kanakanabu"},
                                 new {Id = "xng", Scope = "I", Type = "H", ReferenceName = "Middle Mongolian"},
                                 new {Id = "xnh", Scope = "I", Type = "L", ReferenceName = "Kuanhua"},
                                 new {Id = "xni", Scope = "I", Type = "E", ReferenceName = "Ngarigu"},
                                 new {Id = "xnk", Scope = "I", Type = "E", ReferenceName = "Nganakarti"},
                                 new {Id = "xnn", Scope = "I", Type = "L", ReferenceName = "Northern Kankanay"},
                                 new {Id = "xno", Scope = "I", Type = "H", ReferenceName = "Anglo-Norman"},
                                 new {Id = "xnr", Scope = "I", Type = "L", ReferenceName = "Kangri"},
                                 new {Id = "xns", Scope = "I", Type = "L", ReferenceName = "Kanashi"},
                                 new {Id = "xnt", Scope = "I", Type = "E", ReferenceName = "Narragansett"},
                                 new {Id = "xnu", Scope = "I", Type = "E", ReferenceName = "Nukunul"},
                                 new {Id = "xny", Scope = "I", Type = "L", ReferenceName = "Nyiyaparli"},
                                 new {Id = "xnz", Scope = "I", Type = "L", ReferenceName = "Kenzi"},
                                 new {Id = "xoc", Scope = "I", Type = "E", ReferenceName = "O'chi'chi'"},
                                 new {Id = "xod", Scope = "I", Type = "L", ReferenceName = "Kokoda"},
                                 new {Id = "xog", Scope = "I", Type = "L", ReferenceName = "Soga"},
                                 new {Id = "xoi", Scope = "I", Type = "L", ReferenceName = "Kominimung"},
                                 new {Id = "xok", Scope = "I", Type = "L", ReferenceName = "Xokleng"},
                                 new {Id = "xom", Scope = "I", Type = "L", ReferenceName = "Komo (Sudan)"},
                                 new {Id = "xon", Scope = "I", Type = "L", ReferenceName = "Konkomba"},
                                 new {Id = "xoo", Scope = "I", Type = "E", ReferenceName = "Xukurú"},
                                 new {Id = "xop", Scope = "I", Type = "L", ReferenceName = "Kopar"},
                                 new {Id = "xor", Scope = "I", Type = "L", ReferenceName = "Korubo"},
                                 new {Id = "xow", Scope = "I", Type = "L", ReferenceName = "Kowaki"},
                                 new {Id = "xpa", Scope = "I", Type = "E", ReferenceName = "Pirriya"},
                                 new {Id = "xpc", Scope = "I", Type = "H", ReferenceName = "Pecheneg"},
                                 new {Id = "xpe", Scope = "I", Type = "L", ReferenceName = "Liberia Kpelle"},
                                 new {Id = "xpg", Scope = "I", Type = "A", ReferenceName = "Phrygian"},
                                 new {Id = "xpi", Scope = "I", Type = "H", ReferenceName = "Pictish"},
                                 new {Id = "xpj", Scope = "I", Type = "E", ReferenceName = "Mpalitjanh"},
                                 new {Id = "xpk", Scope = "I", Type = "L", ReferenceName = "Kulina Pano"},
                                 new {Id = "xpm", Scope = "I", Type = "E", ReferenceName = "Pumpokol"},
                                 new {Id = "xpn", Scope = "I", Type = "E", ReferenceName = "Kapinawá"},
                                 new {Id = "xpo", Scope = "I", Type = "E", ReferenceName = "Pochutec"},
                                 new {Id = "xpp", Scope = "I", Type = "A", ReferenceName = "Puyo-Paekche"},
                                 new {Id = "xpq", Scope = "I", Type = "E", ReferenceName = "Mohegan-Pequot"},
                                 new {Id = "xpr", Scope = "I", Type = "A", ReferenceName = "Parthian"},
                                 new {Id = "xps", Scope = "I", Type = "A", ReferenceName = "Pisidian"},
                                 new {Id = "xpt", Scope = "I", Type = "E", ReferenceName = "Punthamara"},
                                 new {Id = "xpu", Scope = "I", Type = "A", ReferenceName = "Punic"},
                                 new {Id = "xpy", Scope = "I", Type = "A", ReferenceName = "Puyo"},
                                 new {Id = "xqa", Scope = "I", Type = "H", ReferenceName = "Karakhanid"},
                                 new {Id = "xqt", Scope = "I", Type = "A", ReferenceName = "Qatabanian"},
                                 new {Id = "xra", Scope = "I", Type = "L", ReferenceName = "Krahô"},
                                 new {Id = "xrb", Scope = "I", Type = "L", ReferenceName = "Eastern Karaboro"},
                                 new {Id = "xrd", Scope = "I", Type = "E", ReferenceName = "Gundungurra"},
                                 new {Id = "xre", Scope = "I", Type = "L", ReferenceName = "Kreye"},
                                 new {Id = "xrg", Scope = "I", Type = "E", ReferenceName = "Minang"},
                                 new {Id = "xri", Scope = "I", Type = "L", ReferenceName = "Krikati-Timbira"},
                                 new {Id = "xrm", Scope = "I", Type = "A", ReferenceName = "Armazic"},
                                 new {Id = "xrn", Scope = "I", Type = "E", ReferenceName = "Arin"},
                                 new {Id = "xrq", Scope = "I", Type = "E", ReferenceName = "Karranga"},
                                 new {Id = "xrr", Scope = "I", Type = "A", ReferenceName = "Raetic"},
                                 new {Id = "xrt", Scope = "I", Type = "E", ReferenceName = "Aranama-Tamique"},
                                 new {Id = "xru", Scope = "I", Type = "L", ReferenceName = "Marriammu"},
                                 new {Id = "xrw", Scope = "I", Type = "L", ReferenceName = "Karawa"},
                                 new {Id = "xsa", Scope = "I", Type = "A", ReferenceName = "Sabaean"},
                                 new {Id = "xsb", Scope = "I", Type = "L", ReferenceName = "Sambal"},
                                 new {Id = "xsc", Scope = "I", Type = "A", ReferenceName = "Scythian"},
                                 new {Id = "xsd", Scope = "I", Type = "A", ReferenceName = "Sidetic"},
                                 new {Id = "xse", Scope = "I", Type = "L", ReferenceName = "Sempan"},
                                 new {Id = "xsh", Scope = "I", Type = "L", ReferenceName = "Shamang"},
                                 new {Id = "xsi", Scope = "I", Type = "L", ReferenceName = "Sio"},
                                 new {Id = "xsj", Scope = "I", Type = "L", ReferenceName = "Subi"},
                                 new {Id = "xsl", Scope = "I", Type = "L", ReferenceName = "South Slavey"},
                                 new {Id = "xsm", Scope = "I", Type = "L", ReferenceName = "Kasem"},
                                 new {Id = "xsn", Scope = "I", Type = "L", ReferenceName = "Sanga (Nigeria)"},
                                 new {Id = "xso", Scope = "I", Type = "E", ReferenceName = "Solano"},
                                 new {Id = "xsp", Scope = "I", Type = "L", ReferenceName = "Silopi"},
                                 new {Id = "xsq", Scope = "I", Type = "L", ReferenceName = "Makhuwa-Saka"},
                                 new {Id = "xsr", Scope = "I", Type = "L", ReferenceName = "Sherpa"},
                                 new {Id = "xss", Scope = "I", Type = "E", ReferenceName = "Assan"},
                                 new {Id = "xsu", Scope = "I", Type = "L", ReferenceName = "Sanumá"},
                                 new {Id = "xsv", Scope = "I", Type = "E", ReferenceName = "Sudovian"},
                                 new {Id = "xsy", Scope = "I", Type = "L", ReferenceName = "Saisiyat"},
                                 new {Id = "xta", Scope = "I", Type = "L", ReferenceName = "Alcozauca Mixtec"},
                                 new {Id = "xtb", Scope = "I", Type = "L", ReferenceName = "Chazumba Mixtec"},
                                 new {Id = "xtc", Scope = "I", Type = "L", ReferenceName = "Katcha-Kadugli-Miri"},
                                 new
                                     {
                                         Id            = "xtd",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Diuxi-Tilantongo Mixtec"
                                     },
                                 new {Id = "xte", Scope = "I", Type = "L", ReferenceName = "Ketengban"},
                                 new {Id = "xtg", Scope = "I", Type = "A", ReferenceName = "Transalpine Gaulish"},
                                 new {Id = "xth", Scope = "I", Type = "E", ReferenceName = "Yitha Yitha"},
                                 new {Id = "xti", Scope = "I", Type = "L", ReferenceName = "Sinicahua Mixtec"},
                                 new {Id = "xtj", Scope = "I", Type = "L", ReferenceName = "San Juan Teita Mixtec"},
                                 new {Id = "xtl", Scope = "I", Type = "L", ReferenceName = "Tijaltepec Mixtec"},
                                 new
                                     {
                                         Id            = "xtm",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Magdalena Peñasco Mixtec"
                                     },
                                 new
                                     {
                                         Id            = "xtn",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Northern Tlaxiaco Mixtec"
                                     },
                                 new {Id = "xto", Scope = "I", Type = "A", ReferenceName = "Tokharian A"},
                                 new
                                     {
                                         Id            = "xtp",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "San Miguel Piedras Mixtec"
                                     },
                                 new {Id = "xtq", Scope = "I", Type = "H", ReferenceName = "Tumshuqese"},
                                 new {Id = "xtr", Scope = "I", Type = "A", ReferenceName = "Early Tripuri"},
                                 new {Id = "xts", Scope = "I", Type = "L", ReferenceName = "Sindihui Mixtec"},
                                 new {Id = "xtt", Scope = "I", Type = "L", ReferenceName = "Tacahua Mixtec"},
                                 new {Id = "xtu", Scope = "I", Type = "L", ReferenceName = "Cuyamecalco Mixtec"},
                                 new {Id = "xtv", Scope = "I", Type = "E", ReferenceName = "Thawa"},
                                 new {Id = "xtw", Scope = "I", Type = "L", ReferenceName = "Tawandê"},
                                 new {Id = "xty", Scope = "I", Type = "L", ReferenceName = "Yoloxochitl Mixtec"},
                                 new {Id = "xtz", Scope = "I", Type = "E", ReferenceName = "Tasmanian"},
                                 new {Id = "xua", Scope = "I", Type = "L", ReferenceName = "Alu Kurumba"},
                                 new {Id = "xub", Scope = "I", Type = "L", ReferenceName = "Betta Kurumba"},
                                 new {Id = "xud", Scope = "I", Type = "E", ReferenceName = "Umiida"},
                                 new {Id = "xug", Scope = "I", Type = "L", ReferenceName = "Kunigami"},
                                 new {Id = "xuj", Scope = "I", Type = "L", ReferenceName = "Jennu Kurumba"},
                                 new {Id = "xul", Scope = "I", Type = "E", ReferenceName = "Ngunawal"},
                                 new {Id = "xum", Scope = "I", Type = "A", ReferenceName = "Umbrian"},
                                 new {Id = "xun", Scope = "I", Type = "E", ReferenceName = "Unggaranggu"},
                                 new {Id = "xuo", Scope = "I", Type = "L", ReferenceName = "Kuo"},
                                 new {Id = "xup", Scope = "I", Type = "E", ReferenceName = "Upper Umpqua"},
                                 new {Id = "xur", Scope = "I", Type = "A", ReferenceName = "Urartian"},
                                 new {Id = "xut", Scope = "I", Type = "E", ReferenceName = "Kuthant"},
                                 new {Id = "xuu", Scope = "I", Type = "L", ReferenceName = "Kxoe"},
                                 new {Id = "xve", Scope = "I", Type = "A", ReferenceName = "Venetic"},
                                 new {Id = "xvi", Scope = "I", Type = "L", ReferenceName = "Kamviri"},
                                 new {Id = "xvn", Scope = "I", Type = "A", ReferenceName = "Vandalic"},
                                 new {Id = "xvo", Scope = "I", Type = "A", ReferenceName = "Volscian"},
                                 new {Id = "xvs", Scope = "I", Type = "A", ReferenceName = "Vestinian"},
                                 new {Id = "xwa", Scope = "I", Type = "L", ReferenceName = "Kwaza"},
                                 new {Id = "xwc", Scope = "I", Type = "E", ReferenceName = "Woccon"},
                                 new {Id = "xwd", Scope = "I", Type = "E", ReferenceName = "Wadi Wadi"},
                                 new {Id = "xwe", Scope = "I", Type = "L", ReferenceName = "Xwela Gbe"},
                                 new {Id = "xwg", Scope = "I", Type = "L", ReferenceName = "Kwegu"},
                                 new {Id = "xwj", Scope = "I", Type = "E", ReferenceName = "Wajuk"},
                                 new {Id = "xwk", Scope = "I", Type = "E", ReferenceName = "Wangkumara"},
                                 new {Id = "xwl", Scope = "I", Type = "L", ReferenceName = "Western Xwla Gbe"},
                                 new {Id = "xwo", Scope = "I", Type = "E", ReferenceName = "Written Oirat"},
                                 new {Id = "xwr", Scope = "I", Type = "L", ReferenceName = "Kwerba Mamberamo"},
                                 new {Id = "xwt", Scope = "I", Type = "E", ReferenceName = "Wotjobaluk"},
                                 new {Id = "xww", Scope = "I", Type = "E", ReferenceName = "Wemba Wemba"},
                                 new {Id = "xxb", Scope = "I", Type = "E", ReferenceName = "Boro (Ghana)"},
                                 new {Id = "xxk", Scope = "I", Type = "L", ReferenceName = "Ke'o"},
                                 new {Id = "xxm", Scope = "I", Type = "E", ReferenceName = "Minkin"},
                                 new {Id = "xxr", Scope = "I", Type = "E", ReferenceName = "Koropó"},
                                 new {Id = "xxt", Scope = "I", Type = "E", ReferenceName = "Tambora"},
                                 new {Id = "xya", Scope = "I", Type = "E", ReferenceName = "Yaygir"},
                                 new {Id = "xyb", Scope = "I", Type = "E", ReferenceName = "Yandjibara"},
                                 new {Id = "xyj", Scope = "I", Type = "E", ReferenceName = "Mayi-Yapi"},
                                 new {Id = "xyk", Scope = "I", Type = "E", ReferenceName = "Mayi-Kulan"},
                                 new {Id = "xyl", Scope = "I", Type = "E", ReferenceName = "Yalakalore"},
                                 new {Id = "xyt", Scope = "I", Type = "E", ReferenceName = "Mayi-Thakurti"},
                                 new {Id = "xyy", Scope = "I", Type = "L", ReferenceName = "Yorta Yorta"},
                                 new {Id = "xzh", Scope = "I", Type = "A", ReferenceName = "Zhang-Zhung"},
                                 new {Id = "xzm", Scope = "I", Type = "E", ReferenceName = "Zemgalian"},
                                 new {Id = "xzp", Scope = "I", Type = "H", ReferenceName = "Ancient Zapotec"});
        }
    }
}