using Microsoft.EntityFrameworkCore;

namespace Cicm.Database.Seeders.Iso639Split
{
    public static class Y
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Models.Iso639>()
                        .HasData(new {Id = "yaa", Scope = "I", Type = "L", ReferenceName = "Yaminahua"},
                                 new {Id = "yab", Scope = "I", Type = "L", ReferenceName = "Yuhup"},
                                 new {Id = "yac", Scope = "I", Type = "L", ReferenceName = "Pass Valley Yali"},
                                 new {Id = "yad", Scope = "I", Type = "L", ReferenceName = "Yagua"},
                                 new {Id = "yae", Scope = "I", Type = "L", ReferenceName = "Pumé"},
                                 new
                                 {
                                     Id            = "yaf",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Yaka (Democratic Republic of Congo)"
                                 }, new {Id = "yag", Scope = "I", Type = "L", ReferenceName = "Yámana"},
                                 new {Id    = "yah", Scope = "I", Type = "L", ReferenceName = "Yazgulyam"},
                                 new {Id    = "yai", Scope = "I", Type = "L", ReferenceName = "Yagnobi"},
                                 new {Id    = "yaj", Scope = "I", Type = "L", ReferenceName = "Banda-Yangere"},
                                 new {Id    = "yak", Scope = "I", Type = "L", ReferenceName = "Yakama"},
                                 new {Id    = "yal", Scope = "I", Type = "L", ReferenceName = "Yalunka"},
                                 new {Id    = "yam", Scope = "I", Type = "L", ReferenceName = "Yamba"},
                                 new {Id    = "yan", Scope = "I", Type = "L", ReferenceName = "Mayangna"},
                                 new
                                 {
                                     Id            = "yao",
                                     Part2B        = "yao",
                                     Part2T        = "yao",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Yao"
                                 }, new
                                 {
                                     Id            = "yap",
                                     Part2B        = "yap",
                                     Part2T        = "yap",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Yapese"
                                 }, new {Id = "yaq", Scope = "I", Type = "L", ReferenceName = "Yaqui"},
                                 new {Id    = "yar", Scope = "I", Type = "L", ReferenceName = "Yabarana"},
                                 new {Id    = "yas", Scope = "I", Type = "L", ReferenceName = "Nugunu (Cameroon)"},
                                 new {Id    = "yat", Scope = "I", Type = "L", ReferenceName = "Yambeta"},
                                 new {Id    = "yau", Scope = "I", Type = "L", ReferenceName = "Yuwana"},
                                 new {Id    = "yav", Scope = "I", Type = "L", ReferenceName = "Yangben"},
                                 new {Id    = "yaw", Scope = "I", Type = "L", ReferenceName = "Yawalapití"},
                                 new {Id    = "yax", Scope = "I", Type = "L", ReferenceName = "Yauma"},
                                 new {Id    = "yay", Scope = "I", Type = "L", ReferenceName = "Agwagwune"},
                                 new {Id    = "yaz", Scope = "I", Type = "L", ReferenceName = "Lokaa"},
                                 new {Id    = "yba", Scope = "I", Type = "L", ReferenceName = "Yala"},
                                 new {Id    = "ybb", Scope = "I", Type = "L", ReferenceName = "Yemba"},
                                 new {Id    = "ybe", Scope = "I", Type = "L", ReferenceName = "West Yugur"},
                                 new {Id    = "ybh", Scope = "I", Type = "L", ReferenceName = "Yakha"},
                                 new {Id    = "ybi", Scope = "I", Type = "L", ReferenceName = "Yamphu"},
                                 new {Id    = "ybj", Scope = "I", Type = "L", ReferenceName = "Hasha"},
                                 new {Id    = "ybk", Scope = "I", Type = "L", ReferenceName = "Bokha"},
                                 new {Id    = "ybl", Scope = "I", Type = "L", ReferenceName = "Yukuben"},
                                 new {Id    = "ybm", Scope = "I", Type = "L", ReferenceName = "Yaben"},
                                 new {Id    = "ybn", Scope = "I", Type = "E", ReferenceName = "Yabaâna"},
                                 new {Id    = "ybo", Scope = "I", Type = "L", ReferenceName = "Yabong"},
                                 new {Id    = "ybx", Scope = "I", Type = "L", ReferenceName = "Yawiyo"},
                                 new {Id    = "yby", Scope = "I", Type = "L", ReferenceName = "Yaweyuha"},
                                 new {Id    = "ych", Scope = "I", Type = "L", ReferenceName = "Chesu"},
                                 new {Id    = "ycl", Scope = "I", Type = "L", ReferenceName = "Lolopo"},
                                 new {Id    = "ycn", Scope = "I", Type = "L", ReferenceName = "Yucuna"},
                                 new {Id    = "ycp", Scope = "I", Type = "L", ReferenceName = "Chepya"},
                                 new {Id    = "yda", Scope = "I", Type = "E", ReferenceName = "Yanda"},
                                 new {Id    = "ydd", Scope = "I", Type = "L", ReferenceName = "Eastern Yiddish"},
                                 new {Id    = "yde", Scope = "I", Type = "L", ReferenceName = "Yangum Dey"},
                                 new {Id    = "ydg", Scope = "I", Type = "L", ReferenceName = "Yidgha"},
                                 new {Id    = "ydk", Scope = "I", Type = "L", ReferenceName = "Yoidik"},
                                 new {Id    = "yea", Scope = "I", Type = "L", ReferenceName = "Ravula"},
                                 new {Id    = "yec", Scope = "I", Type = "L", ReferenceName = "Yeniche"},
                                 new {Id    = "yee", Scope = "I", Type = "L", ReferenceName = "Yimas"},
                                 new {Id    = "yei", Scope = "I", Type = "E", ReferenceName = "Yeni"},
                                 new {Id    = "yej", Scope = "I", Type = "L", ReferenceName = "Yevanic"},
                                 new {Id    = "yel", Scope = "I", Type = "L", ReferenceName = "Yela"},
                                 new {Id    = "yer", Scope = "I", Type = "L", ReferenceName = "Tarok"},
                                 new {Id    = "yes", Scope = "I", Type = "L", ReferenceName = "Nyankpa"},
                                 new {Id    = "yet", Scope = "I", Type = "L", ReferenceName = "Yetfa"},
                                 new {Id    = "yeu", Scope = "I", Type = "L", ReferenceName = "Yerukula"},
                                 new {Id    = "yev", Scope = "I", Type = "L", ReferenceName = "Yapunda"},
                                 new {Id    = "yey", Scope = "I", Type = "L", ReferenceName = "Yeyi"},
                                 new {Id    = "yga", Scope = "I", Type = "E", ReferenceName = "Malyangapa"},
                                 new {Id    = "ygi", Scope = "I", Type = "E", ReferenceName = "Yiningayi"},
                                 new {Id    = "ygl", Scope = "I", Type = "L", ReferenceName = "Yangum Gel"},
                                 new {Id    = "ygm", Scope = "I", Type = "L", ReferenceName = "Yagomi"},
                                 new {Id    = "ygp", Scope = "I", Type = "L", ReferenceName = "Gepo"},
                                 new {Id    = "ygr", Scope = "I", Type = "L", ReferenceName = "Yagaria"},
                                 new {Id    = "ygs", Scope = "I", Type = "L", ReferenceName = "Yolŋu Sign Language"},
                                 new {Id    = "ygu", Scope = "I", Type = "L", ReferenceName = "Yugul"},
                                 new {Id    = "ygw", Scope = "I", Type = "L", ReferenceName = "Yagwoia"},
                                 new {Id    = "yha", Scope = "I", Type = "L", ReferenceName = "Baha Buyang"},
                                 new {Id    = "yhd", Scope = "I", Type = "L", ReferenceName = "Judeo-Iraqi Arabic"},
                                 new {Id    = "yhl", Scope = "I", Type = "L", ReferenceName = "Hlepho Phowa"},
                                 new
                                     {
                                         Id            = "yhs",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Yan-nhaŋu Sign Language"
                                     },
                                 new {Id = "yia", Scope = "I", Type = "L", ReferenceName = "Yinggarda"},
                                 new
                                 {
                                     Id            = "yid",
                                     Part2B        = "yid",
                                     Part2T        = "yid",
                                     Part1         = "yi",
                                     Scope         = "M",
                                     Type          = "L",
                                     ReferenceName = "Yiddish"
                                 }, new {Id = "yif", Scope = "I", Type = "L", ReferenceName = "Ache"},
                                 new {Id    = "yig", Scope = "I", Type = "L", ReferenceName = "Wusa Nasu"},
                                 new {Id    = "yih", Scope = "I", Type = "L", ReferenceName = "Western Yiddish"},
                                 new {Id    = "yii", Scope = "I", Type = "L", ReferenceName = "Yidiny"},
                                 new {Id    = "yij", Scope = "I", Type = "L", ReferenceName = "Yindjibarndi"},
                                 new {Id    = "yik", Scope = "I", Type = "L", ReferenceName = "Dongshanba Lalo"},
                                 new {Id    = "yil", Scope = "I", Type = "E", ReferenceName = "Yindjilandji"},
                                 new {Id    = "yim", Scope = "I", Type = "L", ReferenceName = "Yimchungru Naga"},
                                 new {Id    = "yin", Scope = "I", Type = "L", ReferenceName = "Riang Lai"},
                                 new {Id    = "yip", Scope = "I", Type = "L", ReferenceName = "Pholo"},
                                 new {Id    = "yiq", Scope = "I", Type = "L", ReferenceName = "Miqie"},
                                 new {Id    = "yir", Scope = "I", Type = "L", ReferenceName = "North Awyu"},
                                 new {Id    = "yis", Scope = "I", Type = "L", ReferenceName = "Yis"},
                                 new {Id    = "yit", Scope = "I", Type = "L", ReferenceName = "Eastern Lalu"},
                                 new {Id    = "yiu", Scope = "I", Type = "L", ReferenceName = "Awu"},
                                 new {Id    = "yiv", Scope = "I", Type = "L", ReferenceName = "Northern Nisu"},
                                 new {Id    = "yix", Scope = "I", Type = "L", ReferenceName = "Axi Yi"},
                                 new {Id    = "yiz", Scope = "I", Type = "L", ReferenceName = "Azhe"},
                                 new {Id    = "yka", Scope = "I", Type = "L", ReferenceName = "Yakan"},
                                 new {Id    = "ykg", Scope = "I", Type = "L", ReferenceName = "Northern Yukaghir"},
                                 new {Id    = "yki", Scope = "I", Type = "L", ReferenceName = "Yoke"},
                                 new {Id    = "ykk", Scope = "I", Type = "L", ReferenceName = "Yakaikeke"},
                                 new {Id    = "ykl", Scope = "I", Type = "L", ReferenceName = "Khlula"},
                                 new {Id    = "ykm", Scope = "I", Type = "L", ReferenceName = "Kap"},
                                 new {Id    = "ykn", Scope = "I", Type = "L", ReferenceName = "Kua-nsi"},
                                 new {Id    = "yko", Scope = "I", Type = "L", ReferenceName = "Yasa"},
                                 new {Id    = "ykr", Scope = "I", Type = "L", ReferenceName = "Yekora"},
                                 new {Id    = "ykt", Scope = "I", Type = "L", ReferenceName = "Kathu"},
                                 new {Id    = "yku", Scope = "I", Type = "L", ReferenceName = "Kuamasi"},
                                 new {Id    = "yky", Scope = "I", Type = "L", ReferenceName = "Yakoma"},
                                 new {Id    = "yla", Scope = "I", Type = "L", ReferenceName = "Yaul"},
                                 new {Id    = "ylb", Scope = "I", Type = "L", ReferenceName = "Yaleba"},
                                 new {Id    = "yle", Scope = "I", Type = "L", ReferenceName = "Yele"},
                                 new {Id    = "ylg", Scope = "I", Type = "L", ReferenceName = "Yelogu"},
                                 new {Id    = "yli", Scope = "I", Type = "L", ReferenceName = "Angguruk Yali"},
                                 new {Id    = "yll", Scope = "I", Type = "L", ReferenceName = "Yil"},
                                 new {Id    = "ylm", Scope = "I", Type = "L", ReferenceName = "Limi"},
                                 new {Id    = "yln", Scope = "I", Type = "L", ReferenceName = "Langnian Buyang"},
                                 new {Id    = "ylo", Scope = "I", Type = "L", ReferenceName = "Naluo Yi"},
                                 new {Id    = "ylr", Scope = "I", Type = "E", ReferenceName = "Yalarnnga"},
                                 new {Id    = "ylu", Scope = "I", Type = "L", ReferenceName = "Aribwaung"},
                                 new {Id    = "yly", Scope = "I", Type = "L", ReferenceName = "Nyâlayu"},
                                 new {Id    = "ymb", Scope = "I", Type = "L", ReferenceName = "Yambes"},
                                 new {Id    = "ymc", Scope = "I", Type = "L", ReferenceName = "Southern Muji"},
                                 new {Id    = "ymd", Scope = "I", Type = "L", ReferenceName = "Muda"},
                                 new {Id    = "yme", Scope = "I", Type = "E", ReferenceName = "Yameo"},
                                 new {Id    = "ymg", Scope = "I", Type = "L", ReferenceName = "Yamongeri"},
                                 new {Id    = "ymh", Scope = "I", Type = "L", ReferenceName = "Mili"},
                                 new {Id    = "ymi", Scope = "I", Type = "L", ReferenceName = "Moji"},
                                 new {Id    = "ymk", Scope = "I", Type = "L", ReferenceName = "Makwe"},
                                 new {Id    = "yml", Scope = "I", Type = "L", ReferenceName = "Iamalele"},
                                 new {Id    = "ymm", Scope = "I", Type = "L", ReferenceName = "Maay"},
                                 new {Id    = "ymn", Scope = "I", Type = "L", ReferenceName = "Yamna"},
                                 new {Id    = "ymo", Scope = "I", Type = "L", ReferenceName = "Yangum Mon"},
                                 new {Id    = "ymp", Scope = "I", Type = "L", ReferenceName = "Yamap"},
                                 new {Id    = "ymq", Scope = "I", Type = "L", ReferenceName = "Qila Muji"},
                                 new {Id    = "ymr", Scope = "I", Type = "L", ReferenceName = "Malasar"},
                                 new {Id    = "yms", Scope = "I", Type = "A", ReferenceName = "Mysian"},
                                 new {Id    = "ymx", Scope = "I", Type = "L", ReferenceName = "Northern Muji"},
                                 new {Id    = "ymz", Scope = "I", Type = "L", ReferenceName = "Muzi"},
                                 new {Id    = "yna", Scope = "I", Type = "L", ReferenceName = "Aluo"},
                                 new {Id    = "ynd", Scope = "I", Type = "E", ReferenceName = "Yandruwandha"},
                                 new {Id    = "yne", Scope = "I", Type = "L", ReferenceName = "Lang'e"},
                                 new {Id    = "yng", Scope = "I", Type = "L", ReferenceName = "Yango"},
                                 new {Id    = "ynk", Scope = "I", Type = "L", ReferenceName = "Naukan Yupik"},
                                 new {Id    = "ynl", Scope = "I", Type = "L", ReferenceName = "Yangulam"},
                                 new {Id    = "ynn", Scope = "I", Type = "E", ReferenceName = "Yana"},
                                 new {Id    = "yno", Scope = "I", Type = "L", ReferenceName = "Yong"},
                                 new {Id    = "ynq", Scope = "I", Type = "L", ReferenceName = "Yendang"},
                                 new {Id    = "yns", Scope = "I", Type = "L", ReferenceName = "Yansi"},
                                 new {Id    = "ynu", Scope = "I", Type = "E", ReferenceName = "Yahuna"},
                                 new {Id    = "yob", Scope = "I", Type = "E", ReferenceName = "Yoba"},
                                 new {Id    = "yog", Scope = "I", Type = "L", ReferenceName = "Yogad"},
                                 new {Id    = "yoi", Scope = "I", Type = "L", ReferenceName = "Yonaguni"},
                                 new {Id    = "yok", Scope = "I", Type = "L", ReferenceName = "Yokuts"},
                                 new {Id    = "yol", Scope = "I", Type = "E", ReferenceName = "Yola"},
                                 new {Id    = "yom", Scope = "I", Type = "L", ReferenceName = "Yombe"},
                                 new {Id    = "yon", Scope = "I", Type = "L", ReferenceName = "Yongkom"},
                                 new
                                 {
                                     Id            = "yor",
                                     Part2B        = "yor",
                                     Part2T        = "yor",
                                     Part1         = "yo",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Yoruba"
                                 }, new {Id = "yot", Scope = "I", Type = "L", ReferenceName = "Yotti"},
                                 new {Id    = "yox", Scope = "I", Type = "L", ReferenceName = "Yoron"},
                                 new {Id    = "yoy", Scope = "I", Type = "L", ReferenceName = "Yoy"},
                                 new {Id    = "ypa", Scope = "I", Type = "L", ReferenceName = "Phala"},
                                 new {Id    = "ypb", Scope = "I", Type = "L", ReferenceName = "Labo Phowa"},
                                 new {Id    = "ypg", Scope = "I", Type = "L", ReferenceName = "Phola"},
                                 new {Id    = "yph", Scope = "I", Type = "L", ReferenceName = "Phupha"},
                                 new {Id    = "ypm", Scope = "I", Type = "L", ReferenceName = "Phuma"},
                                 new {Id    = "ypn", Scope = "I", Type = "L", ReferenceName = "Ani Phowa"},
                                 new {Id    = "ypo", Scope = "I", Type = "L", ReferenceName = "Alo Phola"},
                                 new {Id    = "ypp", Scope = "I", Type = "L", ReferenceName = "Phupa"},
                                 new {Id    = "ypz", Scope = "I", Type = "L", ReferenceName = "Phuza"},
                                 new {Id    = "yra", Scope = "I", Type = "L", ReferenceName = "Yerakai"},
                                 new {Id    = "yrb", Scope = "I", Type = "L", ReferenceName = "Yareba"},
                                 new {Id    = "yre", Scope = "I", Type = "L", ReferenceName = "Yaouré"},
                                 new {Id    = "yrk", Scope = "I", Type = "L", ReferenceName = "Nenets"},
                                 new {Id    = "yrl", Scope = "I", Type = "L", ReferenceName = "Nhengatu"},
                                 new {Id    = "yrm", Scope = "I", Type = "L", ReferenceName = "Yirrk-Mel"},
                                 new {Id    = "yrn", Scope = "I", Type = "L", ReferenceName = "Yerong"},
                                 new {Id    = "yro", Scope = "I", Type = "L", ReferenceName = "Yaroamë"},
                                 new {Id    = "yrs", Scope = "I", Type = "L", ReferenceName = "Yarsun"},
                                 new {Id    = "yrw", Scope = "I", Type = "L", ReferenceName = "Yarawata"},
                                 new {Id    = "yry", Scope = "I", Type = "L", ReferenceName = "Yarluyandi"},
                                 new {Id    = "ysc", Scope = "I", Type = "E", ReferenceName = "Yassic"},
                                 new {Id    = "ysd", Scope = "I", Type = "L", ReferenceName = "Samatao"},
                                 new {Id    = "ysg", Scope = "I", Type = "L", ReferenceName = "Sonaga"},
                                 new
                                     {
                                         Id            = "ysl",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Yugoslavian Sign Language"
                                     },
                                 new {Id = "ysn", Scope = "I", Type = "L", ReferenceName = "Sani"},
                                 new {Id = "yso", Scope = "I", Type = "L", ReferenceName = "Nisi (China)"},
                                 new {Id = "ysp", Scope = "I", Type = "L", ReferenceName = "Southern Lolopo"},
                                 new {Id = "ysr", Scope = "I", Type = "E", ReferenceName = "Sirenik Yupik"},
                                 new {Id = "yss", Scope = "I", Type = "L", ReferenceName = "Yessan-Mayo"},
                                 new {Id = "ysy", Scope = "I", Type = "L", ReferenceName = "Sanie"},
                                 new {Id = "yta", Scope = "I", Type = "L", ReferenceName = "Talu"},
                                 new {Id = "ytl", Scope = "I", Type = "L", ReferenceName = "Tanglang"},
                                 new {Id = "ytp", Scope = "I", Type = "L", ReferenceName = "Thopho"},
                                 new {Id = "ytw", Scope = "I", Type = "L", ReferenceName = "Yout Wam"},
                                 new {Id = "yty", Scope = "I", Type = "E", ReferenceName = "Yatay"},
                                 new {Id = "yua", Scope = "I", Type = "L", ReferenceName = "Yucateco"},
                                 new {Id = "yub", Scope = "I", Type = "E", ReferenceName = "Yugambal"},
                                 new {Id = "yuc", Scope = "I", Type = "L", ReferenceName = "Yuchi"},
                                 new
                                 {
                                     Id            = "yud",
                                     Scope         = "I",
                                     Type          = "L",
                                     ReferenceName = "Judeo-Tripolitanian Arabic"
                                 }, new {Id = "yue", Scope = "I", Type = "L", ReferenceName = "Yue Chinese"},
                                 new
                                     {
                                         Id            = "yuf",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Havasupai-Walapai-Yavapai"
                                     },
                                 new {Id = "yug", Scope = "I", Type = "E", ReferenceName = "Yug"},
                                 new {Id = "yui", Scope = "I", Type = "L", ReferenceName = "Yurutí"},
                                 new {Id = "yuj", Scope = "I", Type = "L", ReferenceName = "Karkar-Yuri"},
                                 new {Id = "yuk", Scope = "I", Type = "E", ReferenceName = "Yuki"},
                                 new {Id = "yul", Scope = "I", Type = "L", ReferenceName = "Yulu"},
                                 new {Id = "yum", Scope = "I", Type = "L", ReferenceName = "Quechan"},
                                 new {Id = "yun", Scope = "I", Type = "L", ReferenceName = "Bena (Nigeria)"},
                                 new {Id = "yup", Scope = "I", Type = "L", ReferenceName = "Yukpa"},
                                 new {Id = "yuq", Scope = "I", Type = "L", ReferenceName = "Yuqui"},
                                 new {Id = "yur", Scope = "I", Type = "E", ReferenceName = "Yurok"},
                                 new {Id = "yut", Scope = "I", Type = "L", ReferenceName = "Yopno"},
                                 new
                                     {
                                         Id            = "yuw",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Yau (Morobe Province)"
                                     },
                                 new {Id = "yux", Scope = "I", Type = "L", ReferenceName = "Southern Yukaghir"},
                                 new {Id = "yuy", Scope = "I", Type = "L", ReferenceName = "East Yugur"},
                                 new {Id = "yuz", Scope = "I", Type = "L", ReferenceName = "Yuracare"},
                                 new {Id = "yva", Scope = "I", Type = "L", ReferenceName = "Yawa"},
                                 new {Id = "yvt", Scope = "I", Type = "E", ReferenceName = "Yavitero"},
                                 new {Id = "ywa", Scope = "I", Type = "L", ReferenceName = "Kalou"},
                                 new {Id = "ywg", Scope = "I", Type = "L", ReferenceName = "Yinhawangka"},
                                 new {Id = "ywl", Scope = "I", Type = "L", ReferenceName = "Western Lalu"},
                                 new {Id = "ywn", Scope = "I", Type = "L", ReferenceName = "Yawanawa"},
                                 new {Id = "ywq", Scope = "I", Type = "L", ReferenceName = "Wuding-Luquan Yi"},
                                 new {Id = "ywr", Scope = "I", Type = "L", ReferenceName = "Yawuru"},
                                 new {Id = "ywt", Scope = "I", Type = "L", ReferenceName = "Xishanba Lalo"},
                                 new {Id = "ywu", Scope = "I", Type = "L", ReferenceName = "Wumeng Nasu"},
                                 new {Id = "yww", Scope = "I", Type = "E", ReferenceName = "Yawarawarga"},
                                 new {Id = "yxa", Scope = "I", Type = "E", ReferenceName = "Mayawali"},
                                 new {Id = "yxg", Scope = "I", Type = "E", ReferenceName = "Yagara"},
                                 new {Id = "yxl", Scope = "I", Type = "E", ReferenceName = "Yardliyawarra"},
                                 new {Id = "yxm", Scope = "I", Type = "E", ReferenceName = "Yinwum"},
                                 new {Id = "yxu", Scope = "I", Type = "E", ReferenceName = "Yuyu"},
                                 new {Id = "yxy", Scope = "I", Type = "E", ReferenceName = "Yabula Yabula"},
                                 new {Id = "yyr", Scope = "I", Type = "E", ReferenceName = "Yir Yoront"},
                                 new
                                     {
                                         Id            = "yyu",
                                         Scope         = "I",
                                         Type          = "L",
                                         ReferenceName = "Yau (Sandaun Province)"
                                     },
                                 new {Id = "yyz", Scope = "I", Type = "L", ReferenceName = "Ayizi"},
                                 new {Id = "yzg", Scope = "I", Type = "L", ReferenceName = "E'ma Buyang"},
                                 new {Id = "yzk", Scope = "I", Type = "L", ReferenceName = "Zokhuo"});
        }
    }
}