// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Software.Item.Versions.Item.Screenshots;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Software.Item.Versions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \software\{-id}\versions\{versionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithVersionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The screenshots property</summary>
        public global::Marechai.ApiClient.Software.Item.Versions.Item.Screenshots.ScreenshotsRequestBuilder Screenshots
        {
            get => new global::Marechai.ApiClient.Software.Item.Versions.Item.Screenshots.ScreenshotsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Software.Item.Versions.Item.WithVersionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVersionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software/{%2Did}/versions/{versionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Software.Item.Versions.Item.WithVersionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVersionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software/{%2Did}/versions/{versionId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
