// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AcceptOldDosImportResultDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The insertedDescriptionCount property</summary>
        public int? InsertedDescriptionCount { get; set; }
        /// <summary>The insertedGenreCount property</summary>
        public int? InsertedGenreCount { get; set; }
        /// <summary>The insertedReleaseCount property</summary>
        public int? InsertedReleaseCount { get; set; }
        /// <summary>The insertedVersionCount property</summary>
        public int? InsertedVersionCount { get; set; }
        /// <summary>The promotedSoftwareId property</summary>
        public int? PromotedSoftwareId { get; set; }
        /// <summary>The success property</summary>
        public bool? Success { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.AcceptOldDosImportResultDto"/> and sets the default values.
        /// </summary>
        public AcceptOldDosImportResultDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.AcceptOldDosImportResultDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.AcceptOldDosImportResultDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.AcceptOldDosImportResultDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error", n => { Error = n.GetStringValue(); } },
                { "insertedDescriptionCount", n => { InsertedDescriptionCount = n.GetIntValue(); } },
                { "insertedGenreCount", n => { InsertedGenreCount = n.GetIntValue(); } },
                { "insertedReleaseCount", n => { InsertedReleaseCount = n.GetIntValue(); } },
                { "insertedVersionCount", n => { InsertedVersionCount = n.GetIntValue(); } },
                { "promotedSoftwareId", n => { PromotedSoftwareId = n.GetIntValue(); } },
                { "success", n => { Success = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("error", Error);
            writer.WriteIntValue("insertedDescriptionCount", InsertedDescriptionCount);
            writer.WriteIntValue("insertedGenreCount", InsertedGenreCount);
            writer.WriteIntValue("insertedReleaseCount", InsertedReleaseCount);
            writer.WriteIntValue("insertedVersionCount", InsertedVersionCount);
            writer.WriteIntValue("promotedSoftwareId", PromotedSoftwareId);
            writer.WriteBoolValue("success", Success);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
