// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AcceptWwpcScreenshotDecisionDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The captionOverride property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CaptionOverride { get; set; }
#nullable restore
#else
        public string CaptionOverride { get; set; }
#endif
        /// <summary>The include property</summary>
        public bool? Include { get; set; }
        /// <summary>The softwarePlatformId property</summary>
        public int? SoftwarePlatformId { get; set; }
        /// <summary>The softwareVersionId property</summary>
        public int? SoftwareVersionId { get; set; }
        /// <summary>The wwpcScreenshotId property</summary>
        public long? WwpcScreenshotId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.AcceptWwpcScreenshotDecisionDto"/> and sets the default values.
        /// </summary>
        public AcceptWwpcScreenshotDecisionDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.AcceptWwpcScreenshotDecisionDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.AcceptWwpcScreenshotDecisionDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.AcceptWwpcScreenshotDecisionDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "captionOverride", n => { CaptionOverride = n.GetStringValue(); } },
                { "include", n => { Include = n.GetBoolValue(); } },
                { "softwarePlatformId", n => { SoftwarePlatformId = n.GetIntValue(); } },
                { "softwareVersionId", n => { SoftwareVersionId = n.GetIntValue(); } },
                { "wwpcScreenshotId", n => { WwpcScreenshotId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("captionOverride", CaptionOverride);
            writer.WriteBoolValue("include", Include);
            writer.WriteIntValue("softwarePlatformId", SoftwarePlatformId);
            writer.WriteIntValue("softwareVersionId", SoftwareVersionId);
            writer.WriteLongValue("wwpcScreenshotId", WwpcScreenshotId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
