// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConversationSummaryDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The is_system_thread property</summary>
        public bool? IsSystemThread { get; set; }
        /// <summary>The last_activity_on property</summary>
        public DateTimeOffset? LastActivityOn { get; set; }
        /// <summary>The latest_message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marechai.ApiClient.Models.ConversationSummaryDto.ConversationSummaryDto_latest_message? LatestMessage { get; set; }
#nullable restore
#else
        public global::Marechai.ApiClient.Models.ConversationSummaryDto.ConversationSummaryDto_latest_message LatestMessage { get; set; }
#endif
        /// <summary>The participants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Marechai.ApiClient.Models.UserSummaryDto>? Participants { get; set; }
#nullable restore
#else
        public List<global::Marechai.ApiClient.Models.UserSummaryDto> Participants { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The unread_count property</summary>
        public int? UnreadCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.ConversationSummaryDto"/> and sets the default values.
        /// </summary>
        public ConversationSummaryDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.ConversationSummaryDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.ConversationSummaryDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.ConversationSummaryDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetLongValue(); } },
                { "is_system_thread", n => { IsSystemThread = n.GetBoolValue(); } },
                { "last_activity_on", n => { LastActivityOn = n.GetDateTimeOffsetValue(); } },
                { "latest_message", n => { LatestMessage = n.GetObjectValue<global::Marechai.ApiClient.Models.ConversationSummaryDto.ConversationSummaryDto_latest_message>(global::Marechai.ApiClient.Models.ConversationSummaryDto.ConversationSummaryDto_latest_message.CreateFromDiscriminatorValue); } },
                { "participants", n => { Participants = n.GetCollectionOfObjectValues<global::Marechai.ApiClient.Models.UserSummaryDto>(global::Marechai.ApiClient.Models.UserSummaryDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "unread_count", n => { UnreadCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("id", Id);
            writer.WriteBoolValue("is_system_thread", IsSystemThread);
            writer.WriteDateTimeOffsetValue("last_activity_on", LastActivityOn);
            writer.WriteObjectValue<global::Marechai.ApiClient.Models.ConversationSummaryDto.ConversationSummaryDto_latest_message>("latest_message", LatestMessage);
            writer.WriteCollectionOfObjectValues<global::Marechai.ApiClient.Models.UserSummaryDto>("participants", Participants);
            writer.WriteStringValue("subject", Subject);
            writer.WriteIntValue("unread_count", UnreadCount);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Marechai.ApiClient.Models.ConversationSummaryDto_latest_messageMember1"/>, <see cref="global::Marechai.ApiClient.Models.MessageSummaryDto"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConversationSummaryDto_latest_message : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Marechai.ApiClient.Models.ConversationSummaryDto_latest_messageMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Marechai.ApiClient.Models.ConversationSummaryDto_latest_messageMember1? ConversationSummaryDtoLatestMessageMember1 { get; set; }
#nullable restore
#else
            public global::Marechai.ApiClient.Models.ConversationSummaryDto_latest_messageMember1 ConversationSummaryDtoLatestMessageMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Marechai.ApiClient.Models.MessageSummaryDto"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Marechai.ApiClient.Models.MessageSummaryDto? MessageSummaryDto { get; set; }
#nullable restore
#else
            public global::Marechai.ApiClient.Models.MessageSummaryDto MessageSummaryDto { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Marechai.ApiClient.Models.ConversationSummaryDto.ConversationSummaryDto_latest_message"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Marechai.ApiClient.Models.ConversationSummaryDto.ConversationSummaryDto_latest_message CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Marechai.ApiClient.Models.ConversationSummaryDto.ConversationSummaryDto_latest_message();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ConversationSummaryDtoLatestMessageMember1 = new global::Marechai.ApiClient.Models.ConversationSummaryDto_latest_messageMember1();
                }
                else if("MessageSummaryDto".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MessageSummaryDto = new global::Marechai.ApiClient.Models.MessageSummaryDto();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ConversationSummaryDtoLatestMessageMember1 != null)
                {
                    return ConversationSummaryDtoLatestMessageMember1.GetFieldDeserializers();
                }
                else if(MessageSummaryDto != null)
                {
                    return MessageSummaryDto.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ConversationSummaryDtoLatestMessageMember1 != null)
                {
                    writer.WriteObjectValue<global::Marechai.ApiClient.Models.ConversationSummaryDto_latest_messageMember1>(null, ConversationSummaryDtoLatestMessageMember1);
                }
                else if(MessageSummaryDto != null)
                {
                    writer.WriteObjectValue<global::Marechai.ApiClient.Models.MessageSummaryDto>(null, MessageSummaryDto);
                }
            }
        }
    }
}
#pragma warning restore CS0618
