// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MessageDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Body { get; set; }
#nullable restore
#else
        public string Body { get; set; }
#endif
        /// <summary>The conversation_id property</summary>
        public long? ConversationId { get; set; }
        /// <summary>The created_on property</summary>
        public DateTimeOffset? CreatedOn { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The is_read property</summary>
        public bool? IsRead { get; set; }
        /// <summary>The is_system_authored property</summary>
        public bool? IsSystemAuthored { get; set; }
        /// <summary>The parent_message_id property</summary>
        public long? ParentMessageId { get; set; }
        /// <summary>The sender property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marechai.ApiClient.Models.MessageDto.MessageDto_sender? Sender { get; set; }
#nullable restore
#else
        public global::Marechai.ApiClient.Models.MessageDto.MessageDto_sender Sender { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.MessageDto"/> and sets the default values.
        /// </summary>
        public MessageDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.MessageDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.MessageDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.MessageDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetStringValue(); } },
                { "conversation_id", n => { ConversationId = n.GetLongValue(); } },
                { "created_on", n => { CreatedOn = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "is_read", n => { IsRead = n.GetBoolValue(); } },
                { "is_system_authored", n => { IsSystemAuthored = n.GetBoolValue(); } },
                { "parent_message_id", n => { ParentMessageId = n.GetLongValue(); } },
                { "sender", n => { Sender = n.GetObjectValue<global::Marechai.ApiClient.Models.MessageDto.MessageDto_sender>(global::Marechai.ApiClient.Models.MessageDto.MessageDto_sender.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("body", Body);
            writer.WriteLongValue("conversation_id", ConversationId);
            writer.WriteDateTimeOffsetValue("created_on", CreatedOn);
            writer.WriteLongValue("id", Id);
            writer.WriteBoolValue("is_read", IsRead);
            writer.WriteBoolValue("is_system_authored", IsSystemAuthored);
            writer.WriteLongValue("parent_message_id", ParentMessageId);
            writer.WriteObjectValue<global::Marechai.ApiClient.Models.MessageDto.MessageDto_sender>("sender", Sender);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Marechai.ApiClient.Models.MessageDto_senderMember1"/>, <see cref="global::Marechai.ApiClient.Models.UserSummaryDto"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MessageDto_sender : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Marechai.ApiClient.Models.MessageDto_senderMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Marechai.ApiClient.Models.MessageDto_senderMember1? MessageDtoSenderMember1 { get; set; }
#nullable restore
#else
            public global::Marechai.ApiClient.Models.MessageDto_senderMember1 MessageDtoSenderMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Marechai.ApiClient.Models.UserSummaryDto"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Marechai.ApiClient.Models.UserSummaryDto? UserSummaryDto { get; set; }
#nullable restore
#else
            public global::Marechai.ApiClient.Models.UserSummaryDto UserSummaryDto { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Marechai.ApiClient.Models.MessageDto.MessageDto_sender"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Marechai.ApiClient.Models.MessageDto.MessageDto_sender CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Marechai.ApiClient.Models.MessageDto.MessageDto_sender();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MessageDtoSenderMember1 = new global::Marechai.ApiClient.Models.MessageDto_senderMember1();
                }
                else if("UserSummaryDto".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UserSummaryDto = new global::Marechai.ApiClient.Models.UserSummaryDto();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MessageDtoSenderMember1 != null)
                {
                    return MessageDtoSenderMember1.GetFieldDeserializers();
                }
                else if(UserSummaryDto != null)
                {
                    return UserSummaryDto.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(MessageDtoSenderMember1 != null)
                {
                    writer.WriteObjectValue<global::Marechai.ApiClient.Models.MessageDto_senderMember1>(null, MessageDtoSenderMember1);
                }
                else if(UserSummaryDto != null)
                {
                    writer.WriteObjectValue<global::Marechai.ApiClient.Models.UserSummaryDto>(null, UserSummaryDto);
                }
            }
        }
    }
}
#pragma warning restore CS0618
