// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PersonFullDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The books property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Marechai.ApiClient.Models.PersonByBookDto>? Books { get; set; }
#nullable restore
#else
        public List<global::Marechai.ApiClient.Models.PersonByBookDto> Books { get; set; }
#endif
        /// <summary>The companies property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Marechai.ApiClient.Models.PersonByCompanyDto>? Companies { get; set; }
#nullable restore
#else
        public List<global::Marechai.ApiClient.Models.PersonByCompanyDto> Companies { get; set; }
#endif
        /// <summary>The documents property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Marechai.ApiClient.Models.PersonByDocumentDto>? Documents { get; set; }
#nullable restore
#else
        public List<global::Marechai.ApiClient.Models.PersonByDocumentDto> Documents { get; set; }
#endif
        /// <summary>The magazines property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Marechai.ApiClient.Models.PersonByMagazineDto>? Magazines { get; set; }
#nullable restore
#else
        public List<global::Marechai.ApiClient.Models.PersonByMagazineDto> Magazines { get; set; }
#endif
        /// <summary>The person property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marechai.ApiClient.Models.PersonDto? Person { get; set; }
#nullable restore
#else
        public global::Marechai.ApiClient.Models.PersonDto Person { get; set; }
#endif
        /// <summary>The software_credits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Marechai.ApiClient.Models.PersonBySoftwareDto>? SoftwareCredits { get; set; }
#nullable restore
#else
        public List<global::Marechai.ApiClient.Models.PersonBySoftwareDto> SoftwareCredits { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.PersonFullDto"/> and sets the default values.
        /// </summary>
        public PersonFullDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.PersonFullDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.PersonFullDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.PersonFullDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "books", n => { Books = n.GetCollectionOfObjectValues<global::Marechai.ApiClient.Models.PersonByBookDto>(global::Marechai.ApiClient.Models.PersonByBookDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "companies", n => { Companies = n.GetCollectionOfObjectValues<global::Marechai.ApiClient.Models.PersonByCompanyDto>(global::Marechai.ApiClient.Models.PersonByCompanyDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "documents", n => { Documents = n.GetCollectionOfObjectValues<global::Marechai.ApiClient.Models.PersonByDocumentDto>(global::Marechai.ApiClient.Models.PersonByDocumentDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "magazines", n => { Magazines = n.GetCollectionOfObjectValues<global::Marechai.ApiClient.Models.PersonByMagazineDto>(global::Marechai.ApiClient.Models.PersonByMagazineDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "person", n => { Person = n.GetObjectValue<global::Marechai.ApiClient.Models.PersonDto>(global::Marechai.ApiClient.Models.PersonDto.CreateFromDiscriminatorValue); } },
                { "software_credits", n => { SoftwareCredits = n.GetCollectionOfObjectValues<global::Marechai.ApiClient.Models.PersonBySoftwareDto>(global::Marechai.ApiClient.Models.PersonBySoftwareDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Marechai.ApiClient.Models.PersonByBookDto>("books", Books);
            writer.WriteCollectionOfObjectValues<global::Marechai.ApiClient.Models.PersonByCompanyDto>("companies", Companies);
            writer.WriteCollectionOfObjectValues<global::Marechai.ApiClient.Models.PersonByDocumentDto>("documents", Documents);
            writer.WriteCollectionOfObjectValues<global::Marechai.ApiClient.Models.PersonByMagazineDto>("magazines", Magazines);
            writer.WriteObjectValue<global::Marechai.ApiClient.Models.PersonDto>("person", Person);
            writer.WriteCollectionOfObjectValues<global::Marechai.ApiClient.Models.PersonBySoftwareDto>("software_credits", SoftwareCredits);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
