// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ResolutionByScreenDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The resolution property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marechai.ApiClient.Models.ResolutionByScreenDto.ResolutionByScreenDto_resolution? Resolution { get; set; }
#nullable restore
#else
        public global::Marechai.ApiClient.Models.ResolutionByScreenDto.ResolutionByScreenDto_resolution Resolution { get; set; }
#endif
        /// <summary>The resolution_id property</summary>
        public int? ResolutionId { get; set; }
        /// <summary>The screen_id property</summary>
        public int? ScreenId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.ResolutionByScreenDto"/> and sets the default values.
        /// </summary>
        public ResolutionByScreenDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.ResolutionByScreenDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.ResolutionByScreenDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.ResolutionByScreenDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetLongValue(); } },
                { "resolution", n => { Resolution = n.GetObjectValue<global::Marechai.ApiClient.Models.ResolutionByScreenDto.ResolutionByScreenDto_resolution>(global::Marechai.ApiClient.Models.ResolutionByScreenDto.ResolutionByScreenDto_resolution.CreateFromDiscriminatorValue); } },
                { "resolution_id", n => { ResolutionId = n.GetIntValue(); } },
                { "screen_id", n => { ScreenId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("id", Id);
            writer.WriteObjectValue<global::Marechai.ApiClient.Models.ResolutionByScreenDto.ResolutionByScreenDto_resolution>("resolution", Resolution);
            writer.WriteIntValue("resolution_id", ResolutionId);
            writer.WriteIntValue("screen_id", ScreenId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Marechai.ApiClient.Models.ResolutionByScreenDto_resolutionMember1"/>, <see cref="global::Marechai.ApiClient.Models.ResolutionDto"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ResolutionByScreenDto_resolution : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Marechai.ApiClient.Models.ResolutionByScreenDto_resolutionMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Marechai.ApiClient.Models.ResolutionByScreenDto_resolutionMember1? ResolutionByScreenDtoResolutionMember1 { get; set; }
#nullable restore
#else
            public global::Marechai.ApiClient.Models.ResolutionByScreenDto_resolutionMember1 ResolutionByScreenDtoResolutionMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Marechai.ApiClient.Models.ResolutionDto"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Marechai.ApiClient.Models.ResolutionDto? ResolutionDto { get; set; }
#nullable restore
#else
            public global::Marechai.ApiClient.Models.ResolutionDto ResolutionDto { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Marechai.ApiClient.Models.ResolutionByScreenDto.ResolutionByScreenDto_resolution"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Marechai.ApiClient.Models.ResolutionByScreenDto.ResolutionByScreenDto_resolution CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Marechai.ApiClient.Models.ResolutionByScreenDto.ResolutionByScreenDto_resolution();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ResolutionByScreenDtoResolutionMember1 = new global::Marechai.ApiClient.Models.ResolutionByScreenDto_resolutionMember1();
                }
                else if("ResolutionDto".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ResolutionDto = new global::Marechai.ApiClient.Models.ResolutionDto();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ResolutionByScreenDtoResolutionMember1 != null)
                {
                    return ResolutionByScreenDtoResolutionMember1.GetFieldDeserializers();
                }
                else if(ResolutionDto != null)
                {
                    return ResolutionDto.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ResolutionByScreenDtoResolutionMember1 != null)
                {
                    writer.WriteObjectValue<global::Marechai.ApiClient.Models.ResolutionByScreenDto_resolutionMember1>(null, ResolutionByScreenDtoResolutionMember1);
                }
                else if(ResolutionDto != null)
                {
                    writer.WriteObjectValue<global::Marechai.ApiClient.Models.ResolutionDto>(null, ResolutionDto);
                }
            }
        }
    }
}
#pragma warning restore CS0618
