// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReviewReportDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_on property</summary>
        public DateTimeOffset? CreatedOn { get; set; }
        /// <summary>The explanation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Explanation { get; set; }
#nullable restore
#else
        public string Explanation { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The is_resolved property</summary>
        public bool? IsResolved { get; set; }
        /// <summary>The reason property</summary>
        public int? Reason { get; set; }
        /// <summary>The reporter_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReporterId { get; set; }
#nullable restore
#else
        public string ReporterId { get; set; }
#endif
        /// <summary>The reporter_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReporterName { get; set; }
#nullable restore
#else
        public string ReporterName { get; set; }
#endif
        /// <summary>The resolved_by_user_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResolvedByUserName { get; set; }
#nullable restore
#else
        public string ResolvedByUserName { get; set; }
#endif
        /// <summary>The resolved_on property</summary>
        public DateTimeOffset? ResolvedOn { get; set; }
        /// <summary>The reviewer_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReviewerName { get; set; }
#nullable restore
#else
        public string ReviewerName { get; set; }
#endif
        /// <summary>The review_id property</summary>
        public long? ReviewId { get; set; }
        /// <summary>The software_id property</summary>
        public int? SoftwareId { get; set; }
        /// <summary>The software_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SoftwareName { get; set; }
#nullable restore
#else
        public string SoftwareName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.ReviewReportDto"/> and sets the default values.
        /// </summary>
        public ReviewReportDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.ReviewReportDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.ReviewReportDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.ReviewReportDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_on", n => { CreatedOn = n.GetDateTimeOffsetValue(); } },
                { "explanation", n => { Explanation = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "is_resolved", n => { IsResolved = n.GetBoolValue(); } },
                { "reason", n => { Reason = n.GetIntValue(); } },
                { "reporter_id", n => { ReporterId = n.GetStringValue(); } },
                { "reporter_name", n => { ReporterName = n.GetStringValue(); } },
                { "resolved_by_user_name", n => { ResolvedByUserName = n.GetStringValue(); } },
                { "resolved_on", n => { ResolvedOn = n.GetDateTimeOffsetValue(); } },
                { "review_id", n => { ReviewId = n.GetLongValue(); } },
                { "reviewer_name", n => { ReviewerName = n.GetStringValue(); } },
                { "software_id", n => { SoftwareId = n.GetIntValue(); } },
                { "software_name", n => { SoftwareName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_on", CreatedOn);
            writer.WriteStringValue("explanation", Explanation);
            writer.WriteLongValue("id", Id);
            writer.WriteBoolValue("is_resolved", IsResolved);
            writer.WriteIntValue("reason", Reason);
            writer.WriteStringValue("reporter_id", ReporterId);
            writer.WriteStringValue("reporter_name", ReporterName);
            writer.WriteStringValue("resolved_by_user_name", ResolvedByUserName);
            writer.WriteDateTimeOffsetValue("resolved_on", ResolvedOn);
            writer.WriteStringValue("reviewer_name", ReviewerName);
            writer.WriteLongValue("review_id", ReviewId);
            writer.WriteIntValue("software_id", SoftwareId);
            writer.WriteStringValue("software_name", SoftwareName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
