// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchResultDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alt_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AltName { get; set; }
#nullable restore
#else
        public string AltName { get; set; }
#endif
        /// <summary>The country_id property</summary>
        public int? CountryId { get; set; }
        /// <summary>The country_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryName { get; set; }
#nullable restore
#else
        public string CountryName { get; set; }
#endif
        /// <summary>The display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The entity_id property</summary>
        public long? EntityId { get; set; }
        /// <summary>The entity_type property</summary>
        public int? EntityType { get; set; }
        /// <summary>The has_image property</summary>
        public bool? HasImage { get; set; }
        /// <summary>The score property</summary>
        public double? Score { get; set; }
        /// <summary>The year property</summary>
        public int? Year { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.SearchResultDto"/> and sets the default values.
        /// </summary>
        public SearchResultDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.SearchResultDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.SearchResultDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.SearchResultDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alt_name", n => { AltName = n.GetStringValue(); } },
                { "country_id", n => { CountryId = n.GetIntValue(); } },
                { "country_name", n => { CountryName = n.GetStringValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "entity_id", n => { EntityId = n.GetLongValue(); } },
                { "entity_type", n => { EntityType = n.GetIntValue(); } },
                { "has_image", n => { HasImage = n.GetBoolValue(); } },
                { "score", n => { Score = n.GetDoubleValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alt_name", AltName);
            writer.WriteIntValue("country_id", CountryId);
            writer.WriteStringValue("country_name", CountryName);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteLongValue("entity_id", EntityId);
            writer.WriteIntValue("entity_type", EntityType);
            writer.WriteBoolValue("has_image", HasImage);
            writer.WriteDoubleValue("score", Score);
            writer.WriteIntValue("year", Year);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
