// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SoftwarePromoArtDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The caption property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Caption { get; set; }
#nullable restore
#else
        public string Caption { get; set; }
#endif
        /// <summary>The group_id property</summary>
        public int? GroupId { get; set; }
        /// <summary>The group_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupName { get; set; }
#nullable restore
#else
        public string GroupName { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The original_extension property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalExtension { get; set; }
#nullable restore
#else
        public string OriginalExtension { get; set; }
#endif
        /// <summary>The software_id property</summary>
        public int? SoftwareId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.SoftwarePromoArtDto"/> and sets the default values.
        /// </summary>
        public SoftwarePromoArtDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.SoftwarePromoArtDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.SoftwarePromoArtDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.SoftwarePromoArtDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "caption", n => { Caption = n.GetStringValue(); } },
                { "group_id", n => { GroupId = n.GetIntValue(); } },
                { "group_name", n => { GroupName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "original_extension", n => { OriginalExtension = n.GetStringValue(); } },
                { "software_id", n => { SoftwareId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("caption", Caption);
            writer.WriteIntValue("group_id", GroupId);
            writer.WriteStringValue("group_name", GroupName);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("original_extension", OriginalExtension);
            writer.WriteIntValue("software_id", SoftwareId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
