// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SoftwareRequirementDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The required_software_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequiredSoftwareVersion { get; set; }
#nullable restore
#else
        public string RequiredSoftwareVersion { get; set; }
#endif
        /// <summary>The required_software_version_id property</summary>
        public int? RequiredSoftwareVersionId { get; set; }
        /// <summary>The requirement_type property</summary>
        public int? RequirementType { get; set; }
        /// <summary>The software_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SoftwareVersion { get; set; }
#nullable restore
#else
        public string SoftwareVersion { get; set; }
#endif
        /// <summary>The software_version_id property</summary>
        public int? SoftwareVersionId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.SoftwareRequirementDto"/> and sets the default values.
        /// </summary>
        public SoftwareRequirementDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.SoftwareRequirementDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.SoftwareRequirementDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.SoftwareRequirementDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "required_software_version", n => { RequiredSoftwareVersion = n.GetStringValue(); } },
                { "required_software_version_id", n => { RequiredSoftwareVersionId = n.GetIntValue(); } },
                { "requirement_type", n => { RequirementType = n.GetIntValue(); } },
                { "software_version", n => { SoftwareVersion = n.GetStringValue(); } },
                { "software_version_id", n => { SoftwareVersionId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("required_software_version", RequiredSoftwareVersion);
            writer.WriteIntValue("required_software_version_id", RequiredSoftwareVersionId);
            writer.WriteIntValue("requirement_type", RequirementType);
            writer.WriteStringValue("software_version", SoftwareVersion);
            writer.WriteIntValue("software_version_id", SoftwareVersionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
