// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SoftwareCompilationDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The front_cover_id property</summary>
        public Guid? FrontCoverId { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The machine property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Machine { get; set; }
#nullable restore
#else
        public string Machine { get; set; }
#endif
        /// <summary>The machine_id property</summary>
        public int? MachineId { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The predecessor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Predecessor { get; set; }
#nullable restore
#else
        public string Predecessor { get; set; }
#endif
        /// <summary>The predecessor_id property</summary>
        public int? PredecessorId { get; set; }
        /// <summary>The relationship_type property</summary>
        public int? RelationshipType { get; set; }
        /// <summary>The software property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Software { get; set; }
#nullable restore
#else
        public string Software { get; set; }
#endif
        /// <summary>The software_id property</summary>
        public int? SoftwareId { get; set; }
        /// <summary>The successors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Marechai.ApiClient.Models.SoftwareCompilationSuccessorDto>? Successors { get; set; }
#nullable restore
#else
        public List<global::Marechai.ApiClient.Models.SoftwareCompilationSuccessorDto> Successors { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.SoftwareCompilationDto"/> and sets the default values.
        /// </summary>
        public SoftwareCompilationDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.SoftwareCompilationDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.SoftwareCompilationDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.SoftwareCompilationDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "front_cover_id", n => { FrontCoverId = n.GetGuidValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "machine", n => { Machine = n.GetStringValue(); } },
                { "machine_id", n => { MachineId = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "predecessor", n => { Predecessor = n.GetStringValue(); } },
                { "predecessor_id", n => { PredecessorId = n.GetIntValue(); } },
                { "relationship_type", n => { RelationshipType = n.GetIntValue(); } },
                { "software", n => { Software = n.GetStringValue(); } },
                { "software_id", n => { SoftwareId = n.GetIntValue(); } },
                { "successors", n => { Successors = n.GetCollectionOfObjectValues<global::Marechai.ApiClient.Models.SoftwareCompilationSuccessorDto>(global::Marechai.ApiClient.Models.SoftwareCompilationSuccessorDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("front_cover_id", FrontCoverId);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("machine", Machine);
            writer.WriteIntValue("machine_id", MachineId);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("predecessor", Predecessor);
            writer.WriteIntValue("predecessor_id", PredecessorId);
            writer.WriteIntValue("relationship_type", RelationshipType);
            writer.WriteStringValue("software", Software);
            writer.WriteIntValue("software_id", SoftwareId);
            writer.WriteCollectionOfObjectValues<global::Marechai.ApiClient.Models.SoftwareCompilationSuccessorDto>("successors", Successors);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
