// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SoftwareRankingDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The critic_average property</summary>
        public double? CriticAverage { get; set; }
        /// <summary>The critic_review_count property</summary>
        public int? CriticReviewCount { get; set; }
        /// <summary>The family property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Family { get; set; }
#nullable restore
#else
        public string Family { get; set; }
#endif
        /// <summary>The front_cover_id property</summary>
        public Guid? FrontCoverId { get; set; }
        /// <summary>The kind property</summary>
        public int? Kind { get; set; }
        /// <summary>The marechai_score property</summary>
        public double? MarechaiScore { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The rank property</summary>
        public int? Rank { get; set; }
        /// <summary>The software_id property</summary>
        public int? SoftwareId { get; set; }
        /// <summary>The user_rating_count property</summary>
        public int? UserRatingCount { get; set; }
        /// <summary>The user_star_average property</summary>
        public double? UserStarAverage { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.SoftwareRankingDto"/> and sets the default values.
        /// </summary>
        public SoftwareRankingDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.SoftwareRankingDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.SoftwareRankingDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.SoftwareRankingDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "critic_average", n => { CriticAverage = n.GetDoubleValue(); } },
                { "critic_review_count", n => { CriticReviewCount = n.GetIntValue(); } },
                { "family", n => { Family = n.GetStringValue(); } },
                { "front_cover_id", n => { FrontCoverId = n.GetGuidValue(); } },
                { "kind", n => { Kind = n.GetIntValue(); } },
                { "marechai_score", n => { MarechaiScore = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "rank", n => { Rank = n.GetIntValue(); } },
                { "software_id", n => { SoftwareId = n.GetIntValue(); } },
                { "user_rating_count", n => { UserRatingCount = n.GetIntValue(); } },
                { "user_star_average", n => { UserStarAverage = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("critic_average", CriticAverage);
            writer.WriteIntValue("critic_review_count", CriticReviewCount);
            writer.WriteStringValue("family", Family);
            writer.WriteGuidValue("front_cover_id", FrontCoverId);
            writer.WriteIntValue("kind", Kind);
            writer.WriteDoubleValue("marechai_score", MarechaiScore);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("rank", Rank);
            writer.WriteIntValue("software_id", SoftwareId);
            writer.WriteIntValue("user_rating_count", UserRatingCount);
            writer.WriteDoubleValue("user_star_average", UserStarAverage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
