// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SoundSynthDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The company property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Company { get; set; }
#nullable restore
#else
        public string Company { get; set; }
#endif
        /// <summary>The company_id property</summary>
        public int? CompanyId { get; set; }
        /// <summary>The depth property</summary>
        public int? Depth { get; set; }
        /// <summary>The frequency property</summary>
        public double? Frequency { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The introduced property</summary>
        public DateTimeOffset? Introduced { get; set; }
        /// <summary>The introduced_precision property</summary>
        public int? IntroducedPrecision { get; set; }
        /// <summary>The model_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModelCode { get; set; }
#nullable restore
#else
        public string ModelCode { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The square_wave property</summary>
        public int? SquareWave { get; set; }
        /// <summary>The type property</summary>
        public int? Type { get; set; }
        /// <summary>The voices property</summary>
        public int? Voices { get; set; }
        /// <summary>The white_noise property</summary>
        public int? WhiteNoise { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.SoundSynthDto"/> and sets the default values.
        /// </summary>
        public SoundSynthDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.SoundSynthDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.SoundSynthDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.SoundSynthDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "company", n => { Company = n.GetStringValue(); } },
                { "company_id", n => { CompanyId = n.GetIntValue(); } },
                { "depth", n => { Depth = n.GetIntValue(); } },
                { "frequency", n => { Frequency = n.GetDoubleValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "introduced", n => { Introduced = n.GetDateTimeOffsetValue(); } },
                { "introduced_precision", n => { IntroducedPrecision = n.GetIntValue(); } },
                { "model_code", n => { ModelCode = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "square_wave", n => { SquareWave = n.GetIntValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
                { "voices", n => { Voices = n.GetIntValue(); } },
                { "white_noise", n => { WhiteNoise = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("company", Company);
            writer.WriteIntValue("company_id", CompanyId);
            writer.WriteIntValue("depth", Depth);
            writer.WriteDoubleValue("frequency", Frequency);
            writer.WriteIntValue("id", Id);
            writer.WriteDateTimeOffsetValue("introduced", Introduced);
            writer.WriteIntValue("introduced_precision", IntroducedPrecision);
            writer.WriteStringValue("model_code", ModelCode);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("square_wave", SquareWave);
            writer.WriteIntValue("type", Type);
            writer.WriteIntValue("voices", Voices);
            writer.WriteIntValue("white_noise", WhiteNoise);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
