// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SuggestionDiffDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current_values_json property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentValuesJson { get; set; }
#nullable restore
#else
        public string CurrentValuesJson { get; set; }
#endif
        /// <summary>The entity_missing property</summary>
        public bool? EntityMissing { get; set; }
        /// <summary>The suggestion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marechai.ApiClient.Models.SuggestionDto? Suggestion { get; set; }
#nullable restore
#else
        public global::Marechai.ApiClient.Models.SuggestionDto Suggestion { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.SuggestionDiffDto"/> and sets the default values.
        /// </summary>
        public SuggestionDiffDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.SuggestionDiffDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.SuggestionDiffDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.SuggestionDiffDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current_values_json", n => { CurrentValuesJson = n.GetStringValue(); } },
                { "entity_missing", n => { EntityMissing = n.GetBoolValue(); } },
                { "suggestion", n => { Suggestion = n.GetObjectValue<global::Marechai.ApiClient.Models.SuggestionDto>(global::Marechai.ApiClient.Models.SuggestionDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("current_values_json", CurrentValuesJson);
            writer.WriteBoolValue("entity_missing", EntityMissing);
            writer.WriteObjectValue<global::Marechai.ApiClient.Models.SuggestionDto>("suggestion", Suggestion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
