// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UnM49BySoftwareReleaseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The region_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegionName { get; set; }
#nullable restore
#else
        public string RegionName { get; set; }
#endif
        /// <summary>The software_release_id property</summary>
        public int? SoftwareReleaseId { get; set; }
        /// <summary>The un_m49_id property</summary>
        public int? UnM49Id { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Models.UnM49BySoftwareReleaseDto"/> and sets the default values.
        /// </summary>
        public UnM49BySoftwareReleaseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.ApiClient.Models.UnM49BySoftwareReleaseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.ApiClient.Models.UnM49BySoftwareReleaseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.ApiClient.Models.UnM49BySoftwareReleaseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "region_name", n => { RegionName = n.GetStringValue(); } },
                { "software_release_id", n => { SoftwareReleaseId = n.GetIntValue(); } },
                { "un_m49_id", n => { UnM49Id = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("region_name", RegionName);
            writer.WriteIntValue("software_release_id", SoftwareReleaseId);
            writer.WriteIntValue("un_m49_id", UnM49Id);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
