// <auto-generated/>
#pragma warning disable CS0618
using Marechai.App.ResolutionsByGpu.Gpus.Item.Resolutions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.App.ResolutionsByGpu.Gpus.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \resolutions-by-gpu\gpus\{resolutionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithResolutionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The resolutions property</summary>
        public global::Marechai.App.ResolutionsByGpu.Gpus.Item.Resolutions.ResolutionsRequestBuilder Resolutions
        {
            get => new global::Marechai.App.ResolutionsByGpu.Gpus.Item.Resolutions.ResolutionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.ResolutionsByGpu.Gpus.Item.WithResolutionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResolutionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resolutions-by-gpu/gpus/{resolutionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.ResolutionsByGpu.Gpus.Item.WithResolutionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResolutionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resolutions-by-gpu/gpus/{resolutionId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
