// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Companies.Logos.ChangeYear.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Companies.Logos.ChangeYear
{
    /// <summary>
    /// Builds and executes requests for operations under \companies\logos\change-year
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChangeYearRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Marechai.ApiClient.companies.logos.changeYear.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Companies.Logos.ChangeYear.Item.ChangeYearItemRequestBuilder"/></returns>
        public global::Marechai.ApiClient.Companies.Logos.ChangeYear.Item.ChangeYearItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Marechai.ApiClient.Companies.Logos.ChangeYear.Item.ChangeYearItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Marechai.ApiClient.companies.logos.changeYear.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.Companies.Logos.ChangeYear.Item.ChangeYearItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Marechai.ApiClient.Companies.Logos.ChangeYear.Item.ChangeYearItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Marechai.ApiClient.Companies.Logos.ChangeYear.Item.ChangeYearItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Companies.Logos.ChangeYear.ChangeYearRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChangeYearRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/companies/logos/change-year", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Companies.Logos.ChangeYear.ChangeYearRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChangeYearRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/companies/logos/change-year", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
