// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Gpus.Photos.Admin.Batch.Item.Status;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Gpus.Photos.Admin.Batch.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \gpus\photos\admin\batch\{jobId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithJobItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The status property</summary>
        public global::Marechai.ApiClient.Gpus.Photos.Admin.Batch.Item.Status.StatusRequestBuilder Status
        {
            get => new global::Marechai.ApiClient.Gpus.Photos.Admin.Batch.Item.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Gpus.Photos.Admin.Batch.Item.WithJobItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithJobItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gpus/photos/admin/batch/{jobId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Gpus.Photos.Admin.Batch.Item.WithJobItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithJobItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gpus/photos/admin/batch/{jobId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
