// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.App.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProcessorDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address_bus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AddressBus { get; set; }
#nullable restore
#else
        public UntypedNode AddressBus { get; set; }
#endif
        /// <summary>The company property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Company { get; set; }
#nullable restore
#else
        public string Company { get; set; }
#endif
        /// <summary>The company_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CompanyId { get; set; }
#nullable restore
#else
        public UntypedNode CompanyId { get; set; }
#endif
        /// <summary>The cores property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Cores { get; set; }
#nullable restore
#else
        public UntypedNode Cores { get; set; }
#endif
        /// <summary>The data_bus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DataBus { get; set; }
#nullable restore
#else
        public UntypedNode DataBus { get; set; }
#endif
        /// <summary>The die_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DieSize { get; set; }
#nullable restore
#else
        public UntypedNode DieSize { get; set; }
#endif
        /// <summary>The fprs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Fprs { get; set; }
#nullable restore
#else
        public UntypedNode Fprs { get; set; }
#endif
        /// <summary>The fpr_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? FprSize { get; set; }
#nullable restore
#else
        public UntypedNode FprSize { get; set; }
#endif
        /// <summary>The gprs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Gprs { get; set; }
#nullable restore
#else
        public UntypedNode Gprs { get; set; }
#endif
        /// <summary>The gpr_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? GprSize { get; set; }
#nullable restore
#else
        public UntypedNode GprSize { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Id { get; set; }
#nullable restore
#else
        public UntypedNode Id { get; set; }
#endif
        /// <summary>The instruction_set property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstructionSet { get; set; }
#nullable restore
#else
        public string InstructionSet { get; set; }
#endif
        /// <summary>The instruction_set_extensions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? InstructionSetExtensions { get; set; }
#nullable restore
#else
        public List<string> InstructionSetExtensions { get; set; }
#endif
        /// <summary>The instruction_set_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? InstructionSetId { get; set; }
#nullable restore
#else
        public UntypedNode InstructionSetId { get; set; }
#endif
        /// <summary>The introduced property</summary>
        public DateTimeOffset? Introduced { get; set; }
        /// <summary>The l1_data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? L1Data { get; set; }
#nullable restore
#else
        public UntypedNode L1Data { get; set; }
#endif
        /// <summary>The l1_instruction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? L1Instruction { get; set; }
#nullable restore
#else
        public UntypedNode L1Instruction { get; set; }
#endif
        /// <summary>The l2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? L2 { get; set; }
#nullable restore
#else
        public UntypedNode L2 { get; set; }
#endif
        /// <summary>The l3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? L3 { get; set; }
#nullable restore
#else
        public UntypedNode L3 { get; set; }
#endif
        /// <summary>The model_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModelCode { get; set; }
#nullable restore
#else
        public string ModelCode { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The package property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Package { get; set; }
#nullable restore
#else
        public string Package { get; set; }
#endif
        /// <summary>The process property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Process { get; set; }
#nullable restore
#else
        public string Process { get; set; }
#endif
        /// <summary>The process_nm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ProcessNm { get; set; }
#nullable restore
#else
        public UntypedNode ProcessNm { get; set; }
#endif
        /// <summary>The simd_registers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? SimdRegisters { get; set; }
#nullable restore
#else
        public UntypedNode SimdRegisters { get; set; }
#endif
        /// <summary>The simd_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? SimdSize { get; set; }
#nullable restore
#else
        public UntypedNode SimdSize { get; set; }
#endif
        /// <summary>The speed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Speed { get; set; }
#nullable restore
#else
        public UntypedNode Speed { get; set; }
#endif
        /// <summary>The threads_per_core property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ThreadsPerCore { get; set; }
#nullable restore
#else
        public UntypedNode ThreadsPerCore { get; set; }
#endif
        /// <summary>The transistors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Transistors { get; set; }
#nullable restore
#else
        public UntypedNode Transistors { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.Models.ProcessorDto"/> and sets the default values.
        /// </summary>
        public ProcessorDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.App.Models.ProcessorDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.App.Models.ProcessorDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.App.Models.ProcessorDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address_bus", n => { AddressBus = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "company", n => { Company = n.GetStringValue(); } },
                { "company_id", n => { CompanyId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "cores", n => { Cores = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "data_bus", n => { DataBus = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "die_size", n => { DieSize = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "fpr_size", n => { FprSize = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "fprs", n => { Fprs = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "gpr_size", n => { GprSize = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "gprs", n => { Gprs = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "instruction_set", n => { InstructionSet = n.GetStringValue(); } },
                { "instruction_set_extensions", n => { InstructionSetExtensions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "instruction_set_id", n => { InstructionSetId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "introduced", n => { Introduced = n.GetDateTimeOffsetValue(); } },
                { "l1_data", n => { L1Data = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "l1_instruction", n => { L1Instruction = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "l2", n => { L2 = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "l3", n => { L3 = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "model_code", n => { ModelCode = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "package", n => { Package = n.GetStringValue(); } },
                { "process", n => { Process = n.GetStringValue(); } },
                { "process_nm", n => { ProcessNm = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "simd_registers", n => { SimdRegisters = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "simd_size", n => { SimdSize = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "speed", n => { Speed = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "threads_per_core", n => { ThreadsPerCore = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "transistors", n => { Transistors = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("address_bus", AddressBus);
            writer.WriteStringValue("company", Company);
            writer.WriteObjectValue<UntypedNode>("company_id", CompanyId);
            writer.WriteObjectValue<UntypedNode>("cores", Cores);
            writer.WriteObjectValue<UntypedNode>("data_bus", DataBus);
            writer.WriteObjectValue<UntypedNode>("die_size", DieSize);
            writer.WriteObjectValue<UntypedNode>("fprs", Fprs);
            writer.WriteObjectValue<UntypedNode>("fpr_size", FprSize);
            writer.WriteObjectValue<UntypedNode>("gprs", Gprs);
            writer.WriteObjectValue<UntypedNode>("gpr_size", GprSize);
            writer.WriteObjectValue<UntypedNode>("id", Id);
            writer.WriteStringValue("instruction_set", InstructionSet);
            writer.WriteCollectionOfPrimitiveValues<string>("instruction_set_extensions", InstructionSetExtensions);
            writer.WriteObjectValue<UntypedNode>("instruction_set_id", InstructionSetId);
            writer.WriteDateTimeOffsetValue("introduced", Introduced);
            writer.WriteObjectValue<UntypedNode>("l1_data", L1Data);
            writer.WriteObjectValue<UntypedNode>("l1_instruction", L1Instruction);
            writer.WriteObjectValue<UntypedNode>("l2", L2);
            writer.WriteObjectValue<UntypedNode>("l3", L3);
            writer.WriteStringValue("model_code", ModelCode);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("package", Package);
            writer.WriteStringValue("process", Process);
            writer.WriteObjectValue<UntypedNode>("process_nm", ProcessNm);
            writer.WriteObjectValue<UntypedNode>("simd_registers", SimdRegisters);
            writer.WriteObjectValue<UntypedNode>("simd_size", SimdSize);
            writer.WriteObjectValue<UntypedNode>("speed", Speed);
            writer.WriteObjectValue<UntypedNode>("threads_per_core", ThreadsPerCore);
            writer.WriteObjectValue<UntypedNode>("transistors", Transistors);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
