// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.App.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SoftwareScreenshotDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The caption property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Caption { get; set; }
#nullable restore
#else
        public string Caption { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The original_extension property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalExtension { get; set; }
#nullable restore
#else
        public string OriginalExtension { get; set; }
#endif
        /// <summary>The platform_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlatformName { get; set; }
#nullable restore
#else
        public string PlatformName { get; set; }
#endif
        /// <summary>The software_id property</summary>
        public int? SoftwareId { get; set; }
        /// <summary>The software_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SoftwareName { get; set; }
#nullable restore
#else
        public string SoftwareName { get; set; }
#endif
        /// <summary>The software_platform_id property</summary>
        public int? SoftwarePlatformId { get; set; }
        /// <summary>The software_version_id property</summary>
        public int? SoftwareVersionId { get; set; }
        /// <summary>The version_string property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionString { get; set; }
#nullable restore
#else
        public string VersionString { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.Models.SoftwareScreenshotDto"/> and sets the default values.
        /// </summary>
        public SoftwareScreenshotDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.App.Models.SoftwareScreenshotDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.App.Models.SoftwareScreenshotDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.App.Models.SoftwareScreenshotDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "caption", n => { Caption = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "original_extension", n => { OriginalExtension = n.GetStringValue(); } },
                { "platform_name", n => { PlatformName = n.GetStringValue(); } },
                { "software_id", n => { SoftwareId = n.GetIntValue(); } },
                { "software_name", n => { SoftwareName = n.GetStringValue(); } },
                { "software_platform_id", n => { SoftwarePlatformId = n.GetIntValue(); } },
                { "software_version_id", n => { SoftwareVersionId = n.GetIntValue(); } },
                { "version_string", n => { VersionString = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("caption", Caption);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("original_extension", OriginalExtension);
            writer.WriteStringValue("platform_name", PlatformName);
            writer.WriteIntValue("software_id", SoftwareId);
            writer.WriteStringValue("software_name", SoftwareName);
            writer.WriteIntValue("software_platform_id", SoftwarePlatformId);
            writer.WriteIntValue("software_version_id", SoftwareVersionId);
            writer.WriteStringValue("version_string", VersionString);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
