// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marechai.App.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SoftwareVariantDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The catalogue_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CatalogueNumber { get; set; }
#nullable restore
#else
        public string CatalogueNumber { get; set; }
#endif
        /// <summary>The distribution_mode property</summary>
        public int? DistributionMode { get; set; }
        /// <summary>The family property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Family { get; set; }
#nullable restore
#else
        public string Family { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Id { get; set; }
#nullable restore
#else
        public UntypedNode Id { get; set; }
#endif
        /// <summary>The introduced property</summary>
        public DateTimeOffset? Introduced { get; set; }
        /// <summary>The minimum_memory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? MinimumMemory { get; set; }
#nullable restore
#else
        public UntypedNode MinimumMemory { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Parent { get; set; }
#nullable restore
#else
        public string Parent { get; set; }
#endif
        /// <summary>The parent_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ParentId { get; set; }
#nullable restore
#else
        public UntypedNode ParentId { get; set; }
#endif
        /// <summary>The part_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartNumber { get; set; }
#nullable restore
#else
        public string PartNumber { get; set; }
#endif
        /// <summary>The product_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductCode { get; set; }
#nullable restore
#else
        public string ProductCode { get; set; }
#endif
        /// <summary>The recommended_memory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RecommendedMemory { get; set; }
#nullable restore
#else
        public UntypedNode RecommendedMemory { get; set; }
#endif
        /// <summary>The required_storage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RequiredStorage { get; set; }
#nullable restore
#else
        public UntypedNode RequiredStorage { get; set; }
#endif
        /// <summary>The serial_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SerialNumber { get; set; }
#nullable restore
#else
        public string SerialNumber { get; set; }
#endif
        /// <summary>The software_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SoftwareVersion { get; set; }
#nullable restore
#else
        public string SoftwareVersion { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>The version_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? VersionId { get; set; }
#nullable restore
#else
        public UntypedNode VersionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.App.Models.SoftwareVariantDto"/> and sets the default values.
        /// </summary>
        public SoftwareVariantDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marechai.App.Models.SoftwareVariantDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marechai.App.Models.SoftwareVariantDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Marechai.App.Models.SoftwareVariantDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "catalogue_number", n => { CatalogueNumber = n.GetStringValue(); } },
                { "distribution_mode", n => { DistributionMode = n.GetIntValue(); } },
                { "family", n => { Family = n.GetStringValue(); } },
                { "id", n => { Id = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "introduced", n => { Introduced = n.GetDateTimeOffsetValue(); } },
                { "minimum_memory", n => { MinimumMemory = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parent", n => { Parent = n.GetStringValue(); } },
                { "parent_id", n => { ParentId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "part_number", n => { PartNumber = n.GetStringValue(); } },
                { "product_code", n => { ProductCode = n.GetStringValue(); } },
                { "recommended_memory", n => { RecommendedMemory = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "required_storage", n => { RequiredStorage = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "serial_number", n => { SerialNumber = n.GetStringValue(); } },
                { "software_version", n => { SoftwareVersion = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
                { "version_id", n => { VersionId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("catalogue_number", CatalogueNumber);
            writer.WriteIntValue("distribution_mode", DistributionMode);
            writer.WriteStringValue("family", Family);
            writer.WriteObjectValue<UntypedNode>("id", Id);
            writer.WriteDateTimeOffsetValue("introduced", Introduced);
            writer.WriteObjectValue<UntypedNode>("minimum_memory", MinimumMemory);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("parent", Parent);
            writer.WriteObjectValue<UntypedNode>("parent_id", ParentId);
            writer.WriteStringValue("part_number", PartNumber);
            writer.WriteStringValue("product_code", ProductCode);
            writer.WriteObjectValue<UntypedNode>("recommended_memory", RecommendedMemory);
            writer.WriteObjectValue<UntypedNode>("required_storage", RequiredStorage);
            writer.WriteStringValue("serial_number", SerialNumber);
            writer.WriteStringValue("software_version", SoftwareVersion);
            writer.WriteStringValue("version", Version);
            writer.WriteObjectValue<UntypedNode>("version_id", VersionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
