// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Messages.Reports.Item.Resolve;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Messages.Reports.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \messages\reports\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReportsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The resolve property</summary>
        public global::Marechai.ApiClient.Messages.Reports.Item.Resolve.ResolveRequestBuilder Resolve
        {
            get => new global::Marechai.ApiClient.Messages.Reports.Item.Resolve.ResolveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Messages.Reports.Item.ReportsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReportsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/messages/reports/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Messages.Reports.Item.ReportsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReportsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/messages/reports/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
