// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.ProcessorsByMachine.ByMachine.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.ProcessorsByMachine.ByMachine
{
    /// <summary>
    /// Builds and executes requests for operations under \processors-by-machine\by-machine
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ByMachineRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Marechai.ApiClient.processorsByMachine.byMachine.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.ProcessorsByMachine.ByMachine.Item.WithMachineItemRequestBuilder"/></returns>
        public global::Marechai.ApiClient.ProcessorsByMachine.ByMachine.Item.WithMachineItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("machineId", position);
                return new global::Marechai.ApiClient.ProcessorsByMachine.ByMachine.Item.WithMachineItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Marechai.ApiClient.processorsByMachine.byMachine.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marechai.ApiClient.ProcessorsByMachine.ByMachine.Item.WithMachineItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Marechai.ApiClient.ProcessorsByMachine.ByMachine.Item.WithMachineItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("machineId", position);
                return new global::Marechai.ApiClient.ProcessorsByMachine.ByMachine.Item.WithMachineItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.ProcessorsByMachine.ByMachine.ByMachineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ByMachineRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/processors-by-machine/by-machine", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.ProcessorsByMachine.ByMachine.ByMachineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ByMachineRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/processors-by-machine/by-machine", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
