<Project Sdk="Uno.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net10.0-android;net10.0-browserwasm;net10.0-desktop</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) Or $([MSBuild]::IsOSPlatform('macos'))">$(TargetFrameworks);net10.0-ios</TargetFrameworks>

        <OutputType>Exe</OutputType>
        <UnoSingleProject>true</UnoSingleProject>

        <!-- Display name -->
        <ApplicationTitle>Marechai.App</ApplicationTitle>
        <!-- App Identifier -->
        <ApplicationId>net.marechai.app</ApplicationId>
        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>
        <!-- Package Publisher -->
        <ApplicationPublisher>O=Marechai.App</ApplicationPublisher>
        <!-- Package Description -->
        <Description>Marechai.App powered by Uno Platform.</Description>

        <!--
          UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
          https://aka.platform.uno/singleproject-features
        -->
        <UnoFeatures>
            Lottie;
            Hosting;
            Toolkit;
            Logging;
            LoggingSerilog;
            Mvvm;
            Configuration;
            HttpKiota;
            Serialization;
            Localization;
            Navigation;
            ThemeService;
            SkiaRenderer;
        </UnoFeatures>
    </PropertyGroup>

</Project>
