<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-browserwasm;net10.0-desktop</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) Or $([MSBuild]::IsOSPlatform('macos'))">$(TargetFrameworks);net10.0-ios</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>Marechai.App</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>net.marechai.app</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>O=Marechai.App</ApplicationPublisher>
    <!-- Package Description -->
    <Description>Marechai.App powered by Uno Platform.</Description>

    <!--
      UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      Lottie;
      Hosting;
      Toolkit;
      Logging;
      LoggingSerilog;
      Mvvm;
      Configuration;
      HttpKiota;
      Serialization;
      Localization;
      ThemeService;
      Storage;
      SkiaRenderer;
      Svg;
    </UnoFeatures>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Marechai.ApiClient\Marechai.ApiClient.csproj"/>
    <ProjectReference Include="..\Marechai.Data\Marechai.Data.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Strings\**\*.resw">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Humanizer"/>
    <PackageReference Include="Microsoft.Extensions.Localization"/>
    <PackageReference Include="Prism.DryIoc.Uno.WinUI"/>
    <PackageReference Include="Svg.Skia"/>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt"/>
    <PackageReference Include="QRCoder"/>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Presentation\Views\Shell.xaml.cs">
      <DependentUpon>Shell.xaml</DependentUpon>
      <IsDefaultItem>true</IsDefaultItem>
    </Compile>
    <Compile Update="Presentation\Views\ComputersPage.xaml.cs">
      <DependentUpon>ComputersPage.xaml</DependentUpon>
      <IsDefaultItem>true</IsDefaultItem>
    </Compile>
    <Compile Update="Presentation\Views\MainPage.xaml.cs">
      <DependentUpon>MainPage.xaml</DependentUpon>
      <IsDefaultItem>true</IsDefaultItem>
    </Compile>
    <Compile Update="Presentation\Views\ComputersListPage.xaml.cs">
      <DependentUpon>ComputersListPage.xaml</DependentUpon>
      <IsDefaultItem>true</IsDefaultItem>
    </Compile>
    <Compile Update="Presentation\Views\NewsPage.xaml.cs">
      <DependentUpon>NewsPage.xaml</DependentUpon>
      <IsDefaultItem>true</IsDefaultItem>
    </Compile>
    <Compile Update="Presentation\Views\MachineViewPage.xaml.cs">
      <DependentUpon>MachineViewPage.xaml</DependentUpon>
      <IsDefaultItem>true</IsDefaultItem>
    </Compile>
    <Compile Update="Presentation\Components\Sidebar.xaml.cs">
      <DependentUpon>Sidebar.xaml</DependentUpon>
      <IsDefaultItem>true</IsDefaultItem>
    </Compile>
    <Compile Update="Presentation\Views\UsersPage.xaml.cs">
      <DependentUpon>UsersPage.xaml</DependentUpon>
      <IsDefaultItem>true</IsDefaultItem>
    </Compile>
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls"/>
    <!-- Add more community toolkit references here -->
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'windows'">
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls"/>
    <!-- Add more uno community toolkit references here -->
  </ItemGroup>


</Project>
