// <auto-generated/>
#pragma warning disable CS0618
using Marechai.ApiClient.Software.Covers.Admin.Batch;
using Marechai.ApiClient.Software.Covers.Admin.Pending;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marechai.ApiClient.Software.Covers.Admin
{
    /// <summary>
    /// Builds and executes requests for operations under \software\covers\admin
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdminRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The batch property</summary>
        public global::Marechai.ApiClient.Software.Covers.Admin.Batch.BatchRequestBuilder Batch
        {
            get => new global::Marechai.ApiClient.Software.Covers.Admin.Batch.BatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pending property</summary>
        public global::Marechai.ApiClient.Software.Covers.Admin.Pending.PendingRequestBuilder Pending
        {
            get => new global::Marechai.ApiClient.Software.Covers.Admin.Pending.PendingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Software.Covers.Admin.AdminRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdminRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software/covers/admin", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marechai.ApiClient.Software.Covers.Admin.AdminRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdminRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/software/covers/admin", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
